### ISSUE TITLE
Theme: Error handler for different responses

### ISSUE THREAD

**Issue by gnadelwartz** [authentic-theme/authentic-theme#1047]
I found that out you can have error handler scripts for displaying customized error respsonses with mimiserv, eg. for 403 you are blocked. this works very easy:

- insert `error_handler_403=error403.cgi`, this cgi is called when error 403 is raised by miniserv
  same for every other error code, to catch all errors use `error_handler=errorhandler.cgi`

result of my (really simple) error handler look like this if to many login attemps happen:

![image](https://user-images.githubusercontent.com/4593242/37245457-710c8966-2498-11e8-8a06-d8dd7261c972.png)

if I change the response code from 403 to 200, everthings else is the same, it's only a gey screen:
![image](https://user-images.githubusercontent.com/4593242/37245504-4ad2b7d8-2499-11e8-9565-a74375fb44fe.png)

but the source is the same, and all elements are there:

![image](https://user-images.githubusercontent.com/4593242/37245514-775050d6-2499-11e8-9705-6f2b42a3d8f8.png)

in both cases it's unauthenticated, onyl difference is reponse 200 instead of 403 delivered to browser.
If you call error430.cgi in authenticated mode ist working ...

If you want to try yourself insert the line  `error_handler_403=error403.cgi` in miniserv.conf and run `update-from-repo.sh -force -repo:gnadelwartz/webmin` now try 5 times to login with the wrong password.

**Comment by qooob** [comment]
Okay, I'll check a bit later. Thanks.

**Comment by gnadelwartz** [comment]
ah, I've forget my fix for -repo isn't merged, so

- download lastest version of update-from-repo with: `wget https://cdn.rawgit.com/gnadelwartz/webmin/3e916dd16f38b0247657ede394ad6a5a7c8fc3bc/update-from-repo.sh`
- run `./update-from-repo.sh  -repo:gnadelwartz/webmin -file miniserv.pl error403.cgi` in webmin dir

**Comment by gnadelwartz** [comment]
Wait, I have a much better idea for displaying login bans witch should work out of the box ..

**Comment by qooob** [comment]
Okay, sure. I'll do the fix for tablets and small screens working with out any additional settings.

**Comment by gnadelwartz** [comment]
what do you think about this?
![image](https://user-images.githubusercontent.com/4593242/37252798-342d1fa2-2528-11e8-9323-405e1595c0fd.png)

I simply put `error_handler_403=session_login.cgi` and add th folloing code to you cgi:

``` perl
...
    !$in{'failed'}                       &&
    !$in{'timed_out'}                    &&
    !$in{'code'})

...
} elsif ($in{'timed_out'}) {
    print '<div class="alert alert-warning">' . "\n";
    print '<strong><i class ="fa fa fa-exclamation-triangle"></i> ' . $Atext{'login_warning'} . '</strong><br />' . "\n";
    print '<span>' . &Atext('session_timed_out', int($in{'timed_out'} / 60)) . "</span>\n";
    print '</div>' . "\n";
} elsif ($in{'code'})   {
    print '<div class="alert alert-warning">' . "\n";
    print '<strong><i class ="fa fa fa-exclamation-triangle"></i> ' . $Atext{'login_warning'} . '</strong><br />' . "\n";
    print '<span><b>' . $in{'message'} . "</b></span>\n";
    print '</div>' . "\n";
}
...
```

**Comment by qooob** [comment]
I'll have to test that. Thanks.

**Comment by gnadelwartz** [comment]
Thanks, would be nice we are able to provide users a more nice error message than only a 403 one liner from miniserv.pl.

BTW: in case a miniserv.pl message is delivered we may remove the user, pass etc.fields and provide a you are blocked message and button for "try again"

**Comment by qooob** [comment]
Does Webmin UI has API for that?

**Comment by gnadelwartz** [comment]
an API for ERROR? yes, you can call any CGI with parameter code and message, this is what i've done here ...

**Comment by qooob** [comment]
Okay, I'll take a closer look. Danke.

**Comment by gnadelwartz** [comment]
seems this solution will statisfy PCI scanner, return code 200 and "real" HMTL meassage provieded to the "user" ...

**Comment by gnadelwartz** [comment]
I have a new example error403.cgi which seems to work also with authentic, only the footer  button us not displayed https://github.com/webmin/webmin/issues/833

**Comment by rostovtsev** [comment]
Hi, 

I am sorry it took a while.

I have just implemented it on the latest commit. It will handle 401, 403, 404 errors.

The script will get the time from _miniserv_ configuration and reload the page after the block time is over.

![image](https://user-images.githubusercontent.com/4426533/52502253-600ca700-2bf3-11e9-8224-9edbb9e13678.png)

Please, give it a try!

**Comment by gnadelwartz** [comment]
hi ilia, looks perfect!
