### ISSUE TITLE
nothing showing up that i lost contact with the server

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1153]
I lost contact with one of my servers but nothing is showing up on the Dashboard that i have lost contact. The only thing i can see are the pie charts that won't move.

Webmin version 1.881
Authentic Theme 19.19

**Comment by rostovtsev** [comment]
Hi,

In case you're not focused on the theme (tab) it disables background data collection. You need to make window active by clicking on it. After doing so, it will show you

**Comment by Sopor-** [comment]
I have made it active but still nothing... I haven't pressed any buttons because that will of course give me an error.

**Comment by rostovtsev** [comment]
You 3xp3ct message to be shown only on Dashboard in familiar cases or all the time connection is lost. User action is important not to create unneeded load.

**Comment by Sopor-** [comment]
But i'm sure you added some kind of message that was showing when i lost connection? Why isn't that showing?
It seems that i can even open menus and press the Dashboard button and it will continue to show the dashboard as everything was okay. Not a single error message. If i do a refresh it takes 30-40 seconds and i get "The connection has timed out".
Most of the times you have the Dashboard open and you know everything will auto update (live) so that page is the most important one but i don't know if someone else have another opinion about it? For me the Dashboard is the important one.

**Comment by rostovtsev** [comment]
It wasn't showing, because in the past there were complains from the users with unstable connection that this message was appearing pretty often.

I have managed to make it work, but it will take some time before it's shown, to avoid further issues.

**Comment by Sopor-** [comment]
In that case you should have added an option so users can choose how long time it should be before showing this message.

**Comment by rostovtsev** [comment]
No, we already have to many options; right now it works perfectly; you will know that you'd lost connection to the server in 7-9 seconds. It's not a big of a deal at all.
