### ISSUE TITLE
Ubuntu server 18.04 - In order to make this option work, git command has to be installed on your system

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1155]
When i open the theme configuration i can read this message:
`In order to make this option work, git command has to be installed on your system`
but i do have git installed:
```
$ git --version
git version 2.17.1

$ whereis git
git: /usr/bin/git
```
Do you know what I'm doing wrong? It is a totally new installation of Ubuntu and i haven't updated the theme. This was installed with Webmin.

Webmin version 1.881 - Authentic Theme 19.09.2

**Comment by rostovtsev** [comment]
Hi,

It might be not on the path. Check Webmin Configuration page and Environmental options.

Make sure that you really have it installed on the system you're talking about and not some other.

Try opening inbuilt command shell and running:

```
apt-get install git
```

**Comment by Sopor-** [comment]
```
$ sudo apt install git
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version (1:2.17.1-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```
I can run `git` without typing full path. It should work in Webmin too.

**Comment by rostovtsev** [comment]
What is the output of `git -v` from inside Webmin (drop-down shell)?

**Comment by Sopor-** [comment]
The output is...
```
# git --version
git version 2.17.1
```
...and with a drop-down shell you mean the `Others / Command shell`?

**Comment by rostovtsev** [comment]
Can you show me the screenshot of what is not working or what error message do you see?

**Comment by Sopor-** [comment]
![image](https://user-images.githubusercontent.com/5789283/41430979-d20a193a-7011-11e8-8ca8-2d07b2072eed.png)

It should looked like this:
![image](https://user-images.githubusercontent.com/5789283/41431112-3729d7e2-7012-11e8-82aa-2efec384edad.png)

**Comment by Sopor-** [comment]
```
$ sudo apt install libwww-perl
Reading package lists... Done
Building dependency tree
Reading state information... Done
libwww-perl is already the newest version (6.31-1).
```

If i do a force update i will get this message but i have continued to try update

![image](https://user-images.githubusercontent.com/5789283/41441763-58466afe-7034-11e8-8753-5116a582fc9b.png)

**Comment by rostovtsev** [comment]
If you continue, what do you have? Does it fail?

**Comment by Sopor-** [comment]
No problems to update

![image](https://user-images.githubusercontent.com/5789283/41470865-36abd4aa-70b2-11e8-92ce-ab2ae657ec32.png)

**Comment by Sopor-** [comment]
Now it seems to work after I installed the latest 19.19. So this issue will probably be fixed as soon as a new Webmin is out.
