### ISSUE TITLE
User Email - Change buttons change color randomly?

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1157]
When browsing my emails i use the `>` to change page and when i do that the two Change buttons and the Delete all button change color and it look like it is randomly.
Change buttons are green but suddenly they are white. Delete all is red but suddenly it is white. The only thing i do is pressing the `>` sign.

![image](https://user-images.githubusercontent.com/5789283/41443891-d861037e-703f-11e8-813d-eb465cf60d2d.png)

Webmin 1.881 - Authentic Theme 19.19

**Comment by rostovtsev** [comment]
This is due to fancy way of guessing button type. The underlying trigger, also changes and it's comming from WebminCore. I don't know why it uses different key name for the same language string.

This part is being reworked right now and very soon you will never see it again, so forget about it.

**Comment by Sopor-** [comment]
Shouldn't this be fixed? The Delete all button still get red in some random way..

**Comment by rostovtsev** [comment]
No, I will discuss it with Jamie again though. He might know why this is happening, after closer look.

**Comment by rostovtsev** [comment]
Fixed.
