### ISSUE TITLE
System Time - impossible to see the country/city when changing Time Zone

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1158]
When changing time zone it will show very little information as you can see in this picture:

![image](https://user-images.githubusercontent.com/5789283/41482953-8d5d083a-70d7-11e8-9229-6eac3041736b.png)

I don't know if it has something to do with the incompatible of 19.19 with older webmin?

**Comment by rostovtsev** [comment]
Thanks.
