### ISSUE TITLE
how do i change the time from 12h to 24h?

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1160]
I now have 12h but is it possible to change it to 24h?
![image](https://user-images.githubusercontent.com/5789283/41635032-d1e45036-7446-11e8-8639-d0ec0e7ce1db.png)

**Comment by rostovtsev** [comment]
You can do it in Webmin/Change Language and theme or in Webmin/Webmin Configuration/Language and Locale (for Webmin) or in Usermin/Change Language (for Usermin).

**Comment by Sopor-** [comment]
Nice, thanks!
