### ISSUE TITLE
Multiple tabs open causes nav to link to wrong site

### ISSUE THREAD

**Issue by Ryvix** [authentic-theme/authentic-theme#1165]
I've had this issue for awhile and it always drives me nuts but I couldn't figure out what the cause was. There have been a number of times I've edited the wrong options for the wrong domain and it's getting pretty annoying. So I finally figured out what the cause is and wanted to report it.

I have 4 domains in the drop down in Virtualmin on this particular server. Let's use Domain1 and Domain3 for this example.

First, I have my **Default page for Virtualmin** option set Domain3. That might be one reason the issue occurs but I have a feeling it happens other times too even when this isn't set to anything but the default. 

I go to Domain1 in Virtualmin and click Edit Virtual Server, for example, but probably any of the virtual server's pages will do.

Next, I open a new browser tab and go to https://siteurl:10000/ and then it's at the default server already, Domain3, which is the one I want to edit, it shows that domain in the dropdown in the nav bar on the top left. It shows the Domain3 summary on the right.

I click Edit Virtual Server, it does not edit the one for that domain, it edits Domain1 instead. Any of the options on the left edit Domain1.

I use multiple tabs like this sometimes in order to compare options, or if I just have to do multiple things at a time, etc.

Thanks =)

**Comment by rostovtsev** [comment]
Hi,

Are you using the latest 19.19 version of the theme? There was a fix for exactly this issue starting from cersion 19.13.

I just opened (using latest 19.19 version) two Virtualmin tabs in Chrome browser, in one selected domain1 and in the second tab I selected domain2 - all navigation menu links lead me to the correct content page.

**Comment by Ryvix** [comment]
Well that is awesome news then!

It sounds like I'm not running the latest version then. I thought that it updated itself or at least updated with Webmin/Virtualmin. If I try to force it to update it tells me I have to update Webmin to a development version but I'm not going to do that. So I guess I'll just wait until it comes along.

Thank you very much =)

**Comment by rostovtsev** [comment]
I use in production latest 19.19. There was very small thing that made it "dependent" on the next Webmin. It's safe to click to force-install it. You can always downgrade to the current version of the theme.

I would like you to double-check it making sure we're talking about the same issue.

Regards,
Ilia

**Comment by Ryvix** [comment]
Yep that does appear to have fixed it. Thank you!
