### ISSUE TITLE
View Logfile -> speed up the search?

### ISSUE THREAD

**Issue by 7starsone** [authentic-theme/authentic-theme#1166]
Hello, how are you? 😄 

I'm here, for an access log...
![Image of log](http://i65.tinypic.com/kegmy8.jpg)

when you enter an IP address and press Refresh, it takes a long time to retrieve the lines, no matter what the number of last lines. Please, what's the cause and is possible to speed up this process? Honestly, I don't think that's so normal...it should be definitely faster

thanks

**Comment by 7starsone** [comment]
Hello,
If by CLI I do something like
`grep -m 10 "xx.xxx.xxx.xx" /var/log/virtualmin/mydomain.com_access_log`

it takes not even one second...

so, IMHO this should be considered, also because in this way that function becomes useless and better to directly use the CLI.
 
Is it a problem with the Virtualmin code or can you fix it in any way?

_Thank you_

**Comment by rostovtsev** [comment]
Hi,

Few releases ago we added _regexp_ support for the search field to work. On Linux type systems it runs:

`grep -i -a -E searched_string`

The reason why it's slow could be the fact that _regexp_ is used, or highly likely the reason that you have very large number of lines to output.

I have tested it on the access log file with the size of about 50MB and it worked almost instantaneously.

What do you have in module config set (cog icon, on the module index, on the top left of the table's header) for _Default number of lines to display_ option?

**Comment by 7starsone** [comment]
OK, on ssh CLI
`grep -i -a -E "xx.xxx.xx.xxx" /var/log/virtualmin/mydomain.com_access_log | tail -n 20`
**less than one second**

on the web interface, even 15 seconds...

this is the config
![image log config](http://i66.tinypic.com/256wm0k.jpg)

**Comment by rostovtsev** [comment]
As you can see, you have an option of _Include compressed logs in searches_, this is the reason for you to take it very long time. :wink:

**Comment by 7starsone** [comment]
ok, thanks, I didn't know about this option and, at this point, maybe it should not be enabled by default...that's it 👍 
_Thank you_
