### ISSUE TITLE
Theme requires a non existent version.

### ISSUE THREAD

**Issue by Ryonez** [authentic-theme/authentic-theme#1167]
The theme is reporting it needs webmin version 1.883:

![image](https://user-images.githubusercontent.com/16157130/42706097-c2a77918-8729-11e8-90ea-cf652a72e22e.png)

I have version 1.881, and webmins git has a tag for version 1.880 (And there's no other branches).

What's going on?

**Comment by rostovtsev** [comment]
It states exactly what it is in the message. 

You can either force install the theme anyway (should work in most cases) or upgrade Webmin using console script.

**Comment by rostovtsev** [comment]
You can see the current version of Webmin at _[README](https://github.com/webmin/webmin/blob/master/README)_.

**Comment by swelljoe** [comment]
Is this version of the theme the "stable" or development release? The stable release should really always be relying on a stable release of Webmin (the one available on Webmin.com) if you're going to encourage people to update to it. The development release can obviously depend on development version of Webmin.

**Comment by Ryonez** [comment]
> You can see the current version of Webmin at README.

Which funny enough, still isn't version 1.883, and matches the 1.880 tag:
![image](https://user-images.githubusercontent.com/16157130/42710654-e738513a-8738-11e8-81ef-b5fe450581a5.png)

And while yes it does say how I can force it, It does concern me that the theme author says it's meant for a version that doesn't seem to exist. And that somehow the ubuntu repo has a version higher than what the master is.

> You can either force install the theme anyway (should work in most cases) or upgrade Webmin using console script.

As I explained, I somehow have a version that's ahead of the git. That shouldn't be happening as far as I know.

I don't understand what's happening with the mismatched versions between the git, the ubuntu repo, and the theme.

**Comment by Ryonez** [comment]
@swelljoe 
The force update option on the Webmin UI for the theme allows me to choose the stable branch of the theme, which I've done. I'm not aware of any development version of Webmin.

**Comment by rostovtsev** [comment]
@swelljoe Okay, I will try to make sure that theme release version will work with current Webmin release version. However, it's not always possible, apparently. When Jamie does changes to the repo, sometimes on request, I catch up on the theme, by adding features that are dependent on yet unreleased version of Webmin. It takes for me about a month to make a release and for Webmin it's about three months usually.

@jcameron Is planning to make a release but hasn't done it yet, I think. Theme development goes ahead and whenever new Webmin version is ready to go, it fetches the latest theme version to be the part of the new stable package.

The message clearly states, that it's depended on the version that is possibly unreleased (git version - unreleased as stable package). Jamie changes the minor version number that stays within the branch. For example, release version 1.880 has the branch with the same name; most of the time other development versions would include 1.88x, where _x_ is the number from _0-9_. When I create the version of the theme that is dependent on yet unreleased version of Webmin, I rely on what Webmin's repo provides on _README_ file, at that particular time.

I understand that right now it's confusing, as it's 1.890, and it looks like something went wrong or happened to be unfinished.

**Comment by Ryonez** [comment]
Whoops, I misread the readme version.

Hmm. I wonder how this all ties in with Ubuntu's repo. Does it get updated at regular times rather than versions?

**Comment by swelljoe** [comment]
As far as I know Webmin is not in any repo provided by Ubuntu, and so it has nothing to do with the discussion.

**Comment by swelljoe** [comment]
It's just a poor user experience to be told to update and then receive an error (and there have been tons of tickets about this kind of mismatch). If a feature needs a new Webmin version, leave it in the development version of the theme until the new Webmin comes out. No error message text can make it a nice experience to receive an error when trying to update...users *really* need to feel safe and confident that updates will always work without trouble (even if nothing else is perfect, the install/update process absolutely needs to be).

Development version can require anything it wants, as it targets more technical users.

**Comment by Ryonez** [comment]
No, it's not in the main repo, but it's available to be added and managed by apt via

`deb http://download.webmin.com/download/repository sarge contrib`

And by adding the signing key:

`wget http://www.webmin.com/jcameron-key.asc`
`sudo apt-key add jcameron-key.asc`

To me this is webmin's ubuntu repo, is signed by the creator, and is a valid release.
A release that is seemingly out of date.

It's only adding to my confusion, do I stop using this and just use git? But then what's the point of the repo?

I'll admit, it's not the issue I came here for, but it is related to the problem of versions, which is why I mentioned it.

**Comment by Ryonez** [comment]
I'll close the issue as I can see the git has a higher version. 
Thank you for pointing where I can find the correct? version number.

**Comment by swelljoe** [comment]
Most folks should use the apt repo (whether it's the Webmin.com one or the Virtualmin.com one, if using Virtualmin). The git version is  only appropriate for developer environments (I don't run it on any system except my development laptop...all of our servers are running the current release from the Virtualmin or Webmin repos). This is just Authentic suggesting a Webmin version that it shouldn't.

**Comment by rostovtsev** [comment]
@swelljoe Okay, I will always keep new, dependent features with development branch. I will also rethink the notification message to be less error-like, as it's not an error.
