### ISSUE TITLE
German Language is a mix of german and english

### ISSUE THREAD

**Issue by htttito** [authentic-theme/authentic-theme#1169]
Hi Ilia!
Please look at the picture....
Language is German (de.UTF-8)
![bildschirmfoto von 2018-07-14 13-12-10](https://user-images.githubusercontent.com/40149753/42723856-8dd2112e-8767-11e8-9480-4ebc425ee26a.png)

**Comment by rostovtsev** [comment]
Hi,

Do you mean the left menu issue (translation)?

This might be related: https://github.com/webmin/webmin/issues/934

**Comment by rostovtsev** [comment]
@gnadelwartz Kay, we don't have left menu fully translated yet?

**Comment by htttito** [comment]
Yes i mean the left menu.
But if you take German (not utf8) the menu is ok, but there is a Problem with "äüö"

**Comment by rostovtsev** [comment]
This isn't the theme issue.

Do you still think that the issue hasn't been fixed? In this case you should report this issue to Webmin repo.
