### ISSUE TITLE
Editing Files Issue

### ISSUE THREAD

**Issue by alexnya** [authentic-theme/authentic-theme#1171]
Browsers: Google Chrome, Mozilla Firefox, Microsoft Edge
OS: Ubuntu 16.04 LTS

Hi,
I'm not sure if this is the right place to ask but I'm having an issue with Webmin where I can't edit or upload files. Before I was able to right click on a file in File Manager and edit it. This is happening on all the browsers I'm using.

Thank you,
Alex Nyamweya

**Comment by alexnya** [comment]
Huh. I'm suddenly able to edit now. Before it was any file or directory I wasn't able to modify. Did you do something? If not, do you know what could've caused this?

**Comment by rostovtsev** [comment]
I have never encountered this. If I did I would remember.

What exactly do you mean by, can't edit? Did you have _Edit_ menu entry in context menu?

**Comment by alexnya** [comment]
When I go to a file or directory usually I'm able to right click it and see
a menu. One of the options in that menu is edit the file.

**Comment by alexnya** [comment]
Ok I'm not able to right-click the file or directory again to edit the file.

**Comment by rostovtsev** [comment]
You can close this issue, as it's not an issue. :wink

**Comment by alexnya** [comment]
I'm still having the same issue again. I can't right click to edit the file when I was able to before. I don't know why I was able to before and why I can't now.

**Comment by rostovtsev** [comment]
Any update here?

**Comment by rostovtsev** [comment]
I can't reproduce it.

What are the exact steps to reproduce it? May be it happens after certain module or other particular actions?

**Comment by alexnya** [comment]
Sorry for the late response! I'm currently away from home right now.  But
basically when I log in and out a few times it works. I'm able to edit a
file then. Im unable to take a screenshot right now because I'm away from
my computer.

**Comment by rostovtsev** [comment]
I was trying to reproduce it but I couldn't in different setups, _**edit**_ link always displayed in context menu.

I will keep this issue closed for now, and when you ready to share more data you could reopen it.

----


> .. not able to right-click the file or directory again to edit the file.

For your information, it's not shown on directories.
