### ISSUE TITLE
Dashboard error, No perl MD5 hashing Module found

### ISSUE THREAD

**Issue by jlionelmo** [authentic-theme/authentic-theme#1173]
System Information
No Perl MD5 hashing module found!

![image](https://user-images.githubusercontent.com/7988272/42960625-f9231fb6-8b51-11e8-8048-21bac90ef590.png)

**Comment by rostovtsev** [comment]
Hi,

What do you have if you change theme to Gray Theme or Virtual Server Framed Theme?

**Comment by rostovtsev** [comment]
So, what do you get in Gray Theme?

Is this clean install? What server OS? What is Webmin version?

**Comment by rostovtsev** [comment]
To solve this just run:

```
yum install perl-Digest-MD5
```

https://github.com/webmin/webmin/issues/942

**Comment by estereofonico** [comment]
Thanks @rostovtsev ! It Worked
