### ISSUE TITLE
File Manager: Upload progress size field unnecessary escaping

### ISSUE THREAD

**Issue by MorningSleeper** [authentic-theme/authentic-theme#1174]
Hi, using version 19.19 and latest Chrome, when I upload a file part of the text in dialog window is not viewable as it runs off the bottom of the browser window. For example:

![image](https://user-images.githubusercontent.com/8920632/42980697-58bec6d8-8b8d-11e8-98a4-1989fd6d4c6c.png)

Perhaps if the dialog box width was a percentage of browser window width the text would be less likely to be forced out of view as the default dialog box size appears too small in relation to my browser window size to contain all the text.

On an unrelated matter, seems most progress indicators I have seen go from left to right but the one in File Manager seems to go from right to left, ie the green bar starts small on right side and gets larger as it moves to left, is this by design or a bug?

**Comment by rostovtsev** [comment]
It's the bug when long file names are used.

Yes progress filling from right to left is not a bug but a feature. :nerd_face:

**Comment by rostovtsev** [comment]
No, it wasn't the actual cause of the bug.

**Comment by rostovtsev** [comment]
It's fixed. Thanks a lot for reporting! :wink: 

Please update.
