### ISSUE TITLE
Theme: Gunmetal palette falsely applies rules to content page

### ISSUE THREAD

**Issue by pacquo** [authentic-theme/authentic-theme#1175]
Hello,

I have installed the latest version of the Authentic theme (19.19).

Opening the "System Log" module I see that the background colour of the dropdown selector shown at the top is dark (#292929).
Since the colour of the foreground is dark as well (#333), the field is unreadable.

I had a look to the stylesheet, finding the following:

``html[data-theme="noir"] .select2-selection, html[data-theme="noir"] .select2-selection--single {
	border: 1px solid rgba(225,225,225,.09) !important;
	background: #292929 !important;
}``

``.__page .select2-content.select2-selection.select2-selection span, .__page .select2-content.select2-selection.select2-selection--single span {
    color: #333 !important;
}``

Here it is a screenshot:

![selector_problem](https://user-images.githubusercontent.com/19971440/43033646-345640c8-8ccd-11e8-9e17-3164c500d199.png)

I am using the latest version of Firefox (61.0.1).

**Comment by rostovtsev** [comment]
Hi,

What happens if you toggle Day/Night mode (sun/moon icon in navigation menu)?

**Comment by pacquo** [comment]
Hello,
I don't see this kind of icon anywhere. Maybe I am missing something.
I have installed Webmin using the "minimal" package, then I have installed Authentic from URL.

**Comment by rostovtsev** [comment]
Which Webmin version? Where did you download it?

**Comment by pacquo** [comment]
In "day mode" the settings of the palette are the following:

![settings](https://user-images.githubusercontent.com/19971440/43036584-c73a820a-8d04-11e8-9bca-bd53c9c17463.png)

**Comment by rostovtsev** [comment]
Okay, now I see the bug. It will be fixed in upcoming 19.20-beta1.

Thanks.

**Comment by pacquo** [comment]
Thank you Ilia!

**Comment by rostovtsev** [comment]
It will be fixed in upcoming 19.20-beta1.
