### ISSUE TITLE
Read Mail link not working 

### ISSUE THREAD

**Issue by gametimesav** [authentic-theme/authentic-theme#1177]
Read User Mail link is not working after the theme update.

**Comment by rostovtsev** [comment]
What theme version do you have installed. What Webmin version?

Mail link doesn't work where? Navigation menu? Are there errors in browser's console?

**Comment by gametimesav** [comment]
Webmin 1.890 ... and the Authentic Theme 19.20-beta1
Ream Mail links not working

**Comment by rostovtsev** [comment]
Hi,

I confirm that this is my bug.

I will fix it in not time.

**Comment by rostovtsev** [comment]
Please update.

Try new mail in Usermin and share your experience please.

It's important to me.
