### ISSUE TITLE
Bug on DNS Records > DMARC item

### ISSUE THREAD

**Issue by fernandolcardoso** [authentic-theme/authentic-theme#1179]
**In previous versions the line was launched like this:**
_dmarc.domain.com.	IN	TXT	"v=DMARC1; pct=100; ruf=mailto:postmaster@domain.com; rua=mailto:postmaster@domain.com; p=none"

**Today is being informed by Virtualmin this way:**
_dmarc.domain.com.	IN	TXT	"v=DMARC1; pct=100; ruf=postmaster@domain.com; rua=postmaster@domain.com; p=none"

In the absence of the 'mailto:' information I am receiving error alerts and am required to manually change each new domain.

**Comment by rostovtsev** [comment]
Hi, Fernando.

This issue has been fixed few weeks ago.

Ref.: https://github.com/virtualmin/virtualmin-gpl/issues/60

**Comment by fernandolcardoso** [comment]
Thanks for the feedback, I made some adjustments in the version (see image) and did not get the results corrected. Will the problem be solved in the future?

![image](https://user-images.githubusercontent.com/16019127/43786823-f3176832-9a3f-11e8-86bb-4d4f4638c80e.png)

**Comment by rostovtsev** [comment]
> I made some adjustments in the version (see image) and did not get the results corrected. 

What do you mean by that? You patched files manually?

**Comment by fernandolcardoso** [comment]
Forgive me my English, I'm Brazilian and I'm using a translator.

I'm saying that I added new domains with the latest version and cotinuo with DNS problems.

I asked if this has been corrected or if it will still be done.

**Comment by rostovtsev** [comment]
It will be fixed in the next Virtualmin release.

Meanwhile, you could apply patch manually:


https://github.com/virtualmin/virtualmin-gpl/commit/de6d8b4026043d26186369b1130bcbb4e2c63bae#diff-edb0dd6f2fc1b6729804ba6b62e10635

**Comment by fernandolcardoso** [comment]
Thanks for the feedback
