### ISSUE TITLE
How to display on home page the IP adress

### ISSUE THREAD

**Issue by stanthewizzard** [authentic-theme/authentic-theme#1183]
All in the title

Thanks for help on that one

**Comment by rostovtsev** [comment]
Hi,

What is the home page for you? What IP address? There are many types of IP addresses.:question:

**Comment by stanthewizzard** [comment]
nevermind I'm dumb :)

In the dns settings I just put dns in first the file and on the homepage I've the DNS name with the correct IP

Thanks

**Comment by rostovtsev** [comment]
I'm glad it worked for you.

Let me know if I could help any further.

**Comment by stanthewizzard** [comment]
Thanks

I don't think so.
But on the default homepage (with kernel and CPU, System uptime, etc) it should be very usefull to be able to display (or not) the network settings
Thanks again

**Comment by rostovtsev** [comment]
It's already displayed as server main IP address, in the column _System hostname_.

Domain based, it's displayed when _[Virtualmin](https://www.virtualmin.com)_ is installed and dedicated addresses are used, then you will see an extra collapsible panel with _IP Address Allocation_ data.
