### ISSUE TITLE
File Manager: Improving context menu interaction on mobile devices

### ISSUE THREAD

**Issue by sz00gun** [authentic-theme/authentic-theme#1184]
Could you please, add the button in the file manager while using the theme on phones? I cannot calculate the size of folders during using the file manager on my smartphone.

**Comment by rostovtsev** [comment]
Hi,

Maybe it's better to improving context menu interactions on mobile devices?

What is not working? Tapping on properties closes context menu?

**Comment by sz00gun** [comment]
Hi, 

Tapping on properties not working.

Perhaps the best solution works be adding: calculate folder size to a menu tools on top, or somewhere...

Thanks

**Comment by sz00gun** [comment]
Hi, 

Tapping on properties not working.

Perhaps the best solution works be adding: calculate folder size to a menu tools on top, or somewhere...

Thanks

**Comment by rostovtsev** [comment]
Okay, I will add this to my todo.


Thanks.

**Comment by rostovtsev** [comment]
It's been added with the latest commit. Please give it a try.
