### ISSUE TITLE
The displayed error text will be displayed outside the screen.

### ISSUE THREAD

**Issue by kosugikun** [authentic-theme/authentic-theme#1186]
[Video](https://xn--0vq403amku.net/wp-content/uploads/2018/08/screenrecording_08-24-0030-08-41-27.mp4)

**Comment by kosugikun** [comment]
Where do I download Webmin 1.893?

**Comment by rostovtsev** [comment]
This is a bug.

Webmin directory has `update-from-repo.sh` script. It will update your Webmin installation. To update Usermin script you would do the same. 

Usermin had a bug. I would have to test it before recommending running it. I will test it and come back to you in a bit.

**Comment by rostovtsev** [comment]
Okay, you can run `update-from-repo.sh` from under Webmin/Usermin to update your installations - they work just fine. (just tested on CentOS). What installation are you running?

Theme automatically updates this script Webmin/Usermin's `update-from-repo.sh` upon its own update to make sure that you run latest installation script. Your are safe to go if the script `update-from-repo.sh` is version **_1.6.4._**. You can check it by running `cat update-from-repo.sh | grep VERS=`

**Comment by rostovtsev** [comment]
It's fixed. Thanks!

**Comment by kosugikun** [comment]
[image](https://xn--0vq403amku.net/wp-content/uploads/2018/08/img_2138.jpg)

**Comment by rostovtsev** [comment]
..then the same should be run on Usermin.

**Comment by kosugikun** [comment]
[I installed it.](https://xn--0vq403amku.net/wp-content/uploads/2018/08/img_2140.jpg)

**Comment by rostovtsev** [comment]
Okay, awesome! Glad it worked for you expected way.

How is the mail? :) You could also use my [website](https://rostovtsev.io) contact form to discuss details or leave wishes.
