### ISSUE TITLE
Iframe blocked

### ISSUE THREAD

**Issue by GeoZzNL** [authentic-theme/authentic-theme#1191]
Hello,

I want to add iframes to the HTML section but its blocked by the theme or so.

Refused to frame 'https://www.MYDOMAIN.nl/' because it violates the following Content Security Policy directive: "frame-src 'self'".

How can i add a iFrame into the HTML section in menu?

**Comment by rostovtsev** [comment]
Content security policy is a HTTP response header, its purpose to prevent XSS attacks, by declaring, which dynamic resources are allowed to load.

By default sent headers `X-Frame-Options: SAMEORIGIN` and `Content-Security-Policy: child-src 'self'` prevent loading data from outer websites. Besides, contemporary browsers on its own block _cross-origin framing_.

Unless hacking around, you will not be able to do it.
