### ISSUE TITLE
Inject css from an overlay theme

### ISSUE THREAD

**Issue by hjmallon** [authentic-theme/authentic-theme#1192]
Is it possible to inject css in an overlay theme? I can get it to work by editing authentic-theme's styles.css (in UI or /etc/authentic-theme/) but would like to distribute as an overlay theme to multiple machines.

The standard methods here (https://doxfer.webmin.com/Webmin/Creating_Overlay_Themes) don't seem to work. Should they work?
e.g. headhtml, inbody, prebody, postbody

**Comment by rostovtsev** [comment]
Hi,

Good point. Missed that. Added on the commit above.

Besides, I added an added extra ability to include files (which was meant by Jamie at the first place and doesn't work correctly in the stock _header_ subroutine), which is easier than writing HTML inline.

The example of _config_ file that will work with _Authentic Theme_:

```
headhtml=<link rel='stylesheet' type='text/css' href='/unauthenticated/overlay.css'>
headinclude=headinclude.html
inbody=data-tag-body="1"
prebody=<span>hidden prebody inline - %OS%</span>
postbody=<span>hidden postbody inline - %HOSTNAME%</span>
postbodyinclude=postbodyinclude.html
prebodyinclude=postbodyinclude.html

```

It should be clear from now on. Complete example is in the [attached .zip file.](https://github.com/authentic-theme/authentic-theme/files/2336862/overlay-theme-with-authentic-theme.zip)


It would be interesting to see your final overlay theme. :wink:

**Comment by hjmallon** [comment]
Thanks @rostovtsev! That was an incredible turn around time!

**Comment by rostovtsev** [comment]
Okay, added. Try just freshly released _19.20-beta4_.

**Comment by hjmallon** [comment]
@rostovtsev  I am having 404s with this change and apache reverse proxy.

The overlay css that it is trying to pull in does not have the /webmin in it
Requests: https://IP/unauthenticated/overlay.css
Should: https://IP/webmin/unauthenticated/overlay.css

**Comment by rostovtsev** [comment]
Yes, sure. You would either needed to add a prefix to the link or use relative path, for example:

```
headhtml=<link rel='stylesheet' type='text/css' href='unauthenticated/overlay.css'>
```
