### ISSUE TITLE
Theme: Inject default settings from an overlay theme

### ISSUE THREAD

**Issue by hjmallon** [authentic-theme/authentic-theme#1193]
Is it possible to inject default settings (e.g. colour pallette) from an overlay theme?

I can add settings files manually to /etc/webmin/authentic-theme/ if not. Would settings with in /etc/webmin/my-overlay/?

**Comment by rostovtsev** [comment]
Harry, hi.

I don't know why would you do that?

You probably could but theme has its own, UI based way of injecting _CSS_, _JS_ and _Perl_. What is the point of using overlays, when you could do it much easier using provided UI?

What are you trying to achieve?

**Comment by hjmallon** [comment]
I am trying to make a branded theme to install on my company's machines. My aim was to do it as an overlay theme (rather than forking themes/webmin) so that we could update webmin and have the overlay work with updated themes going forwards.

Aims:
* Change some images: Easy to acheive with overlay
* Change some images which are served with fontconfig: Easy to acheive now we have css injection
* Change default colours:
  * Could insert a default config file into /etc/webmin/authentic-theme, this isn't overlaying any more.
  * Could patch authentic-theme to fall back to settings in /etc/webmin/my-overlay/.
  * Could patch authentic-theme to have a config file in /usr/libexec/webmin/authentic-theme with the default colours and setup in (rather than in the code). This could then be overridden by overlay theme.

**Comment by rostovtsev** [comment]
Harry, I can not understand what you are asking or what is not working?

For your needs you could use Theme Extensions (searchable from navigation menu) or Theme Overlays. Both of the techniques would work.

You don't needed edit neither Webmin or Theme files.

**Comment by hjmallon** [comment]
I was aiming to set it up during install on multiple machines. You might be right that doing it through authentic-theme configuration and copying that to all teh machines is faster/easier.

**Comment by rostovtsev** [comment]
Yes, you could simply create an installable package after your theme-mod is ready or even create your own repo that would provide, natural updates each time you decide to change it.

Please be kind sending it to me, whenever it's done. I really wonder what it will end up look like.

----

The possible feature to implement here, could be the ability is to pull such mods from pre-set company like website.

For example, upon Virtualmin installation process, install script could ask something like: _Would you like to provide  an URL for running instant company branding?_. In case you supply tar-ball package, it could be pulled from an URL and be installed right there and at once. It could include theme configs/overlays, logos and any other data. Later, it could be added as UI component for Webmin/Usermin itself.

What do you think @jcameron @swelljoe about such improvement? Does it worth it?
