### ISSUE TITLE
Theme: Remove favourite that no longer exists

### ISSUE THREAD

**Issue by micoots** [authentic-theme/authentic-theme#1197]
Hi.

When I have a "favourites" item listed, and the virtual server exists, I can do to the favourites item no problem.

If I however delete that virtual server, and go to the favourites item which is still there, click it, I get an inconsistent display.

It's hard to produce screenshots since I can only do so from a production system.

But I noticed this problem on the "Manage SSL Certificate" page.

I have all the "Manage SSL Certificate" pages in my favourites. I delete one of the virtual servers that no longer a client of mine. I then went to the favourite of the non-existing virtual server and was presented with screen of the attached.

![webmin-issue](https://user-images.githubusercontent.com/16075934/45655201-4a062900-bb22-11e8-8d48-8d0ca9bf3109.jpg)

**Comment by rostovtsev** [comment]
Hi,

It sounds like a good improvement to handle errors property on Manage SSL Certificate page and/or remove from favorites deleted domain.

**Comment by jcameron** [comment]
So was the problem that this page is mostly empty? It's hard to say what's going wrong with that text blacked out.

**Comment by micoots** [comment]
Hi Jamie. The blacked out items are live domains which actually have nothing to do with the Let's Encrypt cert. They have their own SSL certs.

The screenshot shows that "SSL certificate file" and "SSL private key file" are empty, they aren't supposed to be. It also shows on the header "in domain" which is blank.

It should be very simple to reproduce this. Just add the Manage SSL page of a live site to your favourites, delete the live site, go back to the favourite and you'll see what I posted here.

**Comment by jcameron** [comment]
Ok, what should really happen in that case is a fast error that the domain no longer exists. I'll fix this in the next Virtualmin release.

**Comment by rostovtsev** [comment]
Added on the latest commit. If virtual server was removed using UI (most common way), then the favorites will be automatically dropped for deleted server.

**Comment by rostovtsev** [comment]
Latest commit also will check for domains deleted using Cloudmin and Cloudmin's mass domains form.
