### ISSUE TITLE
Theme: Search for text when editing config files manually

### ISSUE THREAD

**Issue by rostovtsev** [authentic-theme/authentic-theme#1198]
Idea:
  1. Return the line and the file name for matched results;
  2. Quick jump to the line and the file;
  3. Store search results across pages (unless cleared by user)

![screenshot from 2018-09-23 13-35-42](https://user-images.githubusercontent.com/4426533/45928081-71a42980-bf46-11e8-9d72-72f9e83a60b8.png)

**Comment by rostovtsev** [comment]
This feature has been added. Give it a try and share your experience.

**Comment by specktator** [comment]
Looks great pal @rostovtsev

**Comment by jcameron** [comment]
Nice work ... this is really handy for large config files.
