### ISSUE TITLE
Index page quote info 

### ISSUE THREAD

**Issue by mkdizajn** [authentic-theme/authentic-theme#1200]
Hi, 

does anyone know is there a setting for how many domain qoutes will be displayed on homepage?

Now I have 10 domains, I'd like more to display..

![info](https://i.imgur.com/UU73ssH.png)

**Comment by rostovtsev** [comment]
Hi, 

It seems that this feature was abandoned for quite some time. I have re-added it. You can set it now with Theme Configuration, in the following section:

![screenshot from 2018-10-02 22-47-27](https://user-images.githubusercontent.com/4426533/46373140-d7ef2180-c695-11e8-94d1-d638362407a9.png)

**Comment by mkdizajn** [comment]
Hey @rostovtsev I've pulled beta5 and now I can configure it :) 

thaaank you very much for light speed reaction!

**Comment by rostovtsev** [comment]
@mkdizajn My pleasure! :smiley:
