### ISSUE TITLE
Theme: Update to version 19.20-beta5 brings issue for fetching page on initial load

### ISSUE THREAD

**Issue by JimTR** [authentic-theme/authentic-theme#1201]
After applying the update  19.20-beta5 I have an issue after log in to the server 
Expected behaviour : after login the dashboard 'screen' should be displayed 
Actual behaviour : no dashboard 'screen' is shown in the right panel and the red loading data line just  continually pulsing.
To stop this you click on an option from the left panel, which then displays the and there after the problem finishes

**Comment by rostovtsev** [comment]
Jim, hi.

This is incompatibility issue. You need at least update `WebminCore.pm` and `web-lib-funcs.pm` files from Webmin package. You could also run `update-from-repo.sh` script to do the work for you.

**Comment by JimTR** [comment]
That Worked :+1:
