### ISSUE TITLE
Theme: Dashboard to display separate arrays information

### ISSUE THREAD

**Issue by vadimmm** [authentic-theme/authentic-theme#1202]
Hello!
It is not convenient for me to see the total free volume of all vaults. This is not informative. I want to see the distribution of the volume of each selected disk (array) on the main page. How can i do this?

**Comment by rostovtsev** [comment]
Hi, Vadim.

At the moment, speaking about Dashboard page you can not. However, it's in my todo to bring this to life. I will do it after 19.20 release with the new Mail.

Do you expect the output like `df -H` command? I think there is a separate module for it.

**Comment by rostovtsev** [comment]
There is [Disk Usage](http://www.webmin.com/download/modules/disk-usage-1.2.wbm.gz) module, that can be easily downloaded and installed using _Webmin Configuration/Webmin Modules_.

It would produce the following result:

![screenshot from 2018-10-05 10-07-11](https://user-images.githubusercontent.com/4426533/46520919-76da7000-c886-11e8-822d-dfbdd128bca2.png)

**Comment by vadimmm** [comment]
> Do you expect the output like `df -H` command? I think there is a separate module for it.

Ilya,
It would be wonderful if you combine the main indicators by the names of the selected arrays with a graphical display of capacity.
I look forward to the next releases!

**Comment by rostovtsev** [comment]
We will have it, that's for sure. I have much more time right now to work on the project.

**Comment by rostovtsev** [comment]
Okay, just added it here https://github.com/webmin/webmin/commit/f2cbf0f001fbde9273d3e2f3d3942465f06b4283.

You can apply the patch above to give it a try.

**Comment by rostovtsev** [comment]
![Screenshot from 2019-03-09 00-10-28](https://user-images.githubusercontent.com/4426533/54056553-7a8d6c80-4201-11e9-9f44-b6d1a2babac8.png)
