### ISSUE TITLE
"Filter content" won't detect text i paste in

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1207]
If i paste in text in the filter it won't work. I need to type on the keyboard to get it to work.

![image](https://user-images.githubusercontent.com/5789283/46924201-7d08e300-d022-11e8-9004-5ae01eebea71.png)

I also think the `Filter` tooltip should go away when i start typing.

Authentic Theme beta 19.20-beta5

**Comment by rostovtsev** [comment]
Nice points. I'll fix that. 🙂

**Comment by rostovtsev** [comment]
Done.

Thank you very much for being picky! :heart:
