### ISSUE TITLE
when i write the page expands for every char i type

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1208]
When i open a file to edit it look like this:
![image](https://user-images.githubusercontent.com/5789283/46994124-43fc6b80-d113-11e8-89e9-5d9df20bcbd3.png)

When i start to type the lower part of the page increases for every char i type:
![image](https://user-images.githubusercontent.com/5789283/46994156-73ab7380-d113-11e8-9486-fab81b40f696.png)

**Comment by rostovtsev** [comment]
Yes, this bug has already been fixed the day before yesterday. It only happened im Firefox.
