### ISSUE TITLE
can't use the tab key when edit files

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1209]
I wondering how i insert a tab when i have a file open for edit?

**Comment by rostovtsev** [comment]
3.19 is a testing kernel. I think that is the source of the bugs, especially if you use X11. What is your desktop OS and version? 🙂

**Comment by Sopor-** [comment]
I'm running server version...

**Comment by rostovtsev** [comment]
Where exactly it doesn't work. Could you provide a screenshot?

**Comment by rostovtsev** [comment]
It's fixed with the latest commit.
