### ISSUE TITLE
add line number when edit files

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1210]
When edit files it would be nice if there was line numbers. If i for example get an error in nginx it will display the line number and it will be much easier to find the error without counting the lines.
I don't know how it works, so this is maybe nothing that has to do with Authentic Theme?

**Comment by rostovtsev** [comment]
What a wonderful joke, Sopor! :smile: 

We have line numbers! It's the first feature I was ever looking for. Besides, you can simply click _Alt+G_ to just to needed line.

See the help for the editor. It has it all. 

![screenshot from 2018-10-17 09-28-16](https://user-images.githubusercontent.com/4426533/47066525-184eb380-d1ef-11e8-9925-301013230cd8.png)


Can I see the screenshot of your editro as well!?!? :smiley:

**Comment by Sopor-** [comment]
In that case it must have something to do with the module i use because i can't get any line numbers :(

**Comment by rostovtsev** [comment]
What module do you use?

**Comment by Sopor-** [comment]
It is the `nginx webserver`.

**Comment by rostovtsev** [comment]
It was added on the latest commits. Thanks for reporting.
