### ISSUE TITLE
File manager - using context menu in path

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1212]
If I right click on a folder name in the path to open the tiny window where i can type in the path, this will make it close the window again. If i want to use the mouse i can't do that because the tiny window close when i move the mouse to the context menu. See the gif below.

![2018-10-18_01-39-26](https://user-images.githubusercontent.com/5789283/47122407-e08b4e80-d276-11e8-9556-9655570dca96.gif)

I'm running Firefox and Authentic Theme 19.20-beta5

**Comment by rostovtsev** [comment]
Fixed, thanks.
