### ISSUE TITLE
File Manager: Uncaught Error: Fancytree assertion failed: topNode must be visible

### ISSUE THREAD

**Issue by bobrain008** [authentic-theme/authentic-theme#1213]
Hello, 
I don't know if related but the tree doesn't stay in place on the bottom, not only it vertically overflows but it also repeats elements from the parent folder...
here the screen

![Image of file manager overflows](http://i64.tinypic.com/14cd7jb.jpg)

and on console I have:
`Uncaught Error: Fancytree assertion failed: topNode must be visible` from bundle.min.js

**Comment by rostovtsev** [comment]
I've checked the code and container is always generated prior to tree initialisation. I don't see how it would be possible? 

Please provide steps to reproduce it.

There was familiar bug in mail folders, that I fixed earlier today.

**Comment by rostovtsev** [comment]
By the way, I remember fixing this issue very long time ago.

What is your theme/Webmin version?

**Comment by bobrain008** [comment]
What is your theme/Webmin version?

> By the way, I remember fixing this issue very long time ago.
> 
> What is your theme/Webmin version?

Webmin version | 1.894
Theme version | Authentic Theme 19.20-beta5

**Comment by bobrain008** [comment]
I recently updated from beta 2 because of not updated Webmin...maybe that was present on beta 2 and it was a upgrading issue about previous temp files? Don't know, if it happens again will let you know...

**Comment by rostovtsev** [comment]
> Please provide steps to reproduce it.

I'd be appreciate if you could summarise of when/how does it happen to you. I can't reproduce it.

**Comment by rostovtsev** [comment]
Okay, I have reproduced it. Thank you for reporting!

**Comment by rostovtsev** [comment]
..and for all this time, I could not reproduce it again. It seems like FancyTree bug, actually. I update to the latest plugin version.

Let's expect it to be fixed, unless it comes up again on you with new upcoming Webmin 1.900 and upcoming theme 19.20.

**Comment by 7starsone** [comment]
yes, I still have this issue on 19.21

**Comment by rostovtsev** [comment]
I would like to know how to reproduce it?

**Comment by 7starsone** [comment]
If I only knew...unfortunately until now that was random

**Comment by 7starsone** [comment]
![related](http://i67.tinypic.com/mj4jt0.jpg)

maybe related to this? I noticed that it may happen if you let the window opened for a while and come back to that window...so maybe network related?

**Comment by rostovtsev** [comment]
This error has been nail and fixed, finally!

Thank you for reporting!
