### ISSUE TITLE
Blank windows in system statistics

### ISSUE THREAD

**Issue by expertdecisions2** [authentic-theme/authentic-theme#1214]
Since last Authentic Theme update, system statistics shown correctly when selecting framed theme but with _authentic theme all I get is a blank window.
Pls see attached screenshot.

CentOS Linux 6.10
Webmin version | 1.894 | Usermin version | 1.741
Virtualmin version | 6.04 Pro | Theme version | Authentic Theme 19.20-beta6
Kernel and CPU | Linux 2.6.32-754.6.3.el6.x86_64 on x86_64
Processor information | Intel(R) Xeon(R) CPU E3-1220 v3 @ 3.10GHz, 4 cores

![screenshit](https://user-images.githubusercontent.com/9258503/47288053-a8786880-d5f4-11e8-938f-f826e9e5e3ed.png)

**Comment by rostovtsev** [comment]
Oops. Thank you very much for reporting it!

Fixed that. Pull the latest dev version using theme configuration to double-test.

**Comment by expertdecisions2** [comment]
Ok, it works again.
Sorry for the delay in my answer , I was just out for vacations
