### ISSUE TITLE
Theme: Latest update 19.20-beta6 doesn't work with older Webmin

### ISSUE THREAD

**Issue by TMTYD** [authentic-theme/authentic-theme#1216]
Hi

habe soeben das update auf beta6 durchgeführt, nun wird aber nicht mehr das dashboard angezeigt

**Comment by rostovtsev** [comment]
Schönen Tag,

Ja, das liegt an Inkompatibilität. Für Theme muss die neueste Änderung auch für Webmin installiert sein. Sie müssten `. / update-from-repo.sh` ausführen, damit es funktioniert.

Die Nachricht, die beim Thema Upgrade erscheint, warnt den Benutzer davor.

Viel Glück.
