### ISSUE TITLE
How to replace the logos on main tabs?

### ISSUE THREAD

**Issue by AlexShapka** [authentic-theme/authentic-theme#1217]
Ilia, we'd like to completely customize the look of the control panel, so looking for proper way to get the logos for Webmin and Virtualmin (for that matter for Cloudmin too) replaced with custom ones. How do we do that?

**Comment by rostovtsev** [comment]
Sasha, hi.

You can type in search bar, in navigation menu, `logo` - you will be taken there. Besides, upcoming release will have an ability to add [background to login page](https://github.com/authentic-theme/authentic-theme/issues/1195).

You can also use CSS/JS extensions to run any code you need to apply any imaginary modifications.

**Comment by AlexShapka** [comment]
Ilia,

I meant logos in on the main tabs and not the theme logo.
<img width="207" alt="screen shot 2018-10-27 at 7 35 50 pm" src="https://user-images.githubusercontent.com/9372724/47606706-92690e80-da1f-11e8-9194-11994339bfab.png">

**Comment by rostovtsev** [comment]
Yes, been busy with the patch. Will come back to you after I finish my home chores.

**Comment by rostovtsev** [comment]
Okay,

 Try the following. You can use theme CSS extension, for example, to replace Webmin icon with G icon, using _:before_ selector. 

```
.wbm-webmin:before {
    content: '\f01a';
}
```

You might need to create your own icon/font pack, which you could address later as a content.

Good luck.

**Comment by AlexShapka** [comment]
Works like a charm! Thanks, Ilia!
