### ISSUE TITLE
komische zeichen im titel name

### ISSUE THREAD

**Issue by TMTYD** [authentic-theme/authentic-theme#1219]
Hi Leutz

habe bei jedem Link den ich aufrufe solche "a€" Zeichen im Name, siehe screenshoot

![zeichen](https://user-images.githubusercontent.com/29516076/47780138-1579b580-dcfb-11e8-99a3-5fc66c0be107.png)

**Comment by rostovtsev** [comment]
Sie können diese Zeichen nicht entfernen. Sie erscheinen aufgrund einer fehlerhaften Kodierung. Sie müssen zu _Webmin/Sprache und Design von Webmin ändern_ und Ihre Sprache auf _UTF-8_ einstellen.


Sie können die aktuell eingestellte Codierung überprüfen, indem Sie in der Browser-Konsole `get_server_data ('charset')` ausführen und die Ausgabe sehen.


Möglicherweise gibt es auch andere Optionen.

**Comment by TMTYD** [comment]
Da habe ich schon DE UTF-8 eingestellt, dennoch wird es angezeigt

**Comment by gnadelwartz** [comment]
Das ist seltsam, sollte mit utf-8 nicht passieren. Welchen Browser und os hast du?  Passiert das auch mit DE ohne utf-8?

**Comment by TMTYD** [comment]
ja beides, browser nutze ich ff
