### ISSUE TITLE
Dashboard : Perl execution failed  version 19.20-beta6

### ISSUE THREAD

**Issue by lukesUbuntu** [authentic-theme/authentic-theme#1220]
Just updated to version 19.20-beta6 and this shows up when going to dashboard its only on dashboard menu.

![image](https://user-images.githubusercontent.com/6184757/47845551-3987e480-de2a-11e8-8ecb-2fedf1291482.png)

theme version: 19.20-beta6
virtualmin version: 6.04.gpl
webmin version: 1.894

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by lukesUbuntu** [comment]
Issue still exist still pulling in last update should i wait for changes to be pushed?
![image](https://user-images.githubusercontent.com/6184757/47847265-88844880-de2f-11e8-8a19-58342221f87f.png)

**Comment by rostovtsev** [comment]
Actually, it's part of Webmin. Can you please go to `/usr/libexec/webmin` and run `./update-from-repo.sh` - it should solve your issue.

**Comment by lukesUbuntu** [comment]
Can confirm resolved thanks closing..

**Comment by rostovtsev** [comment]
Appreciate!
