### ISSUE TITLE
Change width of column in MySQL module.

### ISSUE THREAD

**Issue by MorningSleeper** [authentic-theme/authentic-theme#1221]
I seem to recall in MySQL module clicking the View Data button at bottom of a table and on subsequent page being able to hover mouse over column separator line in header and dragging it to increase or decrease the width of a column but it is not working for me, using 19.20-beta6.

![columnseparator](https://user-images.githubusercontent.com/8920632/47890862-0f282e00-de0e-11e8-96e6-b6c17c615847.PNG)

**Comment by rostovtsev** [comment]
We opt-out in favor of having server to manage table sorting. That feature was tide to particular code. I will take a look if it's possible to do both.

**Comment by rostovtsev** [comment]
Fixed. Please give it a try.

**Comment by MorningSleeper** [comment]
Thanks, works great.

**Comment by MorningSleeper** [comment]
Don't know if this is a bug or enhancement request but when viewing MySQL table data and dragging the edge of one or more column headers to adjust width of column(s) and then clicking the left or right arrow at top to go to last or next page it does not remember the column widths.

**Comment by rostovtsev** [comment]
Sure, good point. 

Added it on the latest commit. Give it a try please.

_Note:_ It will also remember different positions upon different pages/tables.

**Comment by rostovtsev** [comment]
There were few fixes after my last comment. In case you'd updated right after my previous comment, please update once again.
