### ISSUE TITLE
Error - Perl execution failed

### ISSUE THREAD

**Issue by expertdecisions2** [authentic-theme/authentic-theme#1223]
I'm getting this since a few days ago when selecting Dashboard

HTTP/1.0 500 Perl execution failed Server: MiniServ/1.894 Date: Sun, 4 Nov 2018 19:34:23 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed
Can't use an undefined value as a HASH reference at /usr/libexec/webmin/authentic-theme/authentic-lib.pm line 1132.

CentOS Linux 6.10
Webmin version 1.894
Virtualmin version 6.04

I Can't say the Authentic Theme version as I'm unable to display the dashboard.

**Comment by rostovtsev** [comment]
You need to update to the latest Webmin from the repo or wait for another beta/release version.

It's been fixed days ago.

**Comment by expertdecisions2** [comment]
TKS
Curious, it only happens in one of the servers I administer, all of them using same versions, the only difference I the server with the error uses Virtualmin Pro whilst the other s are working with Virtualmin GPL. I'll have a deeper look

**Comment by expertdecisions2** [comment]
OK, updating Webmin to  1.894.1104.0106 did the trick

Thanks again

**Comment by rostovtsev** [comment]
Added a fix anyway, to address missing system information.

**Comment by MarkusVolk** [comment]
I have a similar problem. Authentic Theme 19.16 is working. If updating to 19.21 im getting this:

Can't use an undefined value as a HASH reference at /usr/libexec/webmin/authentic-theme/authentic-lib.pm line 1108.

Updating to webmin 1.900 didn't do the trick for me
