### ISSUE TITLE
Theme: Automatic scrolling control (pause on user input)

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1224]
If i for example run a cron job by pressing `Run now` this will bring up a output window but if i try to scroll horizontal (left to right) it won't work because when something get updated in the window it jumps back to the left side again.

I have `Enable automatic page scrolling for progressive output` and `Hide persistent vertical scrollbar` set to Yes.

Authentic Theme 19.20-beta5

**Comment by rostovtsev** [comment]
Yes, it's expected - once updated, it resets the page over and over again.

What is the expected behavior? If you expect to keep the scroll and/or selection, it's not going to be possible.

**Comment by Sopor-** [comment]
How about adding a button (check mark) that could easy turn off the auto scroll so it will be possible to scroll manually?

**Comment by rostovtsev** [comment]
Ohh.. Okay, I'll do it.

**Comment by lunarovic** [comment]
You also can't scroll vertically to see the upper lines of output until it's finished. Not a big deal, I can either see it later or if it's urgent, I can zoom out or just Ctrl+A and then paste it somewhere. :)

By the way, a year or two ago, I remember you could scroll vertically, but the scroll was sometimes stuck and you couldn't see the last lines, so looks like that was fixed, but now you can't scroll up anymore. But it's better this way! :) Really no need to put time into this, I just wanted to write my thoughts.

**Comment by rostovtsev** [comment]
Thanks, guys. I'll see if I can make it possible to disable it on the fly and not break anything. It should be possible. :smile:

**Comment by rostovtsev** [comment]
..or finally try to make proper implementation of console-like scrolling - when you select anything or scroll up, scrolling stops but when you get to the bottom of the page, scrolling gets activated.

**Comment by rostovtsev** [comment]
Okay, there is no need anymore to disable automatic scrolling to see/read particular output before the progress ends, as now, anytime you scroll page up a little bit, it will stop automatic scrolling and if you manually scroll to the bottom again, the automatic scrolling will restart.

It's the same behaviour now, as in most consoles on progressive output.

Please give it a try and share your experience.
