### ISSUE TITLE
Pin/unpin side slider - don't close when unpin

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1226]
This new `Pin/unpin side slider` is great but i believe it should not close the side slider when i unpin it. It should only be unpinned. Is this something you can change?

**Comment by rostovtsev** [comment]
Yes,

The same logic now will be applied to the navigation menu as well.

Although, when using hotkeys, both navigation and side slider will collapse immediately.

Give it a try
