### ISSUE TITLE
Theme: New favicon

### ISSUE THREAD

**Issue by lunarovic** [authentic-theme/authentic-theme#1227]
I don't know if it's just me, but the current favicon looks kinda ugly. I think you improved it a bit, but it's still the same icon. What does it represent anyway? Sites webmin.com and virtualmin.com have different favicons, and I think they are prettier and more appropriate.

Also, a favicon could be taken from the hostname, maybe as an option in settings. This could be especially useful for server admins who manage multiple Webmin servers, and then when they have multiple tabs open, they could more easily recognize which one to click.

**Comment by rostovtsev** [comment]
Hi,

Yes, great idea. I will play with this tomorrow. All kind of design and icon making is a very painstaking process.

19.20 release going to be huge, with so many nice improvements! :smiley_cat:

**Comment by rostovtsev** [comment]
I have added the individual favicons. This is how they look like. I will give more testing  for it tomorrow/monday. I will discuss with the team if putting them in the round white circle would make them look nicer.

Example:

![screenshot from 2018-11-10 17-53-23](https://user-images.githubusercontent.com/4426533/48305273-b1e05b00-e538-11e8-87af-14c47a38efa6.png)


Please give it a good try, and share your thoughts.

**Comment by rostovtsev** [comment]
Be the way, new favicons will support embedding as shortcut properly on all OSs, like Desktop, Android and iOS.

**Comment by lunarovic** [comment]
Wow, they're great! I think they would look uglier with a white circle, they're perfect the way they are now (transparent bg).
