### ISSUE TITLE
Dashboard not showing

### ISSUE THREAD

**Issue by Abasz** [authentic-theme/authentic-theme#1228]
After updating to beta 6 dashboard no longer shows up, only recent logins:

![image](https://user-images.githubusercontent.com/32517724/48317705-5b395680-e5f6-11e8-889d-8992bd973c7d.png)

In the console I can see an error message: "Manifest: Line: 1, column: 1, Unexpected token." but no other error is visible.

furthermore, I no longer have access to theme extentions, as when I click on the button in theme config, reloads the page

System Ubuntu 18.04
running with proxypass
latest (1.894) webmin

thanks

**Comment by rostovtsev** [comment]
This issue has been reported twist for the past days.

You need to install very latest Git version of Webmin, using `update-from-repo.sh script`.
