### ISSUE TITLE
Issue with filemanager and special characters

### ISSUE THREAD

**Issue by ochbob** [authentic-theme/authentic-theme#1230]
Hello, 

still me and my issues :O

is there a way to deal with this kind of issue with the file manager ?

http://www.noelshack.com/2018-46-1-1542034921-capture.jpg

my webmin language user is set to FR.UTF8.

Thank you.

**Comment by rostovtsev** [comment]
What is the output of the command ran in browser's console?

```
get_server_data('charset')
```

**Comment by rostovtsev** [comment]
You need to make sure that _Webmin/Modification de la langue et du thème_ is actually having it also set to `FR.UTF8` (or default to _utf-8_ version). Also make sure your browser detects it correctly.

If you look at my File Manager instance with French in _utf-8_, it works just fine.
![screenshot from 2018-11-13 18-14-38](https://user-images.githubusercontent.com/4426533/48422712-484a9180-e770-11e8-8366-6eb1c7754669.png)

Example of the settings:

![screenshot from 2018-11-13 18-18-06](https://user-images.githubusercontent.com/4426533/48422836-83e55b80-e770-11e8-82a5-15dcb4ebab92.png)

**Comment by ochbob** [comment]
get_server_data('charset') return to me => "UTF-8"

and webmin is set just like you:

http://www.noelshack.com/2018-46-2-1542124929-capture.png

**Comment by rostovtsev** [comment]
Maybe you could update to the latest development version to see if the issue still exists for you?

Try running `./update-from-repo.sh` script from inside Webmin directory.

**Comment by ochbob** [comment]
Not better :/

Still the same issue.

**Comment by rostovtsev** [comment]
Then check other browser and its encoding settings.

**Comment by ochbob** [comment]
Same issue on Edge and FF (and chrome my default web browser).

get_server_data('charset') return to me => "UTF-8"

**Comment by rostovtsev** [comment]
What are the other settings in _Webmin/Webmin Configuration/Language and Locale_ you have set?

![image](https://user-images.githubusercontent.com/4426533/48561458-0e5cc500-e901-11e8-9740-e59121ed127e.png)

**Comment by ochbob** [comment]
Did not see your feedback, and I still encounter the same issue despite the years, which it's very annoying because I can't interact (rename/delete/move) with file who have those characters.

**Comment by iliarostovtsev** [comment]
Upcoming Webmin 1.950, Usermin 1.800 release, and new Authentic Theme 19.50 will have all of those issues fixed. It will also have complete translations for French and many other languages.

I double checked, if this issue exists with latest development patches, and I can confirm, that issues with charsets will not be happening any longer.
