### ISSUE TITLE
I forced updated the theme for 19.20 beta and now it shows a blank white page!

### ISSUE THREAD

**Issue by Shillos** [authentic-theme/authentic-theme#1231]
There must be a bug on this latest issue i just updated it and got a blank white page with nothing on it. How can I fix this?! Please help!

**Comment by Shillos** [comment]
Any possible workaround from the shell would help!

**Comment by rostovtsev** [comment]
Hi,

Here is what'll do for the next release. I will stop showing update notice for **releases**  that have incompatibly issue.

To work-around the problem, go to the theme directory and run:

```
./theme-update.sh -release
```

**Comment by 7starsone** [comment]
isn't it better to wait for the Webmin update? I know that's slow...eg. here on CentOS (don't know why) but maybe worth the wait...
or also, could Jamie or you create a beta update by click instead of that manual command?
Thanks 👍

**Comment by rostovtsev** [comment]
We're actually in sync with Jamie. But I have to go first, as he includes the theme into the main package and not visa versa.

I will make a patch tonight/tomorrow to make sure that notifications for new releases are not shown, in case there is incompatibly issue.

**Comment by Shillos** [comment]
I don't see a themes directory in my /usr/share/webmin or is it somewhere else? I just confused why there isn't a directory called themes anywhere!

**Comment by Shillos** [comment]
Ops! found it as the name of the authentic-theme. shouldn't webmin make it so it is as separate in a directory for all themes like all usual software does?! a bit confusing thou!
