### ISSUE TITLE
Webmin 1.894.1114.1629 and compatibility issues

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1232]
I have updated to Webmin 1.894.1114.1629 by running the `update-from-repo.sh` but Authentic will still warn me about compatibility issues

![image](https://user-images.githubusercontent.com/5789283/48497709-fddf1880-e834-11e8-89e8-214acfa1c279.png)

**Comment by rostovtsev** [comment]
The message say `unrelased version`. What makes you confused her? Unreleased is unreleased.

Like I mentioned in the previous post, notification for releases with broken dependencies will not be shown, after upcoming patch.

**Comment by Sopor-** [comment]
Yes, but last time i was going to update the Authentic theme i got the same message, but after updating Webmin (to another dev) the message was gone. So why is it showing when i'm running latest dev Webmin?

**Comment by rostovtsev** [comment]
Because this theme was meant to run on 1.900. Technically it could be 1.894, you're right.

**Comment by rostovtsev** [comment]
...auch.. _1.990_ - this version is a bug!

**Comment by rostovtsev** [comment]
I have made a patch, that will prevent showing updates for **_theme releases_** with dependency issue. If there is no dependency issue, than it would be shown (in case it's enabled in settings). It would also be shown to folks on dev (beta) channel updates.

**Comment by rostovtsev** [comment]
Okay, and to be clear why not 1.894. Because 1.894 is in Virtualmin repo already as a package, but there were more changes afterwards done to Webmin repo. Practically, we needed to bump version to 1.895 right after pushing it as a package, then using 1.895 in dependencies would work just fine.
