### ISSUE TITLE
19.20 removed live monitor dials

### ISSUE THREAD

**Issue by adiastra** [authentic-theme/authentic-theme#1233]
After installing 19.20, the live monitor dials at the top of the dashboard are gone as well as information about the system (System Information)

**Comment by rostovtsev** [comment]
Try installing Git version of Webmin or wait for upcoming release 1.900.

**Comment by adiastra** [comment]
its not critical, how long is the wait?

**Comment by adiastra** [comment]
Debian Ubuntu FYI

**Comment by rostovtsev** [comment]
I can not tell you how much exactly more time it would take. It might happen within few days or take few weeks at max!
