### ISSUE TITLE
Authentic Theme update - Blank page after logging in

### ISSUE THREAD

**Issue by danfix** [authentic-theme/authentic-theme#1234]
Hi,

I updated to the latest version, now the dashboard is blank.
Is there a way to down grade the version?
What is the path to over write the new version of the theme with the older version?

Thanks

**Comment by TheGhostHybrid** [comment]
I'm having this issue as well.  Here is a bit of the source code that might be relevant:
`
HTTP/1.0 500 Perl execution failed
--
  | Server: MiniServ/1.890
  | Date: Thu, 15 Nov 2018 01:17:15 GMT
  | Content-type: text/html; Charset=iso-8859-1
  | Connection: close
  |  
  | <h1>Error - Perl execution failed</h1>
  | <p>Undefined subroutine &WebminCore::convert_to_json called at /usr/share/webmin/authentic-theme/authentic-funcs.pm line 72.
  | </p>
`

**Comment by rostovtsev** [comment]
Hi,

There were explicit notice in **red**, explaining that this version of the theme is incompatible with current Webmin releases.

Now, either downgrade the theme or upgrade Webmin using console update scripts.

Nothing special is required.

**Comment by TheGhostHybrid** [comment]
This is my first time using Webmin, and while I know my way around a command line, it wasn't until I found the previous thread (made seven hours prior to this one) that I was able to figure it out.

Plus, I was incredibly tired while doing the update, so I didn't even notice the red.

**Comment by rostovtsev** [comment]
No matter how tired you are, it wouldn't be possible not to notice red and install it, as the link to force-install is on the inside of the red notice and hard to find.

I have made a patch, that will prevent showing updates for theme **_releases_** with dependency issue. If there is no dependency issue, than it would be shown. It would also be shown to folks on dev (beta) channel updates.

**Comment by TheGhostHybrid** [comment]
There's no need to be rude.  Everyone perceives the world differently, and I was simply expressing how it happened on my end.  There have been times when, even though something was right in front of my face, I simply didn't notice.

Regardless, thank you for responding and making the patch.  I hope you have a very pleasant rest of the week!

**Comment by rostovtsev** [comment]
You are very welcome. 🙂

There is no way I would let myself to be rude.

Have a good weekend too.

**Comment by danfix** [comment]
Thanks for the updates on this.

I managed to fix this by downloading an older version and renaming the newer version folder to authentic-theme-19.20. 
Then i copied the older version to /usr/libexec/webmin/authentic-theme/
Back up and running ok now.

**Comment by rostovtsev** [comment]
Yes, but the easiest way is to tell update script to pull particular version.

For example:

```
./theme-update.sh -release:19.19
```
