### ISSUE TITLE
The end of the world is coming ?

### ISSUE THREAD

**Issue by ochbob** [authentic-theme/authentic-theme#1235]
Hi,

after theme update to 19.20, it seems to be the end of the world ? (my dashboard says it)

Should i worry ?

![capture](https://user-images.githubusercontent.com/16723954/48536316-80f08500-e8ae-11e8-8fdd-f9a105aebda1.JPG)

Btw, is this a joke  or something else ? ^^

**Comment by swelljoe** [comment]
New feature...but, not quite running normally yet (it's a way for updates from webmin.com to be displayed to users in the UI, like security updates, etc.). That's the test message, and will go away when the new Webmin is released (it was a joke that wasn't actually meant to be seen by anybody by Ilia for testing, but well...it didn't get changed before 19.20 went out).

**Comment by 7starsone** [comment]
😄 🤣 👍

**Comment by rostovtsev** [comment]
:laughing: Yes. It's new messaging system. The theme is out and if you pulled the latest Webmin too, you would see it. Majority of people are not going to see it.

It's running quite normally, Joe! :smile: You know about the end of the world - means, message delivered.

Besides, I wasn't the one who came up with the message itself, even though I liked the humor!

**Comment by ochbob** [comment]
I had to update webmin from the script without paying attention :sweat_smile: :

Thank you everyone, I understand better now, and I am relieved that the end of the world is not coming. :smile: :laughing:

**Comment by jcameron** [comment]
I will cancel that test message
