### ISSUE TITLE
Webmin displaying blank page

### ISSUE THREAD

**Issue by demlasjr** [authentic-theme/authentic-theme#1236]
The last version is displaying me a blank page.
Checking the page source I'm getting this:

```
<h1>Error - Perl execution failed</h1>
--
  | <p>Undefined subroutine &WebminCore::convert_to_json called at /usr/share/webmin/authentic-theme/authentic-funcs.pm line 72.
  | </p>
```

Any solution? 

Thank you.

**Comment by rostovtsev** [comment]
😄 Yes, there is.

This is due to incompatibly.

Downgrade the theme:

`./theme-update.sh -release:19.19`

or update Webmin to latest Git version using:

`update-from-repo.sh`

**Comment by Kiuman** [comment]
Hei,
When I try to update the theme it complains that I don't have curl installed, but I can't install curl because it requires libcurl4 and I already have libcurl3 for urbackup-server (which is a requirement to have). Also, I don't want to update Webmin from a non release repository.
Is there any other way to downgrade the theme?
Thanks!

**Comment by rostovtsev** [comment]
:smile:  Yes! 

Download the [package](https://github.com/authentic-theme/authentic-theme/releases/download/19.21/authentic-theme-19.21.wbt.gz) and de-archive it to Webmin directory.

I wonder, how could you upgrade to the latest version if you didn't have `curl` at the first place?

**Comment by rostovtsev** [comment]
You could also `git clone https://github.com/authentic-theme/authentic-theme.git` from inside Webmin directory.

`/usr/libexec/webmin`

or

`/usr/share/webmin`

You could run 

```
whereis webmin
```
..to find where it is.

**Comment by Kiuman** [comment]
> 😄 Yes!
> 
> Download the [package](https://github.com/authentic-theme/authentic-theme/releases/download/19.21/authentic-theme-19.21.wbt.gz) and de-archive it to Webmin directory.
> 
> I wonder, how could you upgrade to the latest version if you didn't have `curl` at the first place?

I have it working again, I just added the json missing functions to web-lib-funcs.pl
But I'm going to downgrade using your instructions so I get a clean system.
Regarding on how I upgrade without having curl? no idea, I just did it via the web interface; maybe perl is using liburl3 and not curl directly?
Thanks for the help :) 👍
