### ISSUE TITLE
Background colour missing from left hand (dashboard)panel on Raspberry Pi after automatic update to webmin 1.900

### ISSUE THREAD

**Issue by joecurtis** [authentic-theme/authentic-theme#1237]
On one of my Raspberry pi computers, after updating through webmin  to 1.900 the background colour has gone from the left hand dashboard menu. Presumably downgrading authentic from 19.21 to 19.19 should sort this if I can find the instructions somewhere.
It has also happened on my Zotak system which is running Fedora 28.

**Comment by rostovtsev** [comment]
Did it become white? White is default now. 

You can choose any palette you want from theme configuration.
