### ISSUE TITLE
Missing module config button on "Read user mail"

### ISSUE THREAD

**Issue by lunarovic** [authentic-theme/authentic-theme#1238]
I see this page still exists: `/config.cgi?mailboxes` but I can only get there manually, the cog icon in the upper-left has disappeared from the `/mailboxes/` page.

**Comment by jcameron** [comment]
Thanks for reporting this - I see it too, although only when using the new Authentic theme.

@rostovtsev , any idea why the config link doesn't appear in the Read User Mail module (even when logged in as root) ?

**Comment by lunarovic** [comment]
Yes, that button was definitely there in the previous versions, because I used it, I just don't remember when exactly did it disappear, but I'm sure it was there 3 or 4 version updates ago.

**Comment by rostovtsev** [comment]
Duh, I'm afraid it's a bug

**Comment by rostovtsev** [comment]
It's fixed. I will add it to 19.22 in couple of days.

Thank you!
