### ISSUE TITLE
File editor: color coding issue in .php files

### ISSUE THREAD

**Issue by lunarovic** [authentic-theme/authentic-theme#1239]
In a .php file, if there is a quote (`'`), double quote (`"`) or an HTML entity (e.g. `&#39;`), for example inside of HTML tags, it will break color coding until the end of the file.

Example:
`<p>After the apostrophe, editor's color coding will break.</p>`
(you can create a new .php file and put this in to see)

**Comment by rostovtsev** [comment]
Hi,

What you are suggesting as an example is not a valid PHP syntax. :wink: 

It should be wrapped in special tags, example:

```PHP
<?php
  echo "<p>After the apostrophe, editor's coloring will break.</p>";
?>
```

**Comment by lunarovic** [comment]
Lol, you are 100% right! 😌 However, it seems that a lot of editors (offline and online) don't break color coding in that case, I just tested a lot of them and found that color coding breaks in only one of them. I was writing bad code obviously lol, but it seems to be acceptable for a lot of editors, I don't know why.

**Comment by 7starsone** [comment]
pardon, what editor? I tried with `notepad++`, `sublime text`...
so, good editors treat that as an error, obviously 😄 
please use something normal

**Comment by lunarovic** [comment]
@7starsone Nope.

![image](https://user-images.githubusercontent.com/2381553/48675506-f764df80-eb59-11e8-8f7c-543d1b39dba7.png)

![image](https://user-images.githubusercontent.com/2381553/48675528-32ffa980-eb5a-11e8-8dfd-99779e2d8b45.png)

**Comment by 7starsone** [comment]
hey, but do you know php? Are you sure?
You need to write
`<?php`
at the beginning of any php file...
is that ok to you? 😄

**Comment by 7starsone** [comment]
may be an exception when the file has mixed content...
eg. you start with doctype html, then even starts some `<?php ... ?>`
I did test and here you're right, just because the mixed content is not taken into consideration (this may be a missing feature or a bug, you decide...)
![syntax](http://i68.tinypic.com/23jpbty.jpg)

so, if mixed content, it should do it, if not mixed content, instead you shouldn't save it as php file

**Comment by lunarovic** [comment]
@7starsone Why are you trolling? Of course I use `<?php`, otherwise PHP code wouldn't work... Take a look at this:

![image](https://user-images.githubusercontent.com/2381553/48676552-9e507800-eb68-11e8-859e-b4285a80f9b2.png)

![image](https://user-images.githubusercontent.com/2381553/48676553-a9a3a380-eb68-11e8-8623-b45831095abf.png)

All the PHP code is inside the PHP tags, and HTML is outside of PHP, so that's why that should not be color coded as PHP. I see Sublime will do the same color coding as Webmin, but only if the code is inside the `<?php ... ?>`:

![image](https://user-images.githubusercontent.com/2381553/48676694-95f93c80-eb6a-11e8-884f-73b0c746b3de.png)

But I'm not writing HTML inside PHP! That's the main point.

I didn't use echo because for example in one case I had a 300 line HTML file (index.html), and I needed to add just one PHP line inside, so I just renamed the file to index.php and added one `<?php ... ?>` line.

This obviously works correctly everywhere, and I use those "good editors" as you said, so you are wrong when you said they treat that as an error.

**Comment by 7starsone** [comment]
please, see the comment above...simply, I think that Ilia didn't expect the mixed content when implemented

**Comment by lunarovic** [comment]
Yes, I see your comment, it was constructive for a change, but before that you were accusing me that I was wrong and that "good" editors color code the same as Webmin, but I hope you see the facts now.

**Comment by 7starsone** [comment]
> "...you are wrong when you said they treat that as an error."
no, that's an error if you write it as your above example...I just commented your (wrong) example, that's it.
Please, when you report something, you should be more explicit and clear. Nothing more.
Thank you

**Comment by lunarovic** [comment]
No, it still stands, you can try again, use the example from my first message, name the file `something.php`, put that exact line in Sublime or Notepad++, and put the exact same line in Webmin file editor. It's different.

**Comment by 7starsone** [comment]
In my opinion, in that case Ilia is right, because if no php code at all inside a php file, the .php extension is a real nonsense.
So, (if he wants) he should fix the mixed content.

**Comment by lunarovic** [comment]
Of course that is nonsense, because that was just an example I made up, which I tried to make as short as possible to demonstrate easily. Of course I don't put a .php extension to pure HTML files. I just use mixed content a lot.

**Comment by rostovtsev** [comment]
@7starsone 
> so, if mixed content, it should do it, if not mixed content, instead you shouldn't save it as php file

![image](https://user-images.githubusercontent.com/4426533/48705831-664e4100-ec0b-11e8-8e39-a169a323774b.png)

With mixed content and valid PHP syntax it works just fine.

@lunarovic Even though desktop file editors don't break highlight for invalid syntax, it doesn't mean much. Web browser editor and desktop editor can not be compared, I think.

I will not fix invalid syntax highlight! :wink:

**Comment by lunarovic** [comment]
> With mixed content and valid PHP syntax it works just fine.

But wait, you wrote `test`, and why not `echo "test"` inside `<?php`? So if you think it's fine to write `test` without echo, then you should be able to write anything without echo, right?

Also, if you are writing HTML like that, outside of `<?php` in a .php file, and say that's normal, then why don't you try to use tags for text, like `<p>` or `<div>`? Of course, outside of `<?php`, like the rest of your HTML, like this:

![image](https://user-images.githubusercontent.com/2381553/48707432-b9ba9200-ebff-11e8-90f7-c944bcee9431.png)

So I made exactly the same file as you did in your last message, I just added another simple HTML on line 8, completely correctly, outside of `<?php` and inside `<body>`. And you can see what happens. It seems that the editor doesn't detect `<?php` and `?>` at all.

By the way, I noticed that for .html files there is color coding only on classes/ids and scripts. Tags are not colored for example. And HTML is selected for syntax.

> Even though desktop file editors don't break highlight for invalid syntax, it doesn't mean much. **Web browser editor** and desktop editor can not be compared, I think.

http://sandbox.onlinephpfunctions.com/

http://phptester.net/

https://www.tutorialspoint.com/execute_php_online.php

https://rextester.com/l/php_online_compiler

https://repl.it/repls/PuzzlingSnowWorkers

http://www.compileonline.com/execute_php_online.php

http://phpfiddle.org/

https://3v4l.org/

https://www.jdoodle.com/php-online-editor

...

> I will not fix invalid syntax highlight! 😉

You don't need to really, I just think I have a point about mixed content, the Webmin file editor colors code differently than most (to not say all) other editors, and that's a fact.

**Comment by 7starsone** [comment]
please, Ilia, really not useful to change example...

just consider this, that's wrong without any doubt
![example](http://i66.tinypic.com/2v02048.jpg)

so, if you write a regular p with quote inside or just a text with quote inside, it breaks all the code....

**Comment by rostovtsev** [comment]
Okay, I see the source of the issue.

**Comment by rostovtsev** [comment]
Fixed. It will be added to 19.22 very soon.

Give it a try.

Thank you for reporting.
