### ISSUE TITLE
Theme: Respect system status module's user configuration

### ISSUE THREAD

**Issue by MarkusVolk** [authentic-theme/authentic-theme#1242]
I'm running webmin on my settop box with open-embedded thud. Authentic Theme 19.16 is working. If i update to 19.21 im getting this:

Can't use an undefined value as a HASH reference at /usr/libexec/webmin/authentic-theme/authentic-lib.pm line 1108.

I tried updating to webmin 1.900 ... didn't do the trick for me.

**Comment by rostovtsev** [comment]
https://github.com/authentic-theme/authentic-theme/commit/b2fc53fb6ac265607c5b956b8a8cb0ce548389ef

**Comment by rostovtsev** [comment]
In case you don't see the Dashboard, you would have to make sure that it's collected in System Status module. You can click refresh (recollect) button in Right Side Slider, when dashboard tab is activated.

**Comment by MarkusVolk** [comment]
Seems like the default setting for me is to show nothing .... so there was nothing to see :)

Changing to everything here did the trick

![2018-11-20_153544_082739556](https://user-images.githubusercontent.com/6180877/48780593-987aa400-ecda-11e8-973a-30e61a250f55.jpg)

It's not a bug at all

**Comment by 7starsone** [comment]
> Seems like the default setting for me is to show nothing .... so there was nothing to see :)
> 
> Changing to everything here did the trick
> 
> ![2018-11-20_153544_082739556](https://user-images.githubusercontent.com/6180877/48780593-987aa400-ecda-11e8-973a-30e61a250f55.jpg)
> 
> It's not a bug at all

sorry if that's totally hilarious 😄 😆 🤣 anyway, always more to learn...

**Comment by MarkusVolk** [comment]
Currently I'm using this line in do_install_append to workaround the issue and to make it work directly after pakage installation

echo "show=*" > ${D}${sysconfdir}/webmin/system-status/root.acl

**Comment by rostovtsev** [comment]
It's fixed on the latest commit. Please try it!

**Comment by MarkusVolk** [comment]
Your fix has some effect. Systeminformation is displayed now but it's still empty
![2018-11-21_161703_621140413](https://user-images.githubusercontent.com/6180877/48850768-9f241c80-eda9-11e8-916a-bb2bcd97b5eb.jpg)

**Comment by MarkusVolk** [comment]
That's right. If i select one specific Information, it gets displayed. If i select all, everything is shown. But default here is still to show nothing. "Reset To Full Access" still leads to "Nothing gets shown"

**Comment by rostovtsev** [comment]
I will double check "Reset the fill access. And yes, on nothing selected, panel should not be displayed.

**Comment by rostovtsev** [comment]
Give it a new try. The empty panel will not be displayed. Everything works perfect now. (clear cache if you have issue).

_**Reset to Full Access**_ works as designed.

Thank a lot for reporting! :wink:

**Comment by MarkusVolk** [comment]
Great, thank you

impressive work
