### ISSUE TITLE
No `Show pin/unpin button` in the `Navigation menu options`

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1244]
I'm running 4 Webmin 1.900 with Authentic Theme 19.21, but only one of them have the option `Show pin/unpin button` in the `Navigation menu options`. This is the only Webmin i have made dev updates to.
I have cleared the cache in Firefox 63.0.3 but still nothing.

**Comment by rostovtsev** [comment]
Obviously, it's because you have installed the latest/development version of the theme.

19.22 release will have it.

**Comment by Sopor-** [comment]
Not what i can see:
`In order to make this option work, git command has to be installed on your system (installed and latest version 19.21)`
