### ISSUE TITLE
File Manager: Opening "root" every time on the first start

### ISSUE THREAD

**Issue by lunarovic** [authentic-theme/authentic-theme#1246]
Before, I could leave File Manager on the `/home` directory (I need that path the most) and later when I load it again, it will put me in `/home` again. Now it always loads the `/` path.

(If "Restore previously used tabs on first load" is set to Yes, it will just show the previously used path as a second tab, but `/` will still be loaded as the primary tab.)

**Comment by rostovtsev** [comment]
Yes, great. 🙂

It's known issue. I will fix it.

Thanks a lot for reporting.

**Comment by rostovtsev** [comment]
I have completely reworked tabs interactions on initial load.

The logic - if tab exists and requested via URL it will be selected, if not it will be opened once.

Give it a try.

**Comment by lunarovic** [comment]
I think this issue isn't fixed - could you please check it?

First I thought the problem is that the link for the File manager is this:
`https://domain:10000/filemin/index.cgi?path=/`

Because earlier it was just this:
`https://domain:10000/filemin/index.cgi`

But when I tested it without the path parameter, it was the same.

However, I found out how can I get the original behavior (to load the path from the previous session):
I copied the link to the FM (`https://domain:10000/filemin/index.cgi`) - with or without `?path=/` because it doesn't matter, and I pasted it in a new tab. Then suddenly it worked as it should, the previous session was restored. The root path (or the path from the parameter) shows briefly and then the previously used path loads.

Then I realized it is some kind of a problem with `?xnavigation=1`. When that parameter is in the link, the FM will not load the previous path, and it will go to root path instead, and show the previous path as a second tab.

Thank you.

**Comment by rostovtsev** [comment]
It's actually solved.

In the past if you reload the browser or click on the File Manager over again from navigation menu to initial its reload, the root path was always opened no matter what.

When now, it's not duplicated, if the tab was already opened before. 

It's impossible to avoid having root tab (requested from URL) to be there. It's just not multiplied. That was the point of the fix.

Does it make sense?

**Comment by lunarovic** [comment]
I think you are confusing this issue with #1247. The multiplication was fixed, but this is a different problem. Please read again my first post above, where I describe the issue.

Also, if you say it's impossible to avoid having root tab there because it's in the URL, why not change the FM URL then? Either delete the `?path=/` parameter altogether (as before) or make it equal to the last used path, for example `?path=/home`.

**Comment by rostovtsev** [comment]
Okay, I think it would make better UX, if after reload you would be taken back to previously used tab?

**Comment by lunarovic** [comment]
But that was the original functionality and that's why I opened this issue in the first place. This was already working before, and then it stopped working. FM would always open to the last path used, and then after an update it started to go to root path every time, and that's when I opened this issue.

**Comment by rostovtsev** [comment]
> This was already working before

I am afraid that this feature hasn't ever been implemented, until today.

Please install latest development version to give it a try. It should work as expected.

**Comment by lunarovic** [comment]
> I am afraid that this feature hasn't ever been implemented, until today.

Then how come you didn't say anything about that after I opened this issue and described that feature? Something like: "that wasn't even supposed to work that way before". Sorry, I am just very confused and curious. Did that work by accident before? Because it was a very useful feature/bug for me (lol).

In any case, thank you so much for your super speedy work! Appreciated as always. Without your theme, I would never use Webmin. :)

**Comment by rostovtsev** [comment]
> In any case, thank you so much for your super speedy work! Appreciated as always.

Thank you for your kind words.

**Comment by rostovtsev** [comment]
@lunarovic Hi. I was working on improvements of File Manager initial load time today, and had to remove formerly added feature, to automatically choose previously used tab (as going back to File Manager), due to current design flaws in the code. In the future, as I refactor the client-side of the code, it won't be a problem.

I just wanted to let you know. 

You are welcome to install latest dev version to see how it works now. Besides, for the past weeks, there have been done amazing number of other improvements, including new ability to list and run operations on millions of files, without any slowdowns.
