### ISSUE TITLE
File Manager: multiple same tabs restored

### ISSUE THREAD

**Issue by lunarovic** [authentic-theme/authentic-theme#1247]
When "Restore previously used tabs on first load" is set to Yes, and you go multiple times to the same path by clicking on the directories, the tabs for the same path will begin to multiply:

![image](https://user-images.githubusercontent.com/2381553/48978613-448f0700-f0ae-11e8-9580-a311a35ca78e.png)

I may be wrong, but I could understand this functionality if those were more complex tabs like browser tabs or IDE tabs, where you may have different things set up in each tab even though they are open on the same directory. But here I don't see any scenarios which could make the tabs different.

**Comment by rostovtsev** [comment]
Well, you can never know what user could want to do with having multiple tabs. 

I should be available, I think.

**Comment by lunarovic** [comment]
Yes, I was thinking about that too, it definitely looks like a feature and not a bug, but to me specifically the "Restore previously used tabs on first load" is useless because I constantly have to delete the extra tabs, so I keep it turned off. But it's OK.

**Comment by rostovtsev** [comment]
Yes, because [the other bug ](https://github.com/authentic-theme/authentic-theme/issues/1246) you created is valid and has to be fixed, so tabs wouldn't be growing on each load.
