### ISSUE TITLE
Theme: Warning modal for unsaved forms

### ISSUE THREAD

**Issue by lunarovic** [authentic-theme/authentic-theme#1248]
![image](https://user-images.githubusercontent.com/2381553/48978664-2ece1180-f0af-11e8-8d67-5532ac1420ef.png)

Issue 1: It only works on some pages (for example, your Theme configuration page). I know, this is a complex issue, pages are different etc.

Issue 2: After you've changed something and you use the search bar to go to some other page, the modal doesn't appear and nothing happens, you can't leave the current page. It only works if you click directly on a link, not via the search bar.

Issue 3: The Continue button briefly takes you to the page where you wanted to go, but then it reloads Webmin and goes to the start page.

Issue 4: When you click on the trash icon in the notification sidebar while some operation is going on (like updating packages), it will trigger the modal. If I press cancel, it will still remove the notification, so it seems that the modal is not necessary for that, because removing the notification will not interrupt an ongoing process.

**Comment by rostovtsev** [comment]
- [ ] 1. It also works for editors, and mostly was designed for it. As a bonus at _Theme Configuration_ page, when the theme options were changed but not saved - it returns this warning on navigating away, giving you a chance to return and save it. Should I add the same behaviour for _all forms_ is a good question? What do you think? Especially interested to hear from @swelljoe and @jcameron about this topic.

- [ ] 2. Yes, regular search doesn't work - but autocomplete items work fine. I **_will fix it_** for regular search.

- [ ] 3. Yes, it reloads it, and this only happens for Theme Configuration. It reloads the page not on all changed items - it monitors which items were change and reloads it, in case it makes sense. For example, if you changed navigation menu palette and didn't save it, it would be confusing to have it displayed with new color and then being reset/reverted back upon full page reload. What it lacks is a warning about reloading due to not saving it. I _**will add it**_.   

- [ ] 4.  Great point, and I _**will fix it**_ as well.

**Comment by rostovtsev** [comment]
Okay, I added global form change event listener to display nice message to prevent form data loss.

Give it a try.

**Comment by lunarovic** [comment]
Does the beta version of the theme require some new version of Usermin? Because when I click to force update theme, I get this message:

> Installing this version of Authentic Theme _19.21_ requires latest and/or possibly unreleased version of Usermin to work properly. There might be incompatible changes, that could stop the theme from working as designed. To bypass this warning, and force install the theme anyway _click here_, or upgrade Usermin to the latest development version first using console, by running `update-from-repo.sh` script from its directory.

That looks just like a warning, so I should click "click here"? :) And you will tell us if you make a beta version which requires some newer version of Webmin, right? :) Also, can I revert back to the stable version if needed?

By the way:
> Yes, regular search doesn't work - but autocomplete items work fine.

For me autocomplete doesn't work, that's what I was actually referring to before. I don't use search for the "real" search very often, mostly just for autocomplete.

**Comment by rostovtsev** [comment]
> Does the beta version of the theme require some new version of Usermin? Because when I click to force update theme, I get this message:

Yes, it requires Usermin 1.750, but it's not new; you haven't installed it yet. 

In theme configuration you could opt-out:

**_Install theme updates for Usermin as well_**   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Yes/_**No**_

Do you have Virtualmin installed? If so, Usermin hasn't been pushed yet. 

> That looks just like a warning, so I should click "click here"? :) And you will tell us if you make a beta version which requires some newer version of Webmin, right? :) Also, can I revert back to the stable version if needed?

Yes, I would. It's fully compatible with Webmin 1.900+

> For me autocomplete doesn't work, that's what I was actually referring to before. I don't use search for the "real" search very often, mostly just for autocomplete.

Everything should work with the latest commit. Points 3 and 4 I will fix a bit later.

**Comment by lunarovic** [comment]
Ok, I turned off the Usermin setting and now it's fine. Excellent, points 1 and 2 are fixed! 👌 I see the warning modal now works on all pages, and it now triggers when using search.

By the way, yes, I have Virtualmin, these are my versions:

Webmin version 1.900
Usermin version 1.741
Virtualmin version 6.04

Maybe you could put some sort of a mark next to authentic theme version (19.21) to know that I am on beta, like 19.21-beta or something. And if I'm on beta, on the theme config page, it shows like this:

> (installed version 19.21)

_"19.21" has no color_

While on stable version it's like this:

> (installed and latest version 19.21)

_"19.21" is colored green_

But beta is more "latest" than stable. :D So maybe write "(installed beta version 19.21)" or if you change the version name like I suggested above, then it would be "(installed version 19.21-beta)", which is ok too.

**Comment by rostovtsev** [comment]
> "19.21" is colored green

Done. Bumped to 19.22-beta1.

Thanks.

**Comment by rostovtsev** [comment]
Okay, point _number 3_ was added. Now, when a user changed theme configuration and didn't save it, on navigating away, and confirming it, the _**nice**_ _explanation message_ will appear:


![screenshot from 2018-12-01 20-09-01](https://user-images.githubusercontent.com/4426533/49331232-e6c95600-f5aa-11e8-94a9-597c90c24cb8.png)

**Comment by rostovtsev** [comment]
Point 4 has also been fixed.

Thanks for reporting.

Give it a try. :wink:

**Comment by lunarovic** [comment]
That's an amazing design of the modal, well done! 😮 And I confirm everything is fixed. :)
