### ISSUE TITLE
File Manager: Unforgiving of medium and low res displays

### ISSUE THREAD

**Issue by swelljoe** [authentic-theme/authentic-theme#1250]
File Manager seems designed for very high res displays. It gets funky looking on anything smaller than something like 850 pixels across. It's usable, as I can still scroll over, but it doesn't look great. (This screenshot shows my usual browser width on my 1080p display, and I know we've got users using quite a bit smaller than this on the regular. I don't think this can even be considered an unusually small display situation.)

![screenshot from 2018-11-25 23-05-25](https://user-images.githubusercontent.com/99768/48994101-0540d480-f107-11e8-9d64-4e9d5a08d811.png)

I'm not sure of the best way to handle it...maybe just allowing the border around the file list to expand to fit is the simplest, but maybe another container that gets a scrollbar would be better. Both are kinda clunky, but better than the current behavior.

**Comment by rostovtsev** [comment]
Joe, this is quite complex to achieve, as there is no straight forward solution for it.

Having to scroll only the overflowing table looks much better, I agree.

I will try to come up with the patch... :hourglass_flowing_sand:

**Comment by rostovtsev** [comment]
Okay, git it a try with the latest commit.

This is how it will look after upgrade:

![image](https://user-images.githubusercontent.com/4426533/49091330-a0a18900-f270-11e8-89f0-eb46f6beffed.png)
