### ISSUE TITLE
File Manager: Show total size

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1252]
When using the `Calculate selected space` in the File manager it would be nice if it could show the total size of selected folder/files below the size or at the top

![image](https://user-images.githubusercontent.com/5789283/49036675-a0de4d80-f1b8-11e8-8c5f-a818e4ee8036.png)

**Comment by Sopor-** [comment]
What do you mean? Should total size show up somewhere? Maybe i'm blind ...

**Comment by rostovtsev** [comment]
Yes, it should show up.

![image](https://user-images.githubusercontent.com/4426533/49069668-e2afd800-f23a-11e8-9adf-d5f55d22f009.png)

Then you should have it appeared at the top, in yellow label:

![image](https://user-images.githubusercontent.com/4426533/49069714-06731e00-f23b-11e8-9182-7567590a4d50.png)

**Comment by Sopor-** [comment]
I can't reproduce this so i'm closing it.
