### ISSUE TITLE
File manager: no busy indicator the second time i run calculate selected size

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1253]
The first time i run the `Calculate selected size` i can see a spinning busy wheel for every folder, but if i run it a second time it won't do a thing, or it looks like it is not doing anything but then suddenly i can see the total size increase. If i do a re-calculation the size at each folder should be replaced (or show them both) with the spinning wheel so i can see that something is going on.

**Comment by rostovtsev** [comment]
Fixed. Thank you.
