### ISSUE TITLE
Perl execution failed spam_level_char_def

### ISSUE THREAD

**Issue by Doemela** [authentic-theme/authentic-theme#1254]
When I try to save SpamAssassin Mail Filter -> Message Modification in usermin I get:

`/spam/save_report.cgi : Perl execution failed : Can't locate object method "in" via package "spam_level_char_def" (perhaps you forgot to load "spam_level_char_def"?) at /usr/share/usermin/spam/save_report.cgi line 57.`

`if (&version_atleast(2.6)) {
	for($i=0; defined($addfor = $in{"addfor_$i"}); $i++) {
		next if (!$addfor);
		$addheader = $in{"addheader_$i"};
		$addtext = $in{"addtext_$i"};
		$addheader =~ /^\S+$/ ||
			&error(&text('report_eaddheader', $i+1));
		push(@adds, "$addfor $addheader $addtext");
		}
	if (!in{"spam_level_char_def"} && &char_check($in{"spam_level_char"})) {
		push(@adds, "all Level _STARS(".$in{ "spam_level_char"} .")_" );
		}
	&save_directives($conf, "add_header", \@adds, 1);
	}`

Operating system | Debian Linux 9
Webmin version | 1.900
Usermin version | 1.741
Virtualmin version | 6.04.gpl
Authentic theme version | 19.21
Perl version | v5.24.1

**Comment by jcameron** [comment]
Did you try upgrading to Usermin 1.750 ? It should fix this.
