### ISSUE TITLE
Bootup and shutdown module broken again

### ISSUE THREAD

**Issue by matrix200** [authentic-theme/authentic-theme#1255]
It no longer won't open (nothing happens when I try to open).
Not even empty editor like the last time it broke down.

**Comment by rostovtsev** [comment]
It should not be happening. I can not reproduce it.

What is your Webmin version? What is the server OS? If you open the browser, do you have any console errors?

**Comment by matrix200** [comment]
Strange now it works for me too.
Earlier I was struggling with a malfunctioning VM (running in KVM via cloudmin).
Since it was the fw, I had no internet connection at the time and that particular module just refused to open.
Now I tried it again, and the module opens just fine.

**Comment by rostovtsev** [comment]
I will close this for now, as you can no longer reproduce it. 

You are welcome to re-open it, in case issue re-appears and there'd be a way to reproduce it.
