### ISSUE TITLE
Settings revert on browser focus

### ISSUE THREAD

**Issue by lunarovic** [authentic-theme/authentic-theme#1256]
I found one strange issue while I was testing the #1248 fixes. Go to "Software Package Updates" and look at these options:

![image](https://user-images.githubusercontent.com/2381553/49331951-73711580-f5a5-11e8-954c-04c2d09657ee.png)

Then change something (don't save, just change), for example choose a different option from the drop-down (hour/day/week), type something in the text field, or change which radio buttons are selected (or do all 3). Then open some other window to make the browser lose focus and then click again in the browser window to bring it back to focus. After a second, all the settings reset to what they were initially!

I tested this in Chrome and Firefox on Windows 10, but I'm curious if it also happens on other systems. I couldn't find this behavior on other pages (but I didn't test many). But if this happens on a page with many settings, this is a potential catastrophe, because a user may not notice a certain radio button has reverted and they will save the settings thinking they changed something, when they didn't.

P.S. Is it normal that Firefox doesn't have the stylized scrollbar in the theme? It shows the default scrollbar, which is especially ugly in the dark theme.

**Comment by rostovtsev** [comment]
Yes,

On re-focusing the browser, if user was on _Software Update Packages_ module the page is reloaded automatically. It's done to fetch/clear possible updates.

Now, I though, see a improvement here, as when reload should not happen, in case there were any modifications done (which is rare indeed). I will fix that tomorrow.

Wow! Nice digging! Thank you!

**Comment by lunarovic** [comment]
> Wow! Nice digging! Thank you!

😄

**Comment by rostovtsev** [comment]
Fixed.
