### ISSUE TITLE
Custom Commands - 2 columns work now perfectly!

### ISSUE THREAD

**Issue by strangealien** [authentic-theme/authentic-theme#1259]
Did now install the beta version to test it - works fine! Thank you!

One idea - but not really important: Is it possible to make the description text for each button right adjusted instead of left adjusted?
The reason for this: The edit buttons for each command have all the same size, the command buttons do not because command buttons usually have different text length.
But this is really unimportant, just thought of it when I tested your change. Now my button order is corect again, and all works fine.

**Comment by rostovtsev** [comment]
Hi,

I am glad you liked it.

I personally don't think it (description) should be sticking to the right. _Title_ and _Description_ are representing one idea. Besides, technically it's not easy to do.

I will have to turn down this feature request.

Thank you for reporting and helping in making our products better.
