### ISSUE TITLE
Usermin mailbox new message button disabled

### ISSUE THREAD

**Issue by SpiffyStores** [authentic-theme/authentic-theme#1260]
When logging onto a Usermin mailbox that is empty, the "New message" button does nothing. If you then navigate to a folder which contains mail, then the button gets activated and starts working as normal.

It's a bit confusing to sit on an empty screen when you have an empty Inbox and not be able to compose new messages.

**Comment by rostovtsev** [comment]
Fixed.

**Comment by SpiffyStores** [comment]
This problem hasn't quite been fixed.

If the mailbox is totally empty and all folders are empty, then the "New message" button remains disabled, preventing a new user from creating any mail.

**Comment by rostovtsev** [comment]
Confirmed. I will fix it on the weekend! Having a rough time right now.

Thank you very much for reporting.

**Comment by SpiffyStores** [comment]
No problem. Thanks.

**Comment by rostovtsev** [comment]
Fixed. Thanks for reporting.
