### ISSUE TITLE
Virtualmin Filemanager uses homedir twice when navigating

### ISSUE THREAD

**Issue by arausch-dre** [authentic-theme/authentic-theme#1261]
Hi,

in Virtualmin/Webmin when working a restricted virtualserver admin File Manager uses home directory twice (e.g. /home/example.com/home/example.com/public_html) rather than just /home/example.com/public_html. This does not happen when switching to a different theme.

I'm currently running on CentOS 7.5.1804, Usermin 1.741, Webmin 1.900 and Virtualmin 6.04.
Please excuse me if I missed something to workaround this issue, someone else having this issue too?

Regards,

Andreas

**Comment by rostovtsev** [comment]
Hi, Andreas!

What do you mean by _uses twice_ ? It opens the tab on each new reload? Could you please provide the screenshot?

**Comment by arausch-dre** [comment]
No, the File Manager does not open new tabs, but it tries to access wrong (non-existent) directories when browsing inside a home directory of a virtual server.
I'm attaching a screenshot showing an error message in a red box. The home directory of the virtual server is set to /home/example.com, but File Manager tries to access /home/example.com/home/example.com. 
![screenshot_2018-12-05_07-34-11](https://user-images.githubusercontent.com/45608474/49494576-60d63500-f860-11e8-9e21-04b5c1be4126.png).
This issue is only arising when working with the virtual server's admin account. When working with the Virtualmin root account I don't see that issue. Just in case it helps: virtual server admin uses chroot.

-Andreas

**Comment by rostovtsev** [comment]
Do you have steps to reproduce it? I have logged in as server-owner and everything seems to work as expected?

**Comment by rostovtsev** [comment]
The only way to reproduce it is actually first create a directory, then delete it using console (or by other means) and then going back to File Manager will return this error.

It's not a bug but a feature.

![image](https://user-images.githubusercontent.com/4426533/49642528-5e243d00-fa24-11e8-8ef7-982575cff16f.png)
