### ISSUE TITLE
Update Packages, same version on columns

### ISSUE THREAD

**Issue by 7starsone** [authentic-theme/authentic-theme#1262]
Hello,
just a little error about version compare, it does the same thing for any available package
here the example screenshot
![example](http://i68.tinypic.com/2ennl39.jpg)

thanks

**Comment by jcameron** [comment]
This is a known bug which will be fixed in the next release. The patch can be seen here : https://github.com/webmin/webmin/commit/c0a037b06b0d7a684e259a980edb2d0e511851d3
