### ISSUE TITLE
Custom Commands text fields are too small

### ISSUE THREAD

**Issue by spassmo** [authentic-theme/authentic-theme#1263]
Text fields show with approx 1 character width making them hard to see.

Authentic theme version 19.22-beta2

![image](https://user-images.githubusercontent.com/19356142/49634934-00a3d800-f9b3-11e8-8f38-db02bb3d61a7.png)

**Comment by rostovtsev** [comment]
Did you try typing in this field? :smiley: 

I have added few extra pixels, but it's not really needed as the field is _autoresize_.

**Comment by spassmo** [comment]
Thank you,   Yes I typed in them and realize they are autoresize.  I have users complaining that they don't see them.  This is likely also due to a lack of contrast with only the very thin grey border around the field.

**Comment by rostovtsev** [comment]
I realize that it's monitor and setup specific. This is why I have added an option on the theme to have _High contrast mode_, in theme configurations.

Using theme extensions, you could for increase the contrast for your users or for specific user particularly.
