### ISSUE TITLE
Leaving Update notice will make the Dashboard grayed out

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1266]
I was installing 19.22-beta3 and when i press the `i` to get the `Update notice` the background get grayed out (nothing wrong with that), but when i close the `Update notice` the Dashboard continues to be grayed out so i can't use it. I need to do a refresh to get it back to normal again.

Webmin 1.900
Firefox 63.0.3

**Comment by rostovtsev** [comment]
Opps. Confirmed.

**Comment by rostovtsev** [comment]
Fixed, thank you.
