### ISSUE TITLE
Theme logos Usermin only

### ISSUE THREAD

**Issue by NZCyrus** [authentic-theme/authentic-theme#1269]
Under 'Theme Logos' i have images set for authenticated and unauthenticated users. These appear during a Wemin login for an unauthenticated user and for an authenticated user after logging in.

However, this doesn't occur with Usermin (as it used to).

Usermin version | 1.751
Authentic theme version | 19.22-beta3
Webmin version | 1.900
Operating system | Debian Linux 9

**Comment by NZCyrus** [comment]
```
root@host:~# ls -lsa /etc |grep usermin
 4 drwxr-xr-x  36 root     bin       4096 Dec  7 14:19 usermin
```

**Comment by rostovtsev** [comment]
It's odd. It should be working.

Did you try to force reload the theme and Webmin as well, and afterwards adding logos again?

Are there any errors in browser's console or logged at `/var/webmin`?

**Comment by rostovtsev** [comment]
Also which browser do you use and on which OS?

**Comment by NZCyrus** [comment]
> Did you try to force reload the theme and Webmin as well, and afterwards adding logos again?
Yes, that worked

> Are there any errors in browser's console or logged at /var/webmin?
No

> Also which browser do you use and on which OS?
Google Chrome with Gnome on Archlinux

Thank you :)

**Comment by rostovtsev** [comment]
Okay, I'm glad the issue was resolved for you. 🙂
