### ISSUE TITLE
File Manager: Add ability to resize tree-view

### ISSUE THREAD

**Issue by rostovtsev** [authentic-theme/authentic-theme#1271]
It would be great to have an ability to resize tree-view on the fly.

**Example:**

![image](https://user-images.githubusercontent.com/4426533/50397924-acf00780-0784-11e9-95d8-57dd9b65ac56.png)

**Comment by SylvainLegrand** [comment]
Hi,

Thank's for your job.
I found a problem on the tree view : at the bottom te filter box hide the last directory on the tree.

Greetings,
Sylvain Legrand.

**Comment by rostovtsev** [comment]
Hi, Sylvain.

It's fixed https://github.com/authentic-theme/authentic-theme/commit/0e724addc146fab20d6f3a939c8b8d8d9a995344.

Thanks for reporting.
