### ISSUE TITLE
key (enter/submit) issues

### ISSUE THREAD

**Issue by ThierryMasson** [authentic-theme/authentic-theme#1272]
Hello,
With the last update 19.22, when I would enter (for example) some new mail addresses in spamassassin, mail filter, allow and denied addresses. After anykey is pressed, SAVE button began auto highlighted, and when we press ENTER key to write another line (email addresses in this case) the form is auto submitted (like click on the SAVE button).

**Comment by rostovtsev** [comment]
This is a bug, and it's been [just fixed `bd2b005`](https://github.com/authentic-theme/authentic-theme/commit/bd2b0053387fc56b4281f054722159ac2f370d46).

Thank you very much for reporting now!

Happy New Year! :santa:
