### ISSUE TITLE
File manager - Can't edit all kind of files

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1273]
In the file manager i can edit file but for some reason the extension need to be correct. I understand that Windows use file extensions but in Linux you can have whatever extension you want, even leave it out.
I don't know if this is a Webmin or theme issue but is this possible to change by the user (in this case, me) what kind of file extension i can edit?

It seems that i can edit files without extensions (some of them) but not if the file is called `filename.old`.
What determines if the file can be edited or not?

**Comment by rostovtsev** [comment]
MIME type and the way it's detected.

You can edit the list and expand it (see the type of the file by showing the column _Type_ in File Manager configuration) with the type you need.

For the mentioned file (`filename.old`) the correct file type would be:

```
application-x-trash
```

You need to add this to _Webmin/Webmin Users/Edit Webmin User/Available Webmin modules/Other/File Manager/Module Access Control_. :smile: 

![image](https://user-images.githubusercontent.com/4426533/50638249-17b3f680-0f6e-11e9-92ec-8986ca5a67a0.png)

**Comment by rostovtsev** [comment]
You could also use drop-down command line to call an editor on _any_ file you need.

Click `Alt+K` to call for it (by default) and enter for example:

```
edit /usr/bin/clear
```

![image](https://user-images.githubusercontent.com/4426533/50638368-9872f280-0f6e-11e9-91c4-ba1dcd4ec7c0.png)


You could also do the same using search but you would need to prepend command with `!`, example:

![image](https://user-images.githubusercontent.com/4426533/50638424-bccecf00-0f6e-11e9-8e6f-a6c1a488fd68.png)

**Comment by Sopor-** [comment]
I want to use the context menu / edit on the files... So there is no easy way to do this?

**Comment by rostovtsev** [comment]
This is quite easy way. Just add needed MIME type to the ACL config and it will work?

Is it hard for you to do?

What are the file types you would like to edit, that are currently missing?

**Comment by rostovtsev** [comment]
..after you add needed types it will be available under context-menu!

**Comment by Sopor-** [comment]
I'm not an expert on Linux but some kind of viewer would have been nice. A program that can open and let me show what is inside the file text, html, hex etc. Like the `Lister` in Total Commander :)

**Comment by rostovtsev** [comment]
Yes, I'm planning to implement this. Thanks.
