### ISSUE TITLE
Cloudmin - Graphical Console Size. Again

### ISSUE THREAD

**Issue by a7lan** [authentic-theme/authentic-theme#1274]
Console displays very small and cannot be resized.  latest available version of Authentic
![default](https://user-images.githubusercontent.com/6501090/50768848-139c1780-1293-11e9-8f39-361ca8c1e223.JPG)

**Comment by rostovtsev** [comment]
Hi,

I have made a [patch](https://github.com/authentic-theme/authentic-theme/commit/44239ee4784973f18a6aeb2e9efa447173e128a9). Install latest dev version from theme configuration.

Did it fix it?

**Comment by a7lan** [comment]
yes. it's work. thx!
