### ISSUE TITLE
Updating theme installs bete by default

### ISSUE THREAD

**Issue by Zen4All** [authentic-theme/authentic-theme#1275]
Good-morning, I just installed a new server, with authentic-theme. All went well
After a few minutes I was alerted there was an update to the theme available, so I pressed updated, and the theme updated to 19.23-beta2 instead of the stable 19.22
In my opinion by default only stable releases should be installed, and if I want a beta I will have to explicitly set the switch for that.

**Comment by rostovtsev** [comment]
Yes, that was a bug.

[Latest commit](https://github.com/authentic-theme/authentic-theme/commit/defdae1028a0642ba3a82b21af2614d91d3693e1) fixes it.

**_Note:_** It will still show beta update version and installs one, if it's enabled in `/etc/webmin/authentic-theme/config`, using `beta_updates=1` option.

Thank you reporting!

**Comment by Zen4All** [comment]
Thanks , and yes |I was aware of the beta option 😉
