### ISSUE TITLE
"Read user mail" message count readability

### ISSUE THREAD

**Issue by lunarovic** [authentic-theme/authentic-theme#1277]
In "Read user mail", let's say I have 23 messages for one user, and the number of messages per page is set to 10. When showing the list of messages, in the bottom I see something like this:

1st page: "Messages 23 to 14 of 23"
2nd page: "Messages 13 to 4 of 23" ([example](https://github.com/authentic-theme/authentic-theme/issues/1249#issuecomment-455456531))
3rd page: "Messages 3 to 1 of 23"

I think it's confusing, I've never seen messages being numbered that way anywhere else. Can they be numbered in the "normal" direction? And for even better readability, I would also put "of X" in parentheses (or the Gmail way, see below). So with those 2 changes, it would look something like this:

1st page: "Messages 1 to 10 (of 23)"
2nd page: "Messages 11 to 20 (of 23)"
3rd page: "Messages 21 to 23 (of 23)"

Or the Gmail way: "1-10 of 23"

Don't you agree it's easier to read? But this is just a suggestion, not a real issue.

**Comment by rostovtsev** [comment]
Hi,

In case you mean Webmin/Servers/Read User Mail, then it's the way it was built by the module, it's not the theme issue.

In Usermin, where we already have new mail listing, I do it as you propose.

Example:
![screenshot from 2019-02-06 16-31-58](https://user-images.githubusercontent.com/4426533/52344900-035f8f80-2a2d-11e9-8412-f315f6020e5e.png)

I didn't do testing yet, but the new code that is used in Usermin, should go well to Webmin with minor modifications. 

-----

I would ask you to post this issue to Webmin [repo](https://github.com/webmin/webmin) if you could.
