### ISSUE TITLE
"Read user mail" two issues with links

### ISSUE THREAD

**Issue by lunarovic** [authentic-theme/authentic-theme#1278]
1st issue: In "Read User Mail" configuration, if you check "Open messages in: New window", the messages will not open anymore, nothing happens. I have popups allowed, it's not that, the popup is not attempted at all. This may happen at other places where the same option is used.

2nd issue: In "Read User Mail" configuration under "Spam options", for "Show spam reporting buttons for" check "Mailboxes". Then go to a user mailbox, then to the spam folder, open an email and click "Report ham" (by the way, I just learned that "ham" is an old term for "non-spam" :D). Alternatively, if you don't have any mails in spam to test this with, go to the regular inbox and click "Report spam". After the operation, the page will return to just the inner frame, without the Webmin panels left and right. Maybe it has something to do with the page calling some external spam report link?

P.S. You don't need to switch your attention to this now, keep working what you are working, just leave this issue and come back to it later. :) It's just that I have the time to write this now.

**Comment by rostovtsev** [comment]
> 1st issue: In "Read User Mail" configuration, if you check "Open messages in: New window", the messages will not open anymore, nothing happens. I have popups allowed, it's not that, the popup is not attempted at all. This may happen at other places where the same option is used.

I am planning to implement _compose new message_ feature to always be in new window (panel, like Gmail). I am starting working on it soon.

> 2nd issue: In "Read User Mail"

Do you mean reported from inside the message view?

**Comment by lunarovic** [comment]
> Do you mean reported from inside the message view?

Yes.

**Comment by rostovtsev** [comment]
> 2nd issue: In "Read User Mail"

Read mail page is going to receive new mail reader. I would not worry about fixing it now.

Thanks for you comments.
