### ISSUE TITLE
Theme: Users can't create links with CKEditor (Rich Text) when composing mail

### ISSUE THREAD

**Issue by kadai** [authentic-theme/authentic-theme#1280]
Greetings,

It was brought to my attention that the Rich Text (CKEditor) for the authentic theme in Usermin does not comes with a button to create links in mails being composed by users.

![image](https://user-images.githubusercontent.com/1930055/51586764-7fde6400-1eac-11e9-8770-f80e3ef01dc7.png)

None the less, I have found out that the link plugin is present in the project files and also in the installation files. There is a way to activate it via usermin/virtualmin? Because the only suitable way I found was to edit the config.js file (yet need to figure it out), but that would mean that the change would be overridden with every update.

Thanks in advance

**Comment by rostovtsev** [comment]
It's been just fixed. Force update to the latest development version from theme configuration.

Compose Mail is going to be reworked and will be showing in the pop-up window, like GMail pretty soon. I was going to do it sooner but  there were always things coming up to accomplish first.

**Comment by kadai** [comment]
Will have a look at this. Thank you so much.

**Comment by rostovtsev** [comment]
You are welcome!
