### ISSUE TITLE
Theme: Textarea in plain text composing mail does not behave as expected

### ISSUE THREAD

**Issue by kadai** [authentic-theme/authentic-theme#1281]
Greetings,

When a user composes an email using plain text, a message may be sent by accident when they do press Enter in the mail body textarea field. This prevents that they could create paragraphs, or edit as how one would do on most email clients.

Neither this can be prevented using the shift+enter combination. Only changing to Rich Text this stops happening.

This behavior happens as soon as the "Send Mail" button becomes active. So, for example, one can press Enter twice and have the mail sent without notice.

The expected behavior is that the Enter strokes does not affect and neither trigger the mail sending while writing in the textarea.

**Comment by rostovtsev** [comment]
Yes, it's an ugly bug that has been fixed already a while ago.

**Comment by kadai** [comment]
Oh thank you and sorry then for opening this issue.

**Comment by rostovtsev** [comment]
No worries at all. Please open as many issues as you think nessesary. I am always looking forward to improve! 

Thank you!
