### ISSUE TITLE
Input width for custom command parameters

### ISSUE THREAD

**Issue by DazDotOne** [authentic-theme/authentic-theme#1282]
Just a little one.

It seems that for some reason custom command text parameters seem to get the width set at 12px inline styled (see image), I've recreated it by creating a new command and the text parameter inputs are the same size.

![custom command text input](https://user-images.githubusercontent.com/3983532/51607536-d3809a00-1f0c-11e9-83ed-c3dba0eaa3b8.png)

Thanks for all the hard work, great theme.

**Comment by rostovtsev** [comment]
Okay, sorry for taking too long; needed to fix the compiler to consider new binary _.gz_ files properly.

Anyway, I have balanced the _initial_ width of those inputs. They are adjustable and not static, in case description is to long it matters.

![image](https://user-images.githubusercontent.com/4426533/51683375-c6da6f80-1ffa-11e9-9ac2-d98b03270144.png)

**Comment by DazDotOne** [comment]
Great stuff.

Thanks for the hard work.
