### ISSUE TITLE
Wrong version will be installed when using `Install latest developer version (beta)`

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1283]
If i'm running 19.22 and do an update to 19.23-beta2 by `Install latest developer version (beta)` i get 19.23-beta2. When a new beta was out i installed it by using the `Install latest developer version (beta)` but instead of 19.23-beta3 i now have 19.22.
Same thing if i'm running 19.23-beta3 and run `Install latest developer version (beta)` i will end up with 19.22.

**Comment by rostovtsev** [comment]
Do you click it on theme configuration page or in notification slider?

**Comment by Sopor-** [comment]
configuration page

**Comment by rostovtsev** [comment]
Do you have an option to display beta updates manually enabled, in `/etc/webmin/authentic-theme/config`?

**Comment by Sopor-** [comment]
```
framed=1
cs_link=376ebd
cs_table=feffff
noindex=1
cs_header=ffffff class='thead'
functions=authentic.pl
inframe=1
```

**Comment by rostovtsev** [comment]
You are right! It's fixed! Thanks a lot for reporting.

For your information, you would need to add an option to `/etc/webmin/authentic-theme/config` called `beta_updates=1` to have notifications for beta updates.

**Comment by Sopor-** [comment]
Thanks for the tip, but i don't like notifications so i have it turned off and it is not only here. If i can turn it off in a program i will do it. I even found how to turn off check for new version in Firefox even if that wasn't possible :)

**Comment by rostovtsev** [comment]
What if it's an important security update that'd better be installed with minimum delay? 🙃
