### ISSUE TITLE
Add ARIA labels to screen elements and other screen reader accessibility enhancements

### ISSUE THREAD

**Issue by zuhairmahd** [authentic-theme/authentic-theme#1284]
At the moment, some buttons, such as those to start, stop or apply changes to the Apache server module, buttons to ad an item to favorites (only examples) do not have labels that can be read by a screen reader user.  Adding appropriate labels, whether through the use of native HTML accessibility tags or the use of Accessible Rich Internet Applications (ARIA) would make this great application much more usable by system administrators, like myself, who are blind or visually impaired who use a screen reader.

**Comment by rostovtsev** [comment]
Hi,

Thank you for your recommendations. I will see what I can do in this regard.

**Comment by rostovtsev** [comment]
I have done my best to make sure that each element without explicit description would have _aria-label_ attribute set.

Please give it a try with the latest commit. You can update to the latest development theme version using theme configuration (bottom of the page).

Let me know more if something goes wrong or if I missed anything.

**Comment by zuhairmahd** [comment]
@rostovtsev thanks so much for the quick turnaround.  Almost everything I have tried so far is working except the following:
1. Managing favorites (adding, removing, etc).
2. (Minor) Near the "Edit user" and "Log out" buttons, there appears to be a third one that allows you to edit the theme.  This button does not appear to have a label.

Thanks again.

**Comment by rostovtsev** [comment]
Okay, thanks for your feedback.

It's fixed now!

**Comment by zuhairmahd** [comment]
Theme configuration definitely speaks a label now, but not the add to favorites. I also noticed that add to favorites doesn’t get focus when you try to tab to it — could that be related I wonder?

**Comment by rostovtsev** [comment]
Do you mean by add to favorites, the 🌟 icon, in the middle of the table header?

By the way, I made it (add to favorites) change the label's text, depending on the state. Is this a good practice? Does it make things more clear?

**Comment by zuhairmahd** [comment]
Exactly. The glowing star in the middle of the table header. 
Having the label say “add to favorites” or “remove from favorites”, depending on the status, is definitely a good practice. 
unfortunately, it did not speak when I tried it in the commit you applied earlier today.

**Comment by rostovtsev** [comment]
Okay, I think I know why this was happening. Give it another try please.

**Comment by zuhairmahd** [comment]
Just did ... and it is working great.  Thanks so much @rostovtsev
