### ISSUE TITLE
usermin email "enter" send the email instead of going next line

### ISSUE THREAD

**Issue by aqueos** [authentic-theme/authentic-theme#1285]
hi,

 on the usermin when you try to send a new email in the Mail part , the "ENTER" key is sending the email instead of going to the next line. This make writting of email very hard :)

this is verified on firefox on windows and on ubuntu client : 

  | Authentic theme version | 19.22

debian jessie.

best regards,
Ghislain.

**Comment by rostovtsev** [comment]
Hi,

This is known and already fixed bug.

You can install latest development version to get this issue resolved.
