### ISSUE TITLE
File manager - Calculate size on spacebar

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1286]
When using `Calculate size on spacebar` the behaviour is a bit weird. I move the mouse pointer to a folder row and press space and the folder will get a checkmark and it will start to calculate the folder size. When it is done i unselect this folder and moves to another and press space and it will be selected, but the previous selected folder will be selected again. It seems that the size of the folder will not be included in the total size (at the top of the page).

If i select a folder and then unselect it with the mouse and then press space on another folder the previous folder gets selected too, but not calculated.

![image](https://user-images.githubusercontent.com/5789283/51996832-d99aeb80-24b5-11e9-8c77-ff6f850f27ae.png)

Firefox 64, Authentic theme 19.22

**Comment by rostovtsev** [comment]
Yes, it's one of the parts of upcoming (final part optimization).

**Comment by rostovtsev** [comment]
Try installing latest development version of the theme.

I have just added a big commit:
[`ee4f3a7` - Add optimizations for File Manager. Stage 1/2](https://github.com/authentic-theme/authentic-theme/commit/ee4f3a7b1b1a7f3c3749cf592a2603fe63cd8563)

**Comment by rostovtsev** [comment]
For your information, you can navigate using keyboard. Recent commit also adds support for _PageUp_ and _PageDown_ keys.
