### ISSUE TITLE
Web interface takes very long to load

### ISSUE THREAD

**Issue by neural-oD** [authentic-theme/authentic-theme#1287]
Hi All 

My setup:
Webmin 1.9
Authentic theme - latest. - also tried beta 
Ubuntu 18.04.1

I know that ubuntu 18.04 isn't officially supported yet, however I'm sure it's being worked on. 
Basically it's taking ages to get to a usable web interface.
I think it could be related to the bottom two issues that were raised previously. 
#572 
#47  

Here's a screenshot of the waterfall from inspect in chrome - this is using the beta theme, the stable theme takes even longer to load.

![selection_645](https://user-images.githubusercontent.com/22800677/52120410-de31e200-2624-11e9-96fb-75e25715cb37.png)

What would you suggest to get this sorted out? I'm suspecting the couple of files as can be seen in the waterfall - specifically:
unauthenticated/css/**bundle.min.css**?1923154901888606
unauthenticated/css/**fonts-roboto.min.css**?1923154901888606
unauthenticated/js/**bundle.min.js**?1923154901888606

**Comment by rostovtsev** [comment]
You would need to restart Webmin after editing mentioned file.

**Comment by neural-oD** [comment]
Hi
Thanks for the feedback. Sorry late reply, wasn't on the pc much this weekend.
I tried on the beta and stable versions. Although there was some improvement, the delay is still very long.
In fact I tried increasing that buffer size up till 65536, and this is the results I'm still getting:

![selection_648](https://user-images.githubusercontent.com/22800677/52192788-8679bd80-2854-11e9-9d23-22e0027d6223.png)

We still getting over 31 seconds before screen is up.
Any other solutions? 
Just as a side mention, the server is over-spec'd running 8Gb of ram, and plenty of processing power for what it needs for this to function well....

Any other suggestions would be welcome.

**Comment by rostovtsev** [comment]
Switching to Gray Theme doesn't increase load much, or it does? 

How fast is the link to the server?

I wonder, where is `bundle.min.js` in the screenshot above? 🤔🙂

It seems that fonts Roboto takes  longest time to load in your case. You could install Roboto locally by downloading them from the web, then go to theme configuration, and force to use local version of Roboto fonts, or you could also choose to use Arial or Tahoma instead.

**Comment by rostovtsev** [comment]
Besides, try other browser without any extensions on, and/or Incognito Tab (also with disabled extensions).

**Comment by neural-oD** [comment]
Hi 
I've had similar issues on other browsers - incognito & firefox.
The screenshot before was with the beta version. I've now gone down to the stable version for the rest of these:

Stable version - shipped defaults:
![selection_649](https://user-images.githubusercontent.com/22800677/52193981-8e3c6080-285a-11e9-8111-8c20c53d0410.png)


With arial font selected:
![selection_650](https://user-images.githubusercontent.com/22800677/52194018-aca25c00-285a-11e9-81ce-b7177f7f2308.png)


Now with Grey theme installed - webmin
![selection_651](https://user-images.githubusercontent.com/22800677/52194048-ca6fc100-285a-11e9-9fa7-bb864029901e.png)

Usermin - greyframed theme in incognito: 
![selection_652](https://user-images.githubusercontent.com/22800677/52194137-4538dc00-285b-11e9-8f81-0ab7decdc08e.png)


Usermin, incognito - on authentic theme:
![selection_653](https://user-images.githubusercontent.com/22800677/52194270-d019d680-285b-11e9-801d-79c35f25ea5c.png)


Hope these help out!

**Comment by rostovtsev** [comment]
The interesting thing, is that you have files loaded that are not the part of any packages. 
For example, what is `inject.js` that is loaded in all themes? Why the first line is blurred in all screenshots?

Are you behind proxy, by the way?

When you reload the page, and open console, then go to Network tab, filter out _bundle_, then click on it, how fast does it load?

![image](https://user-images.githubusercontent.com/4426533/52195916-e1b6aa80-286a-11e9-8746-9d05712dae3e.png)

If you download anything large from your server how fast/smooth does it go? Try with compressed data, like a video file.

Do you have compression on? Go to _Webmin Configuration/Web Server Options_ and set _GZip static files_ option to _Use pre-compressed file and compress dynamically_. What is this option set to right now?

-----

Just to note, I have Authentic Theme loaded on my VM in 1.19 seconds, while Virtualmin Framed Theme in 1.09 seconds.

**Comment by neural-oD** [comment]
> The interesting thing, is that you have files loaded that are not the part of any packages.
> For example, what is `inject.js` that is loaded in all themes? Why the first line is blurred in all screenshots?

Not sure what this is at all - I've just put in Virtualmin, and nothing else loaded as yet. I'm not sure what that inject.js??
Also the only reason I blurred out the first line, is that I'm a bit security paranoid - I just took off the server name off the top line....
 
> Are you behind proxy, by the way?

No - I'm not behind a proxy in any way.

> When you reload the page, and open console, then go to Network tab, filter out _bundle_, then click on it, how fast does it load?
> 
> ![image](https://user-images.githubusercontent.com/4426533/52195916-e1b6aa80-286a-11e9-8746-9d05712dae3e.png)

It's loading fast if I filter out those....
![selection_654](https://user-images.githubusercontent.com/22800677/52207899-86df7c00-2887-11e9-9383-61e5004f90f1.png)


> If you download anything large from your server how fast/smooth does it go? Try with compressed data, like a video file.

Hmmmmm..... ok something is strange on the server here.....I've uploaded - not the speediest, but it'll do. However when downloading compressed files, it's very slow.....see below:
![selection_655](https://user-images.githubusercontent.com/22800677/52208197-711e8680-2888-11e9-8cb2-58bc72e36b3b.png)
This is strange, as the cpu on the server is hardly being used:
![selection_657](https://user-images.githubusercontent.com/22800677/52208540-b2fbfc80-2889-11e9-9243-a2cdd562b64a.png)


> Do you have compression on? Go to _Webmin Configuration/Web Server Options_ and set _GZip static files_ option to _Use pre-compressed file and compress dynamically_. What is this option set to right now?
 
Haven't played much yet with Webmin/Virtualmin settings. 
This is what it was: 
![selection_656](https://user-images.githubusercontent.com/22800677/52208330-e1c5a300-2888-11e9-86a7-8f3b6561f5f9.png)

I've now changed it to what you've said.

> Just to note, I have Authentic Theme loaded on my VM in 1.19 seconds, while Virtualmin Framed Theme in 1.09 seconds.

Hmmm - well I'm not sure what's going wrong this side then...?

> With enabled compression my Ubuntu 18.04 initially loads the same fast as other distros.

Strange why mine is not working correctly....
Did another test on my server using rsync - getting ok speed on that:
![selection_658](https://user-images.githubusercontent.com/22800677/52211350-4fc29800-2892-11e9-92e5-258983b2b21b.png)

This is very frustrating, not sure why this is happening on 18.04. I'm going to try run it on a 16.04 freshly minted server, and see what happens....

**Comment by neural-oD** [comment]
Ok, so I think that it might be the KVM network for some reason this seems to be going very slow....
I changes settings on the VM - and this is what I'm getting now:
![selection_659](https://user-images.githubusercontent.com/22800677/52212616-a087c000-2895-11e9-9a81-8902dacf8a36.png)

I'll mark this closed for now - sorry about the run around - never thought to look at the KVM networking - I still need to go and see why it's running so badly...

**Comment by rostovtsev** [comment]
You might also have driver issues.

https://askubuntu.com/questions/1029723/slow-wifi-since-updating-to-18-04

Can you tell more exactly about _KVM_? What was causing it?

**Comment by neural-oD** [comment]
I'm still busy testing various things. I'm running KVM on a debian 9 host. Guest VM is ubuntu 18.04. 
I was using the default rtl8139 for the device model for the network card. I changed to virtio - which seems to have helped a bit, but I still need to check the performance out in more detail.

For now as per the last picture I sent, it seems that this has sorted out the problem mostly, however as said, I still need to test properly.

I will report back and let you know

**Comment by neural-oD** [comment]
ok - so for your info: 
Using virtio driver:
![selection_660](https://user-images.githubusercontent.com/22800677/52218986-696cdb00-28a4-11e9-8e23-0961d181f945.png)

Using the rtl8139 driver:
![selection_661](https://user-images.githubusercontent.com/22800677/52219029-873a4000-28a4-11e9-874b-0bf8c9b9c96c.png)


So the virtio is performing as it should - my home connection is maxed out at 50Mb/s.... The default when setting up the KVM was rtl8139, which we can see is only getting like 843 Kb/s...
I know this isn't your issue, but it's good that I'm posting here, as it could help others in the same situation. :smile:

**Comment by MorningSleeper** [comment]
To anyone stumbling across this thread and the issue is isolated to Firefox, you may want to try resetting your Firefox profile. According to the following page "Firefox starts to noticeably slow down after storing 7-8 identically named self-signed certificates. After storing 10 it slows down significantly and can hang on “Performing a TLS handshake” for 30 seconds or more". When I did this the Authentic Theme in Webmin went from being extremely slow to super fast.

From: https://www.thesslstore.com/blog/troubleshoot-firefoxs-tls-handshake-message/

**Comment by Chartman123** [comment]
I'm facing the exact same problem in our installation. The theme is generally very fast, but slows down as soon as you're loading a page that is based on a larger local file, e.g. our virtual file for postfix (virtual.cgi). In the old "Grey Framed Theme" everything loads very fast and also on that page. It's not browser or client related as this happens for all our users and on different browsers (tested with Firefox and Chrome). I'm using the latest version (19.39-2) and have also tried with the latest beta version.

**Comment by rostovtsev** [comment]
I will give more tests to it. How large is virtual map file?

**Comment by rostovtsev** [comment]
JS file gets executed only once, upon first load.

I am confused now.

Can you provide the screenshot of the page that is loading slowly for you? Maybe video-screencast?

**Comment by rostovtsev** [comment]
2 Mb is quite a lot in our case.

**Comment by rostovtsev** [comment]
Can you send me your map file for Postfix via email, so I could give it a test? `programming аt rostovtsev dоt io`. No screenshot needed.

**Comment by rostovtsev** [comment]
I think I know why this is happening. It could be a general improvement.

**Comment by Chartman123** [comment]
I'll see if I can randomize the local parts of the mail addresses because of GDPR reasons and send it to you ;)

**Comment by rostovtsev** [comment]
Okay, I have added your entries to _Postfix Mail Server/Virtual Domains/_ and yes, loading is slow. Returned HTML is about 1.8Mb.

It takes for me about 10 seconds to load due to rendering and scripting. I will see if that can be fixed/improved.

**Comment by Chartman123** [comment]
Yes that's the same amount of time as for us... Thanks for taking care of this issue :)

**Comment by rostovtsev** [comment]
Okay, I managed to make it load 2 times faster for me.

All grid tables will initialize pagination, if there are more that 1000 rows, allowing to search (using top right filter, in the table header and sort).

![image](https://user-images.githubusercontent.com/4426533/67903125-e3a06680-fb7b-11e9-9cbb-41210bbc82b3.png)

New option added to theme configuration, preventing you completely avoid data tables for super large responses.

![image](https://user-images.githubusercontent.com/4426533/67903237-1ba7a980-fb7c-11e9-80d9-9d311b7fe78a.png)


----


Above everything page render code is very harry and requires more optimizations to be done in the future. At the moment you can control the speed load.

Please feedback within next 12 hours if possible.

**Comment by Chartman123** [comment]
I'll be back at the office on Monday. I like the idea of introducing a pagination and especially the filter.

**Comment by rostovtsev** [comment]
The filter was already there, paginations were not. To make it super fast pagination should happen on the server.

**Comment by rostovtsev** [comment]
However, if you add 4-5 times amount of data that you sent me (about 16000 rows), then it still very slow and takes about 1 minute to render. The good thing that it doesn't crash. I will do further optimizations after the release, if it's even possible to achieve. It's all about parsing large amount of HTML, which has to happen in our case - there are probably ways to make it more efficient though.

**Comment by Chartman123** [comment]
Ok, I've checked the pagination in the current release... I think it's a little bit confusing to have two paginated tables on the left and on the right.

Is it possible to paginate the whole table and show the first n lines on both columns, e.g. lines 1 to 50 in the left column and lines 51 to 100 in the right column?

**Comment by rostovtsev** [comment]
@Chartman123 In practice, the way it's represented now is two different tables. I am not sure if it's possible the way you described it. This part of UI needs improvement.

Did the speed change for you in any way?

**Comment by Chartman123** [comment]
Yes, like you already said, the time decreased to 5 seconds 👍
