### ISSUE TITLE
Change color when update check is disabled

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1289]
Could you make the update interval more gray so it is possible to see when it is disabled when i have turned off the update checks? As it is now it is easy to think something is wrong when the drop down menu isn't working

![image](https://user-images.githubusercontent.com/5789283/52613886-01b02480-2e90-11e9-881e-985bfb5f6abe.png)

**Comment by rostovtsev** [comment]
Do you mean _select_ disabled state should be grayed out more?

**Comment by Sopor-** [comment]
I mean the drop down menu that i have marked in the picture should be grayed out so it is easy to see this is not working when update check is disabled.

**Comment by rostovtsev** [comment]
Okay, try the fix above.
