### ISSUE TITLE
"Show tooltip on buttons" has disappeared

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1292]
I disabled `Show tooltip on buttons` in Firefox and i then logged in from Chrome. Now the tooltip is enabled again and i can't find the `Show tooltip on buttons` settings any more in Firefox or Chrome.

In the picture you can see that `Show tooltip on buttons` is there and below it is not there. That is two different Webmin's but both are running the same version of Webmin and Authentic theme. How can an option disappear like that?

![image](https://user-images.githubusercontent.com/5789283/52621717-4c3d9b00-2ea8-11e9-9a7e-5f1e7803743d.png)

**Comment by rostovtsev** [comment]
Yes, now this option is always enabled!

**Comment by Sopor-** [comment]
Are you kidding me? I can't turn off the tooltips?

**Comment by rostovtsev** [comment]
Why would you want to turn off the tooltips? Besdies, it's shown with 800ms delay, meaning you would only see it if you hold on the button.

You can easily remove it by adding this code to your extensions:

```JavaScript
$(document).on('ready pjax:end', function() {
    setTimeout(function() {
    	$('[data-toggle="tooltip"]').tooltip('disable');
    }, 1000);
})
```

**Comment by Sopor-** [comment]
They get stuck and it look likes this,  that is one reason...

![image](https://user-images.githubusercontent.com/5789283/52628790-a6def300-2eb8-11e9-9476-398460941fa1.png)

**Comment by Sopor-** [comment]
And now i have this stuck on the page and it won't go away until i refresh or change page:

![image](https://user-images.githubusercontent.com/5789283/52629203-73e92f00-2eb9-11e9-8a1f-112e9728e092.png)

**Comment by rostovtsev** [comment]
Because, having to many little features just clogging configuration page and terrifies the user.

I can not reproduce it. Nothing should get stuck really. If so it's a bug. 

How do I reproduce it?

**Comment by Sopor-** [comment]
I only keep the mouse pointer on the button to the page is loaded.
