### ISSUE TITLE
Software updates - Missing text

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1293]
This text `In order to make this option work, git command has to be installed on your system` is missing before `(installed version 19.23-beta5, latest stable 19.22)`

![image](https://user-images.githubusercontent.com/5789283/52622849-1c43c700-2eab-11e9-9f0d-bf6a7bb378ff.png)

**Comment by rostovtsev** [comment]
It's not missing. It's different representation model.

![screenshot from 2019-02-12 11-55-11](https://user-images.githubusercontent.com/4426533/52623367-325a8300-2ebd-11e9-835d-94674420975f.png)

**Comment by Sopor-** [comment]
How should someone know that you have a hidden question mark there?

**Comment by rostovtsev** [comment]
By hovering on the table row?

**Comment by rostovtsev** [comment]
Okay, I decided to make sure that those question mark links, are always displayed, and hovering wouldn't be needed to get access to it. It's better like this.
