### ISSUE TITLE
Question about CSF button

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1294]
It seems that a lot of changes has been made recently so i need to ask you if this also make the buttons in CSF not work as they should? If i press a button nothing happens but if i save it the button seems to have worked. I need to press save before they change state.

![image](https://user-images.githubusercontent.com/5789283/52624194-798d4780-2eae-11e9-94b6-67d53050fecb.png)

**Comment by rostovtsev** [comment]
It's a bug! It's been just fixed.

Thank you very much! :smiley_cat:

**Comment by Sopor-** [comment]
Finally it was a bug :nerd_face:
