### ISSUE TITLE
File manager - how to move/close the edit window?

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1296]
If i open the editor and move it up and release it as in the picture, how do i move the window or close it? I can't grab the window in the title bar and i can't get the close button.

![image](https://user-images.githubusercontent.com/5789283/52632265-4d2ef680-2ec1-11e9-9976-93fc2c460aae.png)

**Comment by rostovtsev** [comment]
You could close the window with double Esc?

**Comment by rostovtsev** [comment]
Okay, I added a footer to editor's panel, so you could also drag on it.

![image](https://user-images.githubusercontent.com/4426533/52633972-0815bf00-2ed7-11e9-918b-f7189b93db43.png)

**Comment by Sopor-** [comment]
That worked perfect :+1:
