### ISSUE TITLE
Drop down menu - arrow points the wrong way

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1297]
No big deal but shouldn't the drop down menu arrow point down after i have used it?

![image](https://user-images.githubusercontent.com/5789283/52684423-852c4d00-2f46-11e9-918a-5eb7efb2e0f1.png)

**Comment by rostovtsev** [comment]
It's showing up, because the element is still active in your case. It's not a bug but a feature! :wink:

**Comment by Sopor-** [comment]
Ohh, as long as it is active it will point upwards :)
