### ISSUE TITLE
Webmin UI locale language and format

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1298]
If i add `YYYY-MM-DD HH:MM` to the `Short format` for the `Webmin UI locale language and format` i get this output `2019-02-13 06:02 6:56 AM` in the `Recent logins` `Last active at`.

If i remove the default L it will not show the default value (see picture below) but if i open the `Recent logins` it will show the default value: `02/13/2019 7:01 AM`

![image](https://user-images.githubusercontent.com/5789283/52690216-36d67880-2f5d-11e9-8883-882c65a0e27d.png)

If i empty the `Short format` why will it still show the default value in `Last active at`? In that case it should show the format it shows in the example in the `Last active at` too.
Something seems to be wrong here ...

**Comment by rostovtsev** [comment]
It's very minor. I fixed that however. It will always display correct default format on the tooltip.

**Comment by Sopor-** [comment]
But should `YYYY-MM-DD HH:mm` show up as `2019-02-13 10:36 10:36 AM`? The output example will show it right

![image](https://user-images.githubusercontent.com/5789283/52701825-6c8a5a00-2f7b-11e9-9348-868e5cd4db17.png)
