### ISSUE TITLE
File manager - Can't copy with context menu

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1299]
Why can't i copy with the context menu? I have to select a file and then use the drop down menu `Edit` / `Copy`

![image](https://user-images.githubusercontent.com/5789283/52893366-bfdaf300-319b-11e9-8431-43572cc5eaba.png)

**Comment by rostovtsev** [comment]
By "selection", it means selected text in the table.

**Comment by rostovtsev** [comment]
![image](https://user-images.githubusercontent.com/4426533/52895437-933ecf80-31cb-11e9-971a-17e47eed7259.png)

**Comment by Sopor-** [comment]
So i need to use the `Edit` menu if i want to copy?
Instead of breaking the traditional Copy, Cut and Paste menu i would suggest that don't have this expandable menu here and leave it to these three commands and instead have a seperate menu to copy path and selected text. It make no sense that i can't use the context menu to copy but i can cut and paste? The new menu you could call it `File names` and this will give the user a hint that this has something to do with the file name and not the actual file.

**Comment by rostovtsev** [comment]
Clicking on "Copy" will copy it! You can also use default shortcuts for doing so.

**Comment by Sopor-** [comment]
Menus like that never work like that so that wasn't obvious that copy should work when it has a submenu.

**Comment by rostovtsev** [comment]
What do you propose?

**Comment by Sopor-** [comment]
Something like this ...

![image](https://user-images.githubusercontent.com/5789283/52898751-f9365180-31e1-11e9-817f-77feb8962316.png)

And you could add more copy function to this submenu:
`Copy file name`, will copy the file name without selecting the text first.
`Copy row`, will copy all the visible columns (Name | Size | Ownership | Permissions | Last modification time).

**Comment by rostovtsev** [comment]
I honestly don't like extra lines added in already long context-menu. Besides, _Select All_ would also had to be reworked.

Familiar functionality is implemented in Google Docs:

![image](https://user-images.githubusercontent.com/4426533/52899004-ef1e4e00-31f5-11e9-88a8-c630e724eb8a.png)

However, they have better logic but the reason why we didn't do it, is because it's not supported by current context-menu, and the way it works.

I would need to rework it to make sub-menu appear only on hovering on the arrow.

**Comment by rostovtsev** [comment]
Updated an image.

**Comment by Sopor-** [comment]
It was only a suggestion to separate the different functions. It wasn't obvious that Copy still work as copy. As programmer of the theme know how it works so for you it is much easier. I don't know, maybe i'm stupid than average user?

**Comment by rostovtsev** [comment]
No you are not stupid, you are right - it can be done better!

I will see if I can do it without reworking the menu. If not, I will add this to my todo for later rework.

**Comment by rostovtsev** [comment]
That was difficult to implement, especially considering that the submenus open on the right, when context-menu triggered too close to the right side on the table.

Give it a try. I hope you will like it. I like it more now for sure. :wink:
