### ISSUE TITLE
File Manager - won't accept mouse clicks

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1300]
I don't know what is wrong but when i click on the folders they won't open. I need to press the root folder icon (or press the refresh button in the file manager) and then it starts to work. When i press the root icon i can see the columns moves a tiny bit.
It started after i changed the `Default number of records per page` but even if i change it back it will still not work.

![image](https://user-images.githubusercontent.com/5789283/52915076-ed28bd80-32cf-11e9-8c47-7a89cd517426.png)

Instead of open the folder it seems to open a new window. This is what happens when i try to open etc.

![image](https://user-images.githubusercontent.com/5789283/52915192-21e94480-32d1-11e9-9e5b-5e6115c8e57b.png)

Firefox 64
Authentic theme 19.23-beta6
Webmin 1.900

**Comment by Sopor-** [comment]
Update:
Now i think i have found it.
1. From Dashboard go to the File manager.
2. Open for example `etc`.
3. Now press the File manager in the left menu again.
4. You should now see that a new file manager has been open and if you know try to open a folder it won't work until you press the root or refresh button.

**Comment by rostovtsev** [comment]
I really tried but I can not reproduce it.

Besides, I don't know how to open File Manager from Dashboard.

Are you sure that you are using very latest version of the theme?

**Comment by Sopor-** [comment]
I didn't explain that you need to open the left menu, click others and then click File manager. I assumed you know how to open the File manager :)

**Comment by Sopor-** [comment]
I have made a [video](https://ufile.io/8qhlr) for you to see

**Comment by rostovtsev** [comment]
Please check if I followed your steps right?


[file_manager_working_first_load.zip](https://github.com/authentic-theme/authentic-theme/files/2875165/file_manager_working_first_load.zip)

----

After I did this video, I decided to test my production server. At first time, I reproduced, while on second time I couldn't.

There is an issue apparently but it's happening sporadically.

I will do more tests.

**Comment by rostovtsev** [comment]
Okay, great! I understood the logic behind the bug!

**Comment by rostovtsev** [comment]
Okay, thank you for your great reporting and provided data!

It's fixed https://github.com/webmin/webmin/commit/b46fcab0075c498c9a1f98de765cca90282b3cf6.

**Comment by Sopor-** [comment]
So this require a Webmin update?

**Comment by rostovtsev** [comment]
Yes or you could only update `filemin/filemin-lib.pl` file.

**Comment by Sopor** [comment]
This is still an issue. Same thing happens as before when i press the `File manager`

**Comment by Sopor** [comment]
As i wrote for 7 days ago, this is still an issue :(

Webmin: 1.910
Authentic theme: 19.34-beta9

**Comment by rostovtsev** [comment]
Do you mean it happens for you on initial load?

**Comment by Sopor** [comment]
In the left menu:
- 1. Click Others / File Manager
- 2. Change path to something else than root
- 3. Click File Manager and a new tab will open

You can do step 2 and 3 and it will open a new File Manager tab every time you click on File Manager.

**Comment by Sopor** [comment]
I noticed that the same thing happens if i open the `Module config` and change something and press save. When i get back to the file manager a new tab has open at `/`. For this to happen you need to have the first tab open in another folder, `/etc` will work.

**Comment by rostovtsev** [comment]
I suppose you are experiencing cache issue, as this is the only explanation of why I couldn't reproduce your issue, on _any platform_ for the _past few days_. 

It just works for me no matter what!

Install latest dev version. It has fixes on the cache problems that arose as I started to have betas with 9+ numbering.

After installing hit `Ctrl+Shift+Alt+Meta+R` to clear internal cache and reload the page. (You can also clear theme's cache from configuration page).

**Comment by Sopor** [comment]
So you mean that all my 4 Webmin have the same issue and that i need to clear my cache every time i use the File manager?

I have now cleared every cache i can and it is still open a new tab every time i press File manager. I think you are not doing it right.

1. From Dashboard go to Others/File manager.
2. You should now have the file manager open.
3. Change folder to whatever you want.
4. Press File manager in the left menu.
5. It will now open a new file manager tab.
6. Change to another folder as you did in step 3.
7. Press file manager in the left menu again and a third file manager tab will open.

You can continue like this as long as every tab is showing different folders.

**Comment by Sopor** [comment]
@rostovtsev Did you manage to reproduce it? I have created a video if you still can't reproduce it. Let me know if you want it.

**Comment by rostovtsev** [comment]
Those seven steps of yours to reproduce an issue, look like a Mortal Combat fatality combo. 🙃

Okay, yes, please send me the video. It's very likely that we don't understand each other.

**Comment by rostovtsev** [comment]
:exclamation: 

You wrote a week ago or so:

> This is still an issue. Same thing happens as before when i press the File manager

Now! This is totally different issue from the original one. Read what was the issue in your first comment. 

----

Okay, yes, I can reproduce it. It's not a bug but a feature. File Manager _**stores previously opened tabs**_ and at the same time opens the one from the location that was requested in URL.

If you don't like tabs you can disable them in File Manager configuration.

**Comment by Sopor** [comment]
Sorry if i wrote on the wrong issue, but i'm sure i have reported this before.

So you call this a feature? The same thing happens if i open the `Module config`. You can't call that a feature? It will also open a new tab even if i go back to dashboard. This will also open a new tab everytime i go back to the file manager depending on where i was the last time i used the file manager. For me this is a bug. If i want to open a new tab i use `Add a new tab CTRL+SPACE`.

**Comment by rostovtsev** [comment]
> .. and it will open a new tab.

It doesn't open _new_ tab - it opens previously used tab + `/` tab. If you leave tabs as they are - for example, `/` and `/boot` it will restore them as they were. If you navigate away from `/` tab to something else, then upon next File Manager load, the following tabs would load: `/`, `/boot` and `/somethingelse`.

---

Provide the video-screencast please, possibly we're talking about different things.

**Comment by Sopor** [comment]
[Video-screencast](https://gofile.io/?c=fKALWq)

This is the short version. Obvious you normally not do as in the video but the same thing happens if i go back to the Dashboard before i press File manager again and if i use the `Module config`. Even if it not happens very often that you open the Module config, but still it make no sense that it will open a new tab when i already have one (or more) open tabs.

**Comment by rostovtsev** [comment]
Look, it's perfectly expected.

After 0:25, stop changing tabs from `/` and just hit File Manager in the menu again - there will be no new tabs, or change the new tab using non-default (`/`) tab, for example, from that `/etc`that you have around 0:25 in your video - there will be no new tabs on the next load.

Anytime you navigate away from root tab (root tab - the tab that is requested via URL param, as a `path=`) you will have this tab opened automatically.

It's not a bug - it's a feature. :smile:

**Comment by Sopor** [comment]
Strange feature in my opinion. Very annoying when it opens a new tab in the root when i want to continue where i left off. If a tab is already open it should leave it as it was and not open a new one.

**Comment by Sopor** [comment]
It seems that if i change `Restore previously used tabs on first load` from Yes to No it won't create a new tab, but now it will change to root so it will not remember where i was :(

**Comment by rostovtsev** [comment]
It's designed like this on lower level. It's technically possible to change this but it would require significant change on the module itself to make it work smoothly.

Simply keep root tab intact and your tabs on the initial load will be exactly how you left them.

**Comment by Sopor** [comment]
This is so annoying that i have to press the root folder before i leave the file manager or else it will open a new tab and disable `Restore previously used tabs on first load` will make it not remember where i was so if i want to continue in the folder i have to browse in to it again. Don't you see the problem here?

**Comment by rostovtsev** [comment]
No! But only in case root tab (requested via URL with path param) is opened once - thus always there on initial load.

If it's not the case for you, please make video-screencast, so I can see what's going on.

I test hings on so many different machines, with so many different configurations and I don't see anything unexpected.

**Comment by rostovtsev** [comment]
> This is so annoying that i have to press the root folder before i leave the File Manager.

You don't need to click root folder before leaving and it will not open a new tab for you on the next visit. 

File Manager now as stable as never before.

Please provide a video-screencast if it doesn't work for you.

**Comment by Sopor** [comment]
I have already sent you a video that shows you what happens if i'm not press the root folder when i leave the file manager https://github.com/authentic-theme/authentic-theme/issues/1300#issuecomment-497334292

**Comment by rostovtsev** [comment]
Yes, we have already discussed it.
https://github.com/authentic-theme/authentic-theme/issues/1300#issuecomment-497336420
https://github.com/authentic-theme/authentic-theme/issues/1300#issuecomment-497373711

**Comment by Sopor** [comment]
> You don't need to click root folder before leaving and it will not open a new tab for you on the next visit.

But you are telling me that i don't need to press the root folder, but if i don't do that it will open a new tab every time i get back to the file manager.

**Comment by rostovtsev** [comment]
You don't need to do it in terms that you should let default tab just to be opened. What's the big deal.

In the future, possibly, I will rework it but just not right now.
