### ISSUE TITLE
File manager - Add a close button to the context menu?

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1301]
If i open the context menu it is not easy to close it again without selecting other files. To close the menu i need to do it on the exact same row i opened it on to avoid selecting other files. I can also close it by pressing on an empty space but with many files listed it will fit the whole page so there is no free space to click on.
So it would be nice if the context menu did have a close entry (or an X) that will close the menu.
I know i can use the ESC button but it should be possible to close it with the mouse too.

**Comment by rostovtsev** [comment]
Hi,

You can easily close the contextmenu by clicking anywhere on the page, not necessarily clicking in the table. Besides _escape_ is an awesome key, you should learn to love it. :wink: 

I don't like an idea of having close button for context menu, it sounds bizarre. Sorry.
