### ISSUE TITLE
spaces

### ISSUE THREAD

**Issue by htttito** [authentic-theme/authentic-theme#1302]
@rostovtsev 
Hi Ilia!
By editing files, there is always a "Ä" instead of a space.
Is it normal?
![webmin_edit](https://user-images.githubusercontent.com/40149753/53297832-8e5dc980-3824-11e9-9ef3-fc1ff4dae37c.png)

**Comment by htttito** [comment]
additionally...
There is a "a€" when you copy lines...and in some other situations.
I think it is the German translation?!
![webmin_edit_2](https://user-images.githubusercontent.com/40149753/53297873-45f2db80-3825-11e9-9d2f-6020ec1d2ed7.png)

**Comment by rostovtsev** [comment]
Hi,

It's encoding issue. [Troubleshoot](https://github.com/authentic-theme/authentic-theme/tree/18#troubleshoot).

**Comment by htttito** [comment]
Its not so important - sorry for jamming...
I read this..but my webmin Language is
- German-UTF-8
- my Browser Firefox and Opera shows the same "Ä"

![webmin_edit_3](https://user-images.githubusercontent.com/40149753/53298201-ca942880-382a-11e9-947b-42c2590791d1.png)
![webmin_edit_4](https://user-images.githubusercontent.com/40149753/53298202-cd8f1900-382a-11e9-8c1f-c92a8578b620.png)

**Comment by rostovtsev** [comment]
Last option _Use language specified by browser?_ set to _Yes_ in your case - set this option to _No_. :wink:

**Comment by htttito** [comment]
I have  tried everything, when i do this, the main menu is in German and the sub menu is in English..

**Comment by rostovtsev** [comment]
Okay, I have taken a closer look. It seems like a core bug, in my opinion. For now, you can set an option _Character-Set für HTML-Seiten_ to _utf-8_ to workaround your problem.

@jcameron Jamie, isn't the navigation menu has to be displayed in the user selected language, without doing anything extra? For now, if you select German, navigation menu/sub-menus don't get displayed in German, but only displayed if specified by browser is set to _Yes_ (and language set in browser as well). It's a bug, right?

**Comment by jcameron** [comment]
I noticed this as well, but after I did a full reload of the page in my browser the navigation menu showed up in the correct language.

**Comment by rostovtsev** [comment]
Jamie, I have checked it twice, and hard reload doesn't seem to help.

It doesn't work if settings are like this:

![image](https://user-images.githubusercontent.com/4426533/53331839-ee2aa200-3902-11e9-9051-2c2991856aa3.png)


.. while it does work fine, when settings are like following (and browser language has German set to the top of the list):

![image](https://user-images.githubusercontent.com/4426533/53331906-15816f00-3903-11e9-8df0-4b39ff0f0b60.png)


Check the content of the sub-menus. The first, has English still, while second, displays German correctly.

**Comment by htttito** [comment]
Hello!
Yes it is all correct but then there is still the Problem with the "Ä" and the "a€"

**Comment by gnadelwartz** [comment]
thanks @rostovtsev for diving in the Problem. I also had a look at the Problem and think its a core Problem.
same for the extra characters. the german lang files are ok and does not have the extra characters.

my workaround is to use german language with english modul names in menu ...

**Comment by rostovtsev** [comment]
Kay, my [comment](https://github.com/authentic-theme/authentic-theme/issues/1302#issuecomment-466786893) here, let's you have German completely, including the menus.

**Comment by gnadelwartz** [comment]
Ilia, yes but last time Iˋve done this I had also the Proble with the strange characters, may be this is fixed now :)

**Comment by rostovtsev** [comment]
Kay, I have done more testing and I can make German language work, including submenues and having no strange "Ä" or "a€" chars with the following setup.

![image](https://user-images.githubusercontent.com/4426533/53494381-af394f80-3aae-11e9-99a2-a31992b44689.png)

**Example:**
![image](https://user-images.githubusercontent.com/4426533/53494460-e1e34800-3aae-11e9-844d-d3be24026cd4.png)

You can also go to theme configuration and hit _Clear Cache_.

Does it work for you this way?

**Comment by htttito** [comment]
Yes that's it :-) :-) 
A little thing is rest.
![webmin_umlaut_a](https://user-images.githubusercontent.com/40149753/53516966-d6534980-3acd-11e9-9d18-0bcf2cee0001.png)
Thanks to all, good work

**Comment by gnadelwartz** [comment]
@rostovtsev thanks you are great!

The remaining ? may a wrong char in the lang file, I'll have a look

**Comment by jcameron** [comment]
Ok, after some looking into this, I discovered that it's actually a packaging issue that effects German and other European languages when using a UTF-8 charset. I will fix this in the next Webmin release.

**Comment by cleberjean** [comment]
The same problem occurs in portuguese languages, where in some places appers an interrogation character on cedil, tilde or acute characters place like in "Webmin settings".
