### ISSUE TITLE
Error show Ubuntu version

### ISSUE THREAD

**Issue by purik14** [authentic-theme/authentic-theme#1303]
![annotation 2019-02-24 203620](https://user-images.githubusercontent.com/47950531/53303617-621e6900-3875-11e9-9fa2-4a7f631b4fd7.jpg)
![annotation 2019-02-24 203653](https://user-images.githubusercontent.com/47950531/53303618-621e6900-3875-11e9-83e0-8ca453fb0ed4.jpg)

**Comment by rostovtsev** [comment]
@jcameron Jamie, it seems as core bug, that _MINOR VERSION_ is not getting automatically updated?

@purik14 You can manually update it by going to _Webmin/Webmin Configuration/Operating System and Environment_.

**Comment by jcameron** [comment]
Webmin doesn't automatically update, but it should show a button offering to sync it's idea of the version with the actual version if a mismatch is detected.

**Comment by rostovtsev** [comment]
Yes, true. @purik14 Are you sure that you didn't have such button appearing on the Dashboard and/or in Right Side Slider?
