### ISSUE TITLE
Theme: Custom favorites icon

### ISSUE THREAD

**Issue by SylvainLegrand** [authentic-theme/authentic-theme#1304]
Hi,

thank's for your hard work.

I'm trying to change the favorites icon in the JSON file, but it seems like nothing works except "webmin".

Is it normal behavior, or something I miss?

Greetings,
Sylvain Legrand.

**Comment by rostovtsev** [comment]
Sylvain, good day!

**Comment by rostovtsev** [comment]
Sylvain, good day!

To do so, as an icon name use:

```
x fa-user-md
```

You can replace _fa-user-md_ with any classname from the [icons inventory](https://authentic-theme.com/kit/).

**Comment by SylvainLegrand** [comment]
Hi,

Thank's for your answer.
But I already try this.

If I write :
`{ "link": "/filemin/index.cgi?path=/home/infras", "title": "InfraS home",	 "icon": "webmin"},`
it works.

If I change "webmin" by "fa-hdd-o" for instance, I had no icon at all as a result.
`{ "link": "/filemin/index.cgi?path=/home/infras", "title": "InfraS home",	 "icon": "fa-hdd-o"},`

I'm tryed also "hdd-o" or "hdd" alone, nothing works.

Greetings

**Comment by rostovtsev** [comment]
Replace `fa-hdd-o` with `x fa-hdd-o` and it will work.

**Comment by SylvainLegrand** [comment]
Thank's so much !

It works well !

Have a nice day.
Sylvain Legrand.
