### ISSUE TITLE
Theme: Custom Favicon

### ISSUE THREAD

**Issue by SylvainLegrand** [authentic-theme/authentic-theme#1305]
Hello,

Is it possible to change the Webmin favicon by a custom ?

Greetings
Sylvain Legrand.

**Comment by rostovtsev** [comment]
Hi,

No, it's hard coded, as we don't wish our products to be de-branded.

**Comment by gnadelwartz** [comment]
in Addition, if you want some branding you can add a custum logo to ligjn screen and left menu
