### ISSUE TITLE
Don't working search in DHCP module

### ISSUE THREAD

**Issue by SerBep** [authentic-theme/authentic-theme#1306]
Hello!
In DHCP module (server CentOS 6.10 (x86-64) client Firefox 65 x64) not working search.
Button "Edit the host name:" after click do nothing.
In Gray Framed Theme all working properly.
![default](https://user-images.githubusercontent.com/26068489/53470853-f35b2e80-3a73-11e9-942f-ad2d7638916e.JPG)

**Comment by rostovtsev** [comment]
Fixed https://github.com/webmin/webmin/commit/6922ab89f576cdfa1022fc2cd490303e7d905303
