### ISSUE TITLE
Go to dashboard after a reboot?

### ISSUE THREAD

**Issue by Sopor-** [authentic-theme/authentic-theme#1307]
It would have been nice if it could go to the dashboard after i have performed a reboot. That will indicate that the system is back and running. Now it will only show this page forever:

![image](https://user-images.githubusercontent.com/5789283/53660546-658f6700-3c5e-11e9-803c-740bd18c9aa7.png)

**Comment by rostovtsev** [comment]
Hi,

It's very interesting idea!

I will look into that!

Thanks.

**Comment by rostovtsev** [comment]
It's done. Have a look.

![image](https://user-images.githubusercontent.com/4426533/53803441-cfa55600-3f55-11e9-983a-572d1d70eccc.png)

**Comment by Sopor-** [comment]
I will remember to look for it the next time i reboot :)
