### ISSUE TITLE
Read mail - It doesn't look nice ...

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1310]
When i read mail it look like this

![image](https://user-images.githubusercontent.com/5789283/53847490-39068280-3fb1-11e9-98ae-a1694e8f49b2.png)

not very nice ...

**Comment by jcameron** [comment]
@rostovtsev looks like a theme bug?

**Comment by rostovtsev** [comment]
Yes, I will fix that. I have it on my list. It happens after switching to using UI links row.

After finishing 19.32, I'm planning to start do the mail - view and compose. So this page will not matter in the end.

**Comment by rostovtsev** [comment]
It's fixed for now.
