### ISSUE TITLE
Tooltip looks very weird

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1311]
When i hold the mouse pointer over the icon that looks like a book to the right of the Webmin version the tooltip look like this:

![image](https://user-images.githubusercontent.com/5789283/54556228-b621f680-49b8-11e9-8615-7d325865d358.png)

I get the same on the gear icon to the right of the Authentic theme version but only on three out of four Webmin's.

Authentic theme 19.32-beta1
Webmin 1.900

**Comment by rostovtsev** [comment]
Yes, I noticed it already. It's been fixed about a week ago.

Pull latest changes.

**Comment by rostovtsev** [comment]
Okay. It was fixed for the theme tooltip. Sorry, you're right.

**Comment by rostovtsev** [comment]
Fixed.

Thank you for reporting! :smiley_cat:
