### ISSUE TITLE
Theme: ui_hidden_table_start used repeatedly does not show all tables

### ISSUE THREAD

**Issue by grueni** [authentic-theme/authentic-theme#1312]
If you use ui_hidden_table_start to get collapsible tables authentic-theme produces inccorect results.

I prepared a test file which is displayed correctly with theme "Gray Framed Theme".
Please add this file to an existing module and check the results.
With authentic-theme the last 2 tables are missing.
Table 1 has margins, the follwowing tables have no margins.
Between table 2 and 3 is a gap.

authentic-theme: 19.31
Webmin 1.900

#!/usr/bin/perl

#require './zfsmanager-lib.pl';
#ReadParse();

ui_print_header(undef, "Test", "", undef, 1, 1, 0, undef, undef, undef, undef );

#Show pool information
print ui_hidden_table_start('Pool', "width=100%", 1,'zpool_pool', 1);
#print ui_table_row('Export ',  "<a href='cmd.cgi?cmd=export'>Export pool</a>");
print ui_columns_start([ "Virtual Device", "State", "Read", "Write", "Cksum" ]);
for (my $i = 0; $i < 10; $i++)
{
    print ui_columns_row(["<a href='config-vdev.cgi?pool=".$i.'&dev='.$key."'>|_".$i."</a>", $i, $i, $i, $i]);
}
print ui_columns_end();
print ui_hidden_table_end('zpool_pool');

#show properties for pool
print ui_hidden_table_start('Properties', "width=100%",4,'zpool_properties', 1);
#print ui_table_row('Export ',  "<a href='cmd.cgi?cmd=export'>Export pool</a>");
print ui_columns_start([ "Virtual Device", "State", "Read", "Write", "Cksum" ]);
for (my $i = 0; $i < 10; $i++)
{
    print ui_columns_row(["<a href='config-vdev.cgi?pool=".$i.'&dev='.$key."'>|_".$i."</a>", $i, $i, $i, $i]);
}
print ui_columns_end();
print ui_hidden_table_end('zpool_properties');

#Show associated file systems
print ui_hidden_table_start('File systems', "width=100%",1,'zpool_zfs', 1);
print ui_columns_start([ "Virtual Device", "State", "Read", "Write", "Cksum" ]);
for (my $i = 0; $i < 10; $i++)
{
    print ui_columns_row(["<a href='config-vdev.cgi?pool=".$i.'&dev='.$key."'>|_".$i."</a>", $i, $i, $i, $i]);
}
print ui_columns_end();
print ui_hidden_table_end('zpool_zfs');

#Show device configuration
#TODO: show devices by vdev hierarchy
print ui_hidden_table_start('Virtual Devices', "width=100%", 1,'zpool_vdevs', 1 );
print ui_columns_start([ "Virtual Device", "State", "Read", "Write", "Cksum" ]);
for (my $i = 0; $i < 10; $i++)
{
    print ui_columns_row(["<a href='config-vdev.cgi?pool=".$i.'&dev='.$key."'>|_".$i."</a>", $i, $i, $i, $i]);
}
print ui_columns_end();
print ui_hidden_table_end('zpool_vdevs');

#--tasks table--
print ui_hidden_table_start('Tasks', "width=100%",10,'zpool_tasks',1,['align=left']);
print ui_table_row("New file system: ", "<a href='create.cgi?create=zfs&parent=1'>Create file system</a>");
print ui_table_row('Scrub ', "<a href='cmd.cgi?cmd=scrub&pool=1'>Scrub pool</a>");
print ui_table_row('Upgrade ', "<a href='cmd.cgi?cmd=upgrade&pool=1'>Upgrade pool</a>");
print ui_table_row('Export ',  "<a href='cmd.cgi?cmd=export&pool=1'>Export pool</a>");
print ui_hidden_table_end('zpool_tasks');

**Comment by rostovtsev** [comment]
Hmm. If you have tables missing. it's indication that generated HTML is not valid. The fact that you have it displayed in Gray Theme doesn't mean that there is no issues on generated output. View the source of generated output, and check for its validity.

Just a hint. `ui_columns_row` generally never used with `ui_hidden_*`.

**Comment by grueni** [comment]
I read this too in the documenation (just use ui_table_row with ui_hidden_*).
But it works without any problems with "Gray Framed Theme".
ui_hidden_table creates a table with a one cell in the tbody. In this cell one or more tables are created with ui_columns_start et al.
The hierarchy of embedded tables is vaild HTML code, checked with Firefox und tidyHTML.
With authentic-theme only the first table is in div "panel-body". The following tables are found beneath.

**Comment by rostovtsev** [comment]
Did you make sure that generated HTML is valid, despite the fact that it's displayed "correctly" in non single-page themes?

**Comment by grueni** [comment]
The theme constructs a html with two iframes. I opened with Firefox the iframe with the tables in an own tab. Then I used the developer tools from FF to inspect the generated  source code. FF used HTML validator with tidyHTML to check the HTML code. There are warnings but they can be neglected.
So yes the validity of the created source code is checked by tidyHTML. No errors.

**Comment by rostovtsev** [comment]
The content that you see in developer tool is really not source HTML but rendered. The source can be seen by clicking in context menu, then _This Frame->View Frame Source_.

**Comment by grueni** [comment]
Thanks for your patience and the hint. 
In the real source code are in fact invalid nested table elements. 
Do you see any chance to get a panel with collapsible tables line an accordeon?

**Comment by rostovtsev** [comment]
> Do you see any chance to get a panel with collapsible tables line an accordion?

I am sorry, I didn't understand.

**Comment by grueni** [comment]
With ui_hidden_table_start you get a table which can be collapsed and uncollapsed. This is handy if you have e.g. 5 tables with a lot of rows. 
e.g. https://jqueryui.com/resources/demos/accordion/collapsible.html

**Comment by rostovtsev** [comment]
I beg your pardon! I still can not understand clearly what is your question, and how can I help you?

**Comment by grueni** [comment]
I try to get collapsible tables or better sections.
The first approach was incorrect (see above).

With ui_hidden_start and ui_hidden_end this should be possible.

With the old theme an output ist produced like (copied from the stored html page):
....
<a href="javascript:hidden_opener('hiddendiv_hidden_1', 'hiddenopener_hidden_1')" id='hiddenopener_hidden_1'><img border=0 src='/images/open.gif' alt='*'></a>
<a href="javascript:hidden_opener('hiddendiv_hidden_1', 'hiddenopener_hidden_1')">Tasks 1</a><br>
<div class='opener_shown' id='hiddendiv_hidden_1'>
....
<a href="javascript:hidden_opener('hiddendiv_hidden_2', 'hiddenopener_hidden_2')" id='hiddenopener_hidden_2'><img border=0 src='/images/open.gif' alt='*'></a>
<a href="javascript:hidden_opener('hiddendiv_hidden_2', 'hiddenopener_hidden_2')">Tasks 2</a><br>
<div class='opener_shown' id='hiddendiv_hidden_2'>
...

With authentic-theme an output ist produced like (copied from the stored html page):
...
<a href="javascript:hidden_opener('hiddendiv_hidden_1',%20'hiddenopener_hidden_1')" id="hiddenopener_hidden_1" style="border-bottom: 0px none;"></a>
<div class="opener_extra_container opener_extra_container_style"><div class="opener_extra_container opener_extra_container_style"><div class="opener_extra_container opener_extra_container_style"><div class="opener_extra_container opener_extra_container_style"><div class="opener_extra_container opener_extra_container_style"><div class="opener_extra_container opener_extra_container_style"><div class="opener_extra_container opener_extra_container_style"><a href="javascript:hidden_opener('hiddendiv_hidden_1',%20'hiddenopener_hidden_1')" class="opener_extra_container_a_style link_hover_effect" style="border-bottom: 0px none;">Tasks 1</a></div></div></div></div></div></div></div>
<div class="opener_shown" id="hiddendiv_hidden_1">
...
<a href="javascript:hidden_opener('hiddendiv_hidden_2',%20'hiddenopener_hidden_2')" id="hiddenopener_hidden_2" style="border-bottom: 0px none;"></a>
<a href="javascript:hidden_opener('hiddendiv_hidden_2',%20'hiddenopener_hidden_2')" style="border-bottom: 0px none;">Tasks 2</a><br>
<div class="opener_shown" id="hiddendiv_hidden_2">
...

The first collapsible div is different from the following collapsible divs.
I would prefer the design from the first div.
And I guess there are some unnecessary nested divs too.
I would like to have that all divs created by ui_hidden_start look like first div.

My test page

ui_print_header(undef, "Test", "", undef, 1, 1, 0, undef, undef, undef, undef );

print ui_hidden_start('Tasks 1', 'hidden_1',1 );
print ui_columns_start([ "Virtual Device", "State", "Read", "Write", "Cksum" ]);
for (my $i = 0; $i < 10; $i++)
{
print ui_columns_row(["<a href='config-vdev.cgi?pool=".$i.'&dev='.$key."'>|_".$i."", $i, $i, $i, $i]);
}
print ui_columns_end();
print ui_hidden_end('hidden_1');

print ui_hidden_start('Tasks 2', 'hidden_2',1 );
print ui_columns_start([ "Virtual Device", "State", "Read", "Write", "Cksum" ]);
for (my $i = 0; $i < 10; $i++)
{
print ui_columns_row(["<a href='config-vdev.cgi?pool=".$i.'&dev='.$key."'>|_".$i."", $i, $i, $i, $i]);
}
print ui_columns_end();
print ui_hidden_end('hidden_2');

**Comment by rostovtsev** [comment]
> With Authentic Theme output is produced like (copied from the stored html page).

Where did you copy HTML from, when checking its output in Authentic Theme?

**Comment by grueni** [comment]
In Firefox right cklick on the page, save it to a disk file and open it with an editor.

**Comment by rostovtsev** [comment]
No. This is rendered HTML.

Go to dev tools, network tab, and when you visit/load the page you need to check your accordions on, check for delivered HTML (response), from the last call.

**Comment by grueni** [comment]
The generated source looks good.
```html
<div class="panel-body">
<a href="javascript:hidden_opener('hiddendiv_hidden_1', 'hiddenopener_hidden_1')" id='hiddenopener_hidden_1'></a>
<a href="javascript:hidden_opener('hiddendiv_hidden_1', 'hiddenopener_hidden_1')">Tasks 1</a><br>
<div class='opener_shown' id='hiddendiv_hidden_1'>
<table class="table table-striped table-hover table-condensed">
...
<a href="javascript:hidden_opener('hiddendiv_hidden_2', 'hiddenopener_hidden_2')" id='hiddenopener_hidden_2'></a>
<a href="javascript:hidden_opener('hiddendiv_hidden_2', 'hiddenopener_hidden_2')">Tasks 2</a><br>
<div class='opener_shown' id='hiddendiv_hidden_2'>
<table class="table table-striped table-hover table-condensed">
```
But the first div has an another layout. 
I prepared a gist: https://gist.github.com/grueni/e2d0d0acbb01dc23375f4fe5b3dbc8bd

**Comment by rostovtsev** [comment]
..and now, at this moment, I can see that you're started having UI tabs, that you never mentioned before? 

Look, go through Webmin, find familiar part of UI, see how it works, and use it in your module. Could you do that?

**Comment by grueni** [comment]
Sorry I copied wrong code into the gist. 
No tabs were used. Just the bare minimum for an example. The cgi is started by a link and opened in a new tab. And the rendederd result is shown in the picture.
I found with webmin/status/edit_tmpl.cgi a script using ui_hidden_start. I doubled the section and got the same problem.
The second div looks different.
I try hard to understand why and where this is defined.

**Comment by grueni** [comment]
It is defined in bootstrap.min.js.
```js
a.parent(n).find('a[href^="javascript:hidden_opener"]:eq(1)').wrapAll('<div class="opener_extra_container"></div>')
```
The elements anchor, anchor, break, div created by each ui_start_hidden are only processed for the first occurrence starting with the second anchor.
But all anchors with attribute href=avascript:hidden_opener and followed by an element br should be processed.

**Comment by rostovtsev** [comment]
You are doing something wrong in your code. Openers and the way they are implemented in Webmin, using tables are hard to override for the theme, as `ui_table_row` is called pretty much everywhere in-between. This is the reason why I left them intact, and made them look like Bootstrap collapses using JavaScript and CSS.

Try:

```Perl
print ui_hidden_table_start();

print ui_table_row();

print ui_hidden_table_end();
```

**Comment by grueni** [comment]
You are talking about the first approach which was wrong. There you are right.

But I am talking now about multiple uses of "ui_hidden_start" not "ui_hidden_table_start".
The title of the issue is wrong now and should be changed accordingly.
In the light of this please read my last comment again. 
The code in bootstrap.min.js processes just the first group of elements created by multiple the "ui_hidden_start".

Please see here https://gist.github.com/grueni/e2d0d0acbb01dc23375f4fe5b3dbc8bd

**Comment by rostovtsev** [comment]
Okay, I see the issue now. The problem was, that it's never been used in Webmin/Usermin like that before (more than once), this is why it's left unnoticed.

I will see what I can do!

Thank you for being persistent and patient.

**Comment by grueni** [comment]
The select before finds all anchors from ui_start_hidden.
Then the cursor is repositioned for each hit to the parent of the anchor.
For each anchor a div is inserted and this explains the multiple nested divs.

I changed the selection so that only the anchors with id are found and removed the repositioning.
Then the selected item is used for the transformations.
This works now for me.


```js
        $('a[id*="opener"][id$="_restore"]').parent().is("p") && ($('a[id*="opener"][id$="_restore"]').next("a").parent("p").replaceTagName("div"), $('a[id*="opener"][id$="_restore"]').next("a").removeClass().addClass("opener_extra_container_a_style link_hover_effect").parent("div").addClass("opener_extra_container opener_extra_container_style margined-top-10"), $('a[id*="opener"][id$="_restore"]').remove()), $('a[href^="javascript:hidden_opener"]:not(".opener_trigger").and([id*="opener"])').length > 0 && ($('a[href^="javascript:hidden_opener"]:not(".opener_trigger").and([id*="opener"])').each(function(e, t) {
            var i = !!(v___location_path == v___location_prefix + "/virtual-server/backup_form.cgi" && v___location_href && v___location_href.indexOf("?sched=") > -1);
            if ($(this).find("img").length > 0 && $(this).remove(), $(this).css("border-bottom", "0"), $(this).parents("table.table").addClass("opener_table_style_small"), $(this).parent("td").addClass("opener_table_cell_style_small"), i || $(this).parent("td").addClass("opener_table_cell_style_small opener_table_cell_style_small_exclusion_border_top"), $(this).parent("td").find("a").addClass("link_hover_effect link_hover_effect_style"), $(this).parent().is(".panel-body") || $(this).parent().is(".ui_form")) {
                var a = $(this),
                    n = a.parent().is(".panel-body") ? ".panel-body" : ".ui_form";
                a.wrapAll('<div class="opener_extra_container"></div>'),core.curModuleFile("bind8", "edit_zonekey.cgi") && a.parent(n).find('a[href^="javascript:hidden_opener"]:eq(' + (e + 1) + ")").wrapAll('<div class="opener_extra_container"></div>'), a.parent('.panel-body > a[href^="javascript:hidden_opener"]:first-child').remove();
                var s = a.parent();
                $(s).next("br").remove(), $(s).addClass("opener_extra_container_style"), $(s).find("a").addClass("opener_extra_container_a_style link_hover_effect"), $(s).next(".opener_hidden").attr("style", "padding:8px")                
            }
        }), $.each($(".opener_hidden"), function() {
````

**Comment by rostovtsev** [comment]
I am not sure what that is. I have fixed it already locally. 

I will do other tests, and will push a fix in a bit.

**Comment by rostovtsev** [comment]
Okay, fixed. Give it a try.

Thanks for reporting!

**Comment by grueni** [comment]
LGTM
Thanks a lot!
