### ISSUE TITLE
Theme: theme_ui_columns_row ignores $tdtags

### ISSUE THREAD

**Issue by grueni** [authentic-theme/authentic-theme#1314]
theme_ui_columns_row ignores completely $tdtags.
I try to get empty div in a table cell with a certain width and height to draw  a graph.

  print &ui_columns_start([ "Graph"],100,1);
  print &ui_columns_row(['<div id="cy">.</div>'],['style="background-color:red; width:400px; height:400px"']);
  print &ui_columns_end();

**Comment by rostovtsev** [comment]
Fixed. Thanks for reporting!
