### ISSUE TITLE
After Update 19.32-beta3  not loading file manager

### ISSUE THREAD

**Issue by nasersobhan** [authentic-theme/authentic-theme#1316]
I have updated the theme using git (auto by webmin) but it seem now i can't see the file manager and I tried few day still nothing and I even can't change the theme. 
when i change it it says redirecting but still the same theme.
blew might help from console

`[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

bundle.min.js?1932155472447623:25

**Comment by rostovtsev** [comment]
Hi.

Just try to clear cache first? Reload the page using `Ctrl+Shift+R`.

**Comment by rostovtsev** [comment]
By the way, how many tabs did you have opened previously?

**Comment by rostovtsev** [comment]
Ohh.. Are you opening it in single frame? (without left menu)

**Comment by nasersobhan** [comment]
I did clear the cache and I even tried in another browser (clean one) but still the same, and yes I am opening it in new windows without sidebar.

**Comment by nasersobhan** [comment]
in the same windows i got this error in the console

`Uncaught TypeError: _f__table(...).DataTable is not a function
    at <anonymous>:12:16774
    at dispatch (bundle.min.js?1932155474375823:25)
    at v.handle (bundle.min.js?1932155474375823:25)`
but File manager box still loading

**Comment by nasersobhan** [comment]
but it's loading it now. thanks

**Comment by rostovtsev** [comment]
Okay, I made a patch to make File Manager load without navigation menu as well.

By the way, you don't need to open it in separate tab, as now, you can simply click _Alt+A_ to collapse navigation menu.

Thanks for reporting.

**Comment by nasersobhan** [comment]
thank you sure
