### ISSUE TITLE
File manager - All files will get downloaded when i try to view them

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1317]
In Windows 8.1 in Firefox i could view files in the `File manager` but now when i run Windows 10 and Firefox 66.0.1 it will open a requester asking me what to do and even if i select open it will download the file with the name `download.cgi`. How do i prevent this?

**Comment by rostovtsev** [comment]
>  .. I could view files in the File manager

What type of files you could view?

**Comment by Sopor** [comment]
If i click on a file it will open an editor. At least it did that before.

**Comment by rostovtsev** [comment]
If you clicked on the file you get download. It was forever like this, right? 🙂

To edit the file use F4 or contextmenu.

**Comment by Sopor** [comment]
Yeah, you are right. Silly me. Of course i need to choose Edit from the context menu ...

**Comment by rostovtsev** [comment]
No worries.
