### ISSUE TITLE
Add date/time to the Connection lost dialog

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1325]
Could you add date and time to the ` Connection lost` dialog so it is possible to see when i lost the connection?

**Comment by rostovtsev** [comment]
Okay, added it.

![Screenshot from 2019-04-26 11-05-38](https://user-images.githubusercontent.com/4426533/56792980-88c83400-6813-11e9-9384-bb48100dd0ff.png)
