### ISSUE TITLE
Make it possible to change title bar text

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1326]
Is it possible to change the title bar? Now i have 3 tabs with the name Dashboard that is totally useless for me. Instead i would like to have the host name first. Before this was changed it was showing Webmin, but now when you changed it, it would have been nice if i could choose my own text instead or at least have a drop down menu with different alternatives to choose from like you do when you choose date format and style.

![image](https://user-images.githubusercontent.com/5789283/56725742-be0a4e80-674d-11e9-8c81-9420357f62cb.png)

**Comment by rostovtsev** [comment]
Sopor, hi!

Sounds like a good idea. I added it.

Give it a try. There is new option in _Theme Configuration/Global Options_:

![image](https://user-images.githubusercontent.com/4426533/56742681-e01bc500-677d-11e9-8b87-54a90d036f97.png)

The initial title and the way it looks can be tweaked under _Webmin Configuration/User Interface_ section:

![image](https://user-images.githubusercontent.com/4426533/56739455-5832bc80-6777-11e9-8d45-52981aa1ae9e.png)

**Comment by Sopor** [comment]
Unfortunately it is impossible to remove the `Webmin 1.900` so i still can't get the host name first or the custom name i select in the `User interface` :(

**Comment by rostovtsev** [comment]
What about Webmin option to prepend hostname to page title?

**Comment by rostovtsev** [comment]
What is the expect output, by the way?

**Comment by Sopor** [comment]
To get the hostname first so it is easy to see it in the title bar (tabs) and the `Other name...` in the User interface also could be first to have a custom name in the title bar. When many tabs are open they get really small and only show the first word as you could see in the picture i posted before.

![image](https://user-images.githubusercontent.com/5789283/56759273-e10e2000-6798-11e9-9402-b35ef4da84f2.png)

**Comment by rostovtsev** [comment]
Okay, I am reworking this part and adding more options to format titles, and be shown in one place in UI.

**Comment by rostovtsev** [comment]
How about these kind of formats?

```
Module
Module — Webmin verson (OS type)
Webmin verson (OS type) — Module
Webmin verson (OS type)
hostname - Webmin verson (OS type) — Module
username at hostname - Webmin verson (OS type) — Module
```

**Comment by rostovtsev** [comment]
I was a little hasty in the afternoon. I added even more. I expect this will satisfy you and other users?

![image](https://user-images.githubusercontent.com/4426533/56764352-276d7a00-67ad-11e9-8f98-10701432c4ab.png)

Please give it a try now.

**Comment by rostovtsev** [comment]
By the way, now you can run theme update by clicking hotkey - `Ctrl + Alt + Meta + ⇧ + U`. :smile:

**Comment by Sopor** [comment]
> By the way, now you can run theme update by clicking hotkey - `Ctrl + Alt + Meta + ⇧ + U`. 😄

I don't even know where to find those keys 😕

**Comment by rostovtsev** [comment]
Okay, if you have an idea of other title formats, please share - I might add it.

It's all modifier keys pressed together + U to update to the latest beta, same mod keys + R to clear all kind of theme caches and reload.

**Comment by rostovtsev** [comment]
Meta key is Cmd on Mac, Alt is Option.

One day I'll translate those keys for different platforms.

**Comment by Sopor** [comment]
So these are some kind of hidden hotkeys?

**Comment by rostovtsev** [comment]
Not anymore.

If you hover on Clear Cache and Force Update buttons in Theme Configuration, then you would see the explanation tooltip.

**Comment by yann-papouin** [comment]
For the record, when using the `Authentic Theme`, the option is moved to the theme configurator

![image](https://github.com/webmin/authentic-theme/assets/2794099/016c16c4-860f-4c7f-bcd2-6c36b3424fe3)
