### ISSUE TITLE
The biggest project ever for you

### ISSUE THREAD

**Issue by sz00gun** [authentic-theme/authentic-theme#1328]
Hello,

Can you please consider to make a new product: virtualmin lite ?

Lite version with only essential function to run a server.

With your skills it just possible...

Consider it please

**Comment by rostovtsev** [comment]
Hi,

Interesting idea. 🙂

What is considered to be essential functions? Besides, what is not essential, that is not needed, from your perspective?

**Comment by sz00gun** [comment]
IMHO all this functions what are in client panel + some mandatory such as: IP managment, only basic settings from webmin, backup, file manager etc.

Other functions aren't really used everyday.

Just a light version...

**Comment by rostovtsev** [comment]
These kinds of essential functions selection should be optional.

It would be enough to let user choose which parts of UI should be hidden, I guess for now.

**Comment by rostovtsev** [comment]
I will keep this idea in mind, though I already had one in the past to be honest.

Thanks.
