### ISSUE TITLE
19.32 - File Manager search functionality

### ISSUE THREAD

**Issue by BackPacker777** [authentic-theme/authentic-theme#1329]
I had to downgrade to 19.31 because the search function was not working at all. Kept telling me that nothing was found after searching. 19.31 works great!

**Comment by rostovtsev** [comment]
What is your request string that you're trying to find?

**Comment by BackPacker777** [comment]
Well, I was trying to do a search and replace for apostrophes and replace them with a single quote like I always have to do. That stopped working after the 19.32 upgrade. On a whim, I tried simply searching for file names and that didn't work either. Query mask I used was an *

**Comment by rostovtsev** [comment]
There is no need for masking (using *) anymore.

Can you try without it.

**Comment by BackPacker777** [comment]
Will do. I will report back soon.

**Comment by BackPacker777** [comment]
It wont let my put anything in the '**find in results**' box unless there is something in the '**Query mask**' box

**Comment by BackPacker777** [comment]
Search and replace returns "Error: 200 - Document follows" on a red bar on the bottom of the page.

**Comment by rostovtsev** [comment]
I'll check.

**Comment by rostovtsev** [comment]
I made a quick patch to let you use * for all files. There was unquoted user input. Please pull latest development version to give it a try.

While in the theme just hit `Ctrl+Shift+Alt+Cmd(Meta)+U` to update to latest beta.

I will see if it's possible to add full regex support, like all files ending with digit `\d$`.

**Comment by BackPacker777** [comment]
I've run the update, but I'm still at 19.32....? Anyway, I tried search again and I'm experiencing the same issues. Sorry. I do appreciate your customer service though!

**Comment by rostovtsev** [comment]
I haven't change the version yet.

Are you sure that you have installed latest development version and bit stable? Try using theme configuration instead.

**Comment by rostovtsev** [comment]
I double checked. It should work!

**Comment by BackPacker777** [comment]
Sorry. I've performed the CTRL+SHIFT+ALT+WINDOWS KEY+U several times and I am still experiencing the same issues. I even did the **"Force update theme"** with no luck.

![force](https://user-images.githubusercontent.com/6719086/57014177-078aeb80-6bdd-11e9-83d3-7d0e1d519f21.png)

**Comment by rostovtsev** [comment]
Okay, what is the output of 

For Debian:
```
cat /usr/share/webmin/authentic-theme/extensions/file-manager/file-manager-lib.pm |grep "eq \"\*\""
```

or 

For RHEL
```
cat /usr/share/webmin/authentic-theme/extensions/file-manager/file-manager-lib.pm |grep "eq \"\*\""
```

What if you just search * in your folder, does it return you all results?

What is the exact string that you're trying to replace?

**Comment by BackPacker777** [comment]
* gives me no results.

The cat command returns nothing. I also redirected the output to a file and it was empty.

If you go to https://codedelegance.com you will see that my Hexo blog theme inserts apostrophes instead of single quotes in my articles after generating the html from my md files. Prior to 19.32, I'd use your search capability to replace all of them easily by editing the index.html file, copying the offending character, pasting it into your search tool and typing a ' in the replace box. Always worked great. (I used * as the query mask).

**Comment by rostovtsev** [comment]
Okay, nice site by the way.

I have just released `19.33-alpha1` go and upgrade to the latest development version. After update you should see that you are running `19.33-alpha1` (on Dashboard for example).

About the search. With latest commit you can use regex to search for file name.

For example to get all files ending with digit go with `\d$`. To get all possible matches use `*`. Using wild char and regex might lead to DoS, as of big chunk of data to be processed, so use it with care.

___

About your issue. What is the exact file name that you are searching for? What is the exact string that you are trying to find to replace later and  what is the replacement itself?

**Comment by BackPacker777** [comment]
Thanks!

Ok, I see the update now and file searching works. Replace still returns a 200 error though.

I paste in **‘** to the "**find in results**" box and I type **'** in the "**Replace in results**" box.

**Comment by rostovtsev** [comment]
I did it exactly what you said and it was replaced correctly.

The "error" seems to me like a bug. I will check.

Are you sure that nothing is replaced?

**Comment by rostovtsev** [comment]
Please run another update to see if you still having this "error" showing.

**Comment by BackPacker777** [comment]
I made you a video!

https://drive.google.com/file/d/1mOSrUJsU1n2Xn083i4LMR5QvvO4xylQx/view

**Comment by BackPacker777** [comment]
New video after updating per your request:  https://drive.google.com/file/d/1HIbNu_mz4xFWlGHSc6xuXi-03yjLAVag/view

**Comment by rostovtsev** [comment]
Wow, those were the best video-screencasts, while reporting an issue I have ever seen! :heart_eyes: 

Okay. I am confused now with two things. Why it's not getting replaced for you and why do you get this strange error. What browser do you use and on which platform? I could easily replace exampled chars.

However, there were some bugs which I fixed, but I am not sure if it will help in your case. Let's see. Please update to the latest dev version.

Now you can use regex for file mask and find results.

![image](https://user-images.githubusercontent.com/4426533/57020701-cd4c3900-6c32-11e9-96b2-f9724b083214.png)

**Comment by rostovtsev** [comment]
By the way, there is no reason for waiting until that response is "done". It doesn't hang, 200 is success response and I have no idea yet, why it's an error in your case.

**Comment by rostovtsev** [comment]
I am starting to think, that to make this feature even more useful, we should only be able to find/replace in text files.

**Comment by BackPacker777** [comment]
Okay, I have updated to alpha2 and I am experiencing the same issue with replace. I am using Chrome 73 in incognito & regular mode. I also tried on Chrome 66 and had the exact same problem. I am able to find all files, I just can use the 'grep'/replace functionality.

**Comment by rostovtsev** [comment]
Okay. Such error response means that response received in _text/html_ instead of expected _json_ format. Do the following. Open browser's console. `F12` or `Ctrl+Shift+J`. Go to network tab and run the search/replace. Then check that `search.cgi` request and response that it generates? Maybe making a screenshot?

**Comment by BackPacker777** [comment]
This?
![this](https://user-images.githubusercontent.com/6719086/57027442-61ee7100-6c0a-11e9-805d-0d75e6190f89.png)

**Comment by rostovtsev** [comment]
**Example of how it works for me:**

![replacement](https://user-images.githubusercontent.com/4426533/57027619-92073580-6c45-11e9-9bce-793ea058e190.gif)

**Example of what to do in console:**

![replacement_console](https://user-images.githubusercontent.com/4426533/57027916-591b9080-6c46-11e9-8e19-118617af165a.gif)


What is the output of the console command:

```
get_server_data('charset')
```

**Comment by rostovtsev** [comment]
Stop. I got the same error while replacing from another folder.

Working on it..

**Comment by rostovtsev** [comment]
Howard, it's finally nailed and fixed. Sorry for taking some time. Thank you very much for reporting!

**Comment by CodeElegant** [comment]
Yay! It works now! Thanks so much.

**Comment by CodeElegant** [comment]
To thank you, here is a video. Watch to the very end for a treat!

https://www.youtube.com/watch?v=6SFNW5F8K9Y

**Comment by rostovtsev** [comment]
@CodeElegant This is outstanding performance of the song that I loved since I was a child. And those guitar skills are mind blowing.

You know, YouTube recommended me, right after your song, [this video](https://www.youtube.com/watch?v=o3O_Wi9UDfY), so I couldn't not sharing it and recommend for listening! :wink: It gives me shivers everytime I listen to it. It's very important to surround your self with as many genius and talented people as possible[ - ](https://www.youtube.com/watch?v=kK0rpKOEAt0) physically or remotely.
