### ISSUE TITLE
Extra entries - impossible to scroll

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1330]
This help text has a scrollbar but when i move the mouse to the scrollbar the window will close, so it is impossible to read it all

![image](https://user-images.githubusercontent.com/5789283/56994896-a2190980-6ba0-11e9-9a03-d03a6bc995ad.png)

**Comment by rostovtsev** [comment]
You can click on the question mark icon and the tooltip would stay for you. I considered it.

**Comment by rostovtsev** [comment]
Okay, I have improved it. It's less confusing now. Give it a try.

Thanks for reporting.

**Comment by Sopor** [comment]
Doesn't seems to work everytime i click on it :(

**Comment by Sopor** [comment]
I will give it a try :)
