### ISSUE TITLE
Updating failure - Error 404 File not found

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1331]
I was updating the theme but for some reasons it looked like this

![image](https://user-images.githubusercontent.com/5789283/57035362-19f33c80-6c52-11e9-87f7-44e7665cb4d7.png)

**Comment by rostovtsev** [comment]
What is your set up? What console says?

**Comment by rostovtsev** [comment]
This could happen as the theme files were moved, while updating, and the theme was trying to query in background, possibly live stats. Are the live stats enabled for you? Do you have regular HDDs on your machine, where you were running the update or SSDs?

**Comment by Sopor** [comment]
I'm not sure which of the machines it was. I run HDD, SSD and micro SD card, but why should it fail because i run a certain type of media? It seems that all of them are running 19.33-beta1.

**Comment by rostovtsev** [comment]
I explained why above.

I have made a patch to address it. Thanks for reporting.

**Comment by rostovtsev** [comment]
> Why should it fail because i run a certain type of media?

Update time that is needed to move the files within a second.
