### ISSUE TITLE
Bind DNS Server display problem

### ISSUE THREAD

**Issue by Totobo** [authentic-theme/authentic-theme#1336]
Search under the DNS Bind Server. The same domain name shows the same domain name under different views. It is impossible to distinguish which view. Please optimize the display mode.
This search method is very useful in the case of a lot of domain names.
![image](https://user-images.githubusercontent.com/16574475/57205528-d1d96e80-6ff1-11e9-8ed0-c522d09f5bfb.png)

**Comment by rostovtsev** [comment]
Strange but I have this option working just fine. Do you have the same domains repeated in the list in content (on the right) page?


What is the exact domain length and how are they displayed on the right side?

**Comment by rostovtsev** [comment]
I change my language to _Simplified Chinese_ (UTF-8) and it's still working fine.

I also registred on my debug machine `debug-debian20-very-long-name-that-still-would-work.local` and it seems to be fitting just fine.

![image](https://user-images.githubusercontent.com/4426533/57211513-33490f80-6fe9-11e9-9fa7-1c7a79dcbeac.png)

**Comment by Totobo** [comment]
I'm using view model at bind. 
I have three views, these view may have same domains, when i search the doman at search bar, i can't know which domain is the right view i want access. because the search bar shows three same domain, It does not show which view the domain  corresponds to.

![image](https://user-images.githubusercontent.com/16574475/57216614-e8e48480-7022-11e9-9d21-07f3706d0619.png)

**Comment by rostovtsev** [comment]
Okay, that makes more sense.

Are they the same links or different? 

Do you get this page above (with results) after searching on the main page?

Here:

![image](https://user-images.githubusercontent.com/4426533/57218303-a8bedb00-6ffd-11e9-9b86-2fb05f1e0115.png)

**Comment by Totobo** [comment]
They are different links, just showing the same.

I can see the page when the number of zones greater than the value I set.

But it doesn't show any zones before i search something.

Can the search bar be displayed as follows
![image](https://user-images.githubusercontent.com/16574475/57221324-5dbebb00-7031-11e9-8cf3-76a555252584.png)

**Comment by rostovtsev** [comment]
Yes, it could. I am just not sure how to reproduce such output. Could you email me your BIND complete config on [еmаiI](https://github.com/authentic-theme/authentic-theme/blob/master/401.cgi#L5)?

**Comment by Totobo** [comment]
BIND configuration has been sent to the mailbox, please check the attachment content.

**Comment by rostovtsev** [comment]
Just added it. Pull latest development version to give it a try. :smile_cat:

**Comment by rostovtsev** [comment]
Aside from using search in navigation, I have also added ordinary table(s) filter. Simply start typing while you're on BIND page, and it will filter the table.

**Example:**

![image](https://user-images.githubusercontent.com/4426533/57309889-81e1d100-70f1-11e9-8277-d73c6b5e5c54.png)


May be you would be interested in disabling grouping by view at all. :wink:

**Comment by Totobo** [comment]
Thanks a lot for fix this. The table(s) filter works good.

But I have another problem: Then sidebar doesn't show and Default module for Webmin also lose efficacy  When i upgrade to the latest development version 19.34-alpha2 and click any of modules .

The last version I used was 19.31. I cleaned up the theme's cache and also reset the theme settings, which didn't take effect.

Is there a setting to switch the sidebar open or close but I didn't find it.

Sorry for my poor English, hope you can understand. 😄

Main Page:
![image](https://user-images.githubusercontent.com/16574475/57348114-7ccf6100-7187-11e9-8065-5ab26e2f64ac.png)

access any page
![image](https://user-images.githubusercontent.com/16574475/57348240-f23b3180-7187-11e9-9166-90a6af03f8d9.png)

Theme setting
![image](https://user-images.githubusercontent.com/16574475/57348403-7ee5ef80-7188-11e9-92d1-838b05a97850.png)

**Comment by rostovtsev** [comment]
You can intentionally open a module without navigation menu by holding Ctrl+Alt when clicking any link. 

In order to get back to normal view, just click Home button, in table header.
