### ISSUE TITLE
Editing files not working on mobile

### ISSUE THREAD

**Issue by sz00gun** [authentic-theme/authentic-theme#1337]
Editing files not working on mobiles. I used Chrome (latest) and latest stable version of the theme. Using Ubuntu 16.04

On PC and desktop view on mobiles, editing is working ...

**Comment by rostovtsev** [comment]
What is your mobile device? 2hat do you mean by not working?

**Comment by sz00gun** [comment]
I have LG G7. 
I press edit file, make some changes, click on save. Looks like it saved the content, but nothing been changed in the file.

**Comment by sz00gun** [comment]
Please have a look this on your end, if you cannot reproduce it I can record a screen cast step by step tomorrow.

**Comment by rostovtsev** [comment]
Did you try to request Desktop version of the website?

 ![](https://i.imgur.com/NzSocgg.png)

**Comment by sz00gun** [comment]
Yes. On desktop view it's working fine.

**Comment by rostovtsev** [comment]
Okay, great then! :smile:

**Comment by rostovtsev** [comment]
It's worth making sure that it happens automatically, though. I will make a patch a bit later.

**Comment by rostovtsev** [comment]
I gave it a try on my Pixels 2XL in Chrome and it seems to work just fine in neither modes. Files are saved correctly.

The only problem that I noticed is the initial size of the window. I will improve it.

Thanks for reporting.
