### ISSUE TITLE
Dashboard - Refresh button did show a 404 file not found message

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1338]
When i pressed the refresh button two of my Webmin showed this message

![image](https://user-images.githubusercontent.com/5789283/57316340-dbe49580-70f5-11e9-9eb5-ae9eee6bf8dd.png)

I haven't manage to reproduce it, yet :)

**Comment by Sopor** [comment]
Now i got that error 404 page not found again when i changed theme to Gray theme (as you told me to do) for a few seconds but it continued to load...

**Comment by rostovtsev** [comment]
What is the URL for this page, which returns 404 error?

**Comment by Sopor** [comment]
The first 404 error was the dashboard
`https://192.168.0.10:10000/sysinfo.cgi?xnavigation=1`

The second time it was when i changed theme
`https://192.168.0.10:10000/change-user/?xnavigation=1`

**Comment by rostovtsev** [comment]
Yes, you can get this error upon changing themes. It's not a bug. The page after theme change should be reloaded.

**Comment by Sopor** [comment]
The first picture has nothing to do with changing theme. I only pressed the refresh button. I have to see if i can reproduce it in some way...
