### ISSUE TITLE
Cron jobs - one job won't open

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1339]
In the cron jobs i have one entry that won't open. I'm not sure if this is a theme issue or what but i have to start somewhere

![image](https://user-images.githubusercontent.com/5789283/57329937-0b56ca80-7115-11e9-86fb-5269ed017838.png)

The one i have marked in red will not open. All the others opens after 1-3 seconds.

**Comment by rostovtsev** [comment]
It's not theme related. :wink:  You could check browsers console and Network tab while clicking on the link.

What browser are you using, and on which platform?

**Comment by Sopor** [comment]
This is Raspbian Linux 9 (DietPi) with Firefox 66.0.4. When i press that first entry nothing is showing up in the Network tab.

**Comment by rostovtsev** [comment]
Does anything show up if you switch to Gray Theme?

**Comment by Sopor** [comment]
Yes, it seems to load an empty page, so it seems to be your theme after all :)

![image](https://user-images.githubusercontent.com/5789283/57333567-76a49a80-711d-11e9-98bc-723dff3a63b0.png)

**Comment by rostovtsev** [comment]
What type of cron job is that?

**Comment by rostovtsev** [comment]
You can find it by clicking on _Manually edit cron jobs_ and searching for _readme_ in UI.

**Comment by Sopor** [comment]
It is a file with only comments but the Gray theme will open it :)
```
# /etc/cron.minutely/ is implemented by DietPi and allows to run scripts every chosen amount of minutes.
# Run "dietpi-cron" to enable and configure this feature.
```

**Comment by Sopor** [comment]
It seems that every time i tried to edit that cron job it have created a task that now is stuck

```

ID | Owner | CPU | Command
-- | -- | -- | --
26944 | root | 67.8 % | /usr/share/webmin/cron/edit_cron.cgi
27351 | root | 67.5 % | /usr/share/webmin/cron/edit_cron.cgi
28041 | root | 60.8 % | /usr/share/webmin/cron/edit_cron.cgi
29254 | root | 56.6 % | /usr/share/webmin/cron/edit_cron.cgi
29746 | root | 41.1 % | /usr/share/webmin/cron/edit_cron.cgi
29867 | root | 41.0 % | /usr/share/webmin/cron/edit_cron.cgi
30096 | root | 37.7 % | /usr/share/webmin/cron/edit_cron.cgi
30405 | root | 37.5 % | /usr/share/webmin/cron/edit_cron.cgi
31081 | root | 35.5 % | /usr/share/webmin/cron/edit_cron.cgi
31241 | root | 35.3 % | /usr/share/webmin/cron/edit_cron.cgi
31645 | root | 34.4 % | /usr/share/webmin/cron/edit_cron.cgi
```
So this is something you need to do something about or else it can create a lot of problems.

**Comment by rostovtsev** [comment]
I am afraid, that the theme has absolutely nothing to do with all that you're reporting.

For now, you can just kill those processes.

**Comment by Sopor** [comment]
The Gray theme will open the job, but not Authentic. The authentic theme will create these high CPU usage tasks because they won't open. This must have something to do with your theme.

**Comment by rostovtsev** [comment]
Okay, can you please switch to Gray Theme, visit this cron job with opened console and post me the output, from Network tab for this page?

**Comment by jcameron** [comment]
Yes, looks like a bug in the code that computes the next run time of the cron job.

What is the schedule of that `readme.txt` cron job?

**Comment by Sopor** [comment]
@jcameron 
`#*/0 * * * * root cd / && run-parts --report /etc/cron.minutely`

When i manage to open it, it doesn't show any time as you can see [here](https://github.com/authentic-theme/authentic-theme/issues/1339#issuecomment-490467146)

**Comment by jcameron** [comment]
OK, I see the bug that causes this. We will fix it in the next release, but as as work-around change the `*/0` to `*/1` in that job's time spec.

**Comment by Sopor** [comment]
> OK, I see the bug that causes this. We will fix it in the next release, but as as work-around change the `*/0` to `*/1` in that job's time spec.

@jcameron I did the change you described above but it will still not open the cron job. The only thing that happening was very high CPU usage on edit_cron.cgi. The same thing as i described before.

Is there an easy way to test your fix https://github.com/webmin/webmin/commit/90b759e644bba8b5ae8a253601d528e60130927e so i know it will work any not give me tasks that use a lot of CPU usage?

**Comment by rostovtsev** [comment]
Just replace the file contents from this file:

```
https://github.com/webmin/webmin/blob/master/cron/cron-lib.pl
```

**Comment by Sopor** [comment]
No, still the same when trying to open the cron job for `readme.txt` :(

**Comment by jcameron** [comment]
There's another fix needed : https://github.com/webmin/webmin/commit/c3275fd05a49eebe316897abbfb1c2c1d7340731

**Comment by Sopor** [comment]
I still can't open it. If i press on it, it will create a edit_cron.cgi with very high CPU usage.

**Comment by rostovtsev** [comment]
Sopor, 

Can you `strace` the process and send it to Jamie? Just attach it here as zip file.

It would be easier to understand what's happening.

**Comment by Sopor** [comment]
Yes, because Jamie only fixed the `Show next time each job will run?` and not if i click on it to view it.

@jcameron here is a strace log of what happens when i click on `/etc/cron.minutely/readme.txt`. This isn't fixed and it will create a new `edit_cron.cgi` task every time i click on the `/etc/cron.minutely/readme.txt`. It will also use a lot of CPU, so I'm forced to kill the tasks.

[strace-webmin.zip](https://github.com/authentic-theme/authentic-theme/files/3219650/strace-webmin.zip)

**Comment by jcameron** [comment]
Did you also apply this patch : https://github.com/webmin/webmin/commit/c3275fd05a49eebe316897abbfb1c2c1d7340731

**Comment by Sopor** [comment]
I have included a piece of my [edit_cron.cgi](https://github.com/authentic-theme/authentic-theme/issues/1339#issuecomment-495797911)

**Comment by jcameron** [comment]
Does this still happen if you change the cron's time spec to */1 instead of */0 ?

**Comment by Sopor** [comment]
As default it is `*/0` but i can try to change it again to `*/1`. It shouldn't required any changes, though.

If i change it to `*/1` it seems to work,
![image](https://user-images.githubusercontent.com/5789283/58494687-f6021880-8175-11e9-90d8-9371f927581b.png)

but if i don't made any changes it will still make edit_cron.cgi use a lot of CPU :(

**Comment by MichaIng** [comment]
@Sopor @jcameron 
Note that the command that cron uses (`run-parts`) to executed the included scripts does not executes files with a file ending (generally no files with a dot inside the name) and of course no files that are not executable. Both of this excludes e.g. the `.placeholder` files and also the `readme.txt` that causes the issue here.

It would be reasonable the use the same rules for Webmin/authentic-theme as well before touching files.
Even better/safer: `run-parts --test /cron.*/` to get the file list that would be executed by cron.

**Comment by jcameron** [comment]
Thanks, I'll update webmin in the next release to match what run-parts does.
