### ISSUE TITLE
Recent logins is not showing default sort order

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1340]
The default sort order is not shown in the Recent logins as you can see in the upper picture. It should be as in the lower picture, so i know what sort order it is using.

![image](https://user-images.githubusercontent.com/5789283/57484394-3540f600-72a9-11e9-941b-7746f649bac6.png)

**Comment by rostovtsev** [comment]
It's standard behaviour - default sorting provided by the server.

There is nothing to fix her.

**Comment by Sopor** [comment]
If i press on a column it should in that case be possible to change it back to all sort order arrows to be none selected but that is impossible. How should i know the sort order if i don't have any indicators?

**Comment by Sopor** [comment]
If i open Windows File Explorer i will see the default sort order

![image](https://user-images.githubusercontent.com/5789283/57490723-7392e100-72ba-11e9-8b60-6b7c9d402fe3.png)

**Comment by rostovtsev** [comment]
There are two types of sorting. Server side and client side. Those aren't interacting in any way. There are different types of server sorting, in different modules.

Web application is not the same as desktop.

Making it work across the theme theoretically possible but certainly doesn't worth an effort.

Major rework, possibly for Webmin 2.0, could have this feature, but theme needs to be aware of the default sorting mode for each module anyway.
