### ISSUE TITLE
Authentic theme not in complex schedule

### ISSUE THREAD

**Issue by sz00gun** [authentic-theme/authentic-theme#1342]
This excellent theme for Webmin is almost everywhere, apart from in **Complex schedule** section, as far I noticed. Any chance to format this window with the theme css? _[low priority job]_ I know this is not a big deal, however... LET'S MAKE THE BEST WEB PANEL reporting all bugs and issues !!!

![complex-cron](https://user-images.githubusercontent.com/7549566/57585007-01004c00-74da-11e9-8955-754e0679a3c5.jpg)

**Comment by rostovtsev** [comment]
Let's! 🙂

I will take a look. Indeed, there are few other places where it's not styled yet, as far as I remember in Postfix.

**Comment by rostovtsev** [comment]
Okay, added it.

Check it out:

![image](https://user-images.githubusercontent.com/4426533/58696458-465cbe80-83a0-11e9-905c-a910b3283237.png)

![image](https://user-images.githubusercontent.com/4426533/58696441-3ba22980-83a0-11e9-9156-4cc6d044ed90.png)
