### ISSUE TITLE
Download function is not working properly while ...

### ISSUE THREAD

**Issue by sz00gun** [authentic-theme/authentic-theme#1343]
**Download** function not working properly using Right Mouse Button, while trying downloading folders with emails. Probably because emails have different ownership, with normal files eg. public_html all is working fine...

Let's try explain step by step, where is a problem.

Make a main virtual server: aaa.com
and a new domain as **sub-server**: bbb.com

Let's make some mails accounts eg.: a@bbb.com, b@bbb.com, c@bbb.com and these mails contain some emails inside folders.

Eg. a folder /home/aaa/domains have around 150MB, but after clicking Download under RMB the folder have less than 2MB and the archive don't contain emails. I thought, because a different ownership. However when I move a folder from /home/aaa/domains to eg. /root/domains then downloading is working fine... 

![1](https://user-images.githubusercontent.com/7549566/57585598-3315ac00-74e2-11e9-90a3-f0d3525c2605.jpg)

**Comment by rostovtsev** [comment]
If you disable automatic switching to user mode in File Manager configuration, and keep user as `root`, will download work?

**Comment by rostovtsev** [comment]
I suspect that it would work.

Report back, please.

Now, I don't think that we even need to jail downloads in any additional way than it's already done by the File Manager core.

**Comment by sz00gun** [comment]
It is working as a charm now.
Thanks

**Comment by rostovtsev** [comment]
It's fixed on the latest commit. Thanks for reporting.
