### ISSUE TITLE
problem with user switch 

### ISSUE THREAD

**Issue by bialy7** [authentic-theme/authentic-theme#1344]
After click on button "login to Usermin" my browser is redirected to Webmin Dashboard

I'm using:
Webmin 1.900
Usermin: 1.751
Authentic theme: 19.33

**Comment by rostovtsev** [comment]
Hi,

I think you're logging in to Webmin? Usermin by default uses 20000 port.

For more info provide a screenshot please.

**Comment by bialy7** [comment]
<img width="1125" alt="Zrzut ekranu 2019-05-13 o 15 30 32" src="https://user-images.githubusercontent.com/877306/57625615-834d4680-7594-11e9-94e1-0bf105423e92.png">

Button "Login to Usermin" opening new tab with Dashboard.

**Comment by rostovtsev** [comment]
I see what you mean now.

I will check a bit later.

**Comment by rostovtsev** [comment]
It's fixed on the latest commit. Please give it a try by installing latest development version of the theme.
