### ISSUE TITLE
File manager: sort order

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1347]
When i have the `Default sorting type` set to `None` (blank dropdown) it will sort folders first and then files but folders with the first letter in upper case will be sorted above the other folders.
I wanted them to ignore the upper case so i changed the `Default sorting type` to `Name`.
This will make the folders be sorted in alphabetical order and it seems to ignore the case too, but only when there are only folders to view. If it contains both folders and files it will mix folders and files. This is not what i want. I want to have folders first and then files sorted in case insensitive alphabetical order.

Is this something that is possible to do?

**Comment by rostovtsev** [comment]
It should be possible by extending default sorting function of dataTables. I have no idea whether it can be done for sure. I need to check.

**Comment by rostovtsev** [comment]
There was much easier way of doing it.

Thanks for the suggestion.
