### ISSUE TITLE
File manager: changing folder should start at the top

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1348]
When i have many folders it will make me have several pages in my web browser. If i scroll to page two (as an example) and open a folder that also include a lot of folders and files, it will not open at the top. Instead it will open at the same scrollbar location it was when i open the folder. When i enter a folder it should open at the top and not where the previous scrollbar was.

**Comment by rostovtsev** [comment]
It's possible, however it's better to set pagination number that would fit your screen's height. You can use arrow keys (left and right) to switch between paginated pages.

**Comment by Sopor** [comment]
25 rows per page? It will take forever to view /etc/webmin with 6 pages :(

**Comment by rostovtsev** [comment]
You can start typing while focused on file manager and it will automatically filter needed results for you.

**Comment by rostovtsev** [comment]
It's fixed along with other page calculations issues (making bottom scroll appearing and making vertical scroll tiny).

Please give it a try.
