### ISSUE TITLE
Email: Time/date format change when open emails

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1350]
If i list all emails i have the date format yyyy/mm/dd but when i open it, it will change to dd/mm/yyyy. I will also add to this that the format yyyy/mm/dd is not correct either. It should be yyyy-mm-dd.

![image](https://user-images.githubusercontent.com/5789283/57944917-bc5d2200-78d8-11e9-917b-14206a0d7609.png)

Not a big deal but it will make easy reading become not so easy anymore because i have to think if this is dd/mm/yyyy or mm/dd/yyyy format.

**Comment by rostovtsev** [comment]
@jcameron Jamie, does standard read mail page respects user datetime options?

**Comment by jcameron** [comment]
When you view an email, the date is shown in the format from the message itself.

**Comment by Sopor** [comment]
@rostovtsev This format isn't correct either 2019/05/19. It should be 2019-05-19.

![image](https://user-images.githubusercontent.com/5789283/57976727-527f6e00-79e7-11e9-89fa-23d3f076628d.png)

**Comment by rostovtsev** [comment]
I will consider displaying date in correspondent with locale settings, when implementing new read/compose mail.
