### ISSUE TITLE
Bootup and Shutdown - Edit Action

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1351]
If i edit a file in the File manager i can select text and use the right mouse button to bring up the context menu, but if i want to edit a service i can select text but i can't get the context menu to open. So i'm forced to use the keyboard if i want to copy, paste or cut text.

Is this some kind of limitation in the Edit Action window?

**Comment by rostovtsev** [comment]
Fixed. Thanks.
