### ISSUE TITLE
Dashboard: takes 22 seconds to open

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1352]
When i open the Dashboard on my old `Cubieboard 1` it will take about 6-7 seconds before it is loaded. I understand that this old computer will take some time to open.

I also have an RPi 3 B+ and to open the Dashboard it will take more than 20 seconds. If i go from the Dashboard to the File manager it will take less than 2 seconds (the CB1 will here take 5 seconds). I run the RPi3 on an external SSD, so i can see that everything else is much faster than running it on a micro SD card.

I need to find out why the DB is taking so long time to open. Is it possible to debug it to see what is going on or do you have any other suggestions i can do to find the reason for this slow Dashboard?

One thing i know for sure, it doesn't matter if i change theme. It will still take more than 20 seconds to load it :(

**Comment by rostovtsev** [comment]
Do you have Virtualmin or Cloudmin installed?

**Comment by Sopor** [comment]
No, only Webmin installed on all four.

**Comment by rostovtsev** [comment]
This is way too long. Mine takes only 800ms. I think you don't have caching enabled?

What about, _Webmin/Background Status Collection_ and its option _Collect system status in background?_ I assume it's set to Never in your case? If so, set it to 2-5 minutes.

![image](https://user-images.githubusercontent.com/4426533/57979318-dc016100-7a24-11e9-9f2c-0949dbfd76ba.png)

**Comment by Sopor** [comment]
It was set to 5 minutes. I haven't changed anything. I run almost default on everything.

Yes, it is very slow :(

**Comment by rostovtsev** [comment]
If you click on the refresh button:

![image](https://user-images.githubusercontent.com/4426533/57980358-681a8500-7a33-11e9-8c03-18082a2c7146.png)


..how many seconds does it take to update it? Is it the same time as just opening the Dashboard? You can see it in Network tab, what's exactly happening and for exactly how long.

**Comment by rostovtsev** [comment]
What do you have set in _Webmin/ Webmin Scheduled Functions_? Provide the screenshot, please.

**Comment by Sopor** [comment]
When i pressed that refresh button it took 59 seconds before it was finished.

![image](https://user-images.githubusercontent.com/5789283/57980706-e88ab700-7a2e-11e9-9819-a077d2ca4633.png)

**Comment by Sopor** [comment]
> What do you have set in _Webmin/ Webmin Scheduled Functions_? Provide the screenshot, please.

![image](https://user-images.githubusercontent.com/5789283/57980715-11ab4780-7a2f-11e9-9616-369ea534e465.png)

**Comment by rostovtsev** [comment]
You need to `strace -t -p WEBMIN_PID` while loading Dashboard. You should, on the second go, add `-f` key to the command.

Send me the output of both commands, better using email.

**Comment by Sopor** [comment]
Thanks for your help @rostovtsev!
