### ISSUE TITLE
Where is 19.34-beta6?

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1353]
I noticed there was a new AT out, 19.34-beta6. I started to update three of four computers and when i got to the fourth it was a totally different version of AT (as you can see in the picture below).

![image](https://user-images.githubusercontent.com/5789283/57978011-74d3b480-7a04-11e9-8693-6bc86682cd97.png)

So where is 19.34-beta6?

**Comment by rostovtsev** [comment]
It's cached. Probably cache expiry length is to great. You can force clear the cache from the same page. 

You also need to make sure that checking for updates is enabled.

**Comment by Sopor** [comment]
After clearing the cache it will not even show the dev version :(

![image](https://user-images.githubusercontent.com/5789283/57978815-75744700-7a14-11e9-8bf7-c5902f1284f5.png)


> You also need to make sure that checking for updates is enabled.

What do you mean? I don't have `Check for Authentic Theme updates` enable but it is the same settings i have on all four Webmins and the other three are showing beta6.

**Comment by rostovtsev** [comment]
:smile: In this case you need to set/add:

```conf
beta_updates=1
```

.. to `/etc/webmin/authentic-theme/config` file. If file doesn't exist, create one.

**Comment by Sopor** [comment]
Why is that not there from the beginning?

**Comment by rostovtsev** [comment]
Does adding it helps?

**Comment by Sopor** [comment]
If beta is disable why will it try to check for it?

![image](https://user-images.githubusercontent.com/5789283/57979843-2a156500-7a23-11e9-8bfc-7a8faae731b5.png)

**Comment by Sopor** [comment]
I don't get it... Why do i need to add it when the other work without it? It doesn't sounds logical ..

**Comment by rostovtsev** [comment]
It checks for stable and beta, and just lets the user know. 

However, the prompt for upgrading will not show up on the Dashboard, with out explicit `beta_updates=1` option set in config.

You actually shouldn't add it, my bad. 
Sopor, you need to try to deduct to the core of the problem yourself. I have no clue why it's not working for you on that particular server. Try to figure this out.

It's not the theme bug, I believe.

**Comment by Sopor** [comment]
It will contact github and when i ping github i get a very high ping time so i believe this is a time out issue.
Can i increase the timeout time?

It was the same thing when i was updating the OS. I was forced to set it to 20 seconds. What do you have default in AT?

**Comment by Sopor** [comment]
```
$ ping raw.githubusercontent.com
PING github.map.fastly.net (151.101.84.133) 56(84) bytes of data.
64 bytes from 151.101.84.133 (151.101.84.133): icmp_seq=1 ttl=54 time=13.0 ms
64 bytes from 151.101.84.133 (151.101.84.133): icmp_seq=2 ttl=54 time=13.0 ms
64 bytes from 151.101.84.133 (151.101.84.133): icmp_seq=3 ttl=54 time=13.1 ms
64 bytes from 151.101.84.133 (151.101.84.133): icmp_seq=4 ttl=54 time=13.1 ms
64 bytes from 151.101.84.133 (151.101.84.133): icmp_seq=5 ttl=54 time=13.6 ms
64 bytes from 151.101.84.133 (151.101.84.133): icmp_seq=6 ttl=54 time=13.0 ms
64 bytes from 151.101.84.133 (151.101.84.133): icmp_seq=7 ttl=54 time=13.0 ms
64 bytes from 151.101.84.133 (151.101.84.133): icmp_seq=8 ttl=54 time=13.0 ms
64 bytes from 151.101.84.133 (151.101.84.133): icmp_seq=9 ttl=54 time=13.5 ms

--- github.map.fastly.net ping statistics ---
9 packets transmitted, 9 received, 0% packet loss, time 12032ms
rtt min/avg/max/mdev = 13.036/13.195/13.686/0.237 ms
```

**Comment by Sopor** [comment]
Yes, you need to increase the timeout. I don't know why it is so slow. One thing i see is that i will be connected to different IP addresses. Seems that some servers are slower than others

![image](https://user-images.githubusercontent.com/5789283/57980138-4915f600-7a27-11e9-9b22-dbd8249c463d.png)

**Comment by rostovtsev** [comment]
Your ping is just _fine_. GitHub might block access to its API, if you make to many requests, for example if you disable caching in the theme configuration and visit configuration page multiple times.

What is the output of:

```
curl https://api.github.com/repos/authentic-theme/authentic-theme/contents/theme.info
```

**Comment by Sopor** [comment]
```
$ curl https://api.github.com/repos/authentic-theme/authentic-theme/contents/theme.info
{
  "name": "theme.info",
  "path": "theme.info",
  "sha": "48144764ef3970fde746aec86c1b1fe2213141be",
  "size": 231,
  "url": "https://api.github.com/repos/authentic-theme/authentic-theme/contents/theme.info?ref=master",
  "html_url": "https://github.com/authentic-theme/authentic-theme/blob/master/theme.info",
  "git_url": "https://api.github.com/repos/authentic-theme/authentic-theme/git/blobs/48144764ef3970fde746aec86c1b1fe2213141be",
  "download_url": "https://raw.githubusercontent.com/authentic-theme/authentic-theme/master/theme.info",
  "type": "file",
  "content": "ZGVzYz1BdXRoZW50aWMgVGhlbWUKbG9uZ2Rlc2M9V2VibWluL1VzZXJtaW4v\nVmlydHVhbG1pbi9DbG91ZG1pbiB0aGVtZSBiYXNlZCBvbiBCb290c3RyYXAg\nYW5kIEZvbnQgQXdlc29tZSAoaHR0cHM6Ly9naXRodWIuY29tL2F1dGhlbnRp\nYy10aGVtZS9hdXRoZW50aWMtdGhlbWUpCnZlcnNpb249MTkuMzQtYmV0YTcK\nbXZlcnNpb249MDEKZGVwZW5kcz0xLjkwMCAxLjc1MAp3ZWJtaW49MQp1c2Vy\nbWluPTEK\n",
  "encoding": "base64",
  "_links": {
    "self": "https://api.github.com/repos/authentic-theme/authentic-theme/contents/theme.info?ref=master",
    "git": "https://api.github.com/repos/authentic-theme/authentic-theme/git/blobs/48144764ef3970fde746aec86c1b1fe2213141be",
    "html": "https://github.com/authentic-theme/authentic-theme/blob/master/theme.info"
  }
}
```

**Comment by Sopor** [comment]
When i updated the OS i needed 20 seconds to connect to github or else i got a timeout. When i run your update it show this message after a few seconds, so it seems to try once and then it will give up?

**Comment by rostovtsev** [comment]
Okay, I have increased timeout from 5 to 30 seconds on the prev commit.

**Comment by Sopor** [comment]
I manuell changed the timeout to 30 as you did and guess what :)

![image](https://user-images.githubusercontent.com/5789283/57980448-1cb0a880-7a2c-11e9-9ff1-f48821981952.png)

**Comment by rostovtsev** [comment]
Okay, good to know.
