### ISSUE TITLE
When I saw it on a smartphone, the width is strange

### ISSUE THREAD

**Issue by kosugikun** [authentic-theme/authentic-theme#1356]
When I saw the system information on my smartphone, the width is strange.
![image](https://user-images.githubusercontent.com/33971692/58026893-7d3a0580-7b52-11e9-8060-3b2e1018061c.jpeg)

**Comment by rostovtsev** [comment]
What is the theme version, where you're seeing this?

**Comment by rostovtsev** [comment]
I can not reproduce it in Linux on neither Firefox or Chrome in latest 19.34-beta8.

**Comment by kosugikun** [comment]
Open System Information on your smartphone and open Disk Usage.

**Comment by rostovtsev** [comment]
Fixed. Thanks! :)
