### ISSUE TITLE
File Manager Suggestion

### ISSUE THREAD

**Issue by leijonathan** [authentic-theme/authentic-theme#1358]
Hello, 

Thanks for developing the Authentic Theme. It is easy to use and good. 

I have a few website hosting customers. Would it be possible to be able to disable the encrypt feature in the file manager? Is there a setting that I can change? I would like the file manager to be as simple as possible. 

![Screen Shot 2019-05-20 at 3 16 21 PM](https://user-images.githubusercontent.com/50268983/58046372-15b09580-7b13-11e9-87d9-79b92a3279d8.png)

**Comment by rostovtsev** [comment]
Hi,

Actually, there is no such option and I believe there should be no such option at all.

Although, you can easily disable it (not display it) by editing CSS extension and adding the following code to it:

```CSS
.file-manager .context-o__f_m-dependent-encrypt {
	display: none;
}
```
