### ISSUE TITLE
File manager: bookmarking a search result will not work

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1360]
If i for example search for `edit_cron.cgi` and i get a match for it and i now open the context menu to save this as a bookmark this doesn't seems to work. It will instead save the path to where i was before i started to search, in my case the root.

![image](https://user-images.githubusercontent.com/5789283/58359325-3ebe8680-7e83-11e9-9051-5be729d800e1.png)

If i instead navigate to `/usr/share/webmin/cron/edit_cron.cgi` and open the context menu on that file it will bookmark the folder `/usr/share/webmin/cron` and this is what it should do from the search result too.

**Comment by rostovtsev** [comment]
Okay, no problem. Added it.
