### ISSUE TITLE
File manager: Not a directory

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1361]
If i for example search for `edit_cron.cgi` and i get a match for it and i now click on the file i assumed it should open a new tab and jumped to the file but instead i get this error message.

![image](https://user-images.githubusercontent.com/5789283/58359658-ceb10000-7e84-11e9-84f8-4ac670bb42d2.png)

Folders seems to work but it won't jump to the folder. I have to manually scroll to the folder. This is of course better than the above issue, so even if it is a file i click on it should take me to the folder this file is located in.

**Comment by rostovtsev** [comment]
Actually it shouldn't follow the link in case of a file, as it's not standard behavior.

You would need to use context menu.

Thanks for pointing out.

It's fixed.
