### ISSUE TITLE
Searching will show - Changes you have made...

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1362]
If i search for something using the left menu

![image](https://user-images.githubusercontent.com/5789283/58572382-daf9dc00-823b-11e9-8802-b651abce6cc3.png)

and i press the theme configuration this dialog will popup:

![image](https://user-images.githubusercontent.com/5789283/58572200-86eef780-823b-11e9-8e41-8b05e040eea3.png)

When i then press continue this dialog will popup:

![image](https://user-images.githubusercontent.com/5789283/58572270-a9811080-823b-11e9-8f63-db9d7ab1c937.png)

This can't be right?

**Comment by rostovtsev** [comment]
It is right only in case you have changed anything in theme configuration but never saved it.

**Comment by Sopor** [comment]
Of course i don't change any settings. I told you above what i did.

**Comment by rostovtsev** [comment]
That wouldn't be possible. You changed settings. Try to reproduce it again. If the save button is yellow then the options were changed.

**Comment by Sopor** [comment]
![authentic_theme-search](https://user-images.githubusercontent.com/5789283/58590775-283e7380-8265-11e9-8225-898e936a5d0d.gif)

**Comment by Sopor** [comment]
I have...

Here is a [video](https://gofile.io/?c=xkUSnx.)

**Comment by rostovtsev** [comment]
Indeed. Thanks for reporting. Fixed.

**Comment by Sopor** [comment]
It will still show this dialog

![image](https://user-images.githubusercontent.com/5789283/58634781-777bb700-82ec-11e9-8835-c29a32d098e9.png)

I haven't made any changes?

**Comment by rostovtsev** [comment]
Because the page is searching/progressing.

**Comment by Sopor** [comment]
Very hard for us deadly to understand :)
