### ISSUE TITLE
problem french accent

### ISSUE THREAD

**Issue by mbuffet** [authentic-theme/authentic-theme#1363]
Accented characters no longer display correctly in french. 

![2019-06-02_10h12_43](https://user-images.githubusercontent.com/1812469/58762598-5e0e8100-851f-11e9-9fea-ee806be99a8e.png)

(It worked well until a few weeks ago)

**Comment by rostovtsev** [comment]
Hi,

Check it out:
https://sourceforge.net/p/webadmin/bugs/5270/
