### ISSUE TITLE
Per Directory Settings Table Display Issue

### ISSUE THREAD

**Issue by chrisCAD** [authentic-theme/authentic-theme#1365]
**Table options set to Hide Table Icons (No) Small Table Icons (No)**

When viewing a Virtual Server in the apache module, with per directory options - the folders are displayed as tiles with folder icon, however you can't see which directory is which as the path gets truncated so all directorys seem the same, tooltips don;t work in safari on the buttons so the only way to find a directory is to go into each one. On our application server we have many directories and this is really frustrating - is the any way to either wrap the path or show path in tooltips?

**Comment by rostovtsev** [comment]
Hi, Chris.

Is this how you see it?

![image](https://user-images.githubusercontent.com/4426533/58988059-816c5100-87e9-11e9-9942-b78cad0e629c.png)

**Comment by chrisCAD** [comment]
Hi Ilia,

No it’s the one after when you click the globe icon on the screen you sent.

[cid:image001.png@01D51C48.DA64A670]

The per-directory options, you can only see /srv/www/htt on buttons so its difficult to find folders, they do seem to wrap if they are really long but you still miss some of the path.

Hope this help, let me know if you need anymore info

Cheers
Chris

**Comment by rostovtsev** [comment]
I see now.

I surely needs a tooltip.

**Comment by chrisCAD** [comment]
Great, I really like this theme and that’s the only issue I’ve seen.

Thanks for the response. Keep up the good work

**Comment by rostovtsev** [comment]
Latest commit addresses your issue.

Please install latest dev version of the theme (from theme configuration) to give it a try.

Thanks for reporting.

**Comment by rostovtsev** [comment]
Added another small, related patch. Update over again if you just did.

**Comment by chrisCAD** [comment]
Cheers, Ill try it now

**Comment by chrisCAD** [comment]
Updated, works much better thank you

**Comment by rostovtsev** [comment]
You're welcome.
