### ISSUE TITLE
PAM authentication login screen doesn't show proper question

### ISSUE THREAD

**Issue by okinobk** [authentic-theme/authentic-theme#1367]
I'm using PAM auth with MFA (Username + OTP + Password). This PAM module ask 3 question:
- Username
- Passcode
- Password

Authentic theme do not read questions properly and ask:
- Username
- Password
- Password

This is confusing for users, because they are trying to answer the second question by their password, but it would be passcode instead. So user block himself after a few tries, because system asks wrong.

Old default Webmin theme or SSH session asks proper questions.

**Comment by rostovtsev** [comment]
So it's only the label that is wrong. Fields work correctly, right?

**Comment by rostovtsev** [comment]
Hi,

Could you please install latest dev version of the theme from theme configuration to give it a try?

If it doesn't work correctly for you, can you post a screenshot, so I'd be sure we're talking about the same thing.

**Comment by rostovtsev** [comment]
@okinobk Can you please report back. I am curious if it works alright for you?

**Comment by okinobk** [comment]
Hi,
I applied commit https://github.com/authentic-theme/authentic-theme/commit/9d41e0202339a99789c7b473fb56e739a1f5f716, but without any success, problem isn't solved. 

My auth process has 3 stages, username, passcode and password. I attached screenshots of auth process with old Gray Framed Theme and new Authentic Theme to compare.

![webmin_oldlogin_1](https://user-images.githubusercontent.com/9408271/59181647-38f5c000-8b68-11e9-9b6d-1b2524ffa762.png)
![webmin_oldlogin_2](https://user-images.githubusercontent.com/9408271/59181648-398e5680-8b68-11e9-8a31-f8b13f89f733.png)
![webmin_oldlogin_3](https://user-images.githubusercontent.com/9408271/59181641-385d2980-8b68-11e9-90f4-b35295cbc4bb.png)
![webmin_newlogin_1](https://user-images.githubusercontent.com/9408271/59181643-38f5c000-8b68-11e9-9326-aa69b373bf38.png)
![webmin_newlogin_2](https://user-images.githubusercontent.com/9408271/59181645-38f5c000-8b68-11e9-86dd-b7b87a2e7f2c.png)
![webmin_newlogin_3](https://user-images.githubusercontent.com/9408271/59181646-38f5c000-8b68-11e9-843f-5ea90c4b78c5.png)

**Comment by rostovtsev** [comment]
Oh, okay. I expected that.

Aside from wrong labels, login itself works correctly?

**Comment by okinobk** [comment]
Yes, login works.

**Comment by rostovtsev** [comment]
Okay, I have made another patch. Please install it.

In case it still doesn't work, could you please add to line 26 of `authentic-theme/pam_login.cgi` the following and post output of it here (actual credentials can be replaced with something else, I need to know field names).

```
head();
print "@{[%in]}";
```

**Comment by okinobk** [comment]
Sorry, it doesn't fix the problem. Here is to output:
question Passcode: password 1 cid c5586241181863fbfb7210eedb4fe2d7Auth-type: auth-required=1 Set-Cookie: redirect=1; path=/ Set-Cookie: testing=1; path=/; secure X-Frame-Options: SAMEORIGIN Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval'; frame-src 'self'; child-src 'self' Content-type: text/html; Charset=UTF-8

**Comment by rostovtsev** [comment]
Do you get this output on stage 2 and stage 3?

**Comment by okinobk** [comment]
That was stage 2. Stage 3 is:
question Password: password 1 cid bcb1be839ae9b6652f7df5915db99a3aAuth-type: auth-required=1 Set-Cookie: redirect=1; path=/ Set-Cookie: testing=1; path=/; secure X-Frame-Options: SAMEORIGIN Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval'; frame-src 'self'; child-src 'self' Content-type: text/html; Charset=UTF-8

**Comment by rostovtsev** [comment]
I am confused how Step 2 in your output is not _Passcode_, while in screenshot above it is - the question also should be _Passcode_. 

Are you sure about output?

**Comment by rostovtsev** [comment]
Okay, give it another try please. It should really work right now!

**Comment by okinobk** [comment]
It's working, great! As you can see in screenshot, it's asking for Passphrase in step 2. Passprahe is not hidden, but I don't know if it's necessary.
![webmin_new_stage2](https://user-images.githubusercontent.com/9408271/59199923-6017b600-8b97-11e9-80df-99d96c424163.png)
![webmin_new_stage2-w_passcode](https://user-images.githubusercontent.com/9408271/59199924-6017b600-8b97-11e9-884d-c72344fdb089.png)

.

**Comment by rostovtsev** [comment]
Yes, it's not necessary. Is password hidden now?

**Comment by rostovtsev** [comment]
I mean not now, in step 3 it should be hidden. 

I am glad it's fixed. 🙂

**Comment by okinobk** [comment]
Yes, password is hidden. Thank you for quick fix :)
