### ISSUE TITLE
Can't upload by Chrome

### ISSUE THREAD

**Issue by 7starsone** [authentic-theme/authentic-theme#1369]
Hello,
upload into a directory works with Firefox but not by Chrome, latest version.

It does nothing, both through drag & drop or click to select a file..
after that, nothing happens and the Upload button is not clickable

**Comment by rostovtsev** [comment]
That is true and so odd. It worked and actually still works in Chrome 73 and below, but stopped working in Chrome 74+. I will check what's happening tomorrow morning.

**Comment by rostovtsev** [comment]
It seems to work, though upload button is inactive and number of files is not updated.

**Comment by rostovtsev** [comment]
Okay, this is a fancy bug and it seems more like a draw-back of current Chrome 76 to me.

I think it's due the change that brings native support for super new `Promise.allSettled` and `Promise.any`.

Anyway, it's fixed now.

Thanks for reporting!
