### ISSUE TITLE
Marking / Deleting Spam

### ISSUE THREAD

**Issue by tpnsolutions** [authentic-theme/authentic-theme#1371]
Hi,

When you mark/delete spam it loads the right frame into the overall window instead of inside the framework (no left panel).

**Comment by tpnsolutions** [comment]
![Screenshot from 2019-06-20 22-32-17](https://user-images.githubusercontent.com/4305218/59899935-641fb100-93ab-11e9-800d-90fa334a1269.png)

**Comment by rostovtsev** [comment]
Aren't you using new mail UI?

**Comment by rostovtsev** [comment]
Okay, it used to be submitted to new window. It was removed accidentally in the past. However, it's wrong done on the server side and I fixed it. It will be fine on the next Webmin/Usermin release.
