### ISSUE TITLE
Refresh Message Count (Left Panel)

### ISSUE THREAD

**Issue by tpnsolutions** [authentic-theme/authentic-theme#1372]
Hi,

It would "uber" nice if the left panel "message count" refreshed when you deleted, moved, etc messages like most webmail apps...

*** great job thus far dude, this thing keeps getting better :-) ***

**Comment by rostovtsev** [comment]
Okay, I was going to add this to theme 19.40 release, which is going to be the mail release having new compose and possibly new mail preview as well, but I have added to upcoming 19.35 release just now, which is out within next few days (before June 26).

Give it a try.
