### ISSUE TITLE
Update Theme CLI

### ISSUE THREAD

**Issue by tpnsolutions** [authentic-theme/authentic-theme#1373]
Hi,

Not sure this is possible, perhaps it is... But since I'm on a spree this evening, I would like...

The ability to upgrade "easily" to the latest version of the Authentic Theme via a CLI command. I do a lot of server updates using automated scripts, and would like to simplify updating the theme as well...

**Comment by rostovtsev** [comment]
Hi, Peter.

Yes it's possible. I have just updated `theme-update.sh` script that will now support `-force` switch from command line.

You can use it, starting from theme 19.35 version release as follows, to update to the latest development version:

```
./theme-update.sh -force
```

..and to update to the latest release:

```
./theme-update.sh -force -release
```
