### ISSUE TITLE
Automatic Theme Updates failing

### ISSUE THREAD

**Issue by haqa** [authentic-theme/authentic-theme#1374]
I've been having real difficulty (actually I've been completely unable) automatically updating Authentic for some months. (All my updates have been download the wbt file, install via browser)

I finally got a few moments to test why and found that running `./theme-update.sh -release:19.35` produces the following output:

```
Would you like to update Authentic Theme for Webmin? [y/N] y
Pulling in latest release of Authentic Theme 19.35 (https://github.com/authentic-theme/authentic-theme)...
Updating Authentic Theme, failed.
```

Is anyone else seeing this?

OS: CentOS 6.10
Webmin: 1.900
Virtualmin: 6.06
Git: 1.7.1-9

All packages are up to date.

**Comment by rostovtsev** [comment]
Hi,

The latest update script (checked in already) can accept `-y` param to do things silently.
