### ISSUE TITLE
File manager: update/revert file not always working

### ISSUE THREAD

**Issue by 7starsone** [authentic-theme/authentic-theme#1375]
Hello, where text/log files (example) are there minimized for a while...eg. you keep the window open, then come back to the browser window, change path and so on...
when you click on `Revert File` it just returns the usual message but really it doesn't update anything.

**Comment by rostovtsev** [comment]
Hi,

I have given it a try and confirm that _**it works**_ for me just fine - the file is getting updated content

Are you sure that you're testing it right?

**Comment by rostovtsev** [comment]
So, any updates here? It still doesn't work for you?

Any steady steps to reproduce it? Any video-screencasts that you could possibly provide?

**Comment by rostovtsev** [comment]
I have done more tests and I can always revert the file correctly, disregard of the current directory or even with File Manager being closed.

**Comment by rostovtsev** [comment]
Is this still an issue for you?

**Comment by 7starsone** [comment]
I got it for sure more than one time...I don't know what's the cause at the moment, anyway it seems related to network because I remember a red error message about it on dev console...if it happens again I will let you know

**Comment by rostovtsev** [comment]
Okay, I will close it for now.

**Comment by 7starsone** [comment]
ok, got it again....

[screenshot](https://i.imgur.com/Gi2Dn0Z.jpg)

and also, when it happens if you click to minimize a file window, it completely closes it (disappearing from browser window) instead of minimizing...

**Comment by 7starsone** [comment]
maybe an issue when PC waking up from sleep...

**Comment by rostovtsev** [comment]
Your errors doesn't seem to have anything to do neither with the theme nor with Webmin.

Try disabling extensions one by one to see which extension could cause it. It's [know](https://support.google.com/chrome/thread/2047906?hl=en) problem.

Although, it's normal to get _net::ERR_NETWORK_IO_SUSPENDED_ "error" upon wake up but I don't have any _Unchecked runtime.lastError_ errors on my MacOS and Chrome 75. The revert functionality continues to work after wake up normally.

It seems like one of the extensions issue to me.

What if you not just try to revert the file but do something else? Change folder in File Manager or open some other module? What happens?

**Comment by rostovtsev** [comment]
Okay, I have realised why this was happening. Thank you for reporting.

It's fixed now. :wink:
