### ISSUE TITLE
Virtualmin package updates button fails

### ISSUE THREAD

**Issue by jcameron** [authentic-theme/authentic-theme#1376]
When I click the button to update Virtualmin packages as shown in this screenshot :

![image](https://user-images.githubusercontent.com/102706/60423556-10ba2800-9c21-11e9-900d-9c9dc12d5b74.png)

it fails with the error that no packages were selected (because none are passed to update.cgi)

**Comment by rostovtsev** [comment]
While fixing this issue, and making more tests, I found out that `webprefix` is missing and clicking button returns 404 error:

![image](https://user-images.githubusercontent.com/4426533/60424347-c8870f80-9bf8-11e9-873b-27b54aa6ea80.png)

![image](https://user-images.githubusercontent.com/4426533/60424384-e0f72a00-9bf8-11e9-9b7b-40ba36a311a8.png)

**Comment by rostovtsev** [comment]
Jamie, fixed. The main source of problem is broken HTML.

https://github.com/virtualmin/virtualmin-gpl/commit/1e8db1ba15c56f23b7510882bab8fd6f85caf171

Please update theme to the latest Git version as well. There was also a fix for it.
