### ISSUE TITLE
Access log, wildcard not working as usual

### ISSUE THREAD

**Issue by 7starsone** [authentic-theme/authentic-theme#1379]
Hello,
eg, search for
GET *

it finds results

while
GET * word
it doesn't work anymore and found nothing

thanks

**Comment by rostovtsev** [comment]
Hi,

Unless it's single `*`, which means for all, it can be either `matchedString` or you would need to use regex for complex matches.

Simply enter needed string, without `*` and it will work.

**Comment by 7starsone** [comment]
No, sorry, it worked before...
eg. `GET * .php` OR `GET * php`
it found any GET /path/to/file.php

now it doesn't...

**Comment by rostovtsev** [comment]
Do you mean in File Manager?

**Comment by 7starsone** [comment]
No, `View Logfile` -> any of your access logs....

**Comment by rostovtsev** [comment]
Ah, okay. This is grep regexp.

For example, if you want to grep strings containing `GET` and `.php` simply put into the search field:


```REGEXP
GET*.php
```

May be [this](https://www.cyberciti.biz/faq/grep-regular-expressions) small tutorial would help. In case you still can't match it, provide me with the string example and tell me what you need to match, I could help.

**Note:**  It wouldn't work on FreeBSD supposedly. If you have Debian or RHEL or other linux-like distro, it will work. :wink:

**Comment by 7starsone** [comment]
well, I was wrong because if I put a space before `php`, it obviously can't find it... because the URL doesn't have spaces inside...

indeed, If I do `GET /.*php HTTP` it works as usual...
sorry for that, nevermind
