### ISSUE TITLE
Show Webmin update on the dashboard without a page update

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1380]
On the dashboard i can see when there are new updates but the updates for Webmin will not show up until i update the page.
![image](https://user-images.githubusercontent.com/5789283/60797653-f7106780-a16f-11e9-8c0d-dfbf7ad5d33d.png)

If i open the Package updates i will find the Webmin update here but it would be nice if it could indicate that there is a new Webmin update available. It could be very simple, show an * or something. It is not always you perform an update on the dashboard now when many updates are live.

**Comment by Sopor** [comment]
It will also create this side effect that the message about Webmin update will still be there after i update it from a terminal window
![image](https://user-images.githubusercontent.com/5789283/60807849-1070de00-a187-11e9-9981-3fb5dc52cfe0.png)

**Comment by rostovtsev** [comment]
Hi, 

Sorry for not answering for a while. I was working on adding caching to search results in File Manager.

Alerts seems to not have background updates yet. Do you think it's necessary? I guess I could make it work.

**Comment by rostovtsev** [comment]
Okay, it appears that this was already implemented for alerts, I just forgot to add update for the Dashboard.

It's fixed.

Thanks for reporting.

**Comment by Sopor** [comment]
So it is work much better now?

**Comment by rostovtsev** [comment]
It's now going to update (add/remove) those alert messages (in yellow square, about update/reboot and other) dynamically, without reloading the dashboard.
