### ISSUE TITLE
shows reboot required incorrectly

### ISSUE THREAD

**Issue by deckberg-quantumdigital** [authentic-theme/authentic-theme#1381]
I'm seeing on several servers the reboot required warning even after several reboots.

I don't see that the file exists:    /var/run/reboot-required

Operating system	CentOS Linux 6.10
Kernel and CPU	Linux 2.6.32-754.17.1.el6.x86_64 on x86_64
Authentic theme version	19.36

**Comment by rostovtsev** [comment]
Hi,

We're working on it. It's not the theme issue.

You can find discussion and later the fix for this issue in this [thread](https://sourceforge.net/p/webadmin/bugs/5280/).

**Comment by rostovtsev** [comment]
https://github.com/webmin/webmin/commit/cbe670e664b6b64f64642b58823460d298f18963
