### ISSUE TITLE
Theme issue? - CSF View iptables Log

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1384]
I'm running CSF 13.04 and when i press the `View iptables Log` i get this on the screen:

![image](https://user-images.githubusercontent.com/5789283/61979329-d4959f80-aff3-11e9-9c5e-17f5c235bf15.png)

Authentic theme version 19.38
Firefox 68.0.1

**Comment by rostovtsev** [comment]
Hm. Are there any errors in console?

I have it working.

If you open it in old theme, how does this page looks like? Does it have any content?

Did you try incognito mode? Did you try Chrome?

**Comment by rostovtsev** [comment]
Okay, 

I have the same in Firefox if the page is empty. 

It's a bug.

**Comment by rostovtsev** [comment]
Okay, I see the source of this issue.

**Comment by rostovtsev** [comment]
Okay, it's actually CSF issue.

I reported it. Thanks.

https://forum.configserver.com/viewtopic.php?f=4&t=11398

**Comment by rostovtsev** [comment]
I also made a patch to display _No Log Entries_ message properly. 

_**Note:**_ It will only work when CSF is fixed - version 13.05 and higher.
