### ISSUE TITLE
filter - CTRL+V work but not Paste from context menu

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1385]
If i use the filter and i paste in `cron` with CTRL+V to list all the cron tasks in running processes it will show only the cron task but if i'm instead use the mouse and from the context menu use `Paste` the filter won't work until i press enter or type another char.

Authentic theme version 19.38
Firefox 68.0.1 (64-bit)

**Comment by rostovtsev** [comment]
Hi, Sopor! :smiley: 

Look, it works for me in all browsers? I remember I was fixing it a while ago.

Can you provided the screenshot of where exactly do you use searching?

**Comment by Sopor** [comment]
I can't show you a screenshot because when i do it, it will trigger the filter. It is in the `Running Processes`. I did an animated gif instead :)

![Authentic_Theme-filter](https://user-images.githubusercontent.com/5789283/62061316-325dfd80-b227-11e9-9516-b29fabe78bfe.gif)

**Comment by rostovtsev** [comment]
I am confused, to be honest. Do you use any extensions? Can you try doing it with extensions disabled or in incognito tab? Can you try other browser?

What OS is that?

For me in Linux at Firefox/Chrome this is how it goes (works as expected):

![working_filter_paste](https://user-images.githubusercontent.com/4426533/62087072-0ebba700-b269-11e9-9aec-ece31e9d4792.gif)

**Comment by Sopor** [comment]
In Chrome it seems to work when i paste from the context menu, but if i instead delete the filter it won't work. The same thing happens in Firefox when i delete the filter...

Filter empty but it will only show the cron task
![image](https://user-images.githubusercontent.com/5789283/62126762-bf10c600-b2d0-11e9-9630-ab721b730c21.png)

Chrome doesn't have any Delete in the context menu so you need to use Cut instead.

Private window in Firefox, not working. Same thing with extensions disabled, not working.

I'm running Windows 10 in all they above tests.

If i instead run Ubuntu 18 it seems to work in Firefox, but it won't work if i delete the filter with the context menu. So at least they all have one thing in common :)

**Comment by rostovtsev** [comment]
Interesting. There is a cross button to delete and clear the filter. Those events (delete and cut) were not meant to work, although, I just fixed it. Why not, I just personally never used those and never found it convenient to be used.

Thanks for pointing out though.

----

Okay, It works for me in Linux, (GNOME and KDE), and in MacOS. If it doesn't work for you in Windows, there might be something wrong on your side. For example, keybinding apps could break things unintentionally.
