### ISSUE TITLE
What is the default sort order for Running processes?

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1386]
In the Running processes there is no default sort order. If i press on the columns it is impossible to get the sort order it was when i opened the running processes page.

You can see here that none of the arrows are selected
![image](https://user-images.githubusercontent.com/5789283/62129518-2e89b400-b2d7-11e9-9ba7-524363a26375.png)

Now i can't get the default sort order back (i can't unselect the arrows) without using the left menu `Running Processes`
![image](https://user-images.githubusercontent.com/5789283/62129608-6abd1480-b2d7-11e9-9613-b02ce1db854a.png)

**Comment by rostovtsev** [comment]
Yes, even though it was tricky to implement, as it's not native functionality of data tables, I managed to make it work. Needs more testing but I consider it to be done.

The 3 click on the table header will reset it.

_**Note:**_ Reset will not be triggered, if sorting for multiple columns is run by holding shift key.
