### ISSUE TITLE
Running processes - The sort order for Started is a mess

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1387]
When i sort by `Started` the sort order will be a mess because it will sort by 0-9 and `0`7 is before `2`018. Could this be fixed?

![image](https://user-images.githubusercontent.com/5789283/62130322-0f8c2180-b2d9-11e9-9573-57e2d8f25cc9.png)

I also wondering if it could show a more specific Started time? I believe this will fix the above sort order issue if it show full date-month-day?

**Comment by rostovtsev** [comment]
The sorting results are correct in terms of sorting but it sorts different kind of data, and I am not sure how it's related to the presentation (theme).

@jcameron Can we make _proc_module use `make_date` sub to generate time/date? By doing so, it will do sorting based on timestamp (delivered by `theme_make_date`), and thus will make it correct?

**Comment by Sopor** [comment]
So sort by `Started` is totally useless when it mixes time, dates and years like it was random. Is that really how it should work?

**Comment by rostovtsev** [comment]
This should be fixed on the server-side.

**Comment by jcameron** [comment]
I've checked in a fix to use proper date formatting for this field.

**Comment by rostovtsev** [comment]
Okay, cool.

I have made few tweaks as well and now sorting for _Started_ not only works perfectly but also displays time in from now format, making it very comfortable to read.

Example:

![image](https://user-images.githubusercontent.com/4426533/62205350-f1392b00-b397-11e9-9b83-3cc0f5ff66ed.png)
