### ISSUE TITLE
Additional PHP FPM service to Servers Status

### ISSUE THREAD

**Issue by sz00gun** [authentic-theme/authentic-theme#1389]
Can you add additional row PHP FPM on the front page in Servers Status section?

![Screenshot_20190818-140609(1)(1)](https://user-images.githubusercontent.com/7549566/63224851-fe408180-c1c1-11e9-9f88-68244c12ba21.png)

That would be a very helpful facility. I use FPM but I don't have a control to restart it at all.

**Comment by jcameron** [comment]
Excellent idea .. we'll look into this.

**Comment by jcameron** [comment]
The next release of Webmin will include FPM status buttons.

**Comment by rostovtsev** [comment]
> The next release of Webmin will include FPM status buttons.

Jamie, I haven't found it on Webmin repo yet. Have you committed it?

**Comment by rostovtsev** [comment]
Oh, it's in Virtualmin repo. Thanks.
