### ISSUE TITLE
Authentic theme 19.39-2 vs 19.39 ?

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1390]
There was a beta to install that was 19.39-2 but now i can read that i have installed 19.39 (no other updates are available) but on the dashboard it is still showing 19.39-2?

**Comment by rostovtsev** [comment]
There was no betas. I just released 19.39 straight.

**Comment by Sopor** [comment]
But what is 19.39-2?

**Comment by rostovtsev** [comment]
Compiler error. I will fix that.
