### ISSUE TITLE
Expecting form-data encoding, but got normal encoding in Certificate Manager 1.7

### ISSUE THREAD

**Issue by zuhairmahd** [authentic-theme/authentic-theme#1392]
After installing [Certificate Manager 1.7](http://www.webmin.com/download/modules/certmgr.wbm.gz) and when browsing to the PKI Certificate and Key Management screen under System, I get the following error message when clicking on "Import Certificate":

Error	
Expecting form-data encoding, but got normal encoding
 

I switched to the old Webmin theme and the import worked as expected.

I cleared the theme cache and checked for anything which could be obvious, including searching related issues and doing a bit of googling on the web, but could not find anything specific to this issue.

Thanks,
Zuhair
![2019-08-25](https://user-images.githubusercontent.com/42704235/63656328-5f3afd00-c760-11e9-8941-1bf9c08b8762.png)

**Comment by rostovtsev** [comment]
Zuhair, hi.

This module is almost 10 years old and has issues. It needs to be fixed to work with single-page applications.
