### ISSUE TITLE
Variable filemanager_global_info_total1,2,3,4 and UTF8

### ISSUE THREAD

**Issue by pwozniak89** [authentic-theme/authentic-theme#1393]
I'm trying to translate your Theme in French with UTF8 encoding, and I encounter a little bug in file manager
The variables filemanager_global_info_total1 ... 4 don't accept UTF8 characters and displays hieroglyphs...
![Capture du 2019-08-26 16-37-51](https://user-images.githubusercontent.com/41525331/63698948-23676c80-c820-11e9-84ca-97096287cd8c.png)
Another question... How can I send you translation file when all will have be translated?

**Comment by rostovtsev** [comment]
Pierre, hi. At first thank you for helping with translations! :sweat_smile: 

Okay, can you send me the file that you have already translated, so I could take a closer look in action? You can _zip_ it and attach it right here.

**Comment by pwozniak89** [comment]
Hi, sorry I forgot to say it before...
Here is my partially translated file
[fr.UTF-8.zip](https://github.com/authentic-theme/authentic-theme/files/3541627/fr.UTF-8.zip)

**Comment by rostovtsev** [comment]
Thank you for your time translating it. 

I fixed the initial issue in the commit above. You can install it by updating to the latest dev version of the theme from its configuration page.

Feel free to submit pull request whenever translations are ready.

I [added](https://github.com/authentic-theme/authentic-theme#translations) you as a contributor for French translations.

Merci beaucoup.
