### ISSUE TITLE
File manager: Three dots not working on folders?

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1394]
Those three dots in front of every folders and files they doesn't seems to work for folders, why? When i press on it, it will open the folder.

`Authentic theme version 19.40-alpha1-2` (now i have that 2 again after alpha1, but it will show as alpha1 in the theme configuration)

```
Check for Authentic Theme updates
(installed version 19.40-alpha1, latest stable 19.39)
```

**Comment by rostovtsev** [comment]
Looks like a bug. :/

**Comment by rostovtsev** [comment]
This bug has been introduced starting with 19.34.

Thanks, fixed now.

**Comment by Sopor** [comment]
I see now that it is still alpha1, so that seems to be correct with an extra number after alpha1
`19.40-alpha1-4` :)
