### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by SteffanCline** [authentic-theme/authentic-theme#1396]
When on the screen List Virtual Servers, I normally hit Select All then update to get them all at once. This now results in a 404 error yet when I do them one at a time it works.

**Comment by rostovtsev** [comment]
Hi, Steffan.

It should work actually. I remember encountered familiar errors after page refresh, when URL wasn't updated properly. It's on my radar. However, this is not a systematic error and happens quite rarely.

Try hitting _List Virtual Servers_ in the menu and then try again. It worked for me. Does it for you?

**Comment by rostovtsev** [comment]
It's fixed. Thank you for clarifying details.
