### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1397]
It seems that some of the latest updates make the CPU to work more than it should...
`7211 | root | 69.0 % | /usr/share/webmin/authentic-theme/stats.cgi`
and this seems to also be running
`7523 | root | 42.0 % | /usr/share/webmin/proc/index_cpu.cgi`

19.40-alpha2-2

**Comment by Sopor** [comment]
![image](https://user-images.githubusercontent.com/5789283/64456485-990ceb80-d0f0-11e9-986b-5eefcb827a49.png)

It should be 1-2% not 20+

**Comment by Sopor** [comment]
9176 | root | 44.0 % | /usr/share/webmin/proc/index_cpu.cgi
9175 | root | 25.0 % | /usr/share/webmin/authentic-theme/stats.cgi


9267 | root | 49.0 % | /usr/share/webmin/proc/index_cpu.cgi
9256 | root | 38.0 % | [/usr/share/webm] <defunct>

**Comment by Sopor** [comment]
After going back to `19.39-2` the CPU was back to 0-2%

**Comment by rostovtsev** [comment]
Hi, Sopor.

I have double checked and there were no recent changes at all for this part of the app. It's impossible.

For all of my servers it's just fine. Even where _Real-time monitoring_ is enabled it only takes less than 1% of CPU.

-----

Restart Webmin afterwards and Clear Cache in theme options, or using hot key.

**Comment by rostovtsev** [comment]
Any news?

**Comment by Sopor** [comment]
I have no idea why those cgi used so much CPU, but now it is gone. I did a restart of the RPi so it could have been something else making it do like this.
