### ISSUE TITLE
Complete French translation file

### ISSUE THREAD

**Issue by pwozniak89** [authentic-theme/authentic-theme#1398]
Hi,
The translation in French for Authentic Theme is over !
You can insert it to your next version.
Glad to improve your GREAT JOB !
[fr.UTF-8.zip](https://github.com/authentic-theme/authentic-theme/files/3586780/fr.UTF-8.zip)

**Comment by rostovtsev** [comment]
Merci beaucoup! :sweat_smile:  I have added it locally and will push to the repo a bit later.
