### ISSUE TITLE
Network Configuration - Changes you have made may not be saved

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1399]
When i'm open my network card it will tell me that i have made changes and bring up the dialog `Changes you have made may not be saved`, but i haven't changed anything ...

Check out this [video](https://gofile.io/?c=6dR7u3)

**Comment by rostovtsev** [comment]
Sopor, thank you. You are right. There was a bug. It probably affected other, familiar parts of UI. 

It's fixed now. You can update.
