### ISSUE TITLE
Android/Chrome address bar should reflect the current theme color

### ISSUE THREAD

**Issue by alessandrofrancesconi** [authentic-theme/authentic-theme#1405]
The address bar in Android Chrome is always blue. It would be nice to reflect the theme color instead.

This is an example with Dark Red theme color.
![Screenshot_20190926-074111](https://user-images.githubusercontent.com/1595223/65661285-90de0700-e031-11e9-8e6a-62cccb359709.png)

Changing the address bar color is pretty simple: https://stackoverflow.com/a/26960753

**Comment by rostovtsev** [comment]
Hi, Alessandro.

Yes, good idea. If you check the source, the meta tag with theme color is already there. It's just static (blue).

I will take a look at this to make it dynamic.

**Comment by alessandrofrancesconi** [comment]
The little progress bar should have that color (maybe darker) as well

**Comment by rostovtsev** [comment]
That is debatable.

**Comment by rostovtsev** [comment]
Done.
