### ISSUE TITLE
Filter does not allow to open filtered result

### ISSUE THREAD

**Issue by Sarge2013** [authentic-theme/authentic-theme#1407]
Hello,
first of all - thanks for the excellent Theme what is now default for WebMin !
But it seems I found a bug never seen before.
EXAMPLE - under Webmin open Cron Jobs using Search Panel - Use Filter to find any cron job - and try to open it by click.
In my environment (CentOS 7) it does not work (a couple of months ago it was opening) - please, cross-check.

Issue 2 - not relating to your theme directly but may be you in a direct connection with Webmin developer...because it's IMPORTANT !
Making an update of YUM packages - where is THE LOG ?!
Ideally if it could be a fixed file like
/etc/webmin/yumupdates.log based on
yum update >> /etc/webmin/yumupdates.log to add any new updates made.
But I did not find such a log nowhere within Webmin...
So update process looks excellent - but it MUST BE saved somewhere, IMHO...

Thank you for your attention !
Best regards,

**Comment by rostovtsev** [comment]
About _YUM_ logs. By default the log is saved to `/var/log/yum.log`.

You can see _yum's_ history by running:

```
yum history list
```

Later, by entering an _id_ you can see the details for it:

```
yum history info 32 # (32 is and id, displayed in the leftmost column)
```
