### ISSUE TITLE
Extraneous escapes?

### ISSUE THREAD

**Issue by XhmikosR** [authentic-theme/authentic-theme#1411]
Not sure if this is an issue with authentic theme, but I thought I'd report it :)

Using webmin 1.930 and authentic theme 19.39-2 I see this when updating the packages at the top:

```
Installing update with apt-get -y install openssh\-client openssh\-server openssh\-sftp\-server
```

It seems the `-` is wrongfully escaped in that message.

I don't have a screenshot available right now.

**Comment by rostovtsev** [comment]
Hi,

It's not the theme issue but yes, there are extra escaping done for packages names. I can take a look a bit later.

Thank you for reporting. :smiley_cat:

**Comment by rostovtsev** [comment]
Fixed.
