### ISSUE TITLE
Connection lost - showing the wrong date

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1413]
Today i lost connection to one of my servers and as you can see the date is wrong

![image](https://user-images.githubusercontent.com/5789283/66527961-71011580-eafe-11e9-908f-aec6fa2706a1.png)

authentic-theme 19.40-beta2-23

**Comment by rostovtsev** [comment]
There is only one way to have that data incorrect - is when local data/time on your PC is not set correctly.

It's not the theme issue.

**Comment by Sopor** [comment]
The time is not wrong!

**Comment by Sopor** [comment]
It must be some old cached date that was showing. I'm 100% sure that the date and time was correct. It will sync two times every day to ntp.stupi.se

**Comment by rostovtsev** [comment]
Does it still show the wrong value? You can disable connection in DevTools (console/Network tab/No connection).

**Comment by Sopor** [comment]
I have pulled the network cable but now it won't show up at all. All the real-time stats has frozen (the four pie charts).

I'm running 19.40-beta3-5.

**Comment by rostovtsev** [comment]
Yes, it's intentional. It requires explicit user action. Try clicking some link.

**Comment by Sopor** [comment]
No, it can't be true because if i do, nothing happens... It move the busy line at the top a few times and then it stops.

I did a second test after updating to 19.40-beta3-7 and now it was showing without me doing anything so what you are saying is not the way it work.
