### ISSUE TITLE
Stats history - suggestions / questions

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1415]
The new stats history looks nice but i want to have 24h instead of 12h.

`Stats history duration` will not update the time when moving the time. I have to release it. So my first thought was, it was broken.

I don't see any `Swap` in the `Stats history` or it will only be visible when the swap is in use? But what happens if it use the swap sor a few minutes only. Will it still be visible until the `Stats history duration` is reached?

It would have been nice if it was possible to hide some of the stats history. 

The stats history is set to 1 hour but why will it show more than 7 hours?
```
CPU 2:20:44 AM 2:59:57 AM 3:39:10 AM 4:18:24 AM 4:57:37 AM 5:36:50 AM 6:16:04 AM 6:55:17 AM 7:34:30 AM 8:13:44 AM 8:52:57 AM 9:32:10 AM
```

**Comment by rostovtsev** [comment]
> The new stats history looks nice but i want to have 24h instead of 12h.

Already added earlier today but it might cause significant slowdown. It's being tested now on my production server. Let's see how bad it goes for 24h. I might need to handle (read and parse) the stored data differently.

> Stats history duration will not update the time when moving the time. I have to release it. So my first thought was, it was broken.

Thanks, it's fixed now.

> I don't see any Swap in the Stats history or it will only be visible when the swap is in use? 

I think I can add it as well. I didn't think it was important.

> But what happens if it use the swap sor a few minutes only. Will it still be visible until the Stats history duration is reached?

There were patches I made earlier that should handle data overflow for continuous updates.
As long as the tab of the browser is opened and _Stats History_ is enabled in settings, the data will be collected for given period of time.

> It would have been nice if it was possible to hide some of the stats history.

This will be added next.

> The stats history is set to 1 hour but why will it show more than 7 hours?

I need to make a correction that it's meant only for _continuous_ stats and approximate. Doing more logic to make it extra accurate would result in performance downgrade.

**Comment by Sopor** [comment]
> The new stats history looks nice but i want to have 24h instead of 12h.

Don't misunderstand me here. I want 24h and not AM/PM.

**Comment by rostovtsev** [comment]
Time set globally here.
https://github.com/authentic-theme/authentic-theme/issues/1388#issuecomment-540480399

What do you mean about Swap? I don't understand.

**Comment by Sopor** [comment]
It is showing the right format on the dashboard..

![image](https://user-images.githubusercontent.com/5789283/66593919-3ea3f680-eb98-11e9-93fa-08c52510c337.png)

**Comment by Sopor** [comment]
`theme_xhred_live_stats_virt=Swap`

**Comment by Sopor** [comment]
Still no time in the stats history duration

![image](https://user-images.githubusercontent.com/5789283/66605407-58e9ce80-ebb0-11e9-81e7-c24c231ada56.png)

19.40-beta3-7

**Comment by rostovtsev** [comment]
> It is showing the right format on the dashboard..

It shows the right format, because you explicitly set _Full format_ to `dddd` instead of keeping default `LLLL`. There is no separate option for time, I might add one, though.

To make it work, set locale language to English UK, as in UK they have metric system, like we do in EU, while US have imperial.

> Isn't this the swap file (virtual memory)?

Swap has been added on the latest commit along with other optimizations.

**Comment by Sopor** [comment]
I changed it to English UK and it will now show 24H

**Comment by rostovtsev** [comment]
Okay, now you can also set any time format you want to.

![image](https://user-images.githubusercontent.com/4426533/66782492-75eb0e00-eede-11e9-83b6-49523a3034de.png)

**Comment by rostovtsev** [comment]
Network I/O has been added on the latest commit.

![image](https://user-images.githubusercontent.com/4426533/66967820-f484ae80-f08a-11e9-945a-6994a4d7e7b5.png)
