### ISSUE TITLE
No left menu when my web browser restore pages

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1417]
When Firefox has restarted after an update the dashboard is sometimes missing the left menu. To get it back i need to reload the page. I have four Webmins and i haven't found a pattern when it happens. It is more as it was random. Sometimes only one will fail and other times they all fail to show the menu. They all have very different hardware and speed too.

Do you know why it happens and can it be fixed?

**Comment by rostovtsev** [comment]
When you leave the page, what page is it on, that after refresh gives you no navigation menu? When it happens what is the URL in the address bar?

**Comment by rostovtsev** [comment]
Can you reproduce it?

**Comment by rostovtsev** [comment]
That might be Firefox's caching issues.

**Comment by Sopor** [comment]
They are all at the dashboard:
`https://192.168.0.12:10000/sysinfo.cgi?xnavigation=1`

**Comment by rostovtsev** [comment]
Can you reproduce it now?

**Comment by Sopor** [comment]
I did an update of Firefox yesterday and this time it was one Webmin that the left menu was gone but after a few seconds the tab was showing up, but most of the times i need to reload the whole page when it happens.

**Comment by rostovtsev** [comment]
I made few changes in this regard for upcoming 19.40, that might fix this issue. For the future, try making video-screencast, and send it privately to me, so I could see exactly what is happening. Console output would also help.
