### ISSUE TITLE
local disk space incorrect, latest stable and development version

### ISSUE THREAD

**Issue by chaosx2019** [authentic-theme/authentic-theme#1419]
i have an ntfs partition in my linux server. the reason being it has 7tb of video content that i dont wanna mess around moving. 

the issue is that this isn's visible in the local disk space on the dashboard. or the disk usage tab. it doesn't see the ntfs partition at all. is this meant to be this way or is it a bug.

it would be really useful to have the ntfs disk listed too so i can monitor my disk usage without having to navigate through the menus each time

**Comment by rostovtsev** [comment]
Hi,

Does it get shown in Disk and Network Filesystems module?

What are the mount options, either from _command line_ of from _fstab_ (if that's how you mount it).

I suppose it's not reflected in Gray Theme as well?

**Comment by chaosx2019** [comment]
yes it shows in module

/var/ftp | Windows NT Filesystem (ntfs) | Partition with ID 505260ED5260D96C | 73% | Yes | Yes

from fstab
UUID=505260ED5260D96C /var/ftp ntfs noatime,lazytime,permissions,nofail,x-systemd.automount

**Comment by rostovtsev** [comment]
Okay, just for the record, I have `ntfs` file sistems being displayed on Dashboard.

Try the following:

~~~
umount /var/ftp
~~~

..and then mount it using console command:

```
mount UUID=505260ED5260D96C /var/ftp
```

After that, refresh the page for the Dashboard. Do you see your video content then?

**Comment by chaosx2019** [comment]
i tried that. no difference. it shows fine in the module just not the dashboard

**Comment by chaosx2019** [comment]
let me correct that, it comes up with this now

/var/ftp | fuseblk | 27%  (1.91 TiB) | 7.27 TiB | /dev/sdd1 - in disk usage

local disk space amount is correct but shouldn't it show ntfs??

**Comment by rostovtsev** [comment]
To save the mount and display it after reboot you can use the _Disk and Network Filesystems_ module, click on the device, save mount option. You can also edit _fstab_ manually.

![image](https://user-images.githubusercontent.com/4426533/67128958-ec04b300-f205-11e9-85f6-d01b39d90420.png)

Can you please provide the screenshot of main page of _Disk and Network Filesystems_ and _Edit Mount_ page for this particular mount?

**Comment by rostovtsev** [comment]
..and the Dashboard to see how it looks/calculates.

**Comment by chaosx2019** [comment]
![dash](https://user-images.githubusercontent.com/47483980/67130604-c2458f00-f1f9-11e9-82ef-c9521ffed7c6.gif)

this is the dashboard. i cant edit the mount

![dnf](https://user-images.githubusercontent.com/47483980/67130662-f28d2d80-f1f9-11e9-9ebf-9618d033f625.gif)

disk and network filesystems. i have edited the ips etc out of the images

**Comment by rostovtsev** [comment]
Okay, I am confused now!

You said it wasn't shown on the Disk Usage tab but it does?

![image](https://user-images.githubusercontent.com/4426533/67131089-f9bd3700-f20b-11e9-80f7-05b7a8c03cbb.png)

Do you have `ntfs-3g` package installed?

**Comment by chaosx2019** [comment]
no i said it was working i just asked about the fact its listed at fuseblk

yes i do

**Comment by rostovtsev** [comment]
> The issue is that this isn't visible in the local disk space on the dashboard or the disk usage tab. It doesn't see the _ntfs_ partition at all. Is this meant to be this way or is it a bug.

I am sorry but this is what I understood from your words above.

---

Okay. _fuseblk_ is just the way to report _ntfs_ partitions - _fuse_ is file system in userspace. It's perfectly fine and there is no bug.
