### ISSUE TITLE
MySQL search enhancement

### ISSUE THREAD

**Issue by MorningSleeper** [authentic-theme/authentic-theme#1420]
Hi, I often use the simple search form at bottom of MySQL module to perform multiple searches, one after another, where the same column name contains different values each time ...

![image](https://user-images.githubusercontent.com/8920632/67649181-3caa9900-f8f5-11e9-954c-60a330680b17.png)

After clicking search, when I click my browsers back button, the keyword text form field remembers what I typed and fills it back which is fine but the first two drop down form fields do not remember their previously selected values and instead show the first choice in the drop down ...

![image](https://user-images.githubusercontent.com/8920632/67649203-577d0d80-f8f5-11e9-9182-c9b4a581fb88.png)

Would be a useful enhancement, at least in my case where I am doing multiple searches of the same column name, if it could remember the previously selected values of the two drop down menus or at least the first one where one chooses a column name. For those that don't want such behavior, they can always click the Reset Search button you provide on results page to go back and clear all the fields.

PS - If this is unrelated to your theme, please advise, did not even think about it till I finished writing this.

**Comment by rostovtsev** [comment]
It's related and a good point. The state should be saved as it is.

Fixed now on the latest commit.
