### ISSUE TITLE
Server Selection drop down not showing in Opera & Canary

### ISSUE THREAD

**Issue by nabtron** [authentic-theme/authentic-theme#1422]
The Server Selection dropdown does not appear in opera browser and in chrome canary (on mac). 

The dropdown is hidden behind the big webmin and virtualmin tabs on top left. 

Please check the image for reference. 

![Screenshot 2019-11-10 at 4 49 24 PM](https://user-images.githubusercontent.com/9471128/68543612-28799800-03db-11ea-8c09-69fc65f10656.jpg)

**Comment by rostovtsev** [comment]
What theme version are you running? It's been fixed a long time ago.

**Comment by nabtron** [comment]
Oh! thanks for responding. I just checked that it never informed me to upgrade, as my virtualmin / webmin versions are not updated too.

I am confused, how can i update virtualmin/webmin to latest versions?
I am running webmin 1.90 and webmin 6.05, and everything else is updated. But no option / way to update them?
