### ISSUE TITLE
[BUG] Postfix > SMTP Client Restrictions

### ISSUE THREAD

**Issue by fernandolcardoso** [authentic-theme/authentic-theme#1423]
There is a problem saving RBL data that is generating information clutter.

Try filling in the data, saving, and then coming back to see the result.

![image](https://user-images.githubusercontent.com/16019127/68790732-9d8cdd80-0626-11ea-9f25-9209f3afae23.png)

It was necessary to manually edit the configuration files to reestablish Postfix.

![image](https://user-images.githubusercontent.com/16019127/68790759-ac739000-0626-11ea-9ab4-eeb6a79b5988.png)

**Comment by fernandolcardoso** [comment]
An important note, "check_client_access" should be mentioned before RBL items, as this is preventing the "hash:/etc/postfix/access" filter.

**Comment by rostovtsev** [comment]
Hi,

If you switch to Gray Theme do you get the same result?

**Comment by rostovtsev** [comment]
What is the Postfix version are you running there? What is Webmin version?

I have just saved the page with:
![image](https://user-images.githubusercontent.com/4426533/68840415-c7e8a480-06d3-11ea-9c81-2a9c65a436c5.png)


..and got on the config file, _**main.cf**_ the following line:


~~~
smtpd_client_restrictions = permit_mynetworks permit_inet_interfaces reject_unknown_reverse_client_hostname permit_tls_all_clientcerts permit_sasl_authenticated check_client_access hash:/etc/postfix/access reject_rbl_client zen.spamhaus reject_rbl_client zen.spamhaus2
~~~

The option `check_client_access` precedes `reject_rbl_client` as expected.

**Comment by rostovtsev** [comment]
Any news?

**Comment by fernandolcardoso** [comment]
Hello, here's an example:

The following screen is an initial example:

![image](https://user-images.githubusercontent.com/16019127/69001359-97635f00-08bb-11ea-8e37-88b6137f2b75.png)

Now I will add a new server in RBL Hostname and saved next

![image](https://user-images.githubusercontent.com/16019127/69001373-c7126700-08bb-11ea-8ca6-0963fb80fe73.png)

When checking how it was saved, note that RBL over IP will not be saved and the option for other restrictions has been cleared.

![image](https://user-images.githubusercontent.com/16019127/69001376-dbeefa80-08bb-11ea-904c-1df4ffc64972.png)

**Comment by fernandolcardoso** [comment]
![image](https://user-images.githubusercontent.com/16019127/69001401-5cadf680-08bc-11ea-91f4-740721f39b81.png)

Follow my version of Virtualmin

**Comment by rostovtsev** [comment]
> Note that RBL over IP will not be saved 

It's saved on my CentOS 6 debug server.


> And the option for other restrictions has been cleared.

It isn't cleared. All is being saved correctly.

----

Again, what is your **_Postfix_** version and your _**Webmin**_ version.

**Comment by rostovtsev** [comment]
CentOS 6 has Postfix version 2.6.6, while Debian 10 has Postfix version 3.4.7. Both save data correctly.

**Comment by fernandolcardoso** [comment]
My Postfix version:

![image](https://user-images.githubusercontent.com/16019127/69006215-b9d09900-090a-11ea-93ff-c14743103b4d.png)

**Comment by rostovtsev** [comment]
Here is the thing, Webmin preserves the current order, for example if you manually edit _**main.cf**_ file and place `check_client_access hash:/etc/postfix/access` at the end of  `smtpd_client_restrictions = ` it will stay there after using UI _(SMTP Client Restrictions)_. It appears that it was broken manually beforehand.

To fix it, just open two browser windows, one with _Edit Config Manually_ the other with _SMTP Client Restrictions_. Then when both pages are opened, in the editor, comment out `smtpd_client_restrictions` with `#` and click green save button. Next change to previously opened tab for _SMTP Client Restrictions_ and hit save. Then go back to edit manually page and refresh the page to see what you got - the order will be just fine.

This shouldn't be reported as a theme issue. :wink: I am closing this.
