### ISSUE TITLE
Why release a new final that i can't install

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1424]
Why are you releasing a final version that requires a Webmin release that isn't released yet? It make no sense to do that...

**Comment by rostovtsev** [comment]
It does make sense as theme releases has to precede Webmin releases. 

Besides, Webmin 1.932 is released?

**Comment by rostovtsev** [comment]
Besides, there are changes that make some features (new size units sub, for instance) work incorrectly.

It's not breaking anything but I need to indicate it.

**Comment by Sopor** [comment]
The latest Webmin i can find is 1.930 http://www.webmin.com/download.html

**Comment by rostovtsev** [comment]
Well, I agree, it's a bit inconsistent as, for example, [Virtualmin repos](http://software.virtualmin.com/gpl/universal/?C=M;O=D) have it, just as [devel repos](https://download.webmin.com/devel/rpm/) for Webmin.

**Comment by Sopor** [comment]
Now i have high CPU usage again after updating Webmin and theme :(
```

28590 | root | 43.5 % | [/usr/share/webm] <defunct>
28608 | root | 36.0 % | /usr/share/webmin/proc/index_cpu.cgi
13069 | root | 14.9 % | perl /usr/share/webmin/.~files/webadmin/chinese-to-utf8.pl .
```
![image](https://user-images.githubusercontent.com/5789283/69148249-2945b480-0ad4-11ea-9c3e-0af6c5b594ea.png)

**Comment by rostovtsev** [comment]
`28608 | root | 36.0 % | /usr/share/webmin/proc/index_cpu.cgi` - runs only when you call this page.

Simply `pkill -9 webmin` and start it over again.

**Comment by Sopor** [comment]
```
8315 | root | 106 % | /usr/share/webmin/proc/index_cpu.cgi
8083 | root | 52.3 % | /usr/share/webmin/authentic-theme/stats.cgi
13069 | root | 15.2 % | perl /usr/share/webmin/.~files/webadmin/chinese-to-utf8.pl .
```

**Comment by rostovtsev** [comment]
`perl /usr/share/webmin/.~files` you ran update using update script? It's okay, just let it finish first.

**Comment by Sopor** [comment]
Hmmm, i think it wasn't finished ... 🤒

**Comment by Sopor** [comment]
Yes, i ran the `update-from-repo.sh` and it seems to worked after it told me i could login again and this was making the high CPU usage... Silly me :/

**Comment by gnadelwartz** [comment]
> `perl /usr/share/webmin/.~files` you ran update using update script? It's okay, just let it finish first.

strange, it shouldn't run the translation conversion script in background ...
