### ISSUE TITLE
[BUG] Let's Encrypt on Virtual Server

### ISSUE THREAD

**Issue by fernandolcardoso** [authentic-theme/authentic-theme#1426]
When creating a certificate, I am receiving the following message:

Requesting a certificate for domain.com (exemple) from Let's Encrypt ..
.. request failed : Web-based validation failed : Failed to request certificate :

`Error registering: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.`

DNS-based validation failed : Failed to request certificate :

`Error registering: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.`

**Comment by rostovtsev** [comment]
Off-topic:
-> https://github.com/webmin/webmin/issues

Related:
[x] https://github.com/webmin/webmin/issues/951
[x] https://github.com/webmin/webmin/issues/1124
[x] https://www.virtualmin.com/node/67390
