### ISSUE TITLE
CentOs 6 webmin issue. 

### ISSUE THREAD

**Issue by kaichiu** [authentic-theme/authentic-theme#1435]
Here is the error message. 

HTTP/1.0 500 Perl execution failed Server: MiniServ/1.94012231801 Date: Tue, 24 Dec 2019 04:33:10 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed
Undefined subroutine &WebminCore::format_document_title called at /usr/libexec/webmin/authentic-theme/authentic-init.pm line 1306.
What can help ? 
I have update with git development version.

**Comment by rostovtsev** [comment]
Try:

~~~
pkill -9 webmin
pkill -9 miniserv
/etc/webmin/start
~~~

Other than that try `reboot` ing your server, and/or running `cd /usr/libexec/webmin && ./update-from-repo.sh -y` once again.

I had just tested it on _CentOS 6_, with the latest update, and it works just fine.

**Comment by kaichiu** [comment]
Tested. But still have the same error. 
Dont know why,
Is there any environment issue with it ? 
The CSF system has detected the use login. But still cant show with the system now.

**Comment by kaichiu** [comment]
Server information.
CENTOS 6.10 xen pv

**Comment by rostovtsev** [comment]
What is the output of:

```
md5sum /usr/libexec/webmin/authentic-theme/authentic-init.pm
md5sum /usr/libexec/webmin/authentic-theme/authentic-funcs.pm
```

and

~~~
grep -i -B 10 -A 10 'sub format_document_title' /usr/libexec/webmin/authentic-theme/authentic-funcs.pm
~~~

**Comment by rostovtsev** [comment]
Besides, what is the output of:

~~~
perl -v
~~~

**Comment by kaichiu** [comment]
![image](https://user-images.githubusercontent.com/7088237/71457106-6c7ffb00-27d7-11ea-9061-7ed8abc8b399.png)
![image](https://user-images.githubusercontent.com/7088237/71457145-9802e580-27d7-11ea-9ac6-1e9c65d4dc6b.png)

Perl v5.8.8
Here is the inflammations. 

Thanks alots.

**Comment by rostovtsev** [comment]
.. and this output? :smiley: 

~~~
grep -i -B 10 -A 10 'sub format_document_title' /usr/libexec/webmin/authentic-theme/authentic-funcs.pm
~~~

**Comment by rostovtsev** [comment]
Are you sure that you ran ordinary updates, like `yum update`?

What is the output of:

~~~
yum whatprovides "perl"
~~~

My CentOS 6.10 has Perl 5.10 installed. Perl 5.8.8 is not something what you should have on your system. You most likely have package dependencies issues?

I think the lowest version of Perl that we support is 5.10. Correct @swelljoe?

**Comment by rostovtsev** [comment]
@kaichiu Can you please pull the very latest version of the theme (update to development version using theme configuration) and tell me if it solves your issue? If you can't run Webmin UI, you can go and update it using console script by running:

~~~
/usr/libexec/webmin/authentic-theme/theme-update.sh --force
~~~

**Comment by swelljoe** [comment]
Yes, the oldest Perl version supported is 5.10, which is what comes with CentOS 6 (5.10.1, specifically). 5.8.8 came with CentOS 5, which reached end of life years ago and is not a supported platform (by us or anybody else).

**Comment by kaichiu** [comment]
> @kaichiu Can you please pull the very latest version of the theme (update to development version using theme configuration) and tell me if it solves your issue? If you can't run Webmin UI, you can go and update it using console script by running:
> 
> ```
> /usr/libexec/webmin/authentic-theme/theme-update.sh --force
> ```

@rostovtsev  I have try this before. But the result still the same. I could try again later this week again. Thanks.

**Comment by rostovtsev** [comment]
> I have try this before. But the result still the same. I could try again later this week again. Thanks.

@kaichiu Can I log in and take a look?
