### ISSUE TITLE
One minor (german) lang issue ...

### ISSUE THREAD

**Issue by gnadelwartz** [authentic-theme/authentic-theme#1437]
after changing from entities to UTF-8 codepoints, I have one small issue left on the change language page. every where else it seems to work ...

OLD ```&auml;```
```
theme_xhred_title_locale_auto=Automatisch, aufgrund der ausgew&auml;hlten Sprache
theme_xhred_global_manual=H&auml;ndisch
````
works correct:
![image](https://user-images.githubusercontent.com/4593242/71518498-8c84ec80-28b3-11ea-81f3-c81c642419a3.png)

NEW ```ä```
```
theme_xhred_title_locale_auto=Automatisch, aufgrund der ausgewählten Sprache
theme_xhred_global_manual=Händisch
```
![image](https://user-images.githubusercontent.com/4593242/71518567-d79eff80-28b3-11ea-8203-f7db610b3f51.png)

Don't know if its from my installation or a general issue ... may be you can check ...

**Comment by rostovtsev** [comment]
Have it set all correctly?

![image](https://user-images.githubusercontent.com/4426533/71518698-1ab59e80-28c5-11ea-9bfb-8a340b537656.png)

**Comment by gnadelwartz** [comment]
yes and no, it was the global setting ...  but now its gone also on my side ... even I did several restart and reloads :-(

the only difference now was I used usermin inbetween ,.,

Thanks for checking!
