### ISSUE TITLE
Missing Editor color palette 

### ISSUE THREAD

**Issue by brad1001** [authentic-theme/authentic-theme#1439]
Hi there 
Hope you are well and had a great Christmas and New Year 

I have just updated Webmin and Authentic theme version 19.44-3 was install by default 

I have found that under theme customisation there is no longer the option to change the color palette - the drop down field is missing.

Kind Regards
Brad

**Comment by rostovtsev** [comment]
Hi again, Brad.

Happy New Year! :santa: :christmas_tree: 

Sorry for inconvenience but this button has been moved to Navigation Menu section (accordion) for better logical organization of the features.

**Comment by brad1001** [comment]
Hi Ilia 

Thank you for your reply and season greetings. 

Ah OK  - that is great, thank you very much 

Brad
