### ISSUE TITLE
Virtualmin User Management  > Missing link to Usermin 

### ISSUE THREAD

**Issue by brad1001** [authentic-theme/authentic-theme#1440]
Hi There

I hope all is well

On updating to Webmin 1.940 and Authentic theme 19.44-3 - I have found that the Usermin login link is now missing from  Virtualmin > Edit User > User 

This was such an important link to have available I hope this feature has not been removed intentionally .

Kind Regards
Brad

**Comment by rostovtsev** [comment]
Hi, Brad!

Happy New Year! :santa: :christmas_tree: 

It seems like a bug in Webmin. @jcameron could you check on it, as I could reproduce it in older themes.

**Comment by rostovtsev** [comment]
Brad, it seems that your Usermin is not running.

The link is automatically hidden if Usermin is not running.

**Comment by brad1001** [comment]
Ilia, you are absolutely right.
Thank you very much for your reply and looking into this for me

Kind regards
Brad
