### ISSUE TITLE
Why is some of my emails showing up as 0 PiB?

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1441]
Why is some of my emails showing up as 0 PiB? Those emails showing 0 PiB has more text than those emails showing bytes. I believe if it should be 0 it should be showing 0 bytes.

![image](https://user-images.githubusercontent.com/5789283/71788032-0721da80-301f-11ea-82bf-b22753e60f8f.png)

Webmin version 1.940
Authentic theme version 19.44-3

**Comment by rostovtsev** [comment]
It was a _bug_ and it's gonna be fixed on next Webmin 1.941 release (for all themes).

Although, you can update theme to the latest dev version right now, to have it fixed now.
