### ISSUE TITLE
Other email date formats?

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1442]
Why isn't there other date format to choose than these three?
DD/MM/YYYY
MM/DD/YYYY
YYYY/MM/DD

It is no big deal but in Sweden we use [YYYY-MM-DD](https://github.com/authentic-theme/authentic-theme/issues/1350#issuecomment-493719582) so i'm used to see that format.

**Comment by rostovtsev** [comment]
It's Webmin default. This is how it's been since the dawn of man.
