### ISSUE TITLE
Failed to save spam and virus delivery : Score to delete spam at must be an integer greater than zero

### ISSUE THREAD

**Issue by alanmels** [authentic-theme/authentic-theme#1445]
One a Webmin-managed server one of the domain names started to get lot's of spam with the following entry in the header information: `X-Spam-Status: No, score=2.9 required=3.0` So to prevent spam, I wanted to lower the spam score definition, however going to `Domain Configuration > Spam and Virus Delivery`  and attempt to put `2.9` in the `Delete spam if score is above` field is giving:

```
Failed to save spam and virus delivery : Score to delete spam at must be an integer greater than zero
```

So either Webmin/Virtualmin tandem or Authentic theme thinks `2.9` is not a good value for an integer. Could you please take a look at how this could be fixed? Thanks!

**Comment by jcameron** [comment]
Unfortunately this can't be fixed, because of the way SpamAssassin adds the spam score to email headers, and the way Procmail parses them. Basically it uses a header like `X-Spam-Level:***` where the number of stars indicates the spam score.
