### ISSUE TITLE
How to stop stats history opening on every load

### ISSUE THREAD

**Issue by TheBudda** [authentic-theme/authentic-theme#1449]
How can you stop the stats' history from opening on every load or reload. The only option I see is stats history on/off?

Regards
TheBudda

**Comment by rostovtsev** [comment]
Hi,

Just install latest dev version of the theme, and it will remember last state for any accordion on dashboard.

Release of 19.46 should be shipped tonight (in 12-14 hours).

**Comment by TheBudda** [comment]
@rostovtsev Thanks for the info. Release 19.46 worked like a charm ;- )

**Comment by rostovtsev** [comment]
@TheBudda My pleasure.
