### ISSUE TITLE
Complex chedule not work

### ISSUE THREAD

**Issue by a7lan** [authentic-theme/authentic-theme#1451]
does not save time in the scheduler (Cloudmin-> Backup and Restore-> System Backups-> Backup Shedule) . If you use the Gray theme, then everything works

**Comment by a7lan** [comment]
I use version 19.46

**Comment by rostovtsev** [comment]
Hi,

Appreciate your time to provide useful feedback! 

Fixed on the latest commit as of 19.46-2. You can update to it using Theme Configuration page.
