### ISSUE TITLE
Cloudmin Complex Backup Schedule

### ISSUE THREAD

**Issue by SteffanCline** [authentic-theme/authentic-theme#1452]
I'm unable to create a complex back up schedule. I click on the radio dial for it and select it from the popup but when saving, I get an error "Failed to save backup : No complex schedule was selected" When I edit a complex schedule, the popup does not have the previous selections set.

**Comment by rostovtsev** [comment]
Steffan, hi! :slightly_smiling_face: 

I just was fixing this bug yesterday. Could you pull the latest theme version and try again? It must work by now!

**Comment by SteffanCline** [comment]
Worked that time. Yay!

**Comment by rostovtsev** [comment]
:bowing_man:
