### ISSUE TITLE
Webmin: Network Configuration - display interface(s) data on Dashboard

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1453]
I wondering if you could add IP addresses on the dashboard? I have more than one network interface and i really want to make them both easy viewable.

**Comment by rostovtsev** [comment]
Hi,

Could you share the screenshot of what you are already seeing and to what you are referring to?

Do you see at the moment only first shared IP on a single interface?

**Comment by Sopor** [comment]
There are no IP address at all on the dashboard. How should i add that? Have you an IP address on your dashboard?

**Comment by Sopor** [comment]
Maybe it could be possible to show both internal and external IP addresses?

**Comment by Sopor** [comment]
Here is a picture of my dashboard:

![image](https://user-images.githubusercontent.com/5789283/74664575-486ce480-519e-11ea-8342-fa692812f777.png)

**Comment by Sopor** [comment]
If running more than one network interface it should show the name of the interface and then the IP address but if i only run one network interface behind a router it will only show the internal IP address and that is not so important, so it should show the external IP address too:

enp0s25: 192.168.0.10 (216.58.207.206)

It should show information from "Network Interfaces/Active now" on the dashboard or at least some of the information.

**Comment by rostovtsev** [comment]
Okay, it might be an improvement to Network Configuration module. I will add this when I have spare time.

Thanks for your feedback.

**Comment by Sopor** [comment]
Sounds nice, thanks!

**Comment by iliarostovtsev** [comment]
Okay, it's added with the commit above and will look something like this:

![image](https://user-images.githubusercontent.com/4426533/82495261-83f7b180-9af3-11ea-89a3-f052a3aa403f.png)

@jcameron will review it before actual Webmin 1.950 release.

Thanks for heads up.

**Comment by jcameron** [comment]
Do we need this page when we have the same information in the Network Configuration module?

**Comment by iliarostovtsev** [comment]
I don't know. Like any other Dashboard module info. Obviously, some people will be happy to see it, and some will complain. 

I don't mind having it disabled by default.

**Comment by Sopor** [comment]
I have this enabled on some Webmin's and disabled on others but after updating to Webmin 1.953 it seems to have enabling itself and now i can't find where to disable it again :(

**Comment by iliarostovtsev** [comment]
> I don't mind having it disabled by default.

I said I didn't mind, rather than suggested. Jamie didn't will to disable it by default, so it was left enabled.

> .. to have enabling itself and now i can't find where to disable it again

It's in _Network Configuration_ module's access control.

![image](https://user-images.githubusercontent.com/4426533/86664729-a6885000-bff7-11ea-8d53-0e8ff5f8f435.png)
