### ISSUE TITLE
Change language and time - Full format

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1456]
When i hover the mouse over `Full format` it will show me that the date should be
![image](https://user-images.githubusercontent.com/5789283/77007882-506aa080-6965-11ea-8ad9-4120a7f79473.png)
but that can't be right because if i type in `dddd` on another Webmin it will only show Wednesday but here it will show
![image](https://user-images.githubusercontent.com/5789283/77008032-ad665680-6965-11ea-855e-a0770e83492c.png)

On the other Webmin (totally fresh install of Ubuntu and Webmin) i haven't changed it and `LLLL` will show the same date format as `dddd` above.
![image](https://user-images.githubusercontent.com/5789283/77007996-9889c300-6965-11ea-9c1c-a26c70f9a09c.png)

**Comment by iliarostovtsev** [comment]
Hi,

What exact Webmin version and theme version are install with that Ubuntu? I can't reproduce it on my latest theme version.

**Comment by Sopor** [comment]
Webmin version 1.941
Authentic theme version 19.46-7
Ubuntu Linux 18.04.4

**Comment by iliarostovtsev** [comment]
There is something wrong with browser's cache, I guess. I really tried and couldn't reproduce it. It just shows things correctly for me. If it still doesn't work for you in incognito tab or/and after cache is cleared, then, if you could make a quick video-screenscast, that would help.

**Comment by Sopor** [comment]
I empty the web browser cache and the Authentic cache and it will do the exact same thing.
Here is a [video](https://gofile.io/?c=IwsTd2)

**Comment by Sopor** [comment]
I empty the web browser cache and the Authentic cache and it will do the exact same thing.

I logged in with Chrome and suddenly i could see an extra line in the window to the right of the four d's like this, "dddd I". There was a whole bunch of characters after the d's.
So if you paste in this `dddd DD MMMM YYYY HH:mm` it will be the exact same as `LLLL`.
So now we know why you couldn't reproduce it.

Sorry that i bother you with this silly user errors :(

**Comment by iliarostovtsev** [comment]
No problem, Sopor! Thank you for heads up! I appreciate this!

**Comment by iliarostovtsev** [comment]
Okay, I have added a commit that will make those fields a bit bigger, preventing possible issues like that in the future.
