### ISSUE TITLE
Display bug with utf-8 on File Manager

### ISSUE THREAD

**Issue by pwozniak89** [authentic-theme/authentic-theme#1458]
Special chars (utf-8) in tips balloon on file manager doesn't display correctly (using 19.46-7)
See attachments
Thanks ;-)

![01](https://user-images.githubusercontent.com/41525331/77046960-301dfe80-69c4-11ea-9019-a84af67c452d.jpg)
![02](https://user-images.githubusercontent.com/41525331/77046966-33b18580-69c4-11ea-95d9-8521ae6b1047.jpg)

**Comment by iliarostovtsev** [comment]
Merci, Pierre!
