### ISSUE TITLE
Please add service worker + manifest.json so we can install Virtualmin as Chrome app

### ISSUE THREAD

**Issue by RemyyB** [authentic-theme/authentic-theme#1459]
Hi there,

I wanna say I'm a great fan of this theme, many options, useful, style looks fine etc.

But 1 feature I would really like is to install Virtualmin as a Chrome app, this can only be done if there is a manifest.json file set (that's already the case) and a service-worker.js that indicates the app is installable (and of course a .js file that imports service-worker.js). Could you do this please? Doing this manually isn't always very pretty, I did in the past but it don't want to do it again after an update.

[See here for a quick guide](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs)

Thanks in advance,
Remy

**Comment by iliarostovtsev** [comment]
Hi, Remy. Thanks for the feedback.

> I wanna say I'm a great fan of this theme, many options, useful, style looks fine etc.

Thanks.

> But 1 feature I would really like is to install Virtualmin as a Chrome app. Doing this manually isn't always very pretty, I did in the past but it don't want to do it again after an update.

:slightly_smiling_face: 

What is the real, practical benefit of doing it? I am asking, because most of the times, what a user really needs, is an ability to add a desktop shortcut for their Webmin/Virtualmin panel and have a link alongside with other installed desktop apps. If that is the case, it's already possible by "creating a shortcut" from _More Tools_ sub-menu in Chrome.

**Example:**

![image](https://user-images.githubusercontent.com/4426533/77229209-927e2700-6b9d-11ea-95da-c3bd22f94f6c.png)

**Comment by RemyyB** [comment]
Hi there,

It's just a lot more convenient for me, on Windows a shortcut of a website isn't really what I prefer, a standalone app will make organizing  just a lot more easy for me personally :). I can also just make a script that applies some JS after updating the theme but I think more users would appreciate it since the manifest.json is already there 👍

**Comment by iliarostovtsev** [comment]
Would you like to make a commit, once you say you made it work already? 🙂

**Comment by RemyyB** [comment]
Haha sure, will do a MR

**Comment by abclution** [comment]
You can already do a similar thing to chrome app, without needing the manifest etc.

Open Virtualmin in chrome.
3 dot menu
More Tools
Create Shortcut
Fill in your customization, (open as window reccomended)
Then an icon on your desktop will show up

![image](https://user-images.githubusercontent.com/10130237/94431363-d9c52000-019d-11eb-986b-f169a22cc162.png)

When you run it from that shortcut, you get a Windows taskbar icon and app like window.

![image](https://user-images.githubusercontent.com/10130237/94431685-48a27900-019e-11eb-8aa9-96631d096659.png)

Works in Brave, Chrome for sure, maybe more.

**Comment by iliarostovtsev** [comment]
> You can already do a similar thing to chrome app, without needing the manifest etc.

Yeah, I know. This is why I added `manifest.json` at the first place. Once it's not a general issue, I think it's time to close this issue.

@abclution Just in case, there is a way to make right side slider to have the same colors as left navigation menu:

![image](https://user-images.githubusercontent.com/4426533/94433500-16dee180-01a1-11eb-9036-e1360817a52f.png)

**Comment by iliarostovtsev** [comment]
> I prefer, a standalone app will make organizing just a lot more easy for me personally :)

@RemyyB Upcoming Authentic Theme 19.83 will have it supported.

![image](https://user-images.githubusercontent.com/4426533/130297164-6c023bec-61b7-4200-bd4e-e297d2d0c722.png)
