### ISSUE TITLE
The window will not return to its former state

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1460]
When i edit the config file for my web server the window will not return as it should. I'm forced to update the page.

Before i enter edit mode:
![image](https://user-images.githubusercontent.com/5789283/77140959-89953480-6a7b-11ea-9823-a14d04103da8.png)

Here i edit the config file
![image](https://user-images.githubusercontent.com/5789283/77141491-623f6700-6a7d-11ea-85fa-b796ef054c43.png)

After edit mode:
![image](https://user-images.githubusercontent.com/5789283/77140965-96198d00-6a7b-11ea-81b9-56ee56453eef.png)

I have noticed that Read user mail will also open will much smaller borders, so i'm not sure what is the correct way it should be displayed.
![image](https://user-images.githubusercontent.com/5789283/77141287-9cf4cf80-6a7c-11ea-9e76-b45e64c2e212.png)

But not the The Samba Windows File Sharing
![image](https://user-images.githubusercontent.com/5789283/77141583-b8140f00-6a7d-11ea-8c41-3ec631e06ac0.png)

Webmin version 1.941
Authentic theme version 19.46-7
Firefox 74.0
Windows 10

**Comment by iliarostovtsev** [comment]
Hi,

It's meant to happen at the moment for View Log (System Logs), File Manager, Edit File Manually (All modules), View Table (MySQL/PostgreSQL), Read Mail in Usermin (it was a bug to do it for Read Mail in Webmin - and fixed now - thanks for reporting).

About Nginx - this module that you have installed is very old and not really supported. What you should try installing is:

~~~
https://github.com/virtualmin/virtualmin-nginx/archive/v2.6.tar.gz
~~~

It's way better solution. In order this module to work, you may need to symlink Perl to local, like this:

~~~
ln -s /usr/bin/perl /usr/local/bin/perl
~~~

**Comment by Sopor** [comment]
Thanks, this newer module looks much better. I didn't even know it existed. It is a bit confusing when it is under the name virtualmin-nginx when i run Webmin, so even if i have been able to find it, i probably never had installed it. Why isn't this listed in the Webmin site?

**Comment by iliarostovtsev** [comment]
@jcameron @swelljoe Is there a reason why we just don't replace the old NginX Webserver module with Virtualmin NginX?

I assume, we should distribute this new module as part of Webmin, as it's quite popular one.
