### ISSUE TITLE
Cloudmin Backup Schedule

### ISSUE THREAD

**Issue by SteffanCline** [authentic-theme/authentic-theme#1462]
The Cloudmin backup schedule popup window doesn't show the previously saved time selection.

It would be nice if the text could show on the actual Cloudmin backup page rather than having to popup the chooser window to see what it is.

**Comment by iliarostovtsev** [comment]
Hi, Steff.

Do you man on this page?

![image](https://user-images.githubusercontent.com/4426533/77846020-c5d33e00-71bb-11ea-9b8a-11518747b90a.png)

> It would be nice if the text could show on the actual Cloudmin backup page rather than having to popup the chooser window to see what it is.

I am not sure what you mean? It's standard behavior provided by Cloudmin itself?

**Comment by SteffanCline** [comment]
Yes.
<img width="903" alt="Screen Shot 2020-03-29 at 4 57 14 AM" src="https://user-images.githubusercontent.com/1323544/77848480-debaff80-7179-11ea-85ec-208c0690e44c.png">
They are no longer set to the previous settings when shown.

I was saying it would be nice if whatever was in the dialog above was shown in plain text so the popup was not needed. I'm no cron guru to know what 5 0 * * 0,3 means. (the numbers in the pic)
<img width="972" alt="Screen Shot 2020-03-29 at 4 56 49 AM" src="https://user-images.githubusercontent.com/1323544/77848489-f72b1a00-7179-11ea-81e5-95bc2929aa40.png">

**Comment by iliarostovtsev** [comment]
Actually I fixed that in the near future, but it's on the latest theme, remember?

Could you update and see if you still have this issue?

**Comment by SteffanCline** [comment]
I force updated to the beta and it works. Might be time to publish it.

**Comment by iliarostovtsev** [comment]
> I force updated to the beta and it works. Might be time to publish it.

Will do. Thanks, Steff!
