### ISSUE TITLE
Theme: No monitors on Dashboard regardless of module configuration

### ISSUE THREAD

**Issue by devhostcloud** [authentic-theme/authentic-theme#1463]
Hello,

Is choosing Yes to Webmin - Others - System and Server Status - Show monitors on Dashboard? suppose to add something new to first page Dashboard? I can't see a difference whether this options is set to Yes or No.

Operating system	
Ubuntu Linux 18.04.4

Webmin version	
1.941 	

Usermin version	
1.791

Virtualmin version	
6.08	

Authentic theme version	
19.46 

Thank you.

**Comment by iliarostovtsev** [comment]
Hi,

> I can't see a difference whether this options is set to Yes or No.

You will not see the difference, if you don't have active monitors set:

![image](https://user-images.githubusercontent.com/4426533/77847526-4dbe4580-71c6-11ea-89f2-e0a53b952407.png)

There is also an option that controls to which users display status:

![image](https://user-images.githubusercontent.com/4426533/77847573-c1605280-71c6-11ea-8587-f9ba14d1fd24.png)

If all is right, then you should see something like:

![image](https://user-images.githubusercontent.com/4426533/77847585-e5bc2f00-71c6-11ea-93bf-e40ab831e7d4.png)
