### ISSUE TITLE
Dashboard Stats History start time advances only for 10m storage duration option

### ISSUE THREAD

**Issue by FerhatSavci** [authentic-theme/authentic-theme#1464]
When anything other than 10m storage duration is selected, the start time remains unchanged, the data keeps on accumulating and the graph gets squeezed.

When 10m storage option is selected, the start time advances, and the graph shows the last 10m's worth of data.

v19.46.

**Comment by FerhatSavci** [comment]
![dashboard-realtime-options](https://user-images.githubusercontent.com/24621080/78111572-8ac44b00-7405-11ea-9a4b-3e7bb3899ec7.PNG)
![downboard-stats-history](https://user-images.githubusercontent.com/24621080/78111587-90219580-7405-11ea-9db6-bd204d4686e5.PNG)

**Comment by FerhatSavci** [comment]
Additional info: the "Stats history duration" option actually has 2 "10 minutes" on the slider. One when the slider is to the leftmost, and one a single tick from the left (that is, the first two values are both "10 minutes"). When the second "10 minutes" is selected, it behaves as outlined above, too. The correct behaviour is observed only when the slider is in the leftmost position.

**Comment by iliarostovtsev** [comment]
Okay, I finally figured this out. It's neat now! Give it a try with latest **19.47-RC3** (can be upgrade from theme configuration page).

Thanks for your feedback!

**Comment by silversword411** [comment]
For anyone trying to find this configuration panel and was completely lost like I was the only place I could find to configure the theme was: Bell icon (top right) to open the right side panel, then the gear (bottom right), then theme configuration. 

I couldn't find it in the webmin > webmin configuration > webmin themes > anywhere in there.

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

The option to configure duration time was removed after switching the stats to use a standalone service accessible via WebSockets. This change was made primarily for optimization reasons. A duration longer than 1 hour can be problematic for performance on average systems, as storing history stats for 1 day can lead to inefficiency in reading and writing data. The file size can reach up to 7-9 MB.

However, I may reconsider this in the future and make the option available again, clearly pointing out the downsides. Currently, you can set this option to a maximum of 1 hour by running the following command in the browser's console:
```
settings_sysinfo_real_time_stored_duration = 3600;
theme.config.save();
```

If you're interested in running more tests with lifted sanity checks (i.e., 3600 seconds), let me know.

**Comment by iliajie** [comment]
This feature has been implemented for the next release! There will be an option in theme settings to select the retention period for live stats storage.



https://github.com/user-attachments/assets/d907fd01-0ca8-4cfa-9aac-46cbaf7ebd40

It can already be tested using the nightly version of Webmin.
