### ISSUE TITLE
Custom logo

### ISSUE THREAD

**Issue by SteffanCline** [authentic-theme/authentic-theme#1466]
I made a change to the theme's css via extensions to darken my logo since it was so light and hardly visible. It might be cool to add a slider to adjust the opacity rather than having to use an extension on the theme. 
<pre>
.__logo {
opacity:1;
}
</pre>

On another note, when using a custom image, I think the tool bar should scroll up to it, not below it as seen in the capture. Is there a css addition I can apply for that too?
<img width="298" alt="Screen Shot 2020-04-03 at 2 49 03 PM" src="https://user-images.githubusercontent.com/1323544/78407714-4a59fe00-75ba-11ea-8bd3-d96dd8e39344.png">

**Comment by iliarostovtsev** [comment]
Hi, Steffan!

> It might be cool to add a slider to adjust the opacity rather than having to use an extension on the theme.

Glad you figured this out. Well, it can be easily done by tweaking an image (logo) itself. Adding opacity slider is an extra complexity and it's not in high demand to add this right now. I will keep this in mind for the future, if/when this page is reworked.

> I think the tool bar should scroll up to it, not below it as seen in the capture.

I honestly wouldn't like that, as right now, it feels like it blends deeply with the navigation menu. Having less opacity make it less disturbing in my opinion, but it differs from user to user, and this is why we have extensions.

>  Is there a css addition I can apply for that too?

Yes, give the following a try:

~~~CSS
aside 
{
    padding-bottom: 100px;
}
~~~
