### ISSUE TITLE
Calendar view of backups

### ISSUE THREAD

**Issue by SteffanCline** [authentic-theme/authentic-theme#1468]
In Cloudmin, I know I requested that you put common verbiage for the backup schedule like "Every Monday and Tuesday at 00:00:00" but would it be possible to do something like a calendar that shows the VM names as a "tag" or something where if you mouse over them, you can see the times? It's hard to tell some times when just looking at a list on the "System Backups" page.

**Comment by iliarostovtsev** [comment]
Hi,

Steffan, so having it displayed as follows not good enough?

![image](https://user-images.githubusercontent.com/4426533/79131384-3465ed80-7db1-11ea-80e9-456df120eff4.png)

Do you have your own representation of how it could be implemented? I don't think I understand a request about "tag" and "calendar".

**Comment by iliarostovtsev** [comment]
I understood correctly, this feature rather should be implemented on Cloudmin side.

I will close this due to inactivity.
