### ISSUE TITLE
Webmin shows plain session_login.cgi script when try to open login page

### ISSUE THREAD

**Issue by marcelocode** [authentic-theme/authentic-theme#1469]
when I try to open webmin login page "https://192.168.1.13:10000" it shows plain /usr/share/webmin/authentic-theme/session_login.cgi script, what is problem? I'm running Ubuntu 18.04 and latest version of webmin.

<pre>
#!/usr/bin/perl

#
# Authentic Theme (https://github.com/authentic-theme/authentic-theme)
# Copyright Ilia Rostovtsev 
# Licensed under MIT (https://github.com/authentic-theme/authentic-theme/blob/master/LICENSE)
#
use strict;

use File::Basename;

our (%in, %gconfig, %tconfig, %text, $config_directory, $current_theme, %theme_text);

do(dirname(__FILE__) . "/authentic-lib.pl");

my %miniserv;
get_miniserv_config(\%miniserv);

my $charset = &get_charset();

# Check to add error handler
error_40x_handler();

our %theme_config = (settings($config_directory . "/$current_theme/settings-admin", 'settings_'),
                     settings($config_directory . "/$current_theme/settings-root",  'settings_'));

# Show pre-login text banner
if ($gconfig{'loginbanner'} &&
    get_env('http_cookie') !~ /banner=1/ &&
    !$in{'logout'}                       &&
    !$in{'failed'}                       &&
    !$in{'timed_out'})
{

    print "Auth-type: auth-required=1\r\n";
    print "Set-Cookie: banner=1; path=/\r\n";
    &PrintHeader($charset);
    print '', "\n";
    print '', "\n";
    embed_login_head();
    print '' . "\n";
    embed_overlay_prebody();
    print
'

'
      . "\n";
    my $url = $in{'page'};
    open(BANNER, $gconfig{'loginbanner'});

    while () {
        s/LOGINURL/$url/g;
        print;
    }

    close(BANNER);
    &footer();
    return;
}

my $sec = lc(get_env('https')) eq 'on' ? "; secure" : "";
my $sidname = $miniserv{'sidname'} || "sid";
print "Auth-type: auth-required=1\r\n";
print "Set-Cookie: banner=0; path=/$sec\r\n"   if ($gconfig{'loginbanner'});
print "Set-Cookie: $sidname=x; path=/$sec\r\n" if ($in{'logout'});
print "Set-Cookie: redirect=1; path=/\r\n";
print "Set-Cookie: testing=1; path=/$sec\r\n";
&PrintHeader($charset);
print '', "\n";
print '', "\n";
embed_login_head();
print '' . "\n";
embed_overlay_prebody();
print '' . "\n";

if (defined($in{'failed'})) {
    if ($in{'twofactor_msg'}) {
        print "
",, "

\n";
        print '' . "\n";
        print ' ' . $theme_text{'login_warning'} .
          '
' . &theme_text('session_twofailed', &html_escape($in{'twofactor_msg'})) . "\n";
        print '' . "\n";
    } else {
        print '' . "\n";
        print ' ' .
          $theme_text{'login_warning'} . '
' . "\n";
        print '' . $theme_text{'theme_xhred_session_failed'} . "\n";
        print '' . "\n";
    }
} elsif ($in{'logout'}) {
    print '' . "\n";
    print ' ' . $theme_text{'login_success'} . '
' . "\n";
    print '' . $theme_text{'session_logout'} . "\n";
    print '' . "\n";
} elsif ($in{'timed_out'}) {
    print '' . "\n";
    print ' ' .
      $theme_text{'login_warning'} . '
' . "\n";
    print '' . &theme_text('session_timed_out', int($in{'timed_out'} / 60)) . "\n";
    print '' . "\n";
}
print "$text{'session_prefix'}\n";
print '' . "\n";

print '
     '
  . (&get_product_name() eq 'webmin' ? $theme_text{'theme_xhred_titles_wm'} :
       $theme_text{'theme_xhred_titles_um'}
  ) .
  '' . "\n";

# Process logo
embed_logo();

# Login message
my $host;
if ($gconfig{'realname'}) {
    $host = &get_display_hostname();
} else {
    $host = get_env('server_name');
    $host =~ s/:\d+//g;
    $host = &html_escape($host);
}
print '' . &theme_text('login_message') . ' ' . $host . '

' . "\n";
print '' . "\n";
print '' . "\n";
print
'' . "\n";
print '' . "\n";
print '' . "\n";
print '' . "\n";
print
  '' . "\n";
print '' . "\n";

if ($miniserv{'twofactor_provider'}) {
    print '' . "\n";
    print '' . "\n";
    print
'' . "\n";
    print '' . "\n";
}
if (!$gconfig{'noremember'}) {
    print '
             '
      . $theme_text{'login_save'} . '
         ' . "\n";
}
print '';
print '  ' .
  &theme_text('login_signin') . '' . "\n";

if ($text{'session_postfix'} =~ "href") {
    my $link = get_link($text{'session_postfix'}, 'ugly');

    print '[0] . '", "' . $link->[1] .
'", "toolbar=no,menubar=no,scrollbars=no,resizable=yes,width=700,height=500");return false;\' class="btn btn-warning">  '
      . &theme_text('login_reset')
      . '' . "\n";
}

print '';
print '' . "\n";

&footer();
</pre>

**Comment by iliarostovtsev** [comment]
Hi,

No idea.

Did you try restarting Webmin or rebooting the server? When does this issue started to happen?

**Comment by marcelocode** [comment]
Hi.
yes I restart webmin and reboot the server but problem still exist.
when I move my PC to another city and change my WiFi modem. I use webmin on vmware and use bridge for network connection. everything works fine( mysql, usermin, apache) except webmin login page.

**Comment by iliarostovtsev** [comment]
Make sure that Perl is installed and available.

Check `/var/webmin` logs for more details. As a next debugging step, I would try disabling SSL from `/etc/webmin/config` file.

Next, you need to look at installation package itself.

Besides, it could be networking issue as well. Check if nothing is blocking Webmin port.

It doesn't look like a theme issue at all anyway.

**Comment by marcelocode** [comment]
this is  a part of miniserv.log file. I think problem happen since 18/Apr/2020 

192.168.1.2 - - [24/Jan/2020:12:50:26 +0000] "GET /unauthenticated/css/bundle.min.css?19399999999999902 HTTP/1.1" 200 131678
192.168.1.2 - - [24/Jan/2020:12:50:26 +0000] "GET /unauthenticated/css/fonts-roboto.min.css?19399999999999902 HTTP/1.1" 200 381093
192.168.1.9 - - [19/Feb/2020:00:28:33 +0000] "" 403 1175284
192.168.1.9 - - [19/Feb/2020:00:30:06 +0000] "" 403 1175284
192.168.1.9 - - [19/Feb/2020:00:30:18 +0000] "" 403 1175284
192.168.1.9 - - [19/Feb/2020:00:30:23 +0000] "" 403 1175284
192.168.1.9 - - [19/Feb/2020:00:30:30 +0000] "" 403 1175284
192.168.1.9 - - [19/Feb/2020:00:31:36 +0000] "" 403 1175284
192.168.1.9 - - [19/Feb/2020:22:34:40 +0000] "" 403 1175284
192.168.1.9 - - [19/Feb/2020:22:37:16 +0000] "" 403 1175284
192.168.1.9 - - [27/Feb/2020:23:36:08 +0000] "" 403 1175284
192.168.1.2 - - [10/Mar/2020:22:37:57 +0000] "GET / HTTP/1.1" 401 4628
192.168.1.2 - - [10/Mar/2020:22:37:57 +0000] "GET /unauthenticated/css/fonts-roboto.min.css?19399999999999902 HTTP/1.1" 200 381093
192.168.1.2 - - [10/Mar/2020:22:37:57 +0000] "GET /unauthenticated/css/bundle.min.css?19399999999999902 HTTP/1.1" 200 131678
192.168.1.2 - - [10/Mar/2020:22:37:58 +0000] "GET /images/favicons/webmin/android-chrome-192x192.png HTTP/1.1" 200 6851
192.168.1.2 - - [10/Mar/2020:22:37:58 +0000] "GET /images/favicons/webmin/favicon-16x16.png HTTP/1.1" 200 1146
192.168.0.40 - - [18/Apr/2020:22:31:12 +0000] "GET / HTTP/1.1" 401 6864
192.168.0.40 - - [18/Apr/2020:22:31:12 +0000] "GET /favicon.ico HTTP/1.1" 200 15086
192.168.0.40 - - [18/Apr/2020:22:31:18 +0000] "GET / HTTP/1.1" 401 6864
192.168.0.40 - - [18/Apr/2020:22:31:19 +0000] "GET / HTTP/1.1" 401 6864
192.168.0.40 - - [18/Apr/2020:22:31:20 +0000] "GET / HTTP/1.1" 401 6864
192.168.0.40 - - [18/Apr/2020:22:31:20 +0000] "GET / HTTP/1.1" 401 6864
192.168.0.40 - - [18/Apr/2020:22:31:20 +0000] "GET / HTTP/1.1" 401 6864
192.168.0.40 - - [18/Apr/2020:22:33:32 +0000] "GET / HTTP/1.1" 401 6864
192.168.0.40 - - [18/Apr/2020:22:33:33 +0000] "GET / HTTP/1.1" 401 6864
192.168.0.40 - - [18/Apr/2020:22:35:39 +0000] "GET / HTTP/1.1" 401 6864

**192.168.0.41 - - [01/May/2020:01:44:59 +0000] "GET / HTTP/1.1" 401 6892
192.168.0.41 - - [01/May/2020:01:45:08 +0000] "" 403 368
192.168.0.41 - - [01/May/2020:00:59:16 +0000] "GET / HTTP/1.1" 401 6892
192.168.0.41 - - [01/May/2020:00:59:16 +0000] "GET /favicon.ico HTTP/1.1" 200 15086**

**Comment by iliarostovtsev** [comment]
What about _miniserv_  error log?

**Comment by marcelocode** [comment]
I don't know. 
 "GET /favicon.ico HTTP/1.1" 200 15086
 "GET / HTTP/1.1" 401 6864
is this log normal?

**Comment by marcelocode** [comment]
this is miniserv error log. I think this part "PAM authentication enabled
Already running
Failed to list unit files: Connection timed out" is after the problem happen
<pre>
[23/Apr/2020:22:41:58 +0000] miniserv.pl started
[23/Apr/2020:22:41:58 +0000] IPv6 support enabled
[23/Apr/2020:22:41:58 +0000] Using MD5 module Digest::MD5
[23/Apr/2020:22:41:58 +0000] Using SHA512 module Crypt::SHA
[23/Apr/2020:22:41:58 +0000] PAM authentication enabled
[23/Apr/2020:22:45:44 +0000] Reloading configuration
[23/Apr/2020:22:56:31 +0000] miniserv.pl started
[23/Apr/2020:22:56:31 +0000] IPv6 support enabled
[23/Apr/2020:22:56:31 +0000] Using MD5 module Digest::MD5
[23/Apr/2020:22:56:31 +0000] Using SHA512 module Crypt::SHA
[23/Apr/2020:22:56:31 +0000] PAM authentication enabled
Already running
Failed to list unit files: Connection timed out

</pre>

**Comment by iliarostovtsev** [comment]
Upgrade to the latest Webmin 1.942 and restart the service.

**Comment by marcelocode** [comment]
I already upgraded to the Webmin 1.942 and restart but problem still exist.

**Comment by marcelocode** [comment]
I changed Webmin port also but no change

**Comment by iliarostovtsev** [comment]
Debug the connection then. Start from trying connecting to Webmin using `curl` and/or `lynx` from terminal (locally and remotely) - do you still get source code page?

However, it's very odd. At the moment, I cannot think of anything what could case that. I would check the `perl` install.  I would purged Webmin configuration to defaults, reinstalled Webmin package and started from there.

**Comment by marcelocode** [comment]
<pre>
 do you still get source code page?
</pre>
yes I used terminal (locally and remotely) to load webmin page using links browser, still get source code page. perl is installed. it shows the version using perl -v command.

thank you very much.

**Comment by iliarostovtsev** [comment]
What about reinstalling Webmin?

What is the output of:

```
systemctl status webmin
```

**Comment by marcelocode** [comment]
<pre>
webmin.service - LSB: web-based administration interface for Unix systems
   Loaded: loaded (/etc/init.d/webmin; generated)
   Active: active (running) since Sat 2020-05-02 22:19:45 UTC; 1h 20min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1531 ExecStart=/etc/init.d/webmin start (code=exited, status=0/SUCCESS)
    Tasks: 1 (limit: 2290)
   CGroup: /system.slice/webmin.service
           └─2376 /usr/bin/perl /usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf
</pre>
I must backup my data to reinstall webmin. I will do that

**Comment by marcelocode** [comment]
I found the problem.
in /etc/webmin/miniserv.conf file line "addtype_cgi=internal/cgi" was "ddtype_cgi=internal/cgi
" first 'a' character was deleted. ahhh it takes me 10 days. my big silly mistake :| .
 @iliarostovtsev thank you very much for your help.

**Comment by iliarostovtsev** [comment]
Oh, good to know. No problem. Thanks for feedback! 😉
