### ISSUE TITLE
high cpu on theme and webmin

### ISSUE THREAD

**Issue by pieter-groeneweg** [authentic-theme/authentic-theme#1471]
same as in https://github.com/authentic-theme/authentic-theme/issues/1397

I am on a quest to solve why my PI4 webmin is dropping connection every now and then.

on my PI4 4GB I have similar issue. My webmin connection is dropping.
It doesn't make any difference if I connect within the network directly over IP
Or when I created a port forward or put an nginx reverse proxy in front.

I discovered this actually is happening when I have webmin opened in my browser.

When I am behind the reverse proxy I do have error messages like this:
2020/05/05 13:14:26 [error] 1268#0: *35081 upstream timed out (145: Unknown error) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: sub.domain.com, request: "GET /stats.cgi?xhr-stats=general HTTP/1.1", upstream: "https://yyy.yyy.yyy.yyy:10000/stats.cgi?xhr-stats=general", host: "sub.domain.com:10000", referrer: "https://sub.domain.com/sysinfo.cgi?xnavigation=1"

When I do have connection I find the CPU usage webmin and the theme very high.. sometimes 50%+ on the theme.
When I click the process it then says the process is no longer running.

When I was on 19.45 things where worse.
now I recently upgraded to 19.47 things are better but still there are drops of connection every 15 to 20 minutes. 

Some history on my quest.
From a little discussion: https://sourceforge.net/p/webminstats/discussion/107701/thread/696b601454/
I installed Eric Gerbiers module... nothing of the kind shows.. no CPU values going sky high in the graphs.
Some more history on my project: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=272440

![image](https://user-images.githubusercontent.com/10771283/81064026-349d6880-8ed9-11ea-9b1b-c51818dd9792.png)

I also noticed they get another ID each time. But that may be expected behaviour

![image](https://user-images.githubusercontent.com/10771283/81065552-f786a580-8edb-11ea-8b9b-263e8a1328e9.png)

I am pretty much lost in my search and hope someone can point me in a direction that may solve this issue.

Thanks

**Comment by iliarostovtsev** [comment]
Hi,

It's normal that you see it at a time of loading this page. It doesn't mean it uses CPU all the time for 53.5%.

There is an option at module configuration.
![image](https://user-images.githubusercontent.com/4426533/81071249-18a3c200-8eed-11ea-9dd8-52170462f825.png)

> I am on a quest to solve why my PI4 webmin is dropping connection every now and then.

It may happen on low grade CPUs. I would recommend disabling live stats from theme configuration on increase pull time to be greater than default 1000 ms.

**Comment by pieter-groeneweg** [comment]
Hello Ilia, Thank you for your reply.

Question though... I now disabled all live stats. To see what it does improve.
I also experienced drops in connection when editing in files manager (right click edit).
I experienced these drops in connection then too. (and when browsing though webmin)
Is that because as when webmin in any page is opened in the browser, it is collecting stats when this is enabled?

Tx

**Comment by iliarostovtsev** [comment]
You may want to reload the browser's page after disabling live stats to be sure it's really off, as only recent versions of the theme can enable/disable it properly without page reloads.

Overall, I don't have the exact answer to you about what may cause those connection drops, unless debugging it closely. Check **Network** tab in the browser's console to get more info.

**Comment by pieter-groeneweg** [comment]
i checked network tab.. when having webmin open on any page for a while (doing nothing) i can see:
`index.cgi/?xhr-info=1&webprefix= `
being targetted every five minutes.

That is expected I assume?

**Comment by iliarostovtsev** [comment]
Yes,

It's controlled from **Webmin Configuration/Background Status Collection**. We don't recommend disabling this option.

**Comment by pieter-groeneweg** [comment]
Thank you for your prompt assistance.. this is why I like (love) webmin... :)

Ok, but it could also be set as 10  minutes, 15 minutes maybe?
I also see it collects drive temps.. I don't think a PI can do that.. that should be safe to disable I assume?

For all those settings to minimize the footprint on a PI (or other lesser development boards) is there a list somewhere on possible settings?

**Comment by iliarostovtsev** [comment]
> For all those settings to minimize the footprint on a PI (or other lesser development boards) is there a list somewhere on possible settings?

No the one I can recall at the moment.
