### ISSUE TITLE
German translation lost in latest update

### ISSUE THREAD

**Issue by daniel337pvs** [authentic-theme/authentic-theme#1472]
Hi there,

thanks very much for you good work - this authentif theme is a fantasic addon for our webmin environment!

In the newest theme update 19.50 the German translation is gone. Could you please check this? Would be fine to have this translated GUI back in webmin ... Looking forward to hearing from you.

And please keep on this good work!

Kind regards
Daniel

**Comment by iliarostovtsev** [comment]
Thanks!

Actually, we added complete German and 40 other translations. However, it requires the latest Webmin 1.950 update as well. It hasn't been released yet and the only way for you to upgrade to it is using `update-from-repo.sh` from its directory.

I would take a risk and upgraded from Webmin repo, using mentioned script or rather, which is safer, downgraded the theme to 19.47 for now. It's up to you to decide what is best for you.
