### ISSUE TITLE
The last arrow is in the wrong column

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1473]
When moving rules and cron jobs there are these tiny arrows and something that it a bit annoying is that the last arrow is wrong as you can see here in the picture below

![image](https://user-images.githubusercontent.com/5789283/82166713-98e90080-98b9-11ea-84d5-32372bc4c9ba.png)

So when you start moving it you first have to press in the left column and then in the right. Easy to press the wrong arrow.

Firefox 76.0.1

**Comment by iliarostovtsev** [comment]
Good point. Fixed. Thanks!
