### ISSUE TITLE
webmin version dependence incorrect 

### ISSUE THREAD

**Issue by Omnoms57** [authentic-theme/authentic-theme#1476]
theme.info line 5 
what it is : depends=1.950 1.800
what it should be : depends=1.800

**Comment by iliarostovtsev** [comment]
First number represents Webmin version and second number for Usermin.

**Comment by pcclan** [comment]
> 
> 
> First number represents Webmin version and second number for Usermin.

but the problem with that there is no webmin version for 19.50 ATM, the latest even in the developer build is 19.42.

**Comment by iliarostovtsev** [comment]
Have you installed latest dev version of Webmin and willing to install the theme now?
