### ISSUE TITLE
Webmin updated but i still get a message that i need to update Webmin

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1477]
I was going to update to Authentic theme 19.50 but i got this message
![image](https://user-images.githubusercontent.com/5789283/82409539-4e5cb500-9a6e-11ea-9ed8-a196ad6b8ca0.png)

So i updated Webmin to 1.942.0514.1525 but i still get the above message :(

**Comment by Sopor** [comment]
Something that is really strange is that i get this message when updating Webmin by running `update-from-repo.sh`

```
Warning! Installing this version of Authentic Theme 19.50 requires
latest and/or possibly unreleased version of Webmin to work properly.
Your current version of Webmin is 1.94205141525. There might be incompatible
changes, that could stop the theme from working as designed.
It is recommended to upgrade Webmin to the latest development version, by
running `update-from-repo.sh` script from `/usr/share/webmin` directory.
```

**Comment by iliarostovtsev** [comment]
If you updated it from Git you are safe to go with theme update.

I'll see what I can do to fix that message on theme side.

**Comment by iliarostovtsev** [comment]
Good point. Fixed.
