### ISSUE TITLE
Not sure if this is a theme issue

### ISSUE THREAD

**Issue by JimTR** [authentic-theme/authentic-theme#1478]
Please see attached image what could be going wrong ?
![authvso](https://user-images.githubusercontent.com/4038510/83776453-19607d00-a680-11ea-8631-f6c2fea6f8fe.png)

**Comment by iliarostovtsev** [comment]
Hi,

It is, if you have steps to reproduce it. 🙂

**Comment by iliarostovtsev** [comment]
Jim,

There are no know ways to reproduce it. When did it happen to you? What did you do in particular?

**Comment by JimTR** [comment]
I accessed the apache module for virtualmin some how I can not remember how I did that but I can not reproduce it via webmin->servers->apache->servername

**Comment by iliarostovtsev** [comment]
I know why it could happen and I know how to trigger it manually to break the page like that but there is no way I can reproduce it in real life situation. I wonder, if there are exact steps that you took to make it happen but you are not sure either. 

I will keep this issue closed for now, and if you find the way to reproduce it, please let me know.

What browser was that, by the way?

**Comment by JimTR** [comment]
I am using Google Chrome Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by iliarostovtsev** [comment]
Yeah, I use Google Chrome as well. Please let me know, if you can reproduce it again. If you can remember where you were prior to that and/or what you were doing exactly, would be great. For example, how did you get on that page or if you canceled any current page loads and etc?
