### ISSUE TITLE
File Manager tree view lost after update

### ISSUE THREAD

**Issue by sinankizar** [authentic-theme/authentic-theme#1479]
Hello,
I have searched the issues but couldn't find any info on this. My filemanager works but treeview doesn't show up. Cleared both local storage and cache.
Webmin: 1.941
Authentic Theme: 19.51
Google Chrome latest update pn Windows 10 2004
Thank you.

**Comment by iliarostovtsev** [comment]
Hi,

What error do you get in browser's console? Have you tried force reloading a browser?

**Comment by sinankizar** [comment]
Some errors on console about extensions. I have force reloaded the page and cleared the cache again with ccleaner and the treevies back on. Sorry to bother you with the small issue.

Thanks again for the great work mate 👍

**Comment by iliarostovtsev** [comment]
Okay, good to know. I was baffled as it worked for me just fine.

Thanks for heads up!
