### ISSUE TITLE
Dashboard - Too many CPU temperatures

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1481]
After latest update i now have 6 CPU temps on my dashboard instead of 2:

![image](https://user-images.githubusercontent.com/5789283/86667274-c3ba2000-bff1-11ea-8dc9-70606c176bae.png)

**Comment by Sopor** [comment]
When running `sensors` i get this:
Adapter: ISA adapter
fan1:        1849 RPM
fan2:           0 RPM
fan3:        1270 RPM
fan4:        1029 RPM
temp1:        +54.0°C
temp2:        +53.0°C
temp3:        +29.0°C
temp4:       -128.0°C
 but why haven't there been 6 before the update? Is this something i can configure in Webmin?

**Comment by jcameron** [comment]
Is that the full output from the `sensors` command?

**Comment by iliarostovtsev** [comment]
Thanks, fixed.
https://github.com/webmin/webmin/commit/3fa7141ae729dd0355f6050198b5a4771c7a28b3

**Comment by Sopor** [comment]
I have updated AT to 19.53 but i still have 6 temperature values showing :(

**Comment by 7starsone** [comment]
> I have updated AT to 19.53 but i still have 6 temperature values showing :(
> 
> Hmm, i need to update Webmin too?

same here,
CentOS 7 7.8.2003
Webmin version | 1.953
Virtualmin version | 6.10
Authentic theme version | 19.53

**Comment by Sopor** [comment]
When trying to update Webmin i get this message: `Error: makedist.pl failed! aborting ...` Any suggestion?

**Comment by Sopor** [comment]
Yes, now it seems to work but the theme configuration page looks weird and ugly. All the options have been moved to the middle. Should it really look like that?

**Comment by iliarostovtsev** [comment]
Yes, all options for better readability and UX will be aligned on the right now. It's not ugly at all.

**Comment by iliarostovtsev** [comment]
> Yes, now it seems to work but the theme configuration page looks weird and ugly. All the options have been moved to the middle. Should it really look like that?

Do you still hate this?

**Comment by Sopor** [comment]
Hate is a strong word :)

I don't like it and it looks ugly. I understand it makes it easier to see the settings for every options, but you could add lines or make different shades instead.

What happens if you only move the left side text to the right and leave the right side as it was before? Something like this:

![image](https://user-images.githubusercontent.com/5789283/88063828-c593ef80-cb6a-11ea-9f0d-74e90900577b.png)

**Comment by iliarostovtsev** [comment]
Moving right side away from the left, discards all advantages of having it placed closer to each other at the first place. The easiest solution is to make an option to give users ability to take labels back to the left. That is something that could be done easily, but Joe doesn't like having too many useless options, and I think so too, actually. The good thing, is that you could easily add to you theme's extension CSS a small code that would move labels back on the left. I believe it's better the new way and will let users with older theme switch to the new theme with less adaptation obstacles.

**Comment by Sopor** [comment]
After installing Webmin 1.953.0720.1934 it will now show `(installed version 19.53, latest stable 19.47)`. How can it suddenly show 19.47 as latest stable AT?

**Comment by iliarostovtsev** [comment]
> After updating to Webmin 1.955 and AT 19.54 i now have this issue again:

What is the full output of `sensors` command?

**Comment by Sopor** [comment]
```
$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +37.0°C  (high = +78.0°C, crit = +100.0°C)
Core 1:       +38.0°C  (high = +78.0°C, crit = +100.0°C)

smsc47b397-isa-0480
Adapter: ISA adapter
fan1:        1974 RPM
fan2:           0 RPM
fan3:        1331 RPM
fan4:        1072 RPM
temp1:        +55.0°C
temp2:        +53.0°C
temp3:        +30.0°C
temp4:       -128.0°C
```

**Comment by iliarostovtsev** [comment]
What is this `smsc47b397-isa-0480` device?

**Comment by Sopor** [comment]
I have no idea but you will find it in HP computers. The fix you provided before worked. Why is it back now?

**Comment by iliarostovtsev** [comment]
> The fix you provided before worked. Why is it back now?

Because there are other fancy outputs to consider.

So, you only have two cores?

**Comment by Sopor** [comment]
Computer specs:
`HP Compaq dc7800p Small Form Factor`
`Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz`

**Comment by iliarostovtsev** [comment]
Okay, fixed.

You can update it by running:


~~~
curl https://raw.githubusercontent.com/webmin/webmin/master/proc/linux-lib.pl -o /usr/share/webmin/proc/linux-lib.pl
~~~

**Comment by Sopor** [comment]
Thanks!

And the update version that show the wrong version?

**Comment by iliarostovtsev** [comment]
> And the update version that show the wrong version?

Clear cache and try one more time:
![image](https://user-images.githubusercontent.com/4426533/91227968-1bdaec00-e730-11ea-9dfb-f2ae33980369.png)

**Comment by Sopor** [comment]
You're the best @iliarostovtsev  👍
