### ISSUE TITLE
Dashboard CPU, SSD, .. Temperature 

### ISSUE THREAD

**Issue by htttito** [authentic-theme/authentic-theme#1484]
Hi Ilia!

After update to 19.53 I can' t see the Temperatures (CPU, ... ) in the Dashboard.

System: Ubuntu 18.04
Webmin: 1.953
Theme: 19.53

Thanks :-)!
Regards Tito

**Comment by htttito** [comment]
Hi again....i think it's not an Theme problem...
Can you help, i think i have done something stupid...what is needed to show the temperatures?
By the way....how can i get a dashboard like the photo?! THANKS 
![33145442-717615fa-cfd1-11e7-9c6f-465f7056fe17](https://user-images.githubusercontent.com/40149753/87853860-093ded80-c90e-11ea-9c8f-46d9106386ca.png)

**Comment by jcameron** [comment]
What does the `sensors` command output on your system? That's what Webmin uses to get the underlying temperature data.

**Comment by htttito** [comment]
Hi!

sensors  are OK....

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +39.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +38.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +39.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +39.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +38.0°C  (high = +100.0°C, crit = +100.0°C)

**Comment by htttito** [comment]
Maybe....There was also a webmin update..???

**Comment by htttito** [comment]
The cpu is from sensors....
HDD and NVME...Are also not shown

**Comment by htttito** [comment]
I found the problem.....
![webmin](https://user-images.githubusercontent.com/40149753/87869365-82395580-c99f-11ea-9dc7-2b7c54888d9d.png)

**Comment by iliarostovtsev** [comment]
> By the way....how can i get a dashboard like the photo?! 

You cannnot. We have live stats that do more at them moment.

![image](https://user-images.githubusercontent.com/4426533/87871887-fa624400-c9bc-11ea-8e82-85f105732597.png)
