### ISSUE TITLE
Possible regression in v19.53?

### ISSUE THREAD

**Issue by redfive2012** [authentic-theme/authentic-theme#1485]
In the Custom Commands plugin under Other, the ability to use an external command to build the contents of a dropdown selector appears to be broken compared to the previous version. I have a number of custom commands that use external commands to build lists of files or devices to select from, and they all were working until I upgraded my installed theme to 19.53. Now, the dropdowns are empty, and I see no errors anywhere.

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the heads up.

Please provide a screenshot and zip up and attach the content of `/etc/webmin/custom` for me to be able to test this on my system.

**Comment by iliarostovtsev** [comment]
It all looks great for me.

![image](https://user-images.githubusercontent.com/4426533/88296727-ba29fb00-cd07-11ea-91c2-bb9e08508940.png)

**Comment by redfive2012** [comment]
![Annotation 2020-07-23 104443](https://user-images.githubusercontent.com/1361614/88300588-a5327500-ccd1-11ea-9e60-59f34a8c6c76.png)
The 3 dropdowns I've circled in red are built via commands, and they are terminated with a "|" character as the in-page help notes. I have 3 other dropdowns in the command list, with their contents manually specified. These are working fine.
![Annotation 2020-07-23 104656](https://user-images.githubusercontent.com/1361614/88300852-f3477880-ccd1-11ea-8ad1-bfa62c03476c.png)
This is one of the commands that is supposed to fill a dropdown. `ipset list -n |` is the exact string in the red circled area.
[webmin_help.zip](https://github.com/authentic-theme/authentic-theme/files/4966843/webmin_help.zip)
/etc/webmin/custom/ attached.

**Comment by iliarostovtsev** [comment]
I see this happening in old theme too, besides in Webmin 1.941 and 1.942 it's happening as well. When exactly did it break for you? What was the last version when it worked? 

None of the selects in your files worked for me. @jcameron Do you know what might be causing it?

**Comment by iliarostovtsev** [comment]
Actually, I made more tests and it seems to work just fine if select's text file exists with space separated **name value** pairs..

**Comment by redfive2012** [comment]
I think the previous Webmin version I had was 1.941, and there was a jump upgrade to 1.953. I don't remember seeing a problem until the Authentic theme upgraded to 19.53, but it's possible that the large Webmin version jump broke it.

In all 3 of the dropdowns that aren't working for me, I'm using commands to fill them rather than text files. The 3 that are working are populated from local text files, which I can send you if you want them. They simply have a couple of static directory names in them.

**Comment by iliarostovtsev** [comment]
Fixed, thanks for heads up.
