### ISSUE TITLE
Package updates are available - The following packages have been kept back

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1486]
On the dashboard it will show that i have 10 package available update,
![image](https://user-images.githubusercontent.com/5789283/88597647-fe026480-d067-11ea-98c0-562417bfe7ac.png)
but when i press on it, it will show that i don't have any. I then run it from a terminal prompt and i can see this:
```
The following packages have been kept back:
  ffmpeg libavcodec58 libavdevice58 libavfilter7 libavformat58 libavresample4 libavutil56 libpostproc55 libswresample3 libswscale5
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
```

If i can't update from Webmin they shouldn't be visible. At least some info about it.

**Comment by iliarostovtsev** [comment]
Hi,

This is not Authentic Theme issue, though I will take a look. The solution for this message to go away is to run `apt-get dist-upgrade`.

**Comment by JimTR** [comment]
sort of related .. is this a theme issue ?
<img src = "https://i.imgur.com/y3z5CFx.png"> or webmin ? as you can see top of the dash shows everything up to date but lower down I have updates

**Comment by iliarostovtsev** [comment]
> sort of related .. is this a theme issue ?

No, it's not theme issue!

> as you can see top of the dash shows everything up to date but lower down I have updates

It seems that the cache is not updated simultaneously. Do you still have it shown as such? What happens if you click refresh button at the top right of _System Information_ table header?

**Comment by JimTR** [comment]
Ok refresh button clears it, how I got this to appear was -
1. open notifications
2. click on update packages
3. do updates
4. click dash board from the left menu

**Comment by Sopor** [comment]
> Hi,
> 
> This is not Authentic Theme issue, though I will take a look. The solution for this message to go away is to run `apt-get dist-upgrade`.

Yes, i know how to fix it but it shouldn't show 10 updates when i can't see any in Webmin.

**Comment by iliarostovtsev** [comment]
Moved. https://github.com/webmin/webmin/issues/1285
