### ISSUE TITLE
Linux Firewall IPV4, can't see anything, not working

### ISSUE THREAD

**Issue by 7starsone** [authentic-theme/authentic-theme#1487]
Hello,
it seems that Linux Firewall doesn't work as before for IPV4
I can't see anything, while before all the rules were there as expected.

here the screenshot
![Image of linux firewall](https://img.imageupload.net/2020/07/29/linuxipv4.jpg)

thanks

**Comment by 7starsone** [comment]
Even if I click on Showing IPtable nothing happens and the same clicking on the dropdown, no errors on console

**Comment by iliarostovtsev** [comment]
Hi,

I wonder why it's submitted to theme repo?

Anyway - try applying [this patch](https://github.com/webmin/webmin/commit/3db98c7a2de21147753f2c28da9c39a6a9b84629).

**Comment by 7starsone** [comment]
Sorry for delay, yes, I confirm that patch works 😄 thanks
