### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by nurbles** [authentic-theme/authentic-theme#1488]
I have six Ubuntu 18.04.04 systems running Webmin 1.953 using Authentic 19.53.
I selected a different color for the navigation menu on each system to help me notice that I had switched tabs from one server to another.
Q1:  When I enabled Night Mode on all of the servers, the navigation menu colors were lost in favor of a uniform gray instead of just making the selected color darker, which I would prefer.  There does not appear to be a color selection for the night mode color, either.
Q2:  On only **one** of the six systems (all running with dark mode enabled) the initial log on screen for Webmin is also dark, while the other five are light.  I cannot find the setting for this, but I REALLY want to have them all start dark.

**Comment by iliarostovtsev** [comment]
Hi,

> Q1: When I enabled Night Mode on all of the servers, the navigation menu colors were lost in favor of a uniform gray instead of just making the selected color darker, which I would prefer. There does not appear to be a color selection for the night mode color, either.

This is all correct and designed to be like that.

> Q2: On only one of the six systems (all running with dark mode enabled) the initial log on screen for Webmin is also dark, while the other five are light. I cannot find the setting for this, but I REALLY want to have them all start dark.

What page are you exactly referring to? Could you provide a screenshot?

**Comment by nurbles** [comment]
re Q1: I figured it was designed like that, I am simply disappointed that I am not at least allowed to choose my night-mode colors like I can for day-mode.

re Q2: I clipped the image below (assuming I can figure out how to paste an image) from Firefox.  It shows the ONLY one (out of SIX) systems that has a night mode log on screen.

<img width="502" alt="NightLogin" src="https://user-images.githubusercontent.com/14079927/88932479-1fbc4100-d24c-11ea-8a70-6a84fd1b64c1.png">

This would definitely be my preference, but I have no idea how I selected it and couldn't find the setting when I tried.  All I did was to click the night-mode button on the navigation bar for all six machines and one gives me a night mode logon prompt, too.  Hopefully I can get them all to do that.

**Comment by iliarostovtsev** [comment]
> re Q2: I clipped the image below (assuming I can figure out how to paste an image) from Firefox. It shows the ONLY one (out of SIX) systems that has a night mode log on screen.

It looks that it was auto-completed and that's why the color is darker.

There are theme extensions and one of them is CSS extension (can be found from theme configuration page). You can always make theme look different by creating own custom changes.

Additionally, you could create HTML snippet (theme configuration page) for navigation page to distinguish the servers:

![image](https://user-images.githubusercontent.com/4426533/88943342-0343f700-d294-11ea-81bd-a03cdea5302b.png)

**Comment by nurbles** [comment]
All six screens are auto-completed.  Five are white, one is dark.  Also, FWIW, I open all six at the 'same time' by choosing Firefox's "Open all in tabs" for the set of bookmarks to my six servers.  The dark one is the 3rd tab, for whatever reason it is happening.  I wish it WAS auto-complete because then I would have never asked about it and it would already be working.

Thanks for the HTML snippet part.  I think an extension is beyond me (CSS is very much a foreign language for me!)

**Comment by bstramsek** [comment]
If still relevant 😃

The login screen reflects what theme mode is selected with root user. I don't know why - but - if you login to root user account, change the mode to night theme and logout > the logon screen will stay in dark mode.

Now just use any other user and the login screen should stay in dark mode.

**Comment by iliarostovtsev** [comment]
> The login screen reflects what theme mode is selected with root user. I don't know why - but - if you login to root user account, change the mode to night theme and logout > the logon screen will stay in dark mode.

That is expected. Shouldn't that be working that way? If not, how do you expect a root user to control login screen palette? With an option?

**Comment by nurbles** [comment]
Given the general aversion to logging in as "root", I find the idea that I must login as the root user to change something, um, unexpected.  Understandable, perhaps, but unexpected.  Instead, if the logged in user can get root access, they should be allowed to change global (for want of a better term) settings.  That's just my opinion, but I feel it is what would make the most sense for users who are more of a part-time administrator than a system guru.

**Comment by iliarostovtsev** [comment]
> Instead, if the logged in user can get root access, they should be allowed to change global (for want of a better term) settings

I think that a regular user **must not** have a control over what other user options are like. The best way we can do, as I see it at the moment, is to make it out into a separate option. At the same time, we already have too many options. Perhaps, an option or two could be dropped in favor of adding this one. Will see..

**Comment by nurbles** [comment]
Personally, I consider a user with root access to be effectively the same the the root user.  After all, they can get root access and then do anything root can do.  So why not see if they can get root access and then change the day/night mode of the login screen if they have it?  If everyone on a system has root access, I suspect that system has more important problems than who can set day/night mode!

**Comment by iliarostovtsev** [comment]
Okay, once again please - how do we actually know if it's a root capable user or not **before** logging in?

**Comment by nurbles** [comment]
I thought we were talking about changing a setting?  Doesn't that only happen when logged in?  How did it "know" I was going to log in as root and display the login dark?  I'm confused.

**Comment by iliarostovtsev** [comment]
An option that affects a palette for login page, must only be controlled by root capable user.

**Comment by nurbles** [comment]
Yes!  That's what I've been saying (or at least trying to say, quite ineffectively, apparently.)  It is not how it works right now, though.  Only the one system where I have a root account enabled was able to change the login screen to night mode.  But I login with my root-capable user on the other five.

**Comment by bstramsek** [comment]
This is a setting you only make once... I do know it's frustrating if you don't know why the night theme login doesn't stick - but - if you only need to do this once and then you are always greeted by the night mode login screen - I see no grand problem here.

At start you only have the root login (which you should disable later on anyways), so just one single action to change the theme mode while still logged in as root seems totally fine and acceptable (at least to me).

So yeah a nice setting to have - but not really to have the boolean option for night mode - more like to be able to select the "shade of gray" you want to have while in night mode.

**Comment by nurbles** [comment]
This will be my last comment.  Others will decide.

When I did a clean install of Ubuntu server back in March (to set up VPN office access for working at home) the installer never asks for nor sets a root password. This means that the root account does not work right from installation. It does, however, ask for a user account/password and that user can sudo to perform root tasks.  So I am hearing that we much enable the root account to configure webmin and then disable it again when we are through because a root-enabled user cannot do **ONE** thing that only the user _named_ root can do.  That makes no sense to me.  But hey, I don't write this product, so you folks decide.  I'm just a user and I must live with what I get (I was trained as a Microsoft customer, so I'm used to it.)

**Comment by iliarostovtsev** [comment]
Okay, next release will have an option to enforce color palette for login page, which will no loner be connected with user settings.
![image](https://user-images.githubusercontent.com/4426533/90260851-cdd30800-de54-11ea-8b9c-88daa915e8ec.png)

**Comment by iliarostovtsev** [comment]
There was a bug in yesterday's patch - here is the fix. https://github.com/authentic-theme/authentic-theme/commit/7bc36f04ee6ef6fca8edce0e4c2681b687c60fa7
