### ISSUE TITLE
Enable real-time monitoring? No.

### ISSUE THREAD

**Issue by 7starsone** [authentic-theme/authentic-theme#1489]
Hello,
I would like to get explanations about `Enable real-time monitoring`

I set to **No**. Even restarted Webmin.

On process list
`/usr/libexec/webmin/authentic-theme/stats.cgi` constantly comes and goes, consuming CPU %.

What does that stats.cgi, please? Is it needed or can be disabled anyway?
Thanks

**Comment by iliarostovtsev** [comment]
> What does that _stats.cgi_, please? Is it needed or can be disabled anyway?

Absolutely, disabling real-time monitoring will call shutdown action on querying _stats.cgi_. It should happen without complete page reload and triggered immediately when set to _No_ and theme settings are saved with green _Save_ button. If that didn't work for some reason - full page reload will help.

Are you sure that you're saving theme configuration? Webmin restart is not needed.

**Comment by 7starsone** [comment]
so, the problem was I had 3 open browser tabs about Webmin and you're right, a reload is enough. Thanks for your help, really appreciated 😄

**Comment by iliarostovtsev** [comment]
Yes, having multiple tabs opened with enabled live stats is the main source getting high server load.
