### ISSUE TITLE
File Manager - highlighted text on search

### ISSUE THREAD

**Issue by 7starsone** [authentic-theme/authentic-theme#1490]
Hello,
my issue with the File editor is highlighted text color when I search.
it's a color that does not have adequate contrast. I would keep something like red background with white text, in order to do a good contrast and a quick view of the match, something like that. At the moment, often I can't see in rapid manner where is the matched text.

Thanks

**Comment by iliarostovtsev** [comment]
Hi,

Yes, this can be improved.

**Comment by iliarostovtsev** [comment]
There, it will look like this with the latest changes. Give it a try.

![image](https://user-images.githubusercontent.com/4426533/90312395-d5ee7e80-df0c-11ea-927f-baa8e6506b4c.png)


![image](https://user-images.githubusercontent.com/4426533/90311771-7346b400-df07-11ea-82f3-c517fe44c097.png)
