### ISSUE TITLE
Theme / form issue on Edit Databases ->  Passwords with both Mysql & Postgre Enabled installed version 19.54

### ISSUE THREAD

**Issue by abclution** [authentic-theme/authentic-theme#1495]
See image.

Password fields and icons are jumbled.

![image](https://user-images.githubusercontent.com/10130237/94430097-08da9200-019c-11eb-8d6c-1fd84b4df2cc.png)

Tried clearing cache, no luck.
Still trying to figure out how to upgrade to beta versions (I too like to live dangerously!)

**Comment by iliarostovtsev** [comment]
Hi,

What Virtualmin version is used under the hood?

**Comment by abclution** [comment]
Webmin version | 1.955 | Usermin version | 1.803
-- | -- | -- | --
Virtualmin version | 6.12

**Comment by iliarostovtsev** [comment]
I just made a patch. It should address PostgreSQL database password change field width. However, I never seen an issue you're reporting.

> Still trying to figure out how to upgrade to beta versions (I too like to live dangerously!)

Go to Theme Configuration, and click update button at the bottom.


![image](https://user-images.githubusercontent.com/4426533/94432755-e480b480-019f-11eb-909a-af866765ef1b.png)

**Comment by abclution** [comment]
Ok, updated to the dev version, looks  pretty close to perfect..

![image](https://user-images.githubusercontent.com/10130237/94433196-9cae5d00-01a0-11eb-8292-a338723dbc6a.png)



![image](https://user-images.githubusercontent.com/10130237/94433241-b059c380-01a0-11eb-8549-4f897405effb.png)

Actually as I look closer, each row has repeated icons for show password button for Mysql & Postgresql.
Probably only want the Mysql button for the mysql row, and the same for PG
This is probably not intended.

![image](https://user-images.githubusercontent.com/10130237/94433537-20684980-01a1-11eb-82f9-637765bc45f4.png)

**Comment by iliarostovtsev** [comment]
Could you try `/etc/webmin/restart`, reload the page and see if it still happens after restart?

If it's still an issue, could you send me using my website, a download link  for `/etc/webmin/virtual-server/config` file?

**Comment by abclution** [comment]
No luck. Trying to send you a link to the config, but uh.. your captcha on your form is .. extremely difficult?

I cannot get passed the captcha. F*ck me, am I a robot?

![image](https://user-images.githubusercontent.com/10130237/94437127-00875480-01a6-11eb-87bb-89d8f314bd34.png)


![image](https://user-images.githubusercontent.com/10130237/94437146-0a10bc80-01a6-11eb-9442-aaf5abef7b89.png)

**Comment by abclution** [comment]
Ok, well, I anonymized it and put it here:

https://pastebin.ubuntu.com/p/WVKTdx9BNH/

**Comment by iliarostovtsev** [comment]
I had to make captcha hard.l, sorry, as surprisingly, in 2020 people still expect that spam works.

Speaking about the issue - I forgot to ask you, if you could try other browser or incognito (private) tab (with disabled extensions). It's possible that extensions could cause this issue.

**Comment by iliarostovtsev** [comment]
Okay, reproduced it with custom passwords set.

**Comment by iliarostovtsev** [comment]
Thanks for reporting! Fixed.

**Comment by abclution** [comment]
> I had to make captcha hard.l, sorry, as surprisingly, in 2020 people still expect that spam works.
> 
> Speaking about the issue - I forgot to ask you, if you could try other browser or incognito (private) tab (with disabled extensions). It's possible that extensions could cause this issue.

Sorry for not replying! For some reason my github email notifications went  to space!
