### ISSUE TITLE
Read User Mail orientation

### ISSUE THREAD

**Issue by regs01** [authentic-theme/authentic-theme#1496]
Is it possible to make Read User Mail vertically sorted, instead of horizontally?

**Comment by iliarostovtsev** [comment]
Hi,

What do you mean by "vertically sorted" there?

**Comment by regs01** [comment]
By column
```
a   e   i
b   f   j
c   g   k
d   h   l

```



Instead of
```
a   b   c
d   e   f
g   h  i
j   k   l
```

**Comment by iliarostovtsev** [comment]
Are you talking about user list sorting at initial page or mail sorting for particular user? Could you provide a screenshot to which page you're referring to?

**Comment by regs01** [comment]
Yes, user list

**Comment by iliarostovtsev** [comment]
We have various display options for user list:

![image](https://user-images.githubusercontent.com/4426533/95121547-dc081b00-0757-11eb-9c58-df89a0dfdf9b.png)


I think the best for you would be is to use **User display mode** set to **Full details**.

**Comment by regs01** [comment]
This looks to be fine

**Comment by iliarostovtsev** [comment]
Yes, good point - added it! Pull the latest development theme version, force reload browser's cache and you got it.

**Comment by regs01** [comment]
Working, thanks)
