### ISSUE TITLE
Turn off xnavigation=1

### ISSUE THREAD

**Issue by lightninglu10** [authentic-theme/authentic-theme#1497]
Hey all, is there anyway to turn off xnavigation=1 in the query params?

We're trying to push query params into our webmin based app, and using the authentic theme, but when we do so we get an error. It seems to have to do with xnavigation=1 always being pushed into the url. Is there anyway to turn this off?

**Comment by iliarostovtsev** [comment]
Hi,

What error do you get?

**Comment by lightninglu10** [comment]
Hey @iliarostovtsev , I'm getting a 404 error:

<img width="1399" alt="Screen Shot 2020-10-12 at 3 51 33 PM" src="https://user-images.githubusercontent.com/2453737/95796863-d30cd180-0ca2-11eb-9b29-8e48292e88b5.png">

I'm being pushed to http://localhost:10000/xerror?xnavigation=1

When I try to visit: http://localhost:10000/packs/?xnavigation=1&hello=goodbye

(packs is my own created module)

**Comment by iliarostovtsev** [comment]
1. What error do you get on the browser's console
2. What "packs" exactly?
3. What output does it produce when opened using Gray Theme

Could you attach your module so I could have a look?

**Comment by iliarostovtsev** [comment]
Any update on this?
