### ISSUE TITLE
Is it possible to pre-install Google Authenticator Perl script?

### ISSUE THREAD

**Issue by kimfull** [authentic-theme/authentic-theme#1498]
Google Authenticator  is an important step for login security,
But every time you still have to install the relevant perl to work.

**Comment by swelljoe** [comment]
This isn't a theme question is it? 2FA is part of Webmin. Surely no authentication related stuff is in the theme?

**Comment by iliarostovtsev** [comment]
..surely not the theme issue! It's available as a separate, installable Perl package on Ubuntu, Debian and Fedora. Besides, those are automatically installed with Virtualmin _install.sh_ script. However, it has to be installed using Cpan on CentOS in few easy steps.

**Comment by swelljoe** [comment]
Wait, you mean, it installs from CPAN on CentOS? That's bad. What package is it, I'll add it to the virtualmin repo.

**Comment by iliarostovtsev** [comment]
> Wait, you mean, it installs from CPAN on CentOS? 

Yes, it has always been like that for CentOS. Fedora has it as `perl-Authen-OATH` and Debian/Ubuntu has it as `libauthen-oath-perl`. The native Perl module name is `Authen::OATH`.

However, there is no problem on CentOS to install it from CPAN. Webmin has a link _click here to install_, and it builds/installs it in no time, without any problem.

**Comment by swelljoe** [comment]
That *is* a problem. Let me know when there are commonly used modules like that if they aren't available in any repo we setup during Virtualmin install.

**Comment by iliarostovtsev** [comment]
Okay, _Authen::OATH_ for CentOS. :slightly_smiling_face:

**Comment by jcameron** [comment]
Note that if Webmin offers to install a Perl module, it will prefer to use the distro-provided package if one is available. Only if missing will it fall back to downloading and compiling it from CPAN.

**Comment by pixel-paul** [comment]
I have tried to install 2FA on a CentOS 8.2 server, with only Webmin 1.960 installed and this fails either after 'Continue with Install' or after several steps of 'Fetching Prerequistes', ending with lots of 'install failed'.

![Screenshot_2020-11-05 Perl Modules Install Module — Webmin 1 960 on dns2 (CentOS Linux 8 2 2004)](https://user-images.githubusercontent.com/389303/98246342-1852b500-1f6a-11eb-9514-e2ec02cc8ff2.png)

**Comment by iliarostovtsev** [comment]
@jcameron Jamie, what is resolving deps here? It's not entirely correct.

The workaround here is to first install deps:

~~~
dnf install perl-Digest-SHA1 perl-Digest-HMAC perl-Moo perl-Test perl-Test perl-Authen-SASL perl-Math-BigInt perl-Test-Needs perl-Type-Tiny
~~~

.. and then just click **Continue With Install** button and it will work ..

**Comment by swelljoe** [comment]
This is why installing from CPAN is bad. Mix-and-match between CPAN and OS-provided packages can lead to some disastrously complicated breakages (sometimes breaking things unrelated to what you were installing). It's really pretty dangerous to be so cavalier about installing CPAN packages into the OS-provided Perl (it is easy to fix if you understand where CPAN installs stuff, but it is not at all easy to understand by users unfamiliar with Perl and its library overlay system).

It's just one more thing that is 100% guaranteed to generate avoidable support requests. I'll add this package to our repos when I get a few minutes of free time.

**Comment by iliarostovtsev** [comment]
> This is why installing from CPAN is bad. 

Okay, Joe, thank you! We will leave it up to you to build a package for CentOSs  then. I will close this as theme unrelated.

**Comment by jcameron** [comment]
Should we consider not auto-installing Perl modules from source at all in Webmin?

**Comment by swelljoe** [comment]
It's a neat feature, but if we want to reduce support load it's an obvious feature that produces support requests, including the potential to produce some very time-consuming ones. My policy in the past has been to just make sure Webmin never has reason to install from CPAN, by making sure the Virtualmin installer pre-installs everything (from RPM or deb packages) it needs for normal Virtualmin operation. But, I didn't really notice this was missing for some distros and didn't add it to the dependencies in the virtualmin stack packages. I'll try to wrap that up soon, so this particular case doesn't happen anymore.
