### ISSUE TITLE
Real-time monitoring options

### ISSUE THREAD

**Issue by JimTR** [authentic-theme/authentic-theme#1500]
Real-time monitoring options has been causing a server crash through running out of resource, it appears to be switched on by default, perhaps the default should be the other way around or perhaps work out if the server is capable .. no worries for me now I just switched it off

**Comment by iliarostovtsev** [comment]
What are the server specs?

**Comment by JimTR** [comment]
<img src="https://i.imgur.com/qPXGkIO.png" />

**Comment by iliarostovtsev** [comment]
@jcameron Perhaps, we should add an extra post-wizard step in Virtualmin, to configure basics for the theme, including this option?

**Comment by jcameron** [comment]
Yes, I think a choice to turn off real-time monitoring in the wizard would be useful. Or maybe something on the dashboard UI itself?

**Comment by iliarostovtsev** [comment]
Like ability to disable it from the Dashboard? Possible. Or maybe move an option to system status module in addition? But that, I'm afraid, no one ever going to find this out..

I see it the best to be a part of post install wizard, including choosing other theme options, like navigation menu color.

**Comment by jcameron** [comment]
I actually like having it on the dashboard, ideally close to the graphs that are being updated in realtime, as that's more obvious to the user.

**Comment by iliarostovtsev** [comment]
Good point - will do for 19.70.

**Comment by iliarostovtsev** [comment]
These issue no longer be caused in upcoming 19.71 
release.
