### ISSUE TITLE
Cron Job UI issue

### ISSUE THREAD

**Issue by chrisCAD** [authentic-theme/authentic-theme#1501]
Would it be possible to add an extra line in on the selection boxes for Minutes and Hours etc... on the cron job screen as at present it shows hours 1 - 10  and 12 -22 so hours 11 and 23 are hidden and you have to scroll - this meant some hours where missed off on a few scheduled jobs.

Cheers
Chris

**Comment by iliarostovtsev** [comment]
Hi, Chris!

Thanks for the heads up. It's been fixed on the latest commit. Give it a try.

**Comment by chrisCAD** [comment]
Hi Ilia,

I’ve installed 19.63-beta1-5 from the interface but it’s still the same. Have I applied the correct version?

Kind Regards
Chris

**Comment by iliarostovtsev** [comment]
Chris, can you please show me a screenshot and what is still wrong?

Did you try incognito tab? Perhaps stuck browser's cache issue?

**Comment by chrisCAD** [comment]
Hi Ilia,

The screen grab show the columns with issues highlighted in yellow its basically missing one row off on safari but it’s fine in chrome.

I tried incognito tab and cleared my browsers caches.

Hope this helps, I’m using Safari 14.0.1 (My colleagues also on safari of different version see the same issue)

Kind  Regards
Chris

**Comment by chrisCAD** [comment]
Hi Again,

I found changing the css  min-height to 235px then works on safari and chrome.

select[multiple][size='12'].ui_select, select[multiple][size='12'] {

  1.      min-height: 235px !important;
}

Kind Regards
Chris

**Comment by iliarostovtsev** [comment]
Okay, I have checked it in my Safari 14 browser and witnessed the same issue. It's fixed now.

Give it a try now.

Thanks!

**Comment by chrisCAD** [comment]
Hi Ilia,

That’s working fine now on both browsers, Thanks for looking at this.

Kind Regards
Chris

**Comment by iliarostovtsev** [comment]
You're welcome.
