### ISSUE TITLE
Theme/Mail: Quotes in signature creates issues in Send Mail HTML

### ISSUE THREAD

**Issue by kadai** [authentic-theme/authentic-theme#1502]
Greetings,

I have recently discovered that, when using the Theme on the Usermin interface, an issue can happen when the user has quotes in its signature. This causes the HTML to be broken and the users are unable to send mails.

Please see the image on details of what happens:
![image](https://user-images.githubusercontent.com/1930055/101110504-18fd5c00-35a7-11eb-8300-82b79a0f5302.png)

I am using Usermin version 1.812 and Authentic theme version 19.62.

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the heads up.

That was an escaping issue. It's fixed with the latest commit.
