### ISSUE TITLE
Login page color palette problem?

### ISSUE THREAD

**Issue by FBachofner** [authentic-theme/authentic-theme#1505]
Hi @rostovtsev

I have set "Login page color palette" to "dark" but the login page still shows up "light"   This is counter to my expectation.  Is this a bug or is some other page supposed to be affected.

Also, an enhancement idea:

It might be really cool to "push" the navigation bar color to the "sign in" button on the login page.  This would give a quick visual confirmation that one has connected to the correct server (when one deals with many servers, each having custom navigation bar colors to help distinguish them).

Thanks for your consideration Ilia !

**Comment by iliarostovtsev** [comment]
Fixed. I am not sure how I missed that in the first place. Thanks.

> It might be really cool to "push" the navigation bar color to the "sign in" button on the login page.

That unfortunately is not possible, as it will break consistency. But you can do it for each server individually by using **Theme Extensions > CSS**.
