### ISSUE TITLE
Need to save the settings to see the correct output example language

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1512]
If i hover the mouse over the `Full format` is doesn't matter what i set the `Locale language` to, it will still show the output example in the language it was when i first opened the page.

![image](https://user-images.githubusercontent.com/5789283/104028915-95e4ac80-51c9-11eb-8868-ebfc5d94f811.png)

I changed the language from Afrikaans to English (you can't see that because it is behind the example dialog), but as you can see it will not change language. To see the output example i'm forced to save the page and reopen it to see the selected language.

Btw, i have no idea why it is set to Afrikaans, but it will show the correct date on the dashboard.

![image](https://user-images.githubusercontent.com/5789283/104030247-6171f000-51cb-11eb-9378-cd0566e5f0dd.png)

Dashboard
![image](https://user-images.githubusercontent.com/5789283/104030261-68006780-51cb-11eb-98ac-c2ade270a628.png)

Webmin 19.70
Authentic theme 19.70
Firefox 84

**Comment by Sopor** [comment]
Update: It seems that i need to press on the page before the output example language will change.

Another thing i noticed was that I need to press twice on the language dropdown menu for it to expand.

**Comment by jcameron** [comment]
@iliarostovtsev this looks like part of the UI that the theme controls?

**Comment by iliarostovtsev** [comment]
> @iliarostovtsev this looks like part of the UI that the theme controls?

Yes, Jamie.

> Update: It seems that i need to press on the page before the output example language will change.

Yes, at the moment but this will be fixed for 19.71. I have just improved it -- you can install latest development version of the theme to give it a try now. I hope you'll like it.

Thanks for reporting such little things, as I also believe that those little things make overall UX great.
