### ISSUE TITLE
19.70 sysstats get_raw authenntic.pl 44

### ISSUE THREAD

**Issue by pepper454** [authentic-theme/authentic-theme#1513]
after upgrade to 19.70
/sysstats/
Undefined subroutine &WebminCore::get_raw called at /usr/share/webmin/authentic-theme/authentic.pl line 44

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the heads up.

It's [being discussed](https://forum.virtualmin.com/t/error-perl-execution-failed-undefined-subroutine-main-authentic-called-at-usr-share-webmin-authentic-theme-index-cgi-line-12/108864/23?u=ilia).

Does it only happen with **History System Status** module? If so, check this [thread out](https://sourceforge.net/p/webadmin/bugs/5441/).

**Comment by pepper454** [comment]
yes only historic system statistics module, thank you. I was doing stuff with perl modules the other day which was out of the ordinary. linked discussion makes sense.

**Comment by iliarostovtsev** [comment]
Okay, this issue has been reproduced and [fixed](https://github.com/webmin/webmin/commit/4fef82323e90bec7e917fd57ab960f56ddaec374). 

It was tricky to find out the cause, as it only affected  logins with **sudo-capable** users.

Webmin 1.971 will have it fixed. Meanwhile, you can manually apply the patch and restart Webmin.
