### ISSUE TITLE
You warned me, but I didn't listen. Cannot access Webmin Panel now.

### ISSUE THREAD

**Issue by sz00gun** [authentic-theme/authentic-theme#1514]
Everything worked as a charm today, till I updated Virtualmin theme by pressing **Force update** the latest Stable version. 

My version was 19.62 and I updated to 19.70. I received a _message on the bottom saying there a conflict or something_, but if I really need to do it, just press a link in that warning. So I have done it.

I have (as far I remember):
Webmin: 1.962
Usermin: 1.812
Virtualmin: 6.14
Linux Ubuntu: 18.04.05

After that I get an error, with a login session: 
**Error - Perl execution failed
Undefined subroutine &main::authentic called at /usr/share/webmin/authentic-theme/index.cgi line 12.** 

With a fresh Internet Browser session:
**Error - Perl execution failed
Undefined subroutine &main::get_miniserv_config called at /usr/share/webmin/authentic-theme/session_login.cgi line 15.**

miniserv.conf

> port=12190
> addtype_cgi=internal/cgi
> realm=Webmin Server
> logfile=/var/webmin/miniserv.log
> errorlog=/var/webmin/miniserv.error
> pidfile=/var/webmin/miniserv.pid
> logtime=168
> ssl=1
> no_ssl2=1
> no_ssl3=1
> no_tls1=1
> no_tls1_1=1
> ssl_honorcipherorder=1
> no_sslcompression=1
> env_WEBMIN_CONFIG=/etc/webmin
> env_WEBMIN_VAR=/var/webmin
> atboot=1
> logout=/etc/webmin/logout-flag
> listen=12190
> denyfile=\.pl$
> log=1
> blockhost_failures=5
> blockhost_time=60
> syslog=1
> ipv6=1
> session=1
> userfile=/etc/webmin/miniserv.users
> keyfile=/etc/webmin/letsencrypt-key.pem
> passwd_file=/etc/shadow
> passwd_uindex=0
> passwd_pindex=1
> passwd_cindex=2
> passwd_mindex=4
> passwd_mode=0
> preroot=authentic-theme
> passdelay=1
> cipher_list_def=1
> failed_script=/etc/webmin/failed.pl
> logout_script=/etc/webmin/logout.pl
> login_script=/etc/webmin/login.pl
> sudo=1
> sessiononly=/virtual-server/remote.cgi
> preload=virtual-server=virtual-server/virtual-server-lib-funcs.pl virtual-server=virtual-server/feature-unix.pl virtual-server=virtual-server/feature-dir.pl virtual-server=virtual-server/feature-dns.pl virtual-server=virtual-server/feature-mail.pl virtual-server=virtual-server/feature-web.pl virtual-server=virtual-server/feature-webalizer.pl virtual-server=virtual-server/feature-ssl.pl virtual-server=virtual-server/feature-logrotate.pl virtual-server=virtual-server/feature-mysql.pl virtual-server=virtual-server/feature-postgres.pl virtual-server=virtual-server/feature-ftp.pl virtual-server=virtual-server/feature-spam.pl virtual-server=virtual-server/feature-virus.pl virtual-server=virtual-server/feature-webmin.pl virtual-server=virtual-server/feature-virt.pl virtual-server=virtual-server/feature-virt6.pl
> ssl_cipher_list=ECDHE-RSA-AES256-SHA384:AES256-SHA256:AES256-SHA256:RC4:HIGH:MEDIUM:+TLSv1:+TLSv1.1:+TLSv1.2:!MD5:!ADH:!aNULL:!eNULL:!NULL:!DH:!ADH:!EDH:!AESGCM
> nolog=\/stats\.cgi\?xhr\-stats\=general
> premodules=WebminCore
> error_handler_401=401.cgi
> error_handler_404=404.cgi
> error_handler_403=403.cgi
> no_resolv_myname=0
> sockets=
> ipkey_website.com,*.website.com=/home/website/ssl.key
> ipcert_website.com,*.website.com=/home/website/ssl.cert
> logouttimes=
> expires_paths=
> gzip=1
> nolistdir=
> noshowstderr=
> certfile=/etc/webmin/letsencrypt-cert.pem
> extracas=/etc/webmin/letsencrypt-ca.pem
> ipcert_193.xxx.xxx.x,website.com.co.uk,*.website.com.co.uk=/home/website.com/ssl.cert
> perllib=
> utmp=
> logouttime=
> session_ip=
> no_pam=0
> pam_conv=
> blockuser_failures=
> blocklock=
> blockuser_time=
> pam_end=
> precache=
> ipextracas_193.70.xxx.xxx,aaa.co.uk,*.aaa.co.uk=/home/website.com/domains/aaa.co.uk/ssl.ca
> root=/usr/share/webmin
> mimetypes=/usr/share/webmin/mime.types
> server=MiniServ/1.962
> alwaysresolve=0
> trust_real_ip=0
> libwrap=0
> 

config

> 
> noremember=
> passwd_uindex=0
> notabs_website=1
> passwd_cindex=2
> webprefix=
> passwd_pindex=1
> error_stack=0
> referers_none=1
> os_type=debian-linux
> passwd_mindex=4
> nohostname=0
> sclass=
> nomoduleup=
> realname_redditch=
> notabs_redditch=1
> product=webmin
> notabs=0
> tempdirdelete=1
> notabs_idd=1
> chattr=0
> nowebminup=
> relative_redir=0
> realname_website=
> ownmods_chowart=bind8 mysql apache virtual-server filemin passwd proc cron at telnet change-user htaccess-htpasswd mailboxes syslog phpini
> theme=authentic-theme
> md5pass=2
> realname_chowart=
> cache_size=52428800
> readonly_chowart=virtual-server
> ownmods_website=bind8 mysql apache virtual-server filemin passwd proc cron at telnet change-user htaccess-htpasswd mailboxes syslog phpini
> sprio=
> log=1
> logfiles=1
> path=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
> ownmods_redditch=bind8 mysql apache virtual-server filemin passwd proc cron at telnet change-user htaccess-htpasswd mailboxes syslog phpini
> real_os_version=18.04.5
> ld_env=LD_LIBRARY_PATH
> gotomodule=
> ownmods_idd=bind8 mysql apache virtual-server filemin passwd proc cron at telnet change-user htaccess-htpasswd mailboxes syslog phpini
> readonly_website=virtual-server
> cache_mods=virtual-server
> gotoone=0
> lang=en.UTF-8
> readonly_redditch=virtual-server
> passwd_file=/etc/shadow
> ld_path=
> notabs_chowart=1
> find_pid_command=ps auwwwx | grep NAME | grep -v grep | awk '{ print $2 }'
> realname=
> tempdelete_days=1
> syspath=
> real_os_type=Ubuntu Linux
> by_view=0
> os_version=9.0
> deftab=webmin
> readonly_idd=virtual-server
> realname_idd=
> mobile_theme=authentic-theme
> 

Please advise, restarts don't help. Thanks

**Comment by iliarostovtsev** [comment]
Hi,

Theme version 19.70 is meant to be installed only for Webmin 1.970+. You shouldn't ignore warning messages upon upgrading the theme.

You can easily downgrade to Webmin 1.962 using `apt-get` command or downgrade the theme to 19.62 by using `theme-update.sh -release:19.62` command.

Alternatively you could install Webmin 1.971 devel version:

~~~
wget https://download.webmin.com/devel/deb/webmin_current.deb
apt-get install ./webmin_current.deb
~~~

**Comment by sz00gun** [comment]
Works. thanks.
