### ISSUE TITLE
Sidebar's bottom image is above text

### ISSUE THREAD

**Issue by alessandrofrancesconi** [authentic-theme/authentic-theme#1515]
I've noticed that my custom image appears to be above the sidebar text. Seems more an issue than a feature.
Text is clickable, anyway.
![image](https://user-images.githubusercontent.com/1595223/105628946-544a3780-5e40-11eb-8004-416e20991c10.png)

**Comment by iliarostovtsev** [comment]
Hi,

> Seems more an issue than a feature.

Well, it's certainly a feature for me! 🙂  &nbsp; It happens due to borders alpha transparency. I like it this way, sorry.

> Text is clickable, anyway.

That what matters.

Thanks for the heads up, Alessandro!
