### ISSUE TITLE
Perl execution failed

### ISSUE THREAD

**Issue by Perzegone** [authentic-theme/authentic-theme#1517]
Hello Guys,

I have just updated the authentic-theme to 19.71 and after this, I am keep getting the following error in File Manager and it does not show the contect I want to check, just loading:

Error:  500 - Perl execution failed – Undefined subroutine &extensions::get_acls_status called

Webmin version: 1.970

Thanks.

**Comment by iliarostovtsev** [comment]
Authentic Theme 19.71 is made for unreleased Webmin 1.972. There was a big red banner warning you about it.

You could go to theme's directory and run:

~~~
./theme-update.sh -release:19.70
~~~
