### ISSUE TITLE
Theme Extensions Gone?

### ISSUE THREAD

**Issue by DavidGhedini** [authentic-theme/authentic-theme#1519]
Hi -
On Webmin 1.973 there is no longer an option to add Theme Extensions of custom logos.
Has this option been removed?
Thanks,
David

**Comment by iliarostovtsev** [comment]
Hi,

> Has this option been removed?

I don't think so. 

Where are you checking for this feature?

**Comment by iliarostovtsev** [comment]
I think you should have a look at [this thread](https://forum.virtualmin.com/t/webmin-edit-theme/109736/2). It explains it.
