### ISSUE TITLE
Auth theme 19.71 - 19.73, error 500, Type of arg 1 to keys.......

### ISSUE THREAD

**Issue by arminba** [authentic-theme/authentic-theme#1520]
CentOS 6.10 (EoL)
Webmin 1.973
Virtaulmin 6.14/6.15
Authentic theme 19.73 (same problem present in the v19.71, v19.72)
Perl v. 5.10.1
No problems are present in the version 19.70.

After clicking on the "Configurable options for authentic theme" :
![panel](https://user-images.githubusercontent.com/36296191/111316189-5459fd00-8663-11eb-96ec-aaf36413276d.png)
![panel1](https://user-images.githubusercontent.com/36296191/111316331-75bae900-8663-11eb-84e4-42cdb6cb0446.png)

Thanks
Armin

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the heads up. This should fix it - https://github.com/authentic-theme/authentic-theme/commit/bfd5d37512434584d605d2c3a7e4c6a1e2f36c0c
