### ISSUE TITLE
First login really slow dashboard load time

### ISSUE THREAD

**Issue by 7starsone** [authentic-theme/authentic-theme#1522]
Hello,
if you do a first login after a while (don't know the exact time),
the load times for dashboard are excessive, even more than 30 sec, 1 minute and so on,
even on private browsing (no browser plugins etc.).

While If I sign out and then sign in again, it takes 3-5 seconds to load the dashboard.

So, is it a cache issue? How you exactly manage the cache, in order to avoid this issue?
thanks for your help

**Comment by iliarostovtsev** [comment]
Hi,

> How you exactly manage the cache, in order to avoid this issue?

For the initial Dashboard load only a cache provided by Webmin is used.

> Is it a cache issue?

Yes.

**Comment by 7starsone** [comment]
> 
> 
> Hi,
> 
> > How you exactly manage the cache, in order to avoid this issue?
> 
> For the initial Dashboard load only a cache provided by Webmin is used.
> 
> > Is it a cache issue?
> 
> Yes.

ok, and is it possible to set in some way? Where's this Webmin cache stored and set? Thanks

**Comment by iliarostovtsev** [comment]
**Webmin ⇾ Webmin Configuration: Background Status Collection**:

![image](https://user-images.githubusercontent.com/4426533/111978235-c3789b00-8b14-11eb-8106-bfc4ec949d86.png)

**Comment by 7starsone** [comment]
Ok, so, put the case I want a long life cache, one week: I could set 10080 minutes and then, If I need, I would do a manual refresh on the dashboard? Is it working that way? Thanks

**Comment by iliarostovtsev** [comment]
Was Webmin running all that time you weren't there?

**Comment by 7starsone** [comment]
> Was Webmin running all that time you weren't there?

Isn't Wembin service always running? I'm not sure to understand what you mean...

**Comment by iliarostovtsev** [comment]
>  I'm not sure to understand what you mean...

What is the main goal of asking at the first place then? What are you trying to achieve? If you want to report any bug --  _just do it_.

I am busy right now re-working the theme.

**Comment by 7starsone** [comment]
That's what I wrote at first. To avoid waiting so long the first time you login in a week (example).

**Comment by iliarostovtsev** [comment]
Do you expect me to know what is happening on your system, without knowing myriads of underlying details? :slightly_smiling_face: 

Anything could happen alongside, and it well could be a completely unrelated problem. For instance, there was other heavy process running in background, at the same time while you were visiting the Dashboard, which created an impression that it's a theme or Webmin issue, when it's actually not.

If you have  exact details or steps to reproduce an issue, I'd be interested.

**Comment by 7starsone** [comment]
At first you wrote that's a cache issue. And is a cache issue for sure because it does the same over time.
That's why I asked:
`Ok, so, put the case I want a long life cache, one week: I could set 10080 minutes and then, If I need, I would do a manual refresh on the dashboard? Is it working that way? Thanks`

but, instead of answering the questions, you did another question. Where do I come in this? Honestly....

thanks 👍

**Comment by iliarostovtsev** [comment]
> Where do I come in this

Where are you actually coming from any why bother at all? :slightly_smiling_face: 

> but, instead of answering the questions, you did another question. 

I cannot provide an answer (particularly exactly) if I don't even know what the real question is, and what problem is being solved.

It may look as a clear and easy to answer question to the one who asks it (like this one) _but_ an answer, most of the time, depends on so many abandoned details.

> thanks :+1: 

Not at all.

> Put the case I want a long life cache, one week: I could set 10080 minutes and then, If I need, I would do a manual refresh on the dashboard? Is it working that way?

Yes, manual refresh on the dashboard (including side slider) does force background recollection.

Now, I'd like to ask though - did you see a tooltip text or a delay is too long and you missed it?

![image](https://user-images.githubusercontent.com/4426533/111983264-fde53680-8b1a-11eb-90ff-3e06b8792d26.png)

**Comment by 7starsone** [comment]
Ok, there's a **bug**. I can't set any number of minutes greater than **60**

**Comment by 7starsone** [comment]
I will report to Webmin, thanks.

**Comment by iliarostovtsev** [comment]
Isn't cache period for more than 60 minutes disregard the idea of caching? Perhaps better to disable collection at all and perform on demand only?

**Comment by 7starsone** [comment]
> 
> 
> Isn't cache period for more than 60 minutes disregard the idea of caching? Perhaps better to disable collection at all and perform on demand only?

nevermind, I just changed the homepage to show a fast module instead of the system information. Thanks

**Comment by iliarostovtsev** [comment]
Were you waiting untill the dashboard load was finished? It could be possible to click any other link before the load was finished to terminate it, right?
