### ISSUE TITLE
Old Theme Configuration layout

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1523]
Is it possible to get the old `Theme Configuration` layout? I want to see all the options at the same time and not press next or change it from a dropdown menu :(

**Comment by iliarostovtsev** [comment]
Hi,

Unfortunately it is not longer possible, and it will not be coming back. Sorry. 

However there is a convenient search bar across all options. All you need to do is to start typing -

![image](https://user-images.githubusercontent.com/4426533/112680263-3750d580-8e7e-11eb-9c18-0be79eaf0fe4.png)
