### ISSUE TITLE
Install Missing Perl Module...

### ISSUE THREAD

**Issue by tpnsolutions** [authentic-theme/authentic-theme#1524]
This feature request is in keeping the UI consistent in various areas as the feature already exists in another module, but would be beneficial in the noted module (likely others as well -- this is the one I found).

When a Perl module is missing, but required by a module to work, it would be good to have a link to install the module...

Here's a "working" example of how the feature would work found at:

1. Navigate to "Webmin > Webmin Configuration > Two-Factor Authentication"
2. Choose "Google Authenticator"
3. Click "Save"
4. If the Perl Module "Authen::OATH" has not been installed, you'll see the below screen.

![Screenshot from 2021-03-27 13-48-00](https://user-images.githubusercontent.com/4305218/112734671-77f33200-8f04-11eb-93f9-be3d52a048af.png)

Note how at the end of the error you see Use the "Perl Modules" page in Webmin to install it. The words "Perl Modules" when click actually downloads and installs the missing Perl module.

Here's an example of where this functionality could be added for consistency and simplicity:

1. Navigate to "Virtualmin > Backup and Restore > Amazon S3 Buckets"
2. If the Perl Module "XML::Simple" is not installed, you'll see the below screen.

![Screenshot from 2021-03-27 13-47-27](https://user-images.githubusercontent.com/4305218/112734666-6f9af700-8f04-11eb-90cd-ac2cfe98bfdf.png)

Note how there's no "Use Perl Module page in Webmin to install it" at the end of this error.

**Comment by iliarostovtsev** [comment]
Hi, Peter.

I would rather added this to _yum-groups_ and _stack_ packages rather than changing UI specifically for it.

Although, it's worth nothing to add it on Virtualmin side, to have a suggested link to install either `perl-XML-Simple` or `libxml-simple-perl` package.

I will look into it. I have been busy with huge code refactoring for the theme.

**Comment by tpnsolutions** [comment]
I hear you, I guess the only thing I was look at was a consistent flow so that when the same occurrence happened regardless of where you'd see the same type of message, and/or options.

**Comment by iliarostovtsev** [comment]
Yes, agreed, just it should be done on the module side not on the theme side.

Thanks for heads up. I'll look into it tomorrow. I have 90% finished with the mentioned code refactor.

**Comment by iliarostovtsev** [comment]
This commit will address it - https://github.com/virtualmin/virtualmin-gpl/commit/8d4c44cb336d94f823fd75cd6d6cdc65f3eb4234

Thanks for the heads up.

![image](https://user-images.githubusercontent.com/4426533/112763514-6184cd80-900d-11eb-93e5-02227b8e5e32.png)

**Comment by jcameron** [comment]
Commit looks good, thanks!
