### ISSUE TITLE
Copy Password

### ISSUE THREAD

**Issue by tpnsolutions** [authentic-theme/authentic-theme#1525]
I think it would be cool to have a "Copy Password" button next to "Toggle Password Visibility" and "Generate New Password". A few screens that I'm aware of where this could be implemented (more pages likely in reality) include:

Virtualmin > Edit Passwords > Passwords

Virtualmin > Edit Virtual Server > Configurable Settings > Administration Password

Virtualmin > Edit Users > Edit User > Virtual Domain User Details > Password

*** also noted that "Virtualmin > Edit Users" page has the title "FTP Users" which doesn't align with the menu item which links to it. ***

**Comment by iliarostovtsev** [comment]
Hi, Peter.

> I think it would be cool to have a "Copy Password" button next to "Toggle Password Visibility" and "Generate New Password". A few screens that I'm aware of where this could be implemented (more pages likely in reality) include:

Copy password would be useful anyplace where there is an actual password present. We already have a button for it:

![image](https://user-images.githubusercontent.com/4426533/113517808-e4b49f00-958a-11eb-870e-3f29f08e21a8.png)

> *** also noted that "Virtualmin > Edit Users" page has the title "FTP Users" which doesn't align with the menu item which links to it. ***

Haven't noticed anything, where is it? Could you provide a screenshot?

**Comment by tpnsolutions** [comment]
No, what we have is a pop-up requiring manual copy and paste. As I keep cryptic passwords and don't want to accidentally copy a space which causes the password to become corrupt, it'd be nice to have a simple copy button which places "current" password into the clipboard.

**Comment by tpnsolutions** [comment]
Presently when generating new passwords at least on some screens it copies to clipboard the new password.

**Comment by tpnsolutions** [comment]
I suppose while on the topic, "copy user" could technically be useful.

**Comment by iliarostovtsev** [comment]
> Presently when generating new passwords at least on some screens it copies to clipboard the new password.

Correct, only it happens **on all screens**, as performed by the same plugin.

>  As I keep cryptic passwords and don't want to accidentally copy a space which causes the password to become corrupt

Even though you cannot copy a space, as it's a table cell, and selecting a password will not select any spaces, as there are no any. I will think about doing it in the future.

> I've been spending a lot of time working with Virtualmin and Usermin lately so you'll likely see a slew of feature improvements / requests over the coming weeks after I've put together some details about implementation.

That would be great. Thanks.

> *** also noted that "Virtualmin > Edit Users" page has the title "FTP Users" which doesn't align with the menu item which links to it. ***

That I couldn't reproduce. Any screenshot?

**Comment by tpnsolutions** [comment]
It seems in reference to the "Edit Users" page depending on the types of users you have it will either read "Mail and FTP Users" or "FTP Users" on the page.

Perhaps the navigation would be better adjusted to read "Users" instead of "Edit Users" as in comparison "Edit Virtual Server" in navigation reflects same verbiage on linked page.

If possible either at Virtualmin level or theme level it might be good to separate users into two tables...

Mail Users
FTP Users

Though frankly we don't enable FTP on our servers anymore in favor of SSH/SFTP/SCP... So perhaps the verbiage and separation needs even further changes based on what is installed and/or enabled on server.

Still pondering this one actually...

**Comment by iliarostovtsev** [comment]
Perter, I have taken a closer look to the main topic of this issue "Copy Password" button next to "Toggle Password Visibility" and "Generate New Password" .. Considering that we already have password preview button -

![image](https://user-images.githubusercontent.com/4426533/115239801-cb355a80-a127-11eb-8aa7-3d46cfd61929.png)

.. and the other field (with new extra buttons to generate the password and etc) is not meant to hold initial password:

![image](https://user-images.githubusercontent.com/4426533/115240825-cfae4300-a128-11eb-9e61-935cc287f1e6.png)


.. and besides when the new password is generated it's already pasted to the clipboard automatically.

I don't really think there is anything here that could be improved drastically , unless completely rework how password previews work. But that would not be the theme related improvement.
