### ISSUE TITLE
Duplicate Folder List - Authentic 19.74

### ISSUE THREAD

**Issue by tpnsolutions** [authentic-theme/authentic-theme#1526]
I found what "might" be a bug in Usermin with Authentic Theme 19.74. I also observed this during the RC phase and figured it'd be gone once the stable version had been released. (I had rolled back to 19.73 before making the upgrade to 19.73)

The folder tree on the left is "duplicating" as shown in the below screen shot.

Usermin: 1.823
Authentic Theme: 19.74
OS: CentOS 6.10

![Screenshot from 2021-04-05 10-55-54](https://user-images.githubusercontent.com/4305218/113607380-fbe0a480-95fd-11eb-8709-2dab0a7428d6.png)

**Comment by iliarostovtsev** [comment]
Hi, Peter.

Thanks for the heads up.

This is expected, as this requires latest Usermin patch to work correctly.

**Comment by iliarostovtsev** [comment]
https://github.com/webmin/usermin/commit/ffb9cd0ea82af670e43616088eb1feccbd66f542

**Comment by tpnsolutions** [comment]
Understood, thanks for the clarification
