### ISSUE TITLE
Theme configuration / navigation menu truncated

### ISSUE THREAD

**Issue by acovington7920** [authentic-theme/authentic-theme#1527]
This has occurred on multiple servers with 19.73 and 19.74, all on CentOS 7.  In Theme Configuration, Navigation menu the menu cuts off below the text "Show HTML snippet" but without displaying the contents of that field, and also the Save button is missing.  I've viewed this in multiple browsers (Chrome, Firefox, Safari) in varying screen resolutions but they all exhibit this behavior.  Example screenshot attached.  Any suggestions are appreciated!

![Screenshot 2021-04-07 152103](https://user-images.githubusercontent.com/82120173/113929213-6851d400-97b5-11eb-805d-1089b86d7d5b.jpg)

**Comment by iliarostovtsev** [comment]
Hi,

It looks like an escaping issue. How does your HTML snippet looks like in one of the settings files under `/etc/webmin/authentic-theme` directory?

Also, if you open browser's console, switch to its _Network_ tab and then click on _Theme Configuration_ link from navigation menu (to reload the page), what is the full (or related) output in _Response_ sub-tab (of _Network_ tab in browser's console)?

**Comment by acovington7920** [comment]
Thank you!  For some reason it never occurred to me that the HTML in that field would be the problem - that HTML hasn't changed in years, through many versions of the theme.  Anyhow, here's the line that was used prior to today in settings:
settings_leftmenu_user_html='<body><br><br><br><br><h2>SkySync<br>VHOST1</h2></body>';

After I removed all HTML from that line and refreshed the page, it looked fine.  I then copied + pasted back the same code without <body> and </body>, saved, refreshed, and it's working nicely.

**Comment by iliarostovtsev** [comment]
Thanks for reporting. There were actually few bugs and I also switched bottom buttons use flexbox.
