### ISSUE TITLE
Usermin: Mail "Final Sync"

### ISSUE THREAD

**Issue by tpnsolutions** [authentic-theme/authentic-theme#1528]
So, when you're doing an operation in Usermin with regards to mail such as "move" or "delete" for instance...

As you complete an operation, the "left panel" refreshes the total message count in the folder affected. However, upon the final operation like when I've moved the final message(s) or deleted the final message(s) from the folder, it does not sync the left column requiring you to click the "Mail" tab to trigger an update.

*** To clarify, I realize that the "message count" beside the folder only references "new - unread" messages ***

Usermin: 1.823
Authentic Theme: 19.74

*** This issue has been around for some time BTW ***

**Comment by iliarostovtsev** [comment]
Confirmed.

Thanks.

**Comment by iliarostovtsev** [comment]
Fixed.
