### ISSUE TITLE
Webmin + Comodo WAF

### ISSUE THREAD

**Issue by daddygo** [authentic-theme/authentic-theme#1534]
Hello,

This is an old question as I see. I don't know if I'm asking the question on right place...(?)

I started using this wonderful WHM not so long ago (6-8m), since I also use CWAF I immediately encountered this issue in Webmin's HTML5 interface, - the old one works fine (Gray Framed Theme)...

_Blank (white) page when I open CWAF from the new HTML5 interface:_

https://forums.comodo.com/free-modsecurity-rules-comodo-web-application-firewall/webmin-plugin-t111397.0.html

Is this a Comodo question or Webmin question, thanks for pointing me in the right direction?

![2021-05-02_15h50_01](https://user-images.githubusercontent.com/59891570/116817912-9e8a3580-ab60-11eb-890f-2aed9bea00e7.jpg)
![2021-05-02_15h51_17](https://user-images.githubusercontent.com/59891570/116817913-9f22cc00-ab60-11eb-9e0b-ae487b93c987.jpg)
![2021-05-02_16h06_50](https://user-images.githubusercontent.com/59891570/116817914-9f22cc00-ab60-11eb-8b4a-94149d9eb7d5.jpg)
![2021-05-02_16h07_24](https://user-images.githubusercontent.com/59891570/116817916-9f22cc00-ab60-11eb-8e8f-0e2383d2f544.jpg)

**Comment by iliarostovtsev** [comment]
Hi,

I think these issues should be fixed by modules' developers.

Do you have a download link for Comodo WAF module? I could take a quick look if this can be easily reproduced and reliably addressed on the theme side.

**Comment by daddygo** [comment]
Hi,
Thanks for your reply.

I thought the same thing, but as you can see (from my forum comodo link) there was the problem several years before and nothing happens.

BTW, I opened a ticket on CWAF support, more than a month ago, no reply yet.
I guess since the free rule set is not so much a priority.
A script installs CWAF under Webmin after Apche / Nginx + Modsecurity is installed from CLI or Webmin.

The ruleset will be downloaded by the module, at the set intervals, which requires a free registration .

The ruleset is not required for the test, so here is the installation script file.
Thanks if you can take the time for a quick review.

[cwaf_client_install.zip](https://github.com/authentic-theme/authentic-theme/files/6419699/cwaf_client_install.zip)

+ https://waf.comodo.com/doc/Comodo_Web_Application_Firewall_Admin_Guide.pdf

**Comment by iliarostovtsev** [comment]
I have taken a closer look a made a patch to make Comodo WAF work in a separate window with Authentic Theme. Yet, they use a lot of custom code and don't use Webmin UI lib properly, so the rest of the fixes should be done on Comodo side.

At lest it will work.

You can pull latest development version of the theme to give it a try.

**Comment by daddygo** [comment]
Thank you for this great and incredible speed of support.
I will test it in a few days and come back with a short feedback, at the same time, while also trying to encourage the support team of CWAF.
