### ISSUE TITLE
Blue menu color too bright

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1535]
I updated to Authentic theme 19.75 and the blue menu color is way too bright. How to i get the old blue color back?

Now the text (clickable links) and the menu have two different blue colors that make it look totally wrong :(

**Comment by iliarostovtsev** [comment]
Hi,

You can use filters in theme configuration to control saturation.

What do you mean by different blue colors?

**Comment by iliarostovtsev** [comment]
Sopor, could you provide a screenshot of what looks wrong to you?

**Comment by Sopor** [comment]
Old color:
![image](https://user-images.githubusercontent.com/5789283/116911715-7de8db00-ac47-11eb-8f9b-95280e25bdd7.png)

New color:
![image](https://user-images.githubusercontent.com/5789283/116911747-8ccf8d80-ac47-11eb-82a0-601c39729b3e.png)

**Comment by iliarostovtsev** [comment]
> Now the text (clickable links) and the menu have two different blue colors that make it look totally wrong :(

I am sorry, but by looking at the screenshots I see nothing wrong? Where exactly the menu has two different blue colors?

**Comment by Sopor** [comment]
So you see no difference between the two pictures?

**Comment by iliarostovtsev** [comment]
I do see the great difference. Which is expected. But you said `the menu have two different blue colors` - what does that mean - what different colors - different colors on the same screenshot or different colors on previous and current versions?

The navigation default menu color was a bit adjusted, it's expected. Is there anything wrong with it? I suggest you checking it on your phone/tablet with a good screen and see if it still looks wrong?

**Comment by iliarostovtsev** [comment]
.. I could agree making it slightly less bluish, to raise contrast of the text even more ..

**Comment by Sopor** [comment]
> Now the text (clickable links) and the menu have two different blue colors that make it look totally wrong

I wrote that the clickable links now has two different colors. I don't mean the menu.

Clickable links was more like the old blue menu color.

**Comment by iliarostovtsev** [comment]
> I wrote that the clickable links now has two different colors. I don't mean the menu.

I am sorry but I don't understand what your words are referring to exactly ..

> So is there a way for me to change it back? It is way too bright for me.

Yes, sure. You can pull the latest dev version and have a look if it fits you better.

Otherwise you can apply filters and tweak it to any tint/color you like.

Using this feature:

![image](https://user-images.githubusercontent.com/4426533/117061522-fb394c00-ad2a-11eb-94dd-4aca4c88ef9d.png)


.. and you can easily change its look _from -> to_:

**Comment by iliarostovtsev** [comment]
![image](https://user-images.githubusercontent.com/4426533/117061706-2d4aae00-ad2b-11eb-8291-d44df73831d1.png) ![image](https://user-images.githubusercontent.com/4426533/117061851-5bc88900-ad2b-11eb-9422-96309035ca12.png) ![image](https://user-images.githubusercontent.com/4426533/117061945-76026700-ad2b-11eb-970b-dc855246dc63.png)

**Comment by Sopor** [comment]
No way to type in the color value: 2D5D9D? I suck at color and I will never accomplish to get that old blue color back by moving those sliders :(

**Comment by iliarostovtsev** [comment]
You could use Theme Extensions for CSS and add the following code:

```
#sidebar,
.switch-mins a,
.favorites-border {
    background-color: #2d5d9d;
}

html[data-bgs='gainsboro'] .right-side-tabs[data-bgs='nav'],
html[data-bgs='gainsboro'] .right-side-tabs[data-bgs='nav'] .list-group-item,
html[data-bgs='gainsboro'] .right-side-tabs[data-bgs='nav'] .right-side-tabs-dismiss,
html[data-bgs='gainsboro'] .right-side-tabs[data-bgs='nav'] .nav-tabs,
html[data-bgs='gainsboro'] .right-side-tabs[data-bgs='nav'] .nav-tabs .active a,
html[data-bgs='gainsboro'] .right-side-tabs-toggler[data-bgs='nav'] > button,
html[data-bgs='gainsboro'] .right-side-tabs-toggler[data-bgs='nav'].opened > button,
html[data-bgs='gainsboro'] .right-side-tabs-toggler[data-bgs='nav'],
.mobile-menu-toggler > .btn-menu-toggler {
    background-color: #2d5d9d !important;
}
```

**Comment by Sopor** [comment]
Now it looks like it should do, thanks @iliarostovtsev

**Comment by iliarostovtsev** [comment]
> Now it looks like it should do, thanks

It depends a lot on your PC screen. The best test case would be some Apple retina or an iPad Pro or a smartphone with AMOLED screen to realize how the colors really expected to look like. For instance, I have a 27' Acer monitor and it produces way more saturated picture than my MacBook Pro. I suggest you giving it a try on some other device and seeing how it looks?

By the way, what is your monitor manufacture and a model?

**Comment by Sopor** [comment]
That doesn't matter what monitor i use. The color looks like it did before you changed it and that was what i wanted.
