### ISSUE TITLE
Theme Configuration/Navigation menu - Dropdown menu won't open on the first click

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1537]
There is something wrong with the down arrow when i press on the `Blue (default)`. The first time i press on it the little arrow change direction and to get the dropdown menu to open i need to press a second time.

![image](https://user-images.githubusercontent.com/5789283/117072249-73eed700-ad30-11eb-95e4-8a6773ffdac5.png)

Authentic theme version 19.75
Firefox 88.0
Windows 10

**Comment by iliarostovtsev** [comment]
> There is something wrong with the down arrow

What browser and its version you're seeing this issue on?

**Comment by Sopor** [comment]
> Authentic theme version 19.75
Firefox 88.0
Windows 10

It is already in the first comment :)

**Comment by iliarostovtsev** [comment]
This looks to me like unresolved Firefox bug - https://bugzilla.mozilla.org/show_bug.cgi?id=1475396

The fix was easy though. Thanks for reporting!

**Comment by Sopor** [comment]
There still seems to be some issues with the arrow. When i press on it, it will change direction from pointing down to up, but when i press on it a second time it will close the menu but the arrow will still point up. To get it to point down i need to make the whole page active.

**Comment by iliarostovtsev** [comment]
> There still seems to be some issues with the arrow. When i press on it, it will change direction from pointing down to up, but when i press on it a second time it will close the menu but the arrow will still point up. To get it to point down i need to make the whole page active.

Thanks for reporting it too!

However, I have fixed it for Chrome and other browsers with ease but it just won't work in Firefox. I suggest reporting this to Mozilla.
