### ISSUE TITLE
Theme Configuration/Navigation menu/Color palette - Won't change back to default values when leaving the category

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1538]
If i use that Color palette to adjust the color it will change the color directly and that is nice but if i leave the `Configuration category:` i get this dialog telling me the changes will be lost but it will not change the color back on the main menu. It will keep the color until i refresh the page.
![image](https://user-images.githubusercontent.com/5789283/117072918-7bfb4680-ad31-11eb-9f98-a14bb2decfd6.png)

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the suggestion - good point!

> It will keep the color until i refresh the page.

Check the latest dev version. It should work fine starting with 19.76 release.
