### ISSUE TITLE
Only show the 'Force update theme' button when 'Theme updates' is selected

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1539]
Now when you have split up the theme configuration page i will suggest you to only show the `Force update theme` button when the Configuration category is set to `Theme update`. As it is now it is a button i don't see what it do because i can't see the installed version or if there are any updates to install. It is like you have a blind button. If you get what i mean?

![image](https://user-images.githubusercontent.com/5789283/117212652-e6c48480-adfa-11eb-92cb-98d5b81c4043.png)

**Comment by iliarostovtsev** [comment]
Hi,

Yes, cool suggestion - done!
