### ISSUE TITLE
Theme: Navigation Sidebar not working when using Webmin Servers Index

### ISSUE THREAD

**Issue by Rosstarz** [authentic-theme/authentic-theme#1540]
Hello. I first want to thank you so much for this amazing theme and all your hard work you've put into it.

I have this issue with the theme:

When I use Webmin Servers Index, I register a server using the **'Login via Webmin with username'** link type. With username and password filled.

Clicking on the icon with a different user, who doesn't have access to edit the Servers Index - results in a gray screen but not showing the default page of the Indexed server Webmin. And also the **Navigation Sidebar stays the same as the previous Webmin, where the Server Index is, and not the actual linked server.**

I tried BWTheme and in that theme the navigation bar changes correctly when switching to a different server. 

I was wondering how this can be achieved with the amazing authentic-theme as well. Thank you.

**Comment by iliarostovtsev** [comment]
Hi,

> I first want to thank you so much for this amazing theme and all your hard work you've put into it.

Thank you for your kind words!

> Clicking on the icon with a different user, who doesn't have access to edit the Servers Index - results in a gray screen but not showing the default page of the Indexed server Webmin. 

Oh, you're right! I see the bug there too. I will fix it for upcoming Authentic Theme 19.76 release.

Meanwhile, the work-around would be is to hold **`Ctrl`** key while clicking on the needed server, to force it opened on the new window.

**Comment by Rosstarz** [comment]
Thanks for the quick reply.  

Yes I see with Ctrl it works. 

That would be awesome if you could include it in the next update, thank you!

**Comment by iliarostovtsev** [comment]
> That would be awesome if you could include it in the next update, thank you!

Already fixed and included to 19.76-beta1. You can go to **Theme Configuration: Theme updates** and _Update Theme_ to the latest development version.
