### ISSUE TITLE
Can not save theme settings

### ISSUE THREAD

**Issue by lionslair** [authentic-theme/authentic-theme#1582]
I have noticed an issue on last couple of releases. I can not save theme settings through the UI. I get a console error

version: 19.84.7

![Screenshot from 2022-02-20 12-18-05](https://user-images.githubusercontent.com/832259/154828236-83e2a37b-d5ca-4a24-9b9e-621266dcce4d.png)

![Screenshot from 2022-02-20 12-18-50](https://user-images.githubusercontent.com/832259/154828244-3f0d0bbf-5eb6-47f7-9fb4-8d8629ce1bab.png)

**Comment by iliarostovtsev** [comment]
Hello,

Does it help if you force reload the page using `Ctrl+Shift+R` hotkey?

**Comment by lionslair** [comment]
Tried that several times. Cleared cache. Restart webmin. Even removed the theme and reinstalled.

**Comment by iliarostovtsev** [comment]
This is odd.

If you go to **Webmin ⇾ Webmin Configuration: Web Server Options** page and set **Gzip compress static files?** to **Never**, reload the page - does it change anything?

What browser and OS is that?

**Comment by lionslair** [comment]
Sorry for late reply did not see the notification.

Operating system | Ubuntu Linux 20.04.4
Client: Pop os 20.04 so Ubuntu  20.04 desktop

Firefox 97.0 64-BIT

Hmm I did that and even restarted webmin. If I go back to it the ajax request says 200 but then when I navigate away it tells me i have not saved.
![Screenshot from 2022-02-24 16-08-30](https://user-images.githubusercontent.com/832259/155484099-90547889-765d-4099-9ad2-68487c444c95.png)

**Comment by lionslair** [comment]
> Hello,
> 
> Does it help if you force reload the page using `Ctrl+Shift+R` hotkey?

No done that. Cleared cache. Happens on a few systems. All ubuntu and with firefox.

**Comment by iliarostovtsev** [comment]
Does it happen in Brave or Chromium?

**Comment by lionslair** [comment]
Seems to have saved it using chromium but I do not see the refresh button on the dashboard. I tried clear cache too. fresh install of Chromium I did not have it.

**Comment by iliarostovtsev** [comment]
This can be closed.
