### ISSUE TITLE
Scrollbar accessibility

### ISSUE THREAD

**Issue by brad1001** [authentic-theme/authentic-theme#1584]
Hi Ilia

Hope all is well.

I was wondering if there a setting to adjusting the sidebar bar both in contrast and size? 

The contrast is perfect on the older theme versions but I find on the latest version (19.84..)  I am loosing the scrollbar bar all the time, and can no longer edit very large files as navigation for me is almost impossible.

I am using Firefox Developer browser.

Maybe I should look at ccs overrides for this?

Kind regards
Brad

**Comment by iliarostovtsev** [comment]
Hi, Brad.

Which scroll bar you are referring to?

**Comment by brad1001** [comment]
Hi Ilia 

Thank you fro your reply.

It is the far right scrollbar that eludes me most of the time 

![authentic-scrollbar](https://user-images.githubusercontent.com/34011731/156813083-05823236-e444-4306-a92a-f99138483186.png)

The Github scrollbars are a thing of beauty :)  - on my laptop at any rate.

Kind regards
Brad

**Comment by iliarostovtsev** [comment]
This is indeed barely visible. I will fix that!

Thank you for pointing out.

**Comment by brad1001** [comment]
Thank you very much, I for one with be truly grateful. 

All the best
Brad

**Comment by iliarostovtsev** [comment]
Brad, sorry as it took some time. I have improved scrollbars. The main scrollbar and the scroll bar inside of the panels are now separated.

If you have Webmin 1.990 installed you can safely install latest 19.90.2-beta1-1 to try out.

Although, I don't know what result will you get but on my Mac I don't have a great result for the main scrollbars (which you showed on the screenshot above) in neither Firefox nor in Firefox Developer Edition, as the scroll bar just blends with the background and Firefox still doesn't seem to support _::webkit-scrollbar*_ selectors.

Tell me if you have an issue on your side after installing the latest update in Firefox, as it works great for me in Chrome and Safari. If there is still an issue, I will have to find a better workaround for Firefox users.

This is how the main scrollbar is now expected to look:

https://user-images.githubusercontent.com/4426533/157056593-e94ce86e-07b4-4013-ba2a-af56ac4949d0.mov

**Comment by brad1001** [comment]
Hi Ilia
Thank you for your reply and actions.
The included video showing the updated scrollbar on your browser looks perfect.

As you expected - unfortunately these changes are not reflected in Firefox. 

I will use an alternative browser for any big edits -  Actually it is CFS -  settings page that has been the most frustrating.

Thanks again for looking into this.

Kind regards
Brad

**Comment by iliarostovtsev** [comment]
Okay, Brad. I have also fixed the scrollbar for Firefox based browsers. It should work just fine with the latest commit.

Thanks for reporting!

**Comment by brad1001** [comment]
Ah fantastic! 
Thank you very much -  I can confirm your fix has worked for Firefox.
All the best

**Comment by pacquo** [comment]
Hello Ilia,
I have installed Authentic 19.93.1 version on Webmin 1.994 (minimal package) and I'm using Firefox 100.2 .

I use Webmin mainly to read the logs, but despite the last update the scrollbars inside the log window are barely visible. 

The horizontal scrollbar, in particular, auto hides as soon as you start to scroll vertically. In any case it seems impossible to grab it, it's almost transparent and really too thin.

Kind regards,
Andrea
