### ISSUE TITLE
File Manager Upload: can no longer overwrite file

### ISSUE THREAD

**Issue by pixel-paul** [authentic-theme/authentic-theme#1585]
Webmin version | 1.990
-- | --
Authentic theme version | 19.85.1

Hi,

Was there an checkbox to 'Overwrite' on upload before? Or am I imagining things!

![Screenshot 2022-03-10 at 15-57-53 _public_html - File Manager — Webmin 1 990 on server300 (Redhat Enterprise Linux 8)](https://user-images.githubusercontent.com/389303/157701448-99385273-f669-4e2c-ad00-2973dccd6777.png)

**Comment by iliarostovtsev** [comment]
> Was there an checkbox to 'Overwrite' on upload before? Or am I imagining things!

You are not imagining things. There really was that checkbox. But I decided to remove it, so not to clutter the UI. Again, you can still control overwrite mode by using File Manager configuration.

> In fact, now I'm thinking about it a bit more, I'm sure that a modal window would appear and ask to either merge or create a new file. This appears to no longer be happening.

That has never been happening in the past for uploads, only for copy/cut/paste operations (to a different directory).

If you use File Manager configuration to control overwrites, is this suitable for you?

**Comment by pixel-paul** [comment]
If I can set it to overwrite on upload, that is absolutely fine, however I couldn't find this option in 'File Manager' -> 'Module preferences' (assuming this is where it is set):
![Screenshot 2022-03-10 at 17-46-10 File Manager — Webmin 1 990 on server300 (Redhat Enterprise Linux 8)](https://user-images.githubusercontent.com/389303/157723848-dbc8d01f-9552-47c1-9b08-c22d67cd2dff.png)

**Comment by iliarostovtsev** [comment]
The third option from the bottom. On the future release it will be called **Automatically set owner and group equivalent to user home on file operations**.

**Comment by iliarostovtsev** [comment]
I mean to say **Do not overwrite existing files upon operations**.

**Comment by pixel-paul** [comment]
ah, perfect, thanks. the encode/decode bit threw me!

Thanks,

Paul
