### ISSUE TITLE
Running processes - How to show 24H instead of AM/PM?

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1587]
When holding the mouse pointer over `Started` on the `Running processes` page the time will show `AM/PM` but i want it to show `24H`.

![image](https://user-images.githubusercontent.com/5789283/159466170-ef76ba12-adfc-48ab-b639-7dcd5ba37d3d.png)

![image](https://user-images.githubusercontent.com/5789283/159466435-fa8d112b-0c8d-46d4-aff3-c8b5a9be9aa1.png)

### Here are my settings:
![image](https://user-images.githubusercontent.com/5789283/159466087-673315b6-f04e-46c9-a9e4-203df3d75a0e.png)

![image](https://user-images.githubusercontent.com/5789283/159466116-1fc08bcf-affe-4e27-9ecd-e6944151b3bb.png)

**Comment by iliajie** [comment]
Hi,

You are right. I have added more English locales. For your case English (United Kingdom) would work just fine. Give it a try.

**Comment by iliajie** [comment]
The patch above should fix your issue.
