### ISSUE TITLE
Theme: Navigation menu custom links

### ISSUE THREAD

**Issue by myopenflixr** [authentic-theme/authentic-theme#904]
I was wondering if you might be able to give us the option to add our own links on the left menu? Right now, you give us the option to "Show Netdata realtime monitoring link" and include a custom URL.

I would like the ability to add others along with custom URL's.

For example, I have implemented GoAccess (https://goaccess.io/) to gather some stats on my website. I would like the ability to have a link that takes me directly to my GoStats URL built into Webmin's left menu displayed right under my Netdata link.

**Comment by qooob** [comment]
Hi,

Yes, I could do it.

**Comment by qooob** [comment]
Oh, GoAccess seems really cool!

**Comment by swelljoe** [comment]
There's already Custom Links, for just this purpose, in Virtualmin. It's in System Customization->Custom Links.

Do you need it in Webmin without Virtualmin? That's do-able, I think. The only reason it was done in Virtualmin was that when it was introduced (menu years ago), Webmin didn't have a left menu and Virtualmin did. ;-)

**Comment by myopenflixr** [comment]
@qooob - GoAccess is pretty neat! I'm personally having troubles with "Real Time" reporting, but I'll (hopefully) get it figured out eventually.

@swelljoe - I personally need the link in Webmin as I do not use Virtualmin.

And to take it a step further, how difficult would it be to have the option to have these links open the URL inside the main body of Webmin as an iframe? Not sure if it would look right still having Webmin's left menu, but the idea just came to mind.

**Comment by qooob** [comment]
@myopenflixr 

_Webmin Configuration/Edit Categories_ lets you create your own category and then put existing modules in there. In order to do that, you would need to mimic the module to have the link.

I think, it's doable to make the theme inject custom links into Webmin menu. It will create few extra options in theme's configuration though.

About opening it inside of the main body, it would be difficult to make and I mean only the links with the same refere. It's theoretically possible to inject iframe on the fly and insert content there but it's a step back and I wouldn't want to have all of us headed to this direction. In case it's the different location, it will not work out of the box ever.

**Comment by myopenflixr** [comment]
As a temporary solution, I used the theme's _Show HTML Snippet_ to insert a link to my stats page. Hopefully you can come up with a solution that allows us to insert links right below _Realtime Monitoring_. As an added bonus, it would be nice to also be able to assign an icon (Font Awesome) to display in front of our link :)

**Comment by rostovtsev** [comment]
Hi,

I hope it's still valid. Latest commit brings such functionality.

Please give it a try. Search for `Extra entries` under _Navigation menu options_ in Theme Configuration.

There is little help balloon with explanations.

**Comment by myopenflixr** [comment]
Hi @rostovtsev ,

I like the addition! I do have a question though. When setting the icon image for the link, what icon library are we pulling from? Is this based off of font awesome icon library? Just wondering what icon images I have to choose from.

Thanks for the addition!!!

**Comment by rostovtsev** [comment]
It's custom built of icons. I don't have it published yet.

You are welcome!

**Comment by rostovtsev** [comment]
@myopenflixr 

Mike, how about this:
https://authentic-theme.com/kit/

:smiley_cat:

**Comment by rostovtsev** [comment]
It's already possible. Theme has extensions for _CSS_ and _JS_. Simply add there whatever you need, and it will accessible for you and survive updates.

By the way, it would be possible to inject nee links into navigation menu, just by using _JS_ extensions, with writing couple lines of code.

**Comment by rostovtsev** [comment]
I have added an option/feature, where you can define at which login mode a link would be displayed, by specifying the level, in comma separated list: 

_0_ - administrator login; 
_1_ - reseller login;
_2_ - server owner login;
_3_ - user login;
_4_ - system owner login.

**Example:**
```JSON
{  
   "extra":[  
      {  
         "title":"Google Mail",
         "link":"https://gmail.com/",
         "icon":"google",
         "level":"2,3"
      },
      {  
         "title":"BIND DNS Server",
         "link":"/bind8",
         "icon":"server"
      }
   ]
}
```

**Comment by cconde** [comment]
Quick question: If I want an extra link, pointing to the same host the Wembin is running on, but a different port... how can I do without knowing the full URL?

I.e. "link":"https://%myhost%:8443" and having %myhost% filled with my hostname

Is it ever possible? It would be great as the wembin host is running other web services in my installation

**Comment by iliarostovtsev** [comment]
> Is it ever possible?

I don't think it's possible.

**Comment by cconde** [comment]
Could we have a different type of link, adding a port property? Say "link":"/relative", "port":8443
We'd need the theme to process it and compose the proper URL

I guess I'm not the only one having additional web servers running in the same machine as the webmin

In any case, this work is absolutely wonderful, thank you very much

**Comment by iliarostovtsev** [comment]
There you go. 

**Example:**

```JSON
{
   "title":"Usermin",
   "link":"/",
   "icon":"envelope",
   "port":"20000",
   "target":"_blank"
}
```

**Comment by cconde** [comment]
Absolutely fantastic, thank you very much!

I'll go test it as soon as I can

>

**Comment by Kevin-Nexio** [comment]
Hello,

Is it possible to make a forwarding on a port but defining also if the link is in http or https protocol?
for example:
```json 
{
   "title":"Usermin",
   "link":"/",
   "icon":"envelope",
   "port":"20000",
   "target":"_blank"
   "protocol":"http"
}

**Comment by iliajie** [comment]
Yes, you can just remove `"port":"20000",` and for the link just set the full URL you prefer.

**Comment by Kevin-Nexio** [comment]
Thanks for the quick feedback, but my goal would be to be able to do something like [cconde](https://github.com/webmin/authentic-theme/issues/904#issuecomment-593511453) had asked 
`I.e. "link": "https://%myhost%:8443" and having %myhost% filled with my hostname`
I am not in localhost and the server address on which the webmin and my 2nd service (Duplicati) is running is not on fix IP because it will be put in service at different customer sites.

**Comment by iliajie** [comment]
Then check the latest patch I already made to address it. It will allow setting `host` and `protocol` as well. Let me know if it works for you.

**Comment by Kevin-Nexio** [comment]
It works perfectly! Thank you very much

**Comment by iliajie** [comment]
Glad to hear!
